[docs] Storage and Models documentation
osukhoroslov/dslab pull request #101
Opened 2022-07-30 23:37 UTC by kuskarov

2022-08-01 12:24 UTC, osukhoroslov requested changes
И неплохо бы добавить примеры. См. мой PR с документацией к dslab-core.

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/events.rs
> +    /// Size which was read from disk.
```suggestion
    /// Size of data read from disk.
```

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/events.rs
> +    /// Size which was written to disk.
```suggestion
    /// Size of data written to disk.
```

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/events.rs
> +/// Event type for file system read request complete. It is sent from file system to requester.
```suggestion
/// Corresponds to completion of file system read request. Source: file system, destination: requester.
```

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/events.rs
> +    /// Id which was returned from `read` file system method.
```suggestion
    /// Request id returned by [`crate::fs::FileSystem::read()`] method.
```
И ниже поправьте аналогично

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/events.rs
> +    /// Name of the file to read from.
```suggestion
    /// Name of read file.
```

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/events.rs
> +    /// Size which was read from disk.
```suggestion
    /// Size of read data.
```
про диск можно и не упоминать, он же скрыт ФС. а может потом файл будет и на нескольких дисках размещаться.

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/events.rs
> +/// Event type for file system read request failure. It is sent from file system to requester.
```suggestion
/// Corresponds to failure of file system read request. Source: file system, destination: requester.
```

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/events.rs
> +    /// Name of the file to read from.
```suggestion
    /// Name of read file.
```

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/events.rs
> +/// Event type for file system write request complete. It is sent from file system to requester.
```suggestion
/// Corresponds to completion of file system write request. Source: file system, destination: requester.
```

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/events.rs
> +    /// Name of the file to write to.
```suggestion
    /// Name of written file.
```

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/events.rs
> +    /// Size which was written to disk.
```suggestion
    /// Size of written data.
```

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/events.rs
> +/// Event type for file system write request failure. It is sent from file system to requester.
```suggestion
/// Corresponds to failure of file system write request. Source: file system, destination: requester.
```

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/events.rs
> +    /// Name of the file to write to.
```suggestion
    /// Name of written file.
```

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/fs.rs
> +    /// Unmounts disk which is mounted to `mount_point` if there is any.
```suggestion
    /// Unmounts a disk which is mounted to `mount_point` if there is any.
```

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/fs.rs
> +    /// Requests reading from `file_name` of `size`. Emits response event to `requester`. Returns `request_id` which is unique to this file system.
Поправьте описания read/write функций по аналогии с дисковыми.

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/fs.rs
> +    /// Creates file with name `file_name` if there is not any yet.
```suggestion
    /// Creates file with name `file_name` if it doesn’t already exist.
```

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/fs.rs
> +    /// Deletes file with name `file_name` if there is any yet.
```suggestion
    /// Deletes file with name `file_name` if there is any.    
```

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/fs.rs
> +    /// Returns amount of used space on all disks on this file system.
```suggestion
    /// Returns amount of used space on all disks currently used by this file system.
```

2022-08-01 12:24 UTC, osukhoroslov commented on crates/dslab-storage/src/shared_disk.rs
> +//! Shared disk model.
Здесь поправьте аналогично замечаниям к `disk.rs`.

2022-08-03 22:25 UTC, kuskarov commented on crates/dslab-models/src/model.rs
> +//! Definition of the throughput model trait.
Сделал по-другому - создал поддиректорию throughput_sharing, в нее унес все, что касается этой модели. Внутри упростил все названия (так как они все находятся уже внутри throughput_sharing), и сделал экспортные названия через `pub use` в throughput_sharing/mod.rs. Еще из плюсов - теперь в одном месте можно подменить быструю модель на медленную и везде это подхватится.

Другие модели можно аналогично располагать в отдельных поддиректориях.

2022-08-03 22:33 UTC, kuskarov commented on crates/dslab-models/README.md
> +## Throughput sharing model
Унес в throughput_sharing/README.md. Насчет уноса в код не знаю - если так сделать, то получается, что документация будет рендериться, только если `rustdoc` запустить и открыть html. А md-файлы можно и на GitHub читать, и в IDE.

Еще я собираюсь добавить полный вывод формул для fast model, для этого нужен рендеринг ТеХ-а в MarkDown, в GitHub он уже есть, а в коде будет страшно выглядеть.

2022-08-03 22:33 UTC, kuskarov commented on crates/dslab-storage/src/fs.rs
> +    /// Requests reading from `file_name` of `size`. Emits response event to `requester`. Returns `request_id` which is unique to this file system.
Done

2022-08-03 22:33 UTC, kuskarov commented on crates/dslab-storage/src/shared_disk.rs
> +//! Shared disk model.
Done

2022-08-03 23:09 UTC, kuskarov commented on crates/dslab-storage/README.md
> +Simple disk model has two main methods - `read` and `write`, and some utility functions as `mark_free` or `get_used_space`. It can be created by `new_simple` function if bandwidths are fixed.
Done

2022-08-03 23:09 UTC, kuskarov commented on crates/dslab-storage/README.md
> +## Disk
Done

2022-08-03 23:09 UTC, kuskarov commented on crates/dslab-storage/README.md
> +## Shared disk
Done

2022-08-03 23:09 UTC, kuskarov commented on crates/dslab-storage/README.md
> +## File system
Done

2022-08-03 23:11 UTC, kuskarov commented on crates/dslab-storage/src/bandwidth.rs
> +//! Bandwidth models.
Done

2022-08-03 23:29 UTC, kuskarov commented
Насчет примеров - ну не знаю, вообще, там довольно понятные примеры в examples/ уже есть ко всем модулям. Добавил туда немного комментариев и упомянул их в описаниях модулей storage. Я бы предложил так оставить.

2022-08-08 16:48 UTC, osukhoroslov commented on crates/dslab-models/README.md
> +* [Throughput sharing model](./src/throughput_sharing/)
В сгенерированной документации ссылка не работает (404 Not Found).

2022-08-08 17:01 UTC, osukhoroslov commented on crates/dslab-models/src/model.rs
> +//! Definition of the throughput model trait.
Я бы все-таки оставил оригинальные развертнутые названия типа `ThrougputSharingModel`, вместо коротких типа `Model`, так легче ориентироваться к коде и не будет таких странностей в документации:

![image](https://user-images.githubusercontent.com/1322460/183472994-2aad9ce0-2723-4e68-87c9-873b07663f4d.png)

2022-08-08 18:05 UTC, osukhoroslov commented on crates/dslab-storage/src/bandwidth.rs
> +//! All implementations must have [`get_bandwidth`](BWModel::get_bandwidth) method, which returns bandwidth value from `size` and simulation context `ctx`.
Перенесите здесь и в других местах строки длиной более 120 символов.

2022-08-08 18:17 UTC, osukhoroslov commented on crates/dslab-models/src/throughput_sharing/model.rs
> +//! Definition of the throughput model trait.
```suggestion
//! Definition of the throughput sharing model trait.
```

2022-08-08 18:20 UTC, osukhoroslov commented on crates/dslab-models/src/throughput_sharing/model.rs
> +    /// Returns the next activity completion time (if any) along with corresponding activity item.
```suggestion
    /// Returns the next activity completion time (if any) along with corresponding activity item.
    ///
    /// The returned activity is removed from the model.
```

2022-08-08 18:22 UTC, osukhoroslov commented on crates/dslab-models/src/throughput_sharing/model.rs
> +    /// Returns reference to the next request of the model.
```suggestion
    /// Returns the next activity completion time (if any) along with corresponding activity item.
    ///
    /// In contrast to `pop`, the returned activity is not removed from the model.
```

2022-08-08 18:55 UTC, osukhoroslov commented on crates/dslab-storage/src/bandwidth.rs
> +//! These models represent different policies on how bandwidth changes over the size and the simulation time.
```suggestion
//! These models describe the dependence of storage bandwidth on the request size and the simulation time.
```

2022-08-08 19:24 UTC, osukhoroslov commented on crates/dslab-storage/src/bandwidth.rs
> +    /// Function which will be called each time when bandwidth is needed.
```suggestion
    /// Returns the bandwidth per request.
    ///
    /// It is called each time new read/write request is made.
    /// The model is provided with request size and simulation context.
    /// The latter can be used to obtain the current simulation time and the random engine.
```

2022-08-08 19:28 UTC, osukhoroslov commented on crates/dslab-storage/src/bandwidth.rs
> +//! These models represent different policies on how bandwidth changes over the size and the simulation time.
```suggestion
//! These models allow to dynamically compute per-request bandwidth based on the request size, current simulation time, etc.
```

2022-08-08 19:35 UTC, osukhoroslov commented on crates/dslab-storage/src/disk.rs
> +//! Simple disk model.
```suggestion
//! A simple disk model, which processes read/write requests sequentially.
```

2022-08-08 19:40 UTC, osukhoroslov commented on crates/dslab-storage/src/disk.rs
> +//! There is also a support for __bandwidth models__ - methods that provide bandwidth for given size.
```suggestion
//! There is also support for [bandwidth models](crate:bandwidth) that dynamically compute per-request bandwidth based on the request size, current simulation time, etc.
```

2022-08-08 19:47 UTC, osukhoroslov commented on crates/dslab-storage/src/disk.rs
> +//! Constant, randomized and empirical models are preset on this crate and arbitrary used-defined models can be defined by user.
```suggestion
//! Several implementations of these models are included in this crate, and other user-defined models can also be used.
```

2022-08-08 19:49 UTC, osukhoroslov commented on crates/dslab-storage/src/disk.rs
> +//! This model of disk **does not** support throughput sharing, so disk can process only one request on each time.
```suggestion
//! This model of disk **does not** support bandwidth sharing, so disk can process only one request at a time.
//! The requests are processed sequentially in FIFO order.
```

2022-08-08 19:52 UTC, osukhoroslov commented on crates/dslab-storage/src/disk.rs
> +//! Corresponding example: `storage-disk`
```suggestion
//! Usage example can be found in `examples/storage-disk`.
```

2022-08-08 20:33 UTC, osukhoroslov commented on crates/dslab-storage/src/fs.rs
> +//! Corresponding example: `storage-fs`
```suggestion
//! File system model.
//!
//! It is built on top of the disk model and supports modeling a storage system on the level of file system operations.
//! The model provides common methods for manipulating the file system such as creation and deletion of files, mounting and unmounting disks, reading and writing files.
//! It also supports modeling a system consisting of multiple disks mounted on distinct mount points.
//!
//! Usage example can be found in `examples/storage-fs`
```

2022-08-08 20:34 UTC, osukhoroslov commented on crates/dslab-storage/src/shared_disk.rs
> +//! Corresponding example: `storage-shared-disk`
```suggestion
//! Usage example can be found in `/examples/storage-shared-disk`
```

2022-08-08 20:38 UTC, osukhoroslov commented on crates/dslab-storage/src/fs.rs
> +    /// Creates file with name `file_name` if it doesn’t already exist.
Хорошо бы пояснить, что file_name это уникальное имя в пределах файловой системы, то есть по сути полный путь, а не просто имя. Может быть заменим на `file_path`?

2022-08-08 21:58 UTC, osukhoroslov commented on examples/storage-disk/src/main.rs
> +        // Creating uniformly randomized bandwidth model with bounds [DISK_WRITE_BW - 10; DISK_WRITE_BW + 10)
```suggestion
        // Creating randomized bandwidth model with uniform distribution in [DISK_WRITE_BW - 10; DISK_WRITE_BW + 10)
```

2022-08-08 22:13 UTC, osukhoroslov commented on crates/dslab-storage/src/shared_disk.rs
> +//! It depends on [dslab-models](../dslab-models/) crate and transfers all computations to abstract fair sharing model.
```suggestion
//! This is an alternative disk model that supports concurrent execution of requests with bandwidth sharing.
//! It uses the generic fair throughput sharing model from `dslab-models` to compute the request completion times.
```

2022-08-08 22:16 UTC, osukhoroslov commented on crates/dslab-storage/src/shared_disk.rs
> +//! Methods set is the same as for simple disk model.
Я тут подумал, а почему не сделать единый трейт для моделей диска? Это бы позволило использовать в FS не только простой Disk, но и SharedDisk, или какой-то ещё.

2022-08-08 22:22 UTC, kuskarov commented on crates/dslab-storage/src/shared_disk.rs
> +//! Methods set is the same as for simple disk model.
Можно. Хотя я бы подумал и просто насчет закапывания non-shared диска. Не очень понятно, зачем он нужен сейчас. Bandwidth models можно реализовать над slow throughput model.

2022-08-08 22:29 UTC, osukhoroslov commented on crates/dslab-models/src/throughput_sharing/README.md
> +
Надо еще написать про поддержку ThroughputFunction:

The dependence of resource throughput on the number of concurrent activities, i.e. throughput degradation, can be modeled with an arbitrary used-defined function.

2022-08-08 22:50 UTC, osukhoroslov commented on crates/dslab-storage/src/shared_disk.rs
> +//! Methods set is the same as for simple disk model.
Хотя бы потому, что просто disk обрабатывает запросы последовательно, чего сейчас не может делать shared disk. 

Кроме того непонятно как реализовать текущие bandwidth models над slow throughput model - bandwidth model вычисляет bandwidth для каждого запроса независимо и на все время его выполнения, а fair throughput model для всех запросов сразу и несколько раз. Хотя сами по себе текущие bandwidth models выглядят сомнительно - почему bandwidth определяется отдельно для каждого запроса и не меняется во время его выполнения? В SimGrid такое есть?

2022-08-15 00:21 UTC, kuskarov commented on crates/dslab-storage/src/bandwidth.rs
> +//! All implementations must have [`get_bandwidth`](BWModel::get_bandwidth) method, which returns bandwidth value from `size` and simulation context `ctx`.
Сделал, в nightly режиме rustfmt умеет сам, если добавить в rustfmt.toml

```
wrap_comments = true
comment_width = 120
```

2022-08-15 00:34 UTC, kuskarov commented on crates/dslab-storage/src/fs.rs
> +    /// Creates file with name `file_name` if it doesn’t already exist.
Согласен, сделал

2022-08-15 00:52 UTC, kuskarov commented on crates/dslab-models/README.md
> +* [Throughput sharing model](./src/throughput_sharing/)
Убрал ссылку

2022-08-15 00:52 UTC, kuskarov commented on crates/dslab-storage/src/lib.rs
> +//! This crate includes the models of storage resources, such as disk and file system.
Done

2022-08-15 00:52 UTC, kuskarov commented on crates/dslab-models/src/throughput_sharing/README.md
> +
Добавил

2022-08-15 00:57 UTC, kuskarov commented on crates/dslab-storage/src/shared_disk.rs
> +//! Methods set is the same as for simple disk model.
Нужно пересмотреть это все, да. Все-таки как-то хочется уменьшить дублирование кода, которое сейчас есть в двух версиях диска, абстракции правильно ввести. Предлагаю в этом PR не делать, вообще сначала надо еще источники посмотреть.

2022-08-15 10:20 UTC, osukhoroslov commented
Осталось описать алгоритмы из Throughput sharing model.

2022-09-09 19:32 UTC, osukhoroslov commented
> Осталось описать алгоритмы из Throughput sharing model.

Запушил по-быстрому свои правки. Осталось описать Fast model.

2022-09-20 21:02 UTC, osukhoroslov commented
@kuskarov доработал описание быстрого алгоритма, посмотрите и если нет замечаний то можно мержить

2022-09-20 21:02 UTC, osukhoroslov approved these changes

2022-10-01 18:08 UTC, merged