[faas] Parallel simulations
osukhoroslov/dslab pull request #110
Opened 2022-08-28 10:02 UTC by SYury

Добавил возможность создать и запустить несколько симуляций параллельно.

2022-09-10 16:08 UTC, osukhoroslov commented on crates/dslab-faas/src/parallel.rs
> +    let n_workers = configs.len();
Число потоков автоматически равно числу конфигов, это неудобно - хочется отдельно задавать число потоков.

2022-09-10 16:16 UTC, osukhoroslov commented on crates/dslab-faas/src/parallel.rs
> +pub struct ParallelHostData {
Напомни из-за чего пришлось делать все эти "параллельные" конфиги?

2022-09-10 16:22 UTC, SYury commented on crates/dslab-faas/src/parallel.rs
> +    let n_workers = configs.len();
Так ведь выше есть parallel_simulation_n_workers

2022-09-10 16:22 UTC, SYury commented on crates/dslab-faas/src/parallel.rs
> +pub struct ParallelHostData {
Чтобы навесить трейт Send на реализации алгоритмов.

2022-09-10 16:39 UTC, osukhoroslov commented on crates/dslab-faas/src/parallel.rs
> +pub struct ParallelHostData {
А почему нельзя навесить его прямо в Config?

2022-09-10 16:41 UTC, osukhoroslov commented on crates/dslab-faas/src/config.rs
> +pub struct HostData {
Предлагаю назвать `HostConfig` для единообразия

2022-09-10 16:43 UTC, osukhoroslov commented on crates/dslab-faas/src/host.rs
> +            let prewarm = f64::max(0.0, self.coldstart.borrow_mut().prewarm_window(app));
Это чтобы не пропускать отрицательные значения?

2022-09-10 16:44 UTC, osukhoroslov commented on crates/dslab-faas/src/simulation.rs
> +        let mut me = Self {
```suggestion
        let mut sim = Self {
```

2022-09-10 16:45 UTC, SYury commented on crates/dslab-faas/src/parallel.rs
> +pub struct ParallelHostData {
Тогда пользователь не сможет запустить даже однопоточную симуляцию в случае, если его алгоритмы небезопасны. А это мне видится вполне вероятной ситуацией, какой-нибудь Rc в планировщике уже не даст реализовать Send.

2022-09-10 16:46 UTC, SYury commented on crates/dslab-faas/src/host.rs
> +            let prewarm = f64::max(0.0, self.coldstart.borrow_mut().prewarm_window(app));
Да, в HybridHistogramPolicy я один раз получил очень маленькое по модулю отрицательное число и получил ошибку, что нельзя отправить событие в прошлое.

2022-09-10 17:16 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +        "Locality-based, warm only".to_string(),
Может добавить в трейт `get_name()`, чтобы не прописывать имена руками? Аналогично для политик в in the wild.

2022-09-10 17:28 UTC, osukhoroslov commented on crates/dslab-faas/src/parallel.rs
> +pub struct ParallelHostData {
Понятно. Проблема возникает из-за того, что конфиги со всякими трейт-объектами в них создаются ВНЕ потоков, ну и далее возникает потребность их передать в поток. А что если устранить эту причину и создавать полноценные конфиги уже ВНУТРИ потоков? Для этого вне потоков нужны какие-то "простые" конфиги (без трейт-объектов) и способ строить полноценные конфиги из них. Может быть пойти по такому пути? Простые конфиги могут быть еще полезны для поддержки чтения конфигурации экспериментов из файлов (как альтернативы описыванию всего в коде через API).

2022-09-10 17:30 UTC, osukhoroslov commented on crates/dslab-faas/src/parallel.rs
> +pub struct ParallelHostData {
Преобразование обычных конфигов в простые кстати тоже можно сделать (и будет еще возможность сбросить в файл конфиг эксперимента).

2022-10-10 07:41 UTC, SYury commented on crates/dslab-faas/src/simulation.rs
> +        let mut me = Self {
Переименовал

2022-10-10 07:42 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +        "Locality-based, warm only".to_string(),
Не хочу добавлять лишний метод в трейт, который не используется в самом симуляторе

2022-10-10 07:44 UTC, SYury commented on crates/dslab-faas/src/parallel.rs
> +pub struct ParallelHostData {
Я так и не придумал нормальный способ сделать текстовый конфиг при наличии пользовательских реализаций трейтов. Видимо лучшее, что можно сделать, это добавить читалку yamlов, куда пользователь передаёт набор фабрик String -> trait object. Такое пойдёт?

2022-10-10 16:13 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +        "Locality-based, warm only".to_string(),
Он может быть полезен в симуляторе тоже, например логировать (через log_debug) используемый шедулер при инициализации контроллера.

2022-10-10 16:14 UTC, osukhoroslov commented on crates/dslab-faas/src/parallel.rs
> +pub struct ParallelHostData {
Давай попробуем так и посмотрим

2022-10-13 20:06 UTC, osukhoroslov commented on crates/dslab-faas/src/parallel.rs
> +pub struct ParallelHostData {
Похоже на то что надо. Осталось только добавить `experiment.yaml` c таким содержимым:

```
coldstart_policy:
- No unloading
- 20-minute keepalive
- 45-minute keepalive
- 60-minute keepalive
- 90-minute keepalive
- 120-minute keepalive
- Hybrid Histogram policy, 2 hours bound
- Hybrid Histogram policy, 3 hours bound
- Hybrid Histogram policy, 4 hours bound
```

и передавать этот файл (и может config.yaml в него тоже утащить в поле config).

По сути у нас тогда появится файл, описывающий весь эксперимент, как набор исследуемых политик, который можно править при желании (не перекомпилируя код) и в пределах того, что позволяет resolver.

2022-10-14 18:38 UTC, SYury commented on crates/dslab-faas/src/parallel.rs
> +pub struct ParallelHostData {
Сделал

2022-10-14 18:40 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +        "Locality-based, warm only".to_string(),
Ок, убедил)
Добавил такой метод во все пользовательские трейты, но сделал при этом реализации-заглушки на случай, если пользователю не нужен никакой логгинг и он не хочет писать больше кода, чем нужно для задачи.

2022-10-21 17:03 UTC, osukhoroslov requested changes

2022-10-21 17:03 UTC, osukhoroslov commented on crates/dslab-faas/src/coldstart.rs
> +            "Fixed-time policy with keepalive = {:.2} and prewarm = {:.2}",
Как насчёт такого формата: `FixedTimeColdStartPolicy[keepalive=0.0,prewarm=0.0]`? (подсмотрел [здесь](https://github.com/atlarge-research/opendc/blob/aa9b32f8cd1467e9718959f400f6777e5d71737d/opendc-simulator/opendc-simulator-compute/src/main/kotlin/org/opendc/simulator/compute/power/MsePowerModel.kt#L48)).

Чем такой формат удобен:
- Используется имя реализации, то есть можно найти по нему код.
- Параметры перечислены в виде удобном для парсинга (например, если понадобится парсить лог).
- Этот же формат можно поддержать в резолвере когда по имени создается реализация (единообразие, пользователю легче освоиться).

Это предложение касется не только политик, но вообще всех таких компонентов, которым нужны имена и резолверы.

2022-10-21 17:05 UTC, osukhoroslov commented on crates/dslab-faas/src/parallel.rs
> +pub struct ParallelHostData {
Мне такой вариант нравится. Предлагаю эксперимент с планировщиками тоже перевести на `config.yaml`.

2022-10-24 16:17 UTC, SYury commented on crates/dslab-faas/src/parallel.rs
> +pub struct ParallelHostData {
Перевёл его тоже

2022-10-24 16:17 UTC, SYury commented on crates/dslab-faas/src/config.rs
> +/// YAML-serializeable config
Сделал

2022-10-24 16:19 UTC, SYury commented on examples/serverless-in-the-wild/src/main.rs
> +    let policy_resolver = |s: &str| -> Box<dyn ColdStartPolicy> {
Я сделал в dslab-faas и dslab-faas-extra нормальные ресолверы, которые читают что-то вида HybridHistogramPolicy[range=...,bin_len=...,...], а этот решил оставить тут, так как у меня в конфиге нормальные читаемые имена, которые я потом печатаю при обработке результатов.

2022-10-24 16:19 UTC, SYury commented on examples/serverless-in-the-wild/config.yaml
> +policies:
Сделал

2022-10-24 16:19 UTC, SYury commented on crates/dslab-faas/src/config.rs
> +        coldstart_policy_resolver: &dyn Fn(&str) -> Box<dyn ColdStartPolicy>,
Создал ConfigParamResolvers в config.rs

2022-10-24 16:19 UTC, SYury commented on examples/serverless-in-the-wild/src/main.rs
> +        Box::new(stub_idle_deployer_resolver),
Сделал

2022-10-24 16:20 UTC, SYury commented on crates/dslab-faas-extra/src/simple_schedulers.rs
> +    fn get_name(&self) -> String {
Добавил step, с hasher проблема, непонятно как напечатать произвольную функцию.

2022-10-24 16:20 UTC, SYury commented on crates/dslab-faas/src/coldstart.rs
> +            "Fixed-time policy with keepalive = {:.2} and prewarm = {:.2}",
Сделал такой формат везде

2022-10-29 16:57 UTC, osukhoroslov commented on examples/serverless-in-the-wild/src/main.rs
> +    let policy_resolver = |s: &str| -> Box<dyn ColdStartPolicy> {
Хорошо, пусть будет как пример пользовательского резолвера

2022-10-29 17:06 UTC, osukhoroslov commented on crates/dslab-faas-extra/src/simple_schedulers.rs
> +    fn get_name(&self) -> String {
Передавать отдельно hasher_name, и его печатать в name

2022-10-29 17:34 UTC, osukhoroslov requested changes

2022-10-29 17:34 UTC, osukhoroslov commented on crates/dslab-faas-extra/src/resolvers.rs
> +/// This file contains additional resolvers for YAML configs
комментарий к модулю должен быть первой строкой

2022-10-29 17:34 UTC, osukhoroslov commented on crates/dslab-faas/src/coldstart.rs
> +pub trait ColdStartConvertHelper {
Эта штука нам по-прежнему нужна?

2022-10-29 17:34 UTC, osukhoroslov commented on crates/dslab-faas/src/parallel.rs
> +pub fn parallel_simulation_n_workers(
Я правильно понимаю, что сейчас это (и ParallelConfig) нигде в примерах не используются? Если да, то предлгаю сделать небольшой пример `examples/faas-parallel` на это.

2022-10-29 17:34 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/config.yaml
> +  coldstart_policy: FixedTimeColdStartPolicy[keepalive=1200.0,prewarm=0.0]
Так будет работать?

```suggestion
  coldstart_policy: FixedTimeColdStartPolicy[keepalive=1200,prewarm=0]
```

2022-10-29 17:34 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +    resolvers.scheduler_resolver = Box::new(extra_scheduler_resolver);
Все-таки я не очень понимаю смысл отдельной библиотеки `faas-extra`. То, что реализации планировщиков находятся сейчас в ней выражается в том, что надо руками прописывать этот резолвер. А в дефолтном там только BaseScheduler, Почему бы не перенести как минимум планировщики в `dslab-faas`?

2022-10-29 17:34 UTC, osukhoroslov commented on examples/serverless-in-the-wild/src/main.rs
> +    let sim_config = experiment_config.base_config;
`base_config`

2022-10-29 17:34 UTC, osukhoroslov commented on examples/serverless-in-the-wild/src/main.rs
> +    let policy_resolver = |s: &str| -> Box<dyn ColdStartPolicy> {
Унеси в отдельную функцию чтобы не загромождать main

2022-10-29 17:34 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +    let sim_config = experiment_config.base_config;
`base_config`

2022-11-12 12:25 UTC, SYury commented on crates/dslab-faas-extra/src/simple_schedulers.rs
> +    fn get_name(&self) -> String {
Сделал класс ApplicationHasher, в котором можно указать имя

2022-11-12 12:25 UTC, SYury commented on crates/dslab-faas-extra/src/resolvers.rs
> +/// This file contains additional resolvers for YAML configs
Поправил

2022-11-12 12:25 UTC, SYury commented on crates/dslab-faas/src/coldstart.rs
> +pub trait ColdStartConvertHelper {
Она нужна для параллельного конфига

2022-11-12 12:25 UTC, SYury commented on crates/dslab-faas/src/parallel.rs
> +pub fn parallel_simulation_n_workers(
Сделал пример

2022-11-12 12:25 UTC, SYury commented on examples/faas-scheduling-experiment/config.yaml
> +  coldstart_policy: FixedTimeColdStartPolicy[keepalive=1200.0,prewarm=0.0]
Да

2022-11-12 12:26 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +    resolvers.scheduler_resolver = Box::new(extra_scheduler_resolver);
Изначально в faas-extra лежали вещи для воспроизведения статьи serverless in the wild, но потом смысл этой библиотеки стал теряться. Перенёс её в отдельный модуль extra внутри dslab-faas

2022-11-12 12:26 UTC, SYury commented on examples/serverless-in-the-wild/src/main.rs
> +    let sim_config = experiment_config.base_config;
Поменял

2022-11-12 12:26 UTC, SYury commented on examples/serverless-in-the-wild/src/main.rs
> +    let policy_resolver = |s: &str| -> Box<dyn ColdStartPolicy> {
Сделал

2022-11-12 12:26 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +    let sim_config = experiment_config.base_config;
Поменял

2022-11-12 13:38 UTC, SYury commented
Что-то CI падает при попытке собрать dslab-network, хотя его мои изменения вообще никак не затрагивают.

2022-11-13 17:39 UTC, osukhoroslov commented on crates/dslab-faas-extra/src/simple_schedulers.rs
> +    fn get_name(&self) -> String {
Добавь еще в ApplicationHasher метод `from_str`, чтобы можно было в конфиге `faas-scheduling-experiment` задать `LocalityBasedScheduler[hasher=Identity,step=1,warm_only=true]` и это подцепилось.

2022-11-13 17:57 UTC, osukhoroslov commented on crates/dslab-faas/src/extra/simple_schedulers.rs
> +        let f = hasher.unwrap_or(ApplicationHasher::new(|a| a, "Identity hasher".to_string()));
```suggestion
        let f = hasher.unwrap_or(ApplicationHasher::new(|a| a, "Identity".to_string()));
```

2022-11-13 17:57 UTC, osukhoroslov commented on examples/faas-parallel/readme.md
> +This crate shows how to setup several parallel simulations using ParallelHostConfig. An alternative way is to use YAML config, as it is done in Serverless in the Wild reproduction experiment.
```suggestion
This example demonstrates how to setup several parallel DSLab FaaS simulations using `ParallelHostConfig`. An alternative way is to use YAML config, as it is done in the [Serverless in the Wild](../serverless-in-the-wild) reproduction experiment.
```

2022-11-13 17:57 UTC, osukhoroslov commented on examples/faas-parallel/src/main.rs
> +    let args: Vec<String> = std::env::args().collect();
Может не здесь, но рекомендую в примерах faas перейти на clap, чтобы был нормальный CLI с подсказками и валидацией: https://github.com/osukhoroslov/dslab/blob/main/examples/dag/src/main.rs#L26

2022-11-13 17:57 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/config.yaml
> +  coldstart_policy: FixedTimeColdStartPolicy[keepalive=1200.0,prewarm=0.0]
Тогда убери .0

2022-11-13 18:03 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +    resolvers.scheduler_resolver = Box::new(extra_scheduler_resolver);
Это пока не решило проблему двух резолверов для планировщиков. Предлагаю унести все реализации планировщиков (включая Basic) в модуль schedulers, и сделать один дефолтный резолвер.

2022-11-13 18:07 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +    let sim_config = experiment_config.base_config;
Вижу по-прежнему `sim_config`

2022-11-13 18:07 UTC, osukhoroslov commented
> Что-то CI падает при попытке собрать dslab-network, хотя его мои изменения вообще никак не затрагивают.

Починили в main

2022-11-13 18:41 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +    resolvers.scheduler_resolver = Box::new(extra_scheduler_resolver);
Я думаю, что можно простые планировщики убрать прямо в scheduler.rs, а Hermes оставить в extra как и все другие вещи из статей

2022-11-13 19:13 UTC, osukhoroslov requested changes

2022-11-13 19:13 UTC, osukhoroslov commented on crates/dslab-faas/src/config.rs
> +pub fn stub_coldstart_policy_resolver(s: &str) -> Box<dyn ColdStartPolicy> {
В dslab-iaas мы пришли к следующему подходу при реализации резолверов:
- резолвер ([пример](https://github.com/osukhoroslov/dslab/blob/main/crates/dslab-iaas/src/core/vm_placement_algorithm.rs#L23)) не парсит строку с опциями, а делегирует это методу `from_str` соответствующей реализации ([пример](https://github.com/osukhoroslov/dslab/blob/main/crates/dslab-iaas/src/core/vm_placement_algorithm.rs#L124)) (лучше тем, что парсинг опций и их выписывание рядом, кстати может `get_name` переименуем в `to_string`?)
- резолвер знает какие реализации имеют опции, реализовывать `from_str` везде не надо
- резолвер находится в том же модуле, что и реализации или трейт

Предлагаю здесь сделать аналогично

2022-11-13 19:13 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +    resolvers.scheduler_resolver = Box::new(extra_scheduler_resolver);
Согласен

2022-12-18 13:43 UTC, SYury commented on examples/faas-scheduling-experiment/config.yaml
> +  coldstart_policy: FixedTimeColdStartPolicy[keepalive=1200.0,prewarm=0.0]
Готово

2022-12-18 13:43 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +    resolvers.scheduler_resolver = Box::new(extra_scheduler_resolver);
Сделал

2022-12-18 13:43 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +    let sim_config = experiment_config.base_config;
Теперь точно поменял

2022-12-18 13:43 UTC, SYury commented on crates/dslab-faas/src/extra/simple_schedulers.rs
> +        let f = hasher.unwrap_or(ApplicationHasher::new(|a| a, "Identity hasher".to_string()));
Сделал

2022-12-18 13:43 UTC, SYury commented on examples/faas-parallel/readme.md
> +This crate shows how to setup several parallel simulations using ParallelHostConfig. An alternative way is to use YAML config, as it is done in Serverless in the Wild reproduction experiment.
Сделал

2022-12-18 13:44 UTC, SYury commented on examples/faas-parallel/src/main.rs
> +    let args: Vec<String> = std::env::args().collect();
В следующем MR

2022-12-18 13:45 UTC, SYury commented on crates/dslab-faas/src/config.rs
> +pub fn stub_coldstart_policy_resolver(s: &str) -> Box<dyn ColdStartPolicy> {
Реализовал метод `from_options_map`, который создаёт объект из `HashMap<String, String>` и переделал резолверы на вызов этого метода

2022-12-18 14:24 UTC, SYury commented on crates/dslab-faas-extra/src/simple_schedulers.rs
> +    fn get_name(&self) -> String {
Сделал

2022-12-23 15:21 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +    let sim_config = experiment_config.base_config;
Ты сделал наоборот - все переменовал в `sim_config`, а мне наоборот хотелось везде увидеть `base_config`, и нравилось что в `ExperimentConfig` поле называлось `base_config`, показывая что это базовый конфиг для всех запусков в рамках эксперимента.

2022-12-23 15:25 UTC, osukhoroslov commented on examples/faas-parallel/src/main.rs
> +    let args: Vec<String> = std::env::args().collect();
Сделал #173

2022-12-23 16:51 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +    let sim_config = experiment_config.base_config;
Поторопился немного, поменял обратно

2022-12-23 16:55 UTC, osukhoroslov approved these changes

2022-12-23 18:31 UTC, merged