Add lookahead
osukhoroslov/dslab pull request #113
Opened 2022-09-12 11:11 UTC by maksim1744

Алгоритмы:
- [HEFT](https://sci-hub.mksa.top/https://ieeexplore.ieee.org/abstract/document/993206)
- [Lookahead](https://sci-hub.mksa.top/https://ieeexplore.ieee.org/abstract/document/5452513)
- [DLS](https://sci-hub.mksa.top/https://ieeexplore.ieee.org/abstract/document/207593)
- [PEFT](https://sci-hub.mksa.top/https://ieeexplore.ieee.org/abstract/document/6471969)

2022-09-23 16:33 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/lookahead.rs
> +pub enum DataTransferStrategy {
Предлагаю не дублировать DataTransferStrategy в каждом алгоритме, а перенести её в `src/data_transfer.rs`. И туда же унести DataTransferMode из `src/runner.rs`.

2022-09-23 16:41 UTC, osukhoroslov commented on examples/dag/src/main.rs
> +        "lookahead" => {
Добавьте еще вывод makespan в конце:

```
    sim.step_until_no_events();
    println!("Makespan: {:.2}", sim.time());
    println!(
        "Processed {} events in {:.2?} ({:.0} events/sec)",
        sim.event_count(),
        t.elapsed(),
        sim.event_count() as f64 / t.elapsed().as_secs_f64()
    );
```

2022-09-23 16:43 UTC, osukhoroslov commented
При запуске примера `dag` с `--scheduler lookahead` есть ошибка:

![image](https://user-images.githubusercontent.com/1322460/192010902-7bdcbe5e-ca46-4322-b9ee-e866feb27ec9.png)

2022-09-23 16:50 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/lookahead.rs
> +        if dag.get_tasks().iter().map(|task| task.min_cores).max()
Эту проверку надо делать не в планировщике, а в runner-e

2022-09-23 16:55 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/lookahead.rs
> +        let assign_task_on_resource = |task: usize,
Не нравятся такие объемные объявления функций внутри функции. Давайте вынесем их в отдельные функции планировщика.

2022-09-23 17:11 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/lookahead.rs
> +struct ScheduledTask {
Сейчас есть много пересечений с HEFT. Предлагаю уменьшить дублирование кода путем выделения общих частей list scheduling алгоритмов:

![image](https://user-images.githubusercontent.com/1322460/192015611-20234209-74de-4e2c-b827-2ebf206d78e1.png)

Например, у HEFT и Lookahead одинаковый код для task selection, а отличия только в функции для node (resource) selection.

2022-09-26 12:41 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/lookahead.rs
> +struct ScheduledTask {
Немного дублирования осталось, но большую часть вынес в отдельный файл

2022-09-26 13:43 UTC, osukhoroslov commented
> > При запуске примера `dag` с `--scheduler lookahead` есть ошибка:
> > ![image](https://user-images.githubusercontent.com/1322460/192010902-7bdcbe5e-ca46-4322-b9ee-e866feb27ec9.png)
> 
> Lookahead и heft никак не учитывают доступную память на ресурсах, поэтому могут назначить задачу на ресурс, на котором осталось мало свободной памяти. Можно находить на каждом ресурсе самый ранний отрезок с нужным количеством свободной памяти, аналогично тому как сейчас находится отрезок с нужным количеством ядер. Но там есть тонкости, можно в планы на будущее записать

Сделал #115

2022-09-26 18:13 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/common.rs
> +    let mut rank = vec![0.; total_tasks];
Лучше назвать `ranks`

2022-09-26 19:37 UTC, osukhoroslov reviewed
Пока только часть успел просмотреть

2022-09-26 19:37 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/heft.rs
> +            for &(succ, weight) in successors(task, dag).iter() {
Результат вызова `successors()` используется только чтобы потом получить `pred`. Предлагаю сделать функцию, которая сразу возвращает `pred`.

2022-09-26 19:37 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/heft.rs
> +        let rank = calc_ranks(avg_flop_time, avg_net_time, dag);
Перенесите эту строку туда, где ранги используются (сортировка задач).

2022-09-26 19:37 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/lookahead.rs
> +        let avg_flop_time = resources.iter().map(|r| 1. / r.speed as f64).sum::<f64>() / resources.len() as f64;
Вычисления всех этих avg_ тоже можно унести куда-то отсюда. Я бы уже завел структуру System, где бы держал ресурсы и сеть. И там тогда было бы удобно добавить методы для расчёта avg_.

2022-09-26 19:37 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/common.rs
> +pub fn assign_task_on_resource(
Название функции неудачное - здесь мы не назначаем задачу на ресурс буквально, а скорее хотим оценить её время старта и выполнения на ресурсе. Предлагаю назвать `evaluate_assignment`

2022-10-14 22:15 UTC, osukhoroslov requested changes
Вторая часть замечаний

2022-10-14 22:15 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/heft.rs
Нужен ли дебаг `scheduling [heft] task {} on resource {} on cores {:?} on time` ниже? Он только загромождает код алгоритма, и кажется можно сделать аналогичный, но универсальный, вывод снаружи при чтении результата вызова планировщика.

2022-10-14 22:15 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/heft.rs
Аналогично чтобы не загромождать основной алгоритм предлагаю вычисление expected makespan вынести в отдельную функцию.

2022-10-17 14:50 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/heft.rs
На первый вопрос -- все-таки есть отличие между тем как heft думает про назначение задач и как в итоге получится. Тут дебаг нужен был, чтобы увидеть различия между этим и понять, являются ли они ожидаемыми (например, из-за latency). Но если алгоритм уже написан, то наверное можно и убрать эти дебаги

2022-10-23 12:50 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/common.rs
> +    task: usize,
Переименуйте в `task_id`

2022-10-23 12:50 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/common.rs
> +        DataTransferStrategy::Eager => pred[task]
Здесь мы обходим предков таска, учитывая передачи данных от них. А потом ниже еще раз обходим инпуты таска, чтобы учесть отдельно передачи глобальных инпутов. Кажется это всё можно сильно упростить, если добавить в `DataItem` поле `producer: Option<usize>` с id таска, который производит эти данные. Тогда можно просто обойти inputs за один раз и вся необходимая информация уже есть (не надо отдельно считать predecessors):

```
    for input_id in dag.get_task(task).inputs.iter() {
        let data_item = dag.get_data_item(*input_id);
        match data_item.producer {
            Some(pred_id) => {
                // input is produced by task `pred_id`     
            }
            None => {
                // DAG input
            }
        }
    }
```

Как вариант можно вообще хранить всю необходимую информацию прямо внутри `inputs`:

```
pub struct Task {
    ...
    pub inputs: Vec<TaskInput>,
    ...
}

pub struct TaskInput {
    pub data_id: usize,
    pub size: u64,
    pub producer: Option<usize>,
}
```

Эти данные не изменяются и не занимают много места, избавляя от необходимости лезть за DataItem в DAG для подобных расчётов.

2022-10-23 12:50 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/common.rs
> +                if scheduled_task.start_time < possible_start + time {
В `time` входит `download_time`, но в действительности нам нужно окно размера `execution_time` (реального выполнения задачи). Загрузка входных данных конечно требует каких-то CPU ресурсов, но это не те самые ядра что для задачи и обычно предполагается что они выделены отдельно. Ну и для выгрузки выходных данных мы уже итак предполагаем что можно перекрывать вычисления и сетевые передачи. Таким образом,  `download_time` должно влиять на начало окна, а не на его размер.

2022-10-23 12:50 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/heft.rs
> На первый вопрос -- все-таки есть отличие между тем как heft думает про назначение задач и как в итоге получится. Тут дебаг нужен был, чтобы увидеть различия между этим и понять, являются ли они ожидаемыми (например, из-за latency). 

Отличия могут быть только в ожидаемых (алгоритмом) и реальных (полученных в ходе симуляции) временах старта и окончания задач. Вы про это? Глобально это разхождение можно заметить по разнице между ожидаемым и получившимся makespan. Но для полной картины предлагаю заносить эти времена внуть ScheduleTask-actions. Это позволит унифицированным образом собрать эти "ожидания" и при необходимости проанализировать расхождения. Также это открывает путь к реализации адаптивных динамических планировщиков, которые перестраивают расписание в случае отклонений от ожиданий статического алгоритма.

2022-10-23 12:59 UTC, osukhoroslov requested changes

2022-10-23 12:59 UTC, osukhoroslov commented on crates/dslab-dag/src/tests.rs
> +    assert_eq!(result, 30.5806369781494140625);
У нас пока нет простого примера графа с "посчитанным на бумажке" результатом для валидации корректности реализаций HEFT и других алгоритмов. Предлагаю такой пример сделать и добавить тест на нем на каждый добавленный алгоритм.

Например, можно взять пример из [статьи про HEFT](https://sci-hub.mksa.top/https://ieeexplore.ieee.org/abstract/document/993206) или из [статьи про Lookahead](https://www.ic.unicamp.br/~bit/ensino/mo809_1s13/papers/Escalonamento/PDP10-DAG%20Scheduling%20Using%20a%20Lookahead%20Variant%20of%20the%20Heterogeneous%20Earliest%20Finish%20Time%20Algorithm.pdf).

2022-10-24 10:49 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/common.rs
> +        DataTransferStrategy::Eager => pred[task]
Сделал `producer: Option<usize>`. Про `TaskInput` пока не уверен, мне кажется лишнее дублирование одной и той же информации может усложнить понимание

2022-11-21 20:20 UTC, osukhoroslov requested changes

2022-11-21 20:20 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/common.rs
> +    if resources[resource].compute.borrow().cores_total() < need_cores {
Предлагаю эту проверку перенести в самое начало метода, чтобы не тратить время на ненужные действия в случае неподходящего ресурса.

2022-11-21 20:20 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/lookahead.rs
> +                let mut children = (0..task_count).filter(|&task| !scheduled[task]).collect::<Vec<usize>>();
Название `children` запутывает, это же не просто дочерние задачи, а вообще все не назначенные. Предлагаю так и назвать `unscheduled_tasks`.

2022-11-21 20:20 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/lookahead.rs
> +            let mut best_task_finish_time = -1.;
Как я понял здесь мы храним лучший makespan для продлений расписания с помощью HEFT, предлагаю так и назвать `best_makespan`

2022-11-21 20:20 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/lookahead.rs
> +                for &child in children.iter() {
Нельзя ли здесь переиспользовать код HEFT, аналогично тому как это было в [pysimgrid](https://github.com/alexmnazarenko/pysimgrid/blob/master/pysimgrid/simdag/algorithms/lookahead.py#L73)?

2022-11-21 20:20 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/common.rs
> +    Some((est, time, cores))
Судя по коду планировщиков, им не особо часто нужен `time`, а чаще нужно `finish_time = est + time`, может его и выводить вместо `time`, ну или дополнительно к нему?

2022-11-28 11:45 UTC, maksim1744 commented on crates/dslab-dag/src/runner.rs
> +use crate::data_item::{DataItemState, DataTransferMode};
Да, стратегия только для алгоритмов планирования сейчас. Lazy можно симулировать, если отдавать расписание из планировщика по шагам в нужные моменты времени

2022-11-28 14:21 UTC, osukhoroslov commented on crates/dslab-dag/src/runner.rs
> +use crate::data_item::{DataItemState, DataTransferMode};
Завел #162

2022-11-28 14:34 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/heft.rs
> +                let (est, finish_time, cores) = res.unwrap();
Давайте везде заменим `est` на `start_time`, чтобы не надо было гадать что это за сокращение и сочеталось с `finish_time`

2022-12-02 16:48 UTC, osukhoroslov commented on crates/dslab-dag/src/runner.rs
> +        expected_span: Option<(f64, f64)>,
Решили сделать структуру TimeSpan с полями.

2022-12-02 19:12 UTC, osukhoroslov requested changes

2022-12-02 19:12 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/peft.rs
> +                            .unwrap_or(0.)
вроде `unwrap_or` тут не нужен, всегда должно быть что-то, то есть просто `unwrap`

2022-12-02 19:12 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/peft.rs
> +                if best_finish == -1. || best_finish > finish_time {
Оптимизируется не просто EFT как в HEFT, а сумма EFT + OCT:

![изображение](https://user-images.githubusercontent.com/1322460/205367229-ab2149f4-bf1e-4cd4-b6da-c458e06911e0.png)

2022-12-02 19:12 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/lookahead.rs
> +                        assert!(best_finish != -1.);
```suggestion
                        assert_ne!(best_finish, -1.);
```

2022-12-02 19:12 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/lookahead.rs
> +            assert!(best_finish != -1.);
```suggestion
            assert_ne!(best_finish, -1.);
```

2022-12-05 12:08 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/dls.rs
> +            for &task_id in task_ids.iter().filter(|&i| !scheduled[*i]).filter(|&i| {
Просто добавлять дочерние нельзя, у них могут быть другие зависимости. Надо тогда будет для каждой задачи поддерживать количество оставшихся незавершенных зависимостей, не уверен, что в итоге получится короче. А на асимптотику такой перебор не влияет

2022-12-05 12:09 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/dls.rs
> +        let mut task_finish_times = vec![1e100; task_count];
Не знаю, поставил 0 (проверил, что ничего не поменялось)

2022-12-05 12:18 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/peft.rs
> +                                        * config.data_transfer_mode.net_time(
![image](https://user-images.githubusercontent.com/38928209/205635053-c1417686-9cba-421c-8dc6-c0c3747c7a09.png)

Наверное меня здесь смутило c[i][j] = 0 если процессоры одинаковые. Вообще немого странно ставить такое условие, но при этом для разных процессоров брать среднее по всем парам, хотя мы можем посчитать явно время передачи для известной пары. В принципе можно поправить, чтобы был честный peft

2022-12-05 12:38 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/heft.rs
>          log_info!(
Ниже еще ответил

Идея как-то отделить статические планировщики мне нравится, но я бы еще подумал над какими-нибудь другими способами это сделать. Предложенный вариант никак не защищает от того, чтобы например что-то отдавать в `on_task_state_changed` даже при наличии `is_static`

2022-12-05 12:38 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/dls.rs
> +        result.into_iter().map(|(_, b)| b).collect()
Мне не очень нравится наличие таких неявных связей, которые в коде никак не выражаются и не проверяются. Например `is_static = true <=> scheduler.on_task_state_changed === Vec::new()`, или что `is_static` гарантирует, что известны `expected_span` --- может там какой-нибудь планировщик просто посчитал topsort и сложил задачи на ресурсы как попало, не считая никаких времен

2022-12-05 15:27 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/peft.rs
> +                                        * config.data_transfer_mode.net_time(
Предлагаю поддержать оба варианта и задавать поведение с помощью опции при создании алгоритма. По умолчанию пусть будет ваш, он мне тоже кажется более логичным.

2022-12-12 16:36 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/peft.rs
> +                                        * match self.original_network_estimation {
Лучше заменить на `if ... else`

2022-12-12 16:44 UTC, osukhoroslov commented
Насчёт #166. Учесть передачу выходных данных в makespan можно с помощью добавления в DAG фиктивной exit-задачи с нулевым весом, к которой пристыкованы все обычные выходные задачи. Видимо в тот момент, когда DAG уже не будет меняться (в начале запуска, например). У этой задачи должно быть зафиксировано место её выполнения - мастер, и планировщик должен это понять и не планировать её. Надо посмотреть насколько сложно будет добавить это в текущий код. Из плюсов тогда сильно упростится вычисление makespan, так как достаточно будет взять максимальное время окончания задачи. Ну и может где-то ещё тоже логика будет проще.

2022-12-19 16:24 UTC, osukhoroslov approved these changes

2022-12-19 16:25 UTC, merged