Add run_experiment
osukhoroslov/dslab pull request #116
Opened 2022-09-26 19:03 UTC by maksim1744

Например, `cargo run -- --schedulers schedulers.yaml --dags ../dag/dags --platforms ./platforms/ -o result.json`

2022-09-26 19:44 UTC, osukhoroslov commented
Предлагаю вместо `platform` везде использовать `system`

2022-10-10 19:27 UTC, osukhoroslov requested changes

2022-10-10 19:27 UTC, osukhoroslov commented on examples/dag-run-experiment/src/main.rs
> +    schedulers: String,
Вместо файла с алгоритмами предлагаю сделать файл, описывающий эксперимент целиком, (например, `my-experiment.yaml`) с такой структурой:

```
dags:
  - path to dag file or dir with such files, relative to this file
  - multiple files or dirs can be specified
systems:
  - path to system file or dir with such files, relative to this file
  - multiple files or dirs can be specified
schedulers:
  - Heft
  - Simple
```

Чтобы воспроизвести эксперимент достаточно иметь архив с этим файлом и всеми файлами/папками, на которые он ссылается.

Соответственно в качестве аргументов достаточно будет оставить только путь к этому файлу, убрав пути к графам и системам.

2022-10-10 19:27 UTC, osukhoroslov commented on examples/dag-run-experiment/src/main.rs
> +    output: String,
По умолчанию можно использовать имя файла эксперимента. Например, если это `my-experiment.yaml`, то результаты можно записать в `my-experiment-results.json` рядом с файлом эксперимента.

2022-10-10 19:27 UTC, osukhoroslov commented on examples/dag-run-experiment/src/main.rs
> +    jobs: usize,
Лучше назвать `threads` (Number of threads for running experiment), так будет понятнее

2022-10-10 19:27 UTC, osukhoroslov commented on examples/dag-run-experiment/src/main.rs
> +    for ((dag_name, dag), (system_name, resources), network, scheduler_type) in experiments.into_iter() {
Это всё предлагаю унести в функцию `experiment.run(num_threads)`, которая возвращает `Vec<RunResult>`.

2022-10-10 19:27 UTC, osukhoroslov commented on examples/dag-run-experiment/src/main.rs
> +struct ExperimentResult {
```suggestion
struct RunResult {
```

2022-10-10 19:27 UTC, osukhoroslov commented on examples/dag-run-experiment/src/main.rs
> +impl YamlScheduler {
Это надо унести в dslab-dag. Здесь должен остаться только код, иллюстрирующий как запустить эксперимент, получить его результаты и сохранить их.

2022-12-26 14:59 UTC, maksim1744 commented on examples/dag-run-experiment/src/main.rs
> +    let systems = systems
С текущей реализацией system так не получится

2022-12-26 15:34 UTC, osukhoroslov commented on examples/dag-run-experiment/src/main.rs
> +    let systems = systems
Можно переделать, чтобы получилось. Предлагаю так:

1. Конфигурацию системы из файла вычитывать в тип System:

```
pub struct System {
    pub resources: Vec<Resource>,
    pub network: Network,
}
```

2. Передавать System в `DagSimulation::new()` - сразу и сеть и ресурсы (отдельное добавление ресурсов здесь не требуется). внутри сразу избавляться от System и хранить отдельно network и resources.

3. Внутри Runner и Scheduler не использовать System и вернуть как было - передавать отдельно сеть и ресурсы.

2022-12-26 15:35 UTC, osukhoroslov commented on examples/dag-run-experiment/src/main.rs
> +    let systems = systems
По сути System удобен только на этапе конфигурации экспериментов, а далее внутри удобнее работать с ресурсами и сетью по отдельности

2022-12-26 18:50 UTC, osukhoroslov requested changes

2022-12-26 18:50 UTC, osukhoroslov commented on crates/dslab-dag/src/experiment.rs
> +                        data_transfer_mode: DataTransferMode::ViaMasterNode,
Надо поддержать эту настройку в конфиг-файле эксперимента

2022-12-26 18:50 UTC, osukhoroslov commented on crates/dslab-dag/src/experiment.rs
> +                    scheduler: format!("{:?}", run.scheduler),
Здесь должна быть точно такая строка как в конфиге эксперимента.

2022-12-26 18:50 UTC, osukhoroslov commented on crates/dslab-dag/src/experiment.rs
> +                    "\rFinished {}/{} runs",
Еще было бы полезно выводить оценку оставшегося времени на основе прошедшего времени и процента завершенных запусков.

2022-12-26 18:50 UTC, osukhoroslov commented on crates/dslab-dag/src/network.rs
> +pub struct Network {
```suggestion
pub struct NetworkConfig {
```

2022-12-26 18:50 UTC, osukhoroslov commented on crates/dslab-dag/src/network.rs
> +pub fn read_network(file: &str) -> Network {
```suggestion
pub fn read_network_config(path: &str) -> Network {
```

2022-12-26 18:50 UTC, osukhoroslov commented on crates/dslab-dag/src/network.rs
> +    let network = read_network(file);
```suggestion
    let network_confing = read_network_config(file);
```

2022-12-26 18:50 UTC, osukhoroslov commented on crates/dslab-dag/src/network.rs
> +            std::process::exit(1);
Почему не просто panic?

2022-12-26 18:50 UTC, osukhoroslov commented on crates/dslab-dag/src/experiment.rs
> +            .filter(|(resources, network, _file_name)| !resources.is_empty() && network.make_network().is_some());
Проверка конфигов на их валидность перед запуском эксперимента нужна. Но надо не просто молча их игнорировать, а падать с ошибкой, чтобы пользователь знал о проблеме.

2022-12-26 18:50 UTC, osukhoroslov commented on crates/dslab-dag/src/resource.rs
> +pub struct YamlResource {
```suggestion
pub struct ResourceConfig {
```

2022-12-26 18:50 UTC, osukhoroslov commented on examples/dag-run-experiment/experiment.yaml
> +schedulers:
Добавьте все поддерживаемые сейчас планировщики

2022-12-26 18:50 UTC, osukhoroslov commented on examples/dag-run-experiment/src/main.rs
> +    /// File with configurations
```suggestion
    /// Path to file with experiment configuration
```

2022-12-26 18:50 UTC, osukhoroslov commented on examples/dag-run-experiment/src/main.rs
> +    /// Output file
```suggestion
    /// Path to output file with experiment results
```

2022-12-26 18:50 UTC, osukhoroslov commented on examples/dag-run-experiment/src/main.rs
> +    #[clap(short, long, default_value = "8")]
Вместо дефолтного 8 лучше сделать равным [std::thread::available_parallelism](https://doc.rust-lang.org/std/thread/fn.available_parallelism.html)

2022-12-26 18:50 UTC, osukhoroslov commented on examples/dag-run-experiment/src/main.rs
> +fn main() {
Не хватает пустой строки перед main()

2022-12-26 18:50 UTC, osukhoroslov commented on examples/dag-run-experiment/src/main.rs
> +    input: String,
```suggestion
    config: String,
```

2022-12-26 18:51 UTC, osukhoroslov commented on examples/dag-run-experiment/src/main.rs
> +    let systems = systems
Снимаю это предложение

2023-01-09 14:55 UTC, maksim1744 commented on crates/dslab-dag/src/experiment.rs
> +                    scheduler: format!("{:?}", run.scheduler),
Добавил `scheduler_resolver`, в таком виде уже неактуально

2023-01-13 15:53 UTC, osukhoroslov commented on crates/dslab-dag/src/experiment.rs
> +            });
```suggestion
        let systems = get_all_files(&config.systems).into_iter().map(|path| {
            let file_name = path.file_name().unwrap().to_str().unwrap().to_string();
            let resources = read_resources(&path);
            assert!(
                !resources.is_empty(),
                "Can't have empty list of resources: {}",
                file_name
            );
            let network = read_network_config(&path);
            assert!(
                network.make_network().is_some(),
                "Unknown network model in {}: {:?}",
                file_name,
                network
            );
            (file_name, resources, network)
        });
```

2023-01-13 16:04 UTC, osukhoroslov commented on crates/dslab-dag/src/scheduler_resolver.rs
> +use std::cell::RefCell;
Предлагаю перенести это все в `scheduler.rs`, чтобы не множить модули.

2023-01-13 16:05 UTC, osukhoroslov commented on crates/dslab-dag/src/scheduler_resolver.rs
> +        "Heft" => Some(Rc::new(RefCell::new(HeftScheduler::from_scheduler_params(params)))),
HEFT, PEFT и DLS хочется задавать заглавными буквами

2023-01-13 19:39 UTC, osukhoroslov requested changes

2023-01-13 19:39 UTC, osukhoroslov commented on crates/dslab-dag/src/experiment.rs
> +            .map(|s| SchedulerParams::from_str(&s).unwrap_or_else(|| panic!("Can't parse scheduler params from {s}")))
Вместо проверки на None и паники со ошибкой здесь лучше в `from_str` сразу возвращать `Result<Self, String>`, а здесь тогда просто вызвать unwrap(). Или даже вообще сразу паниковать в `from_str`, потому что если формат неправильный, то это фатально.

2023-01-13 19:39 UTC, osukhoroslov commented on crates/dslab-dag/src/experiment.rs
> +                    panic!("Can't parse scheduler params from params {params:?}")
Здесь тоже кажется логичным паниковать сразу в резолвере и убрать Option. Кстати сообщение здесь такое же что выше, а должно быть другое, типа "Can't resolve scheduler...".

2023-01-13 19:39 UTC, osukhoroslov commented on crates/dslab-dag/src/scheduler_resolver.rs
> +    match params.name.as_ref() {
```suggestion
    match params.name.as_str() {
```

2023-01-13 19:39 UTC, osukhoroslov commented on crates/dslab-dag/src/experiment.rs
> +                    scheduler: format!("{}", run.scheduler),
```suggestion
                    scheduler: run.scheduler.to_string(),
```

2023-01-13 19:39 UTC, osukhoroslov commented on crates/dslab-dag/src/experiment.rs
> +        result.sort_by(|a, b| a.makespan.total_cmp(&b.makespan));
Сортировка по makespan не нужна, лучше возвращать результаты в некотором стабильном порядке декартового произведения (dag, system. scheduler).

2023-01-13 19:39 UTC, osukhoroslov commented on crates/dslab-dag/src/experiment.rs
> +        let result = Arc::new(Mutex::new(Vec::new()));
Переименуйте в `results`

2023-01-16 14:10 UTC, maksim1744 commented on crates/dslab-dag/src/experiment.rs
> +                    Duration::from_secs_f64(elapsed.as_secs_f64() / finished as f64 * (total_runs - finished) as f64);
Чтобы распечаталось красиво

2023-01-16 14:19 UTC, maksim1744 commented on crates/dslab-dag/src/scheduler_resolver.rs
> +    params: BTreeMap<String, String>,
Сохранять порядок наверное не обязательно, а вот если он будет меняться между запусками -- это довольно странно. Решил, что сортировать по алфавиту нормально

2023-01-16 14:34 UTC, maksim1744 commented on crates/dslab-dag/src/experiment.rs
> +                    panic!("Can't parse scheduler params from params {params:?}")
Если из scheduler_resolver возвращать Option, кажется их будет проще соединять в цепочку.
Что-то вида
```rs
Experiment::load("file", |s| my_resolver(s).or_else(|| default_resolver(s)))
```

2023-01-16 15:31 UTC, osukhoroslov commented on examples/dag-run-experiment/src/main.rs
> +}
От unwrap тоже можно избавиться:

```
fn main() -> std::io::Result<()> {
    let args = Args::parse();

    let experiment = Experiment::load(&args.config, default_scheduler_resolver);
    let result = experiment.run(args.threads);

    let mut output = std::fs::File::create(args.output.unwrap_or_else(|| {
        args.config
            .with_file_name([args.config.file_stem().unwrap().to_str().unwrap(), "-results"].concat())
            .with_extension("json")
    }))?;
    output.write_all(serde_json::to_string_pretty(&result).unwrap().as_bytes())
}
```

2023-01-16 17:00 UTC, osukhoroslov commented on crates/dslab-dag/src/scheduler_resolver.rs
> +    params: BTreeMap<String, String>,
Лучше сохранять порядок, чтобы в json с результатами значение "scheduler" совпадала со строкой из конфига эксперимента. Это может быть удобно для работы с результатами, написания скриптов обработки результатов.

2023-01-16 17:00 UTC, osukhoroslov commented on crates/dslab-dag/src/scheduler_resolver.rs
> +    params: BTreeMap<String, String>,
Так что предлагаю перейти на IndexMap

2023-01-16 17:58 UTC, osukhoroslov commented on crates/dslab-dag/src/scheduler.rs
> +    /// Creates SchedulerParams from string, for example `Porfolio[algo=8,other_param=xyz]`.
```suggestion
    /// Creates SchedulerParams from a string in the following format: `SchedulerName[param1=value1,param2=value2...]`.
```

2023-01-16 18:46 UTC, osukhoroslov approved these changes

2023-01-16 18:48 UTC, merged