Add throughput models comparison
osukhoroslov/dslab pull request #118
Opened 2022-10-10 19:06 UTC by maksim1744

2022-10-10 19:51 UTC, osukhoroslov commented on crates/dslab-models/src/throughput_sharing/tests.rs
> +        (x - y).abs() < eps || (x.max(y) - x.min(y)) / x.min(y) < eps,
В чем суть этой правки?

2022-10-10 21:03 UTC, maksim1744 commented on crates/dslab-models/src/throughput_sharing/tests.rs
> +        (x - y).abs() < eps || (x.max(y) - x.min(y)) / x.min(y) < eps,
Обсуждали в телеграме
> По поводу погрешности в моделях — обычно используется не абсолютная ошибка, а относительная. Потому что, например, у обычных f64 на мантиссу уходит 52 бита, то есть просто представить число в f64 можно с относительной точностью порядка `2^-52 ~= 1e-15`.
> В частности, если в тесте fairness поставить число активностей 1000, то падает с ошибкой `743365.925366537 != 743365.925366538`, а это относительная разность как раз около 1е-15, странно требовать что-то на уровне машинной точности, это почти ничем не лучше сравнения на равенство. И если условие в assert_float_eq поменять на `(x - y).abs() < eps || (x.max(y) - x.min(y)) / x.min(y) < eps`, то можно увеличивать число активностей хоть до 10000 — не падает

2022-10-13 18:59 UTC, osukhoroslov requested changes

2022-10-13 18:59 UTC, osukhoroslov commented on examples/throughput-model-comparison/Cargo.toml
> +edition = "2021"
Не забываем про license = "MIT OR Apache-2.0"

2022-10-13 19:01 UTC, osukhoroslov commented on crates/dslab-models/src/throughput_sharing/tests.rs
> +        (x - y).abs() < eps || (x.max(y) - x.min(y)) / x.min(y) < eps,
Предлагаю тогда оставить только проверку на относительную ошибку, а само значение ошибки уменьшить до 1e-12.

2022-10-13 19:15 UTC, maksim1744 commented on crates/dslab-models/src/throughput_sharing/tests.rs
> +        (x - y).abs() < eps || (x.max(y) - x.min(y)) / x.min(y) < eps,
Относительная ошибка плохо работает для маленьких чисел. Например, для 0 и eps она равна 1 или inf, смотря на что делить

2022-10-13 19:42 UTC, osukhoroslov commented on crates/dslab-models/src/throughput_sharing/tests.rs
> +        (x - y).abs() < eps || (x.max(y) - x.min(y)) / x.min(y) < eps,
Действительно. Ну тогда только eps уменьшить до 1e-12, вроде это ничего не сломает.

2022-10-17 18:32 UTC, osukhoroslov approved these changes

2022-10-17 18:36 UTC, merged