feat iaas: more algorithms
osukhoroslov/dslab pull request #148
Opened 2022-11-13 14:01 UTC by vetand

2022-11-14 15:21 UTC, osukhoroslov commented
На будущее - добавляйте пожалуйста в имя ветки префикс с именем модуля DSLab (iaas) в данном случае: `iaas-new-algorithms`

2022-11-14 20:40 UTC, osukhoroslov requested changes

2022-11-14 20:40 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithm.rs
> +                let perp_dist = sin * dist_two;
У такого подхода кажется есть проблема - угол известен, но есть два варианта (зеленый и красный на рисунке ниже), при которых угол одинаковый, но изменение Perp идет в разные стороны. Так что видимо проще в лоб посчитать отдельно Perp(исходный) и Perp(с размещением), и взять разницу между первым и вторым.

![изображение](https://user-images.githubusercontent.com/1322460/201760901-834a5a32-4ba3-4b79-9f82-f69a0223ac48.png)

2022-11-14 20:40 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithm.rs
> +                if perp_dist < min_perp_dist {
Стоп, а почему мы минимизируем? В оригинале чем больше изменение Perp тем лучше.

2022-11-28 07:52 UTC, vetand commented
Пока не доделал интересные тесты для алгоритмов

2022-11-28 15:32 UTC, vetand commented on crates/dslab-iaas/src/core/vm_placement_algorithm.rs
> +                if perp_dist < min_perp_dist {
Предыдущие 2 коммента объясняются тем, что я вместо Delta Perp Distance сделал просто Perp Distance со всеми вытекающими)

Поправил

2022-11-28 22:04 UTC, osukhoroslov requested changes

2022-11-28 22:04 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/norm_based_greedy.rs
> +                let diff = cpu_diff + memory_diff;
```suggestion
                let total_cpu = pool_state.get_total_cpu(host);
                let total_memory = pool_state.get_total_memory(host);
                let available_cpu = pool_state.get_available_cpu(host);
                let available_memory = pool_state.get_available_memory(host);
                let cpu_diff = (alloc.cpu_usage - available_cpu) as f64 / total_cpu as f64;
                let memory_diff = (alloc.memory_usage - available_memory) as f64 / total_memory as f64;
                let diff = cpu_weight * cpu_diff.powi(2) + memory_weight * memory_diff.powi(2);
```

2022-11-29 18:22 UTC, vetand commented on crates/dslab-iaas/src/core/vm_placement_algorithms/norm_based_greedy.rs
> +                let diff = cpu_diff + memory_diff;
Только всё-таки в 40 строчке наоборот, let cpu_diff = (available_cpu - alloc.cpu_usage) as f64 / total_cpu as f64; а то отрицательные значения получаются

2022-11-29 19:00 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/norm_based_greedy.rs
> +                let diff = cpu_diff + memory_diff;
Это не важно, все равно далее возводится в квадрат

2022-11-29 19:09 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/dot_product.rs
> +                    + memory_product / (pool_state.get_total_memory(host) as f64).powi(2);
```suggestion
                let cpu_product = pool_state.get_available_cpu(host) * alloc.cpu_usage;
                let memory_product = pool_state.get_available_memory(host) * alloc.memory_usage;
                let product = cpu_product as f64 / (pool_state.get_total_cpu(host)).pow(2) as f64
                    + memory_product as f64 / (pool_state.get_total_memory(host)).pow(2) as f64;
```

2022-11-29 19:19 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/cosine_similarity.rs
> +                let usage_mem: f64 = pool_state.get_allocated_memory(host) as f64 + alloc.memory_usage as f64;
```suggestion
                let capacity_cpu = pool_state.get_total_cpu(host) as f64;
                let capacity_mem = pool_state.get_total_memory(host) as f64;
                let capacity_norm = (capacity_cpu.powi(2) + capacity_mem.powi(2)).sqrt();
                let usage_cpu = pool_state.get_allocated_cpu(host) as f64 + alloc.cpu_usage as f64;
                let usage_mem = pool_state.get_allocated_memory(host) as f64 + alloc.memory_usage as f64;
```

2022-11-29 19:19 UTC, vetand commented on crates/dslab-iaas/src/core/vm_placement_algorithms/norm_based_greedy.rs
> +                let diff = cpu_diff + memory_diff;
Да, но u32 из-за отрицательных значений падает

2022-11-29 19:19 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/weighted_dot_product.rs
> +                    + memory_product / (pool_state.get_total_memory(host) as f64).powi(2);
```suggestion
                let cpu_product = (pool_state.get_available_cpu(host) * alloc.cpu_usage) as f64;
                let memory_product = (pool_state.get_available_memory(host) * alloc.memory_usage) as f64;
                let product = cpu_weight * cpu_product / (pool_state.get_total_cpu(host)).pow(2) as f64
                    + memory_weight * memory_product / (pool_state.get_total_memory(host)).pow(2) as f64;
```

2022-11-29 19:29 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/delta_perp_distance.rs
> +    distance
```suggestion
    used_norm * sin
```

2022-11-29 19:31 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithm.rs
> +        "CosineSimilarity" => return Box::new(CosineSimilarity::new()),
Уберите везде `return` перед `Box`, он лишний

2022-11-29 19:33 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/best_fit.rs
> +        return result;
```suggestion
        result
```

2022-11-29 19:33 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/best_fit_threshold.rs
> +        return result;
```suggestion
        result
```

2022-11-29 19:36 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/first_fit.rs
> +        return None;
```suggestion
        pool_state
            .get_hosts_list()
            .into_iter()
            .find(|&host| pool_state.can_allocate(&alloc, host) == AllocationVerdict::Success)
```

2022-11-29 19:37 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/worst_fit.rs
> +        return result;
```suggestion
        result
```

2022-11-29 19:51 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/norm_based_greedy.rs
> +                let diff = cpu_diff + memory_diff;
Верно, стормозил

2022-12-10 20:20 UTC, osukhoroslov commented
@vetand отрефакторил и причесал код, добавил в тесты остальные алгоритмы. Сейчас у WorstFit, DotProduct и WeightedDotProduct одинаковые хосты в тесте. Попробуйте поменять конфигурацию тестов так, чтобы у всех алгоритмов были отличия.

2022-12-12 16:54 UTC, merged