Cargo clippy improvments
osukhoroslov/dslab pull request #152
Opened 2022-11-25 12:37 UTC by KiK0S

Там было достаточно много правок от клиппи, я сначала делал все осмысленные, потом оказалось, что их как-то много и я пересел за perf + correctness. По большей части это убирает ненужные clone, и не создает аргументы в функциях по типу expect, которые еще неизвестно, будут ли вызываться

2022-11-25 13:58 UTC, osukhoroslov requested changes

2022-11-25 13:58 UTC, osukhoroslov commented on crates/dslab-faas-extra/src/hybrid_histogram.rs
> +        if let std::collections::hash_map::Entry::Vacant(e) = self.data.entry(id) {
Надо заимпортить std::collections::hash_map::Entry, и ссылаться просто на Entry здесь и ниже

2022-11-25 13:58 UTC, osukhoroslov commented on tools/dag-draw/src/draw_utils.rs
> +    write!(result, "Task: {}\n\n", task.name).unwrap();
Тут нельзя заменить `.unwrap()` на `?` как здесь? https://doc.rust-lang.org/std/macro.write.html

2022-11-25 13:58 UTC, osukhoroslov commented on tools/dag-draw/src/draw_utils.rs
> +use std::fmt::Write;
Надо перенести выше к импортам из std

2022-11-25 14:29 UTC, KiK0S commented on tools/dag-draw/src/draw_utils.rs
> +    write!(result, "Task: {}\n\n", task.name).unwrap();
так ?  возвращает Error, если функция возвращает Result, а эта функция не возвращает Result. Да и тут unwrap символический

2022-11-25 14:33 UTC, KiK0S commented on tools/dag-draw/src/draw_utils.rs
> +use std::fmt::Write;
сделал

2022-11-25 14:33 UTC, KiK0S commented on crates/dslab-faas-extra/src/hybrid_histogram.rs
> +        if let std::collections::hash_map::Entry::Vacant(e) = self.data.entry(id) {
сделал

2022-11-25 16:11 UTC, KiK0S commented on tools/dag-draw/src/draw_utils.rs
> +    write!(result, "Task: {}\n\n", task.name).unwrap();
он нужен потому что макрос применяется еще и для файлов, а там может что-то не записаться. в строке, я так понимаю, он всегда должен отрабатывать

2022-11-25 16:38 UTC, osukhoroslov commented
@KiK0S еще ошибки clippy обнаружились, см. пайплайн

2022-11-25 16:39 UTC, osukhoroslov requested changes
Остались ошибки clippy, пайплайн не проходит

2022-11-26 11:30 UTC, KiK0S commented
https://github.com/KiK0S/dslab/actions/runs/3553497264/jobs/5969041245
Странно, что так произошло, видимо разница версий. Поправил, в форке завелось

2022-11-26 11:59 UTC, osukhoroslov approved these changes

2022-11-26 11:59 UTC, merged