[mp] example mp membership (hw 6 distsys course hse)
osukhoroslov/dslab pull request #163
Opened 2022-12-01 18:04 UTC by KiK0S

Есть проблемы с написанием авторского решения, потому что старые авторские решения ловят какой-то новый ассерт

```
thread 'main' panicked at 'Timer "send-gossip" is already set by process "6" (active timer names should be unique!)', crates/dslab-mp/src/node.rs:175:21
```

но сколько-то тестов проходит, и если поменять на неправильное, то падают
```
--- SIMPLE ---

PASSED

--- RANDOM SEED ---

PASSED

--- NODE JOIN ---

PASSED

--- NODE LEAVE ---

PASSED

--- NODE CRASH ---

PASSED

--- SEED NODE CRASH ---

PASSED

````

```

--- SIMPLE ---

PASSED

--- RANDOM SEED ---

Members lists:
- [3] 0, 2, 3, 4, 5, 6, 7, 8, 9
- [4] 0, 1, 2, 3, 4, 6, 7, 8, 9
- [2] 0, 2, 3, 4, 5, 6, 7, 8, 9
- [7] 0, 1, 2, 3, 4, 6, 7, 8, 9
- [0] 0, 2, 3, 4, 5, 6, 7, 8, 9
- [8] 0, 1, 2, 3, 4, 6, 7, 8, 9
- [9] 0, 1, 2, 3, 4, 6, 7, 8, 9
- [6] 0, 1, 2, 3, 4, 6, 7, 8, 9
- [5] 0, 2, 3, 4, 5, 6, 7, 8, 9
- [1] 0, 1, 2, 3, 4, 6, 7, 8, 9
Expected group: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9

FAILED: Group members lists are not stabilized

--- NODE JOIN ---

PASSED

```

2023-01-20 15:07 UTC, osukhoroslov commented
#164 пофиксили, можно ребейзить и должно работать

2023-02-08 21:53 UTC, KiK0S commented on crates/dslab-mp/src/system.rs
> +        self.sim.add_handler(&node, self.nodes.get(node).unwrap().clone());
раньше вместо recover_node создавался add_node + add_process заново, кажется это нам не нужно - тем более краш ноды просто отключает хендлер

2023-02-08 22:01 UTC, KiK0S commented
Еще раз проверил, на своей старой домашке, вроде работает нормально

2023-02-17 20:18 UTC, osukhoroslov requested changes

2023-02-17 20:18 UTC, osukhoroslov commented on examples/mp-membership/src/main.rs
> +    sys.recover_node(node_id);
Сделал в main так - при краше в ноде чистятся все процессы (чтобы не было возможности их состояние переиспользовать после поднятия ноды), и system тоже забывает про процессы с ноды. Поэтому здесь надо заново создать инстанс процесса и добавить его через system.add_process(), по аналогии со старыми тестами.

2023-02-20 09:45 UTC, KiK0S commented on examples/mp-membership/src/main.rs
> +    sys.recover_node(node_id);
обновил

2023-02-20 09:45 UTC, KiK0S commented on examples/mp-membership/src/main.rs
> +            Message::new("JOIN", &serde_json::to_string(&JoinMessage { seed }).unwrap()),
круто! обновил

2023-02-20 09:46 UTC, KiK0S commented on examples/mp-membership/python/solution.py
> +class GroupMember(Process):
обновил - кажется я у себя взял позапрошлогоднюю заготовку

2023-02-20 09:46 UTC, KiK0S commented on crates/dslab-mp/src/system.rs
> +        self.sim.add_handler(&node, self.nodes.get(node).unwrap().clone());
done

2023-03-03 11:10 UTC, KiK0S commented on examples/mp-membership/src/main.rs
> +fn test_node_join(config: &TestConfig) -> TestResult {
починил нейминги

2023-03-03 11:10 UTC, KiK0S commented on examples/mp-membership/src/main.rs
> +    // node leaves the system
починил нейминги

2023-03-03 11:10 UTC, KiK0S commented on examples/mp-membership/src/main.rs
> +    // node joins the system
починил нейминги

2023-03-03 18:43 UTC, osukhoroslov reviewed
В процессе ревью у меня получился довольно обширный рефакторинг, который я оформил как PR: https://github.com/KiK0S/dslab/pull/3

2023-03-03 19:13 UTC, osukhoroslov commented
> В процессе ревью у меня получился довольно обширный рефакторинг, который я оформил как PR: [KiK0S#3](https://github.com/KiK0S/dslab/pull/3)

И там же добавил фикс, который чинит вывод в случае наличия clock skew.

2023-03-09 20:43 UTC, KiK0S commented
Просмотрел, ребейзнул, вроде все норм. Решение прогоняется

2023-03-11 11:27 UTC, osukhoroslov approved these changes

2023-03-11 11:29 UTC, merged