Allow timer overwrites if specified
osukhoroslov/dslab pull request #165
Opened 2022-12-03 15:17 UTC by KiK0S

solves https://github.com/osukhoroslov/dslab/issues/164

Про что думаю - можно либо поменять нейминг `set_timer_detailed`, либо сделать какой-нибудь timer builder паттерн, потому что уж очень хочется уметь задать default false значение на force

2022-12-23 15:58 UTC, osukhoroslov commented
Предлагаю сделать так:
- `Context.set_timer(self, timer_name: str, delay: float)` устанавливает таймер повторно, не проверяя активен ли он
- `Context.set_timer_once(self, timer_name: str, delay: float)` устанавливает таймер только если такого таймера сейчас нет (а если он есть, то ошибка не выбрасывается). Альтернативный вариант названия `set_timer_safe`.

2023-01-15 11:58 UTC, KiK0S commented on crates/dslab-mp-python/python/dslabmp.py
> +        self._timer_actions.append((timer_name, delay, False))
идеально бы, конечно, прокидывать не bool, а какой-то enum, но я не умею одновременно и в расте и в питоне такое поддерживать

2023-01-16 17:46 UTC, osukhoroslov requested changes

2023-01-16 17:46 UTC, osukhoroslov commented on crates/dslab-mp-python/python/dslabmp.py
> +    def set_timer_once(self, timer_name: str, delay: float):
Добавьте docstring к этому и заодно остальным методам Context

2023-01-16 17:46 UTC, osukhoroslov commented on crates/dslab-mp/src/context.rs
> +    pub fn set_timer_detailed(&mut self, name: &str, delay: f64, once: bool) {
Предлагаю здесь повторить Python API, то есть сделать `set_timer_once` и `set_timer`, а от универсального метода с bool-аргументом отказаться. А в mp-python по полученному из Python bool определять какой метод вызывать.

2023-01-16 19:36 UTC, KiK0S commented on crates/dslab-mp-python/python/dslabmp.py
> +    def set_timer_once(self, timer_name: str, delay: float):
сделал, но не уверен в текстовках, мб что-то из них поправить надо

2023-01-16 19:37 UTC, KiK0S commented on crates/dslab-mp/src/context.rs
> +    pub fn set_timer_detailed(&mut self, name: &str, delay: f64, once: bool) {
Так и сделал, только добавил дополнительный enum вместо bool, чтобы не нужно было лезть вглубь и было проще понять, что происходит

2023-01-16 19:38 UTC, KiK0S commented on crates/dslab-mp/src/node.rs
> +    },
хм, я это не планировал, это кажется мой cargo fmt. откатить?

2023-01-16 19:39 UTC, KiK0S commented on crates/dslab-mp/src/node.rs
> +                    if TimerBehavior::OverrideExisting == behavior || !proc_entry.pending_timers.contains_key(&name) {
было бы очень rust-ish сделать тут паттерн матчинг (и не надо было бы дерайвить partialeq для enum), но мне поругалось, кажется что не разрешено в составных условиях.

2023-01-16 20:10 UTC, osukhoroslov requested changes

2023-01-16 20:10 UTC, osukhoroslov commented on crates/dslab-mp-python/python/dslabmp.py
> +        Sets timer that will trigger on_timer callback after specified delay. Overrides previous timer with the same name.
```suggestion
        Sets a timer that will trigger on_timer callback after the specified delay. 
        If there is an active timer with this name, its delay is overridden.
```

2023-01-16 20:10 UTC, osukhoroslov commented on crates/dslab-mp-python/python/dslabmp.py
> +        Sets timer that will trigger on_timer callback after specified delay. Is ignored if there is an active timer with the same name.
```suggestion
        Sets a timer that will trigger on_timer callback after the specified delay.
        If there is an active timer with this name, this call is ignored.
```

2023-01-16 20:10 UTC, osukhoroslov commented on crates/dslab-mp-python/python/dslabmp.py
> +        Cancels timer with specified name.
```suggestion
        Cancels timer with the specified name.
```

2023-01-16 20:10 UTC, osukhoroslov commented on crates/dslab-mp-python/python/dslabmp.py
> +        Returns current system time.
```suggestion
        Returns the current system time.
```

2023-01-16 20:10 UTC, osukhoroslov commented on crates/dslab-mp/src/node.rs
> +    },
Да

2023-01-16 20:10 UTC, osukhoroslov commented on crates/dslab-mp/src/node.rs
> +#[derive(Clone, PartialEq)]
Не хватает пустой строки перед

2023-01-16 20:10 UTC, osukhoroslov commented on crates/dslab-mp/src/node.rs
> +                    if TimerBehavior::OverrideExisting == behavior || !proc_entry.pending_timers.contains_key(&name) {
Мне кажется более понятен такой порядок `if behavior == TimerBehavior::OverrideExisting`

2023-01-17 08:27 UTC, KiK0S commented on crates/dslab-mp/src/node.rs
> +#[derive(Clone, PartialEq)]
done

2023-01-17 08:27 UTC, KiK0S commented on crates/dslab-mp/src/node.rs
> +    },
done

2023-01-17 08:27 UTC, KiK0S commented on crates/dslab-mp/src/node.rs
> +                    if TimerBehavior::OverrideExisting == behavior || !proc_entry.pending_timers.contains_key(&name) {
done

2023-01-17 08:29 UTC, KiK0S commented
в итоге все же надо применить cargo fmt к `ProcessEvent`, потому что он разросся

2023-01-18 17:51 UTC, osukhoroslov approved these changes

2023-01-18 17:54 UTC, merged