Refactor storage model
osukhoroslov/dslab pull request #167
Opened 2022-12-11 19:10 UTC by kuskarov

2022-12-11 19:13 UTC, kuskarov commented
Пока документация еще не в консистентном виде, не везде убрал упоминания дисков. А почему именно `StorageResource`, почему не `Storage` или `DataStorage`?

2022-12-19 15:13 UTC, osukhoroslov commented
> А почему именно `StorageResource`, почему не `Storage` или `DataStorage`?

Просто `storage` может восприниматься и как просто "хранилище" и как система-ресурс для хранения (включая железо): https://helpcenter.veeam.com/docs/styleguide/tw/storage.html. И есть еще проблема с множественным числом в английском, `storages` не принято писть.

Но вообще я не против попробовать заменить `Storage`, а в документации там где имеет смысл писать `storage resource(s)`.

2022-12-19 15:41 UTC, osukhoroslov requested changes

2022-12-19 15:41 UTC, osukhoroslov commented on crates/dslab-storage/src/fs.rs
> +        self.disks.keys().map(|mount_point| mount_point.to_owned()).collect()
Кажется это эквивалентно и заметно короче

```suggestion
        self.disks.keys().cloned().collect()
```

2022-12-19 15:41 UTC, osukhoroslov commented on crates/dslab-storage/src/tests.rs
> -use crate::disk::{Disk, DiskInfo};
Для SharedDisk у нас сейчас тестов нет. Потом их добавим?

2022-12-19 15:41 UTC, osukhoroslov commented on examples/storage-disk/src/main.rs
> +        WeightedBandwidth {
Не хотите конструктор написать? Будет менее громоздко выглядеть.

2022-12-19 15:41 UTC, osukhoroslov commented on examples/storage-shared-disk-benchmark/src/main.rs
> +use dslab_storage::resource::StorageResource;
Не в тот блок импортов попало

2022-12-19 15:41 UTC, osukhoroslov commented on examples/storage-shared-disk/src/main.rs
> +use dslab_storage::resource::StorageResource;
Не в тот блок импортов попало

2022-12-19 15:47 UTC, kuskarov commented on examples/storage-disk/src/main.rs
> +        WeightedBandwidth {
С конструкторами есть та же проблема, что с tuple, которые я тут выпилил - непонятно, что означают эти числа. Поэтому специально сделал такую инициализацию.

2022-12-19 15:47 UTC, kuskarov commented on crates/dslab-storage/src/tests.rs
> -use crate::disk::{Disk, DiskInfo};
Уберем `Disk` просто )

2022-12-23 16:14 UTC, osukhoroslov commented on examples/storage-disk/src/main.rs
> +        WeightedBandwidth {
Почему непонятно? Вот у меня отображается что это за поля:

![изображение](https://user-images.githubusercontent.com/1322460/209365831-0090877d-ae3a-41c5-82a1-b0a414fce6b3.png)

2022-12-26 15:21 UTC, kuskarov commented on examples/storage-disk/src/main.rs
> +        WeightedBandwidth {
В предположении, что у всех настроен тулинг, да, все хорошо. Наверное на Rust он у большинства людей действительно настроен, ок, будет конструктор

2022-12-26 15:26 UTC, kuskarov commented on examples/storage-shared-disk/src/main.rs
> +use dslab_storage::resource::StorageResource;
Fixed

2022-12-26 15:26 UTC, kuskarov commented on examples/storage-shared-disk-benchmark/src/main.rs
> +use dslab_storage::resource::StorageResource;
Fixed

2022-12-26 15:26 UTC, kuskarov commented on examples/storage-disk/src/main.rs
> +        WeightedBandwidth {
Fixed

2022-12-26 15:28 UTC, kuskarov commented on crates/dslab-storage/src/resource.rs
> +//! [`StorageResource::write()`], and some constant methods that return information about resource.
Fixed

2022-12-26 16:54 UTC, osukhoroslov requested changes

2022-12-26 16:54 UTC, osukhoroslov commented on crates/dslab-storage/src/storage.rs
> +/// Information about storage resource, including its capacity and current usage.
```suggestion
/// Information about storage, including its capacity and current usage.
```

2022-12-26 16:54 UTC, osukhoroslov commented on crates/dslab-storage/src/storage.rs
> +    /// Storage resource capacity. Is equal to `used_space` + `free_space`.
```suggestion
    /// Storage capacity. Is equal to `used_space` + `free_space`.
```

2022-12-26 16:54 UTC, osukhoroslov commented on crates/dslab-storage/src/storage.rs
> +/// Trait for storage resource.
```suggestion
/// A trait for modeling an abstract storage resource, i.e. any device, system or service for storing data.
///
/// The main operations are reading and writing data to/from storage. Implementations should model the delays associated with these operations.
/// The trait also includes operations to get information about the storage, including its capacity, current usage, etc.
```

2022-12-26 16:54 UTC, osukhoroslov commented on crates/dslab-storage/src/storage.rs
> +    /// Note that the returned request id is unique only within the current storage resource.
```suggestion
    /// The amount of data read from storage is specified in `size`.
    /// The component specified in `requester` will receive `DataReadCompleted` event upon the read completion.
    /// If the read size is larger than the storage capacity, `DataReadFailed` event will be immediately
    /// emitted instead.
    /// Note that the returned request id is unique only within the current storage.
```

2022-12-26 16:54 UTC, osukhoroslov commented on crates/dslab-storage/src/storage.rs
> +    /// Note that the returned request id is unique only within the current storage resource.
```suggestion
    /// The amount of data written to storage is specified in `size`.
    /// The component specified in `requester` will receive `DataWriteCompleted` event upon the write completion.
    /// If there is not enough available storage space, `DataWriteFailed` event will be immediately emitted
    /// instead.
    /// Note that the returned request id is unique only within the current storage.
```

2022-12-26 16:54 UTC, osukhoroslov commented on crates/dslab-storage/src/storage.rs
> +    /// The `size` should not exceed the currently used storage resource space.
```suggestion
    /// The `size` should not exceed the currently used storage space.
```

2022-12-26 16:54 UTC, osukhoroslov commented on crates/dslab-storage/src/storage.rs
> +    /// Returns the capacity of storage resource.
```suggestion
    /// Returns the storage capacity.
```

2022-12-26 16:54 UTC, osukhoroslov commented on crates/dslab-storage/src/storage.rs
> +    /// Returns identifier of simulation component representing this storage resource.
```suggestion
    /// Returns identifier of simulation component representing the storage.
```

2022-12-26 16:54 UTC, osukhoroslov commented on crates/dslab-storage/src/storage.rs
> +    /// Returns struct with information about the storage resource.
```suggestion
    /// Returns struct with information about the storage.
```

2023-01-15 17:32 UTC, osukhoroslov approved these changes

2023-01-15 17:45 UTC, merged