feat iaas: fix clippy
osukhoroslov/dslab pull request #169
Opened 2022-12-18 21:09 UTC by vetand

2022-12-23 16:58 UTC, osukhoroslov commented
Не собирается, почините CI

2022-12-24 20:19 UTC, osukhoroslov requested changes

2022-12-24 20:19 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/cosine_similarity.rs
> +impl Default for CosineSimilarity {
Так компактнее:

```
#[derive(Default)]
pub struct CosineSimilarity;

impl CosineSimilarity {
    pub fn new() -> Self {
        Default::default()
    }
}
```

2022-12-24 20:19 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/delta_perp_distance.rs
> +impl Default for DeltaPerpDistance {
Так компактнее:

```
#[derive(Default)]
pub struct DeltaPerpDistance;

impl DeltaPerpDistance {
    pub fn new() -> Self {
        Default::default()
    }
}
```

2022-12-24 20:19 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/dot_product.rs
> +impl Default for DotProduct {
Так компактнее:

```
#[derive(Default)]
pub struct DotProduct;

impl DotProduct {
    pub fn new() -> Self {
        Default::default()
    }
}
```

2022-12-24 20:19 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/first_fit.rs
> +impl Default for FirstFit {
Так компактнее:

```
#[derive(Default)]
pub struct FirstFit;

impl FirstFit {
    pub fn new() -> Self {
        Default::default()
    }
}
```

2022-12-24 20:19 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/norm_diff.rs
> +impl Default for L2NormDiff {
См. компактную форму предложенную для остальных алгоритмов

2022-12-24 20:19 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/weighted_dot_product.rs
> +impl Default for WeightedDotProduct {
См. компактную форму предложенную для остальных алгоритмов

2022-12-24 20:19 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithms/worst_fit.rs
> +impl Default for WorstFit {
См. компактную форму предложенную для остальных алгоритмов

2022-12-24 20:19 UTC, osukhoroslov commented on crates/dslab-iaas/src/extensions/standard_dataset_reader.rs
> +impl Default for StandardDatasetReader {
Так компактнее:

```
#[derive(Default)]
pub struct StandardDatasetReader {
    vm_requests: Vec<VMRequest>,
    current_vm: usize,
}

...

impl StandardDatasetReader {
    /// Creates dataset reader.
    pub fn new() -> Self {
        Default::default()
    }
```

2022-12-24 20:19 UTC, osukhoroslov commented on crates/dslab-iaas/src/simulation.rs
> +    pub fn spawn_vm_now(&mut self, vm_request: VMRequest) -> u32 {
Вместо того, чтобы уносить всё в `vm_request: VMRequest` можно было просто использовать уже имеющийся тип `LoadModels`, тогда аргументов стало бы 7. Предлагаю так сделать.

2022-12-24 20:19 UTC, osukhoroslov commented on examples/iaas/src/main.rs
> +impl Default for DecreaseLoadModel {
Так компактнее:

```
#[derive(Clone, Default)]
pub struct DecreaseLoadModel {}

impl DecreaseLoadModel {
    pub fn new() -> Self {
        Default::default()
    }
}
```

2022-12-25 19:00 UTC, vetand commented on crates/dslab-iaas/src/simulation.rs
> +    pub fn spawn_vm_now(&mut self, vm_request: VMRequest) -> u32 {
Всё-таки предлагаю смириться с неизбежным, что рано или поздно переполним это число аргументов, а потому просто отключить тут clippy)

2022-12-25 19:00 UTC, vetand commented on crates/dslab-iaas/src/core/vm.rs
> +#[derive(Clone)]
Не актуально, убрал это изменение

2022-12-26 09:33 UTC, osukhoroslov requested changes

2022-12-26 09:33 UTC, osukhoroslov commented on crates/dslab-iaas/src/simulation.rs
> +    pub fn spawn_vm_now(&mut self, vm_request: VMRequest) -> u32 {
У меня появилось новое предложение - собрать все про потребление ресурсов в структуру:

```
pub struct ResourceConsumer {
    pub cpu_usage: u32,
    pub memory_usage: u64,
    pub cpu_load_model: Box<dyn LoadModel>,
    pub memory_load_model: Box<dyn LoadModel>,
}
```

Тогда сразу число аргументов уменьшится на 3 и везде будет некоторый запас.

Также удобно тем, что на ResourceConsumer можно сделать дополнительные конструкторы, чтобы компактнее указывать LoadModel, например:

```
cloud_sim.spawn_vm_now(ResourceConsumer::with_full_load(10, 10), 2.0, None, s2); // constant 1.0 load
cloud_sim.spawn_vm_now(ResourceConsumer::with_constant_load(10, 10, 0.5, 0.5), 2.0, None, s2); // constant 0.5 load
```

2023-01-15 18:30 UTC, osukhoroslov approved these changes

2023-01-15 18:32 UTC, merged