[WIP] First version of model checking for dslab-mp
osukhoroslov/dslab pull request #172
Opened 2022-12-23 07:04 UTC by AnthonyUdovichenko

2023-01-18 19:00 UTC, osukhoroslov commented on crates/dslab-mp/src/process.rs
> +pub trait ProcessState {}
Надо потребовать Clone:

```suggestion
pub trait ProcessState: Clone {}
```

2023-01-18 19:04 UTC, osukhoroslov commented on crates/dslab-mp/src/node.rs
> +pub(crate) struct ProcessEntry {
Зачем везде появилось `pub(crate)`?

2023-01-18 19:04 UTC, osukhoroslov commented on crates/dslab-mp/src/node.rs
> +    pub(crate) fn processes(&self) -> HashMap<String, ProcessEntry> {
Зачем `pub(crate)`?

2023-01-18 19:25 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +        let src_node = (*self.proc_locations.get(src).unwrap()).clone();
Здесь точно нужно клонирование?

2023-01-18 19:53 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/model_checker.rs
> +                    events.clone(),
Предлагаю убрать events и event_count в структуру в духе SimulationState (McState). И вместо создания Event-ов прямо в Node, вызывать McState.add_event(), аналогично SimulationState.add_event().

2023-01-21 09:44 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/process.rs
> +pub trait ProcessState {}
Вроде больше не нужно, я убрал клонирование в PyProcess

2023-01-27 17:14 UTC, KiK0S requested changes
сверил с https://github.com/osukhoroslov/dslab/pull/192 и отписал, что я правил пока поднимал в рантайме пример

2023-01-27 17:14 UTC, KiK0S commented on crates/dslab-mp/src/process.rs
> +
давай такое сделаем чтоб по умолчанию было?
```suggestion
impl ProcessState for String {

}
```
вроде у меня без такого не завелось

2023-01-27 17:14 UTC, KiK0S commented on crates/dslab-mp/src/process.rs
> +    fn state(&self) -> Box<dyn ProcessState>;
```suggestion
    fn state(&self) -> Box<dyn ProcessState> {
        Box::new("".to_string())
    }
```

2023-01-27 17:14 UTC, KiK0S commented on crates/dslab-mp/src/process.rs
> +    fn set_state(&self, state: Box<dyn ProcessState>);
```suggestion
    fn set_state(&self, _data: Box<dyn ProcessState>) {}
```

2023-01-27 17:14 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +    fn new(
не могу его создать
```suggestion
    pub fn new(
```

2023-01-27 17:14 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +    process_states: HashMap<String, Box<dyn ProcessState>>,
очень хочу тут local_outbox и что еще может быть нужно из process_entry, можешь посмотреть тут как я делал
https://github.com/KiK0S/dslab/blob/03bd2a3abde413cfbd706dd7cf532829122dde72/crates/dslab-mp/src/mc/node.rs#L17
https://github.com/KiK0S/dslab/blob/03bd2a3abde413cfbd706dd7cf532829122dde72/crates/dslab-mp/src/mc/node.rs#L129
https://github.com/KiK0S/dslab/blob/03bd2a3abde413cfbd706dd7cf532829122dde72/crates/dslab-mp/src/mc/node.rs#L138

2023-01-27 17:14 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +                    assert!(
вот тут ассерт не нужен, у тебя скорее всего реализация не поверх этого коммита https://github.com/osukhoroslov/dslab/pull/165, там должен быть behavior и вместо ассерта что-то такое

```
if behavior == TimerBehavior::OverrideExisting || !proc_entry.pending_timers.contains_key(&name) {
    let event_id = self.net.borrow_mut().set_timer(name.clone(), proc.clone(), self.id);
    proc_entry.pending_timers.insert(name, event_id);
}
```

2023-01-27 17:14 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +            *state.process_states.get_mut(proc).unwrap() = proc_entry.proc_impl.state();
ты падаешь, когда ничего нет в мапе
```suggestion
            state.process_states.insert(proc.to_owned(), proc_entry.proc_impl.state());
```

2023-01-28 18:20 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/node.rs
> +pub(crate) struct ProcessEntry {
`ProcessEntry` используется в `McNode`

2023-01-28 18:26 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/node.rs
> +    pub(crate) fn processes(&self) -> HashMap<String, ProcessEntry> {
Потому что используется в `ModelChecker::new()`, а за пределы `dslap-mp` наверное нет смысла открывать этот метод

2023-01-28 18:35 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/node.rs
> +    process_states: HashMap<String, Box<dyn ProcessState>>,
Сделал ProcessEntryState

2023-01-28 19:06 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/node.rs
> +                    assert!(
Поправил

2023-01-29 15:07 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/model_checker.rs
> +        let sim_state = sim.sim_state();
Сделано

2023-01-29 15:20 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/process.rs
> +
Сделал дефолтную имплементацию с `ProcessStateStub`

2023-01-29 15:21 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/process.rs
> +    fn state(&self) -> Box<dyn ProcessState>;
Сделал дефолтную имплементацию с `ProcessStateStub`

2023-01-29 15:21 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/process.rs
> +    fn set_state(&self, state: Box<dyn ProcessState>);
Сделал

2023-01-29 20:30 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/node.rs
> +            *state.process_states.get_mut(proc).unwrap() = proc_entry.proc_impl.state();
Поправил

2023-02-01 19:47 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +                    if !self.net.borrow_mut().send_message(msg, src, dest, self.id) {
У меня в этом месте больше кода (видимо из-за каких-то штук с сетью), но тут точно баг потому что нужно  `return` -> `continue`

2023-02-02 21:02 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/node.rs
> +                    if !self.net.borrow_mut().send_message(msg, src, dest, self.id) {
Поправил

2023-02-03 13:39 UTC, osukhoroslov requested changes

2023-02-03 13:39 UTC, osukhoroslov commented on crates/dslab-mp-python/src/lib.rs
> +#[derive(Clone, Debug)]
```suggestion
#[derive(Debug)]
```

2023-02-03 13:39 UTC, osukhoroslov commented on crates/dslab-mp-python/src/lib.rs
> +        let data = *state.downcast::<PyProcessState>().unwrap();
```suggestion
        let data = state.downcast::<PyProcessState>().unwrap();
```

2023-02-03 13:39 UTC, osukhoroslov commented on crates/dslab-mp/src/context.rs
> +        };
```suggestion
        let time = if let Some(sim_ctx) = sim_ctx.as_ref() {
            sim_ctx.borrow().time() + clock_skew
        } else {
            0.0
        };
```

2023-02-03 13:39 UTC, osukhoroslov commented on crates/dslab-mp/src/context.rs
> +        self.sim_ctx.as_mut().expect("sim_ctx is None").borrow_mut().rand()
```suggestion
        self.sim_ctx.as_ref().expect("sim_ctx is None").borrow_mut().rand()
```

2023-02-03 13:39 UTC, osukhoroslov commented on crates/dslab-mp/src/events.rs
> +#[derive(Serialize, Clone)]
```suggestion
#[derive(Serialize)]
```

2023-02-03 13:39 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/node.rs
> +    fn handle_process_actions(&mut self, proc: String, time: f64, actions: Vec<ProcessEvent>) {
Приватные функции надо перенести после публичных

2023-02-03 13:39 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +        {
Предлагаю убрать эти фигурные скобки

2023-02-03 13:39 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +    pub fn corrupt_rate(&self) -> f64 {
Перенесите геттеры рядом с соответствующими сеттерами

2023-02-03 13:39 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +    pub fn check_if_dropped(&mut self, src: &String, dest: &String) -> bool {
Эту и другие вспомогательные функции можно сделать приватными

2023-02-03 13:39 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +    pub fn check_if_dropped(&mut self, src: &String, dest: &String) -> bool {
Предлагаю назвать `is_dropped`

2023-02-03 13:39 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +    pub fn duplicate_if_needed(&mut self) -> u32 {
Предлагаю назвать `get_message_count`

2023-02-03 13:39 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +                for _i in 0..dups {
Я бы оставил ветку для случая когда нет дублирования, чтобы избежать клонирования `e`. На практике дублирование редко используется и не хочется платить за это всегда.

2023-02-04 10:51 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/system.rs
> +        self.nodes.get(name).and_then(|res| Some(res.borrow()))
Minor enhancement

2023-02-04 13:56 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +        {
Убрал

2023-02-04 15:01 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/network.rs
> +    pub fn check_if_dropped(&mut self, src: &String, dest: &String) -> bool {
methods called `is_*` usually take self by reference or no self; consider choosing a less ambiguous name

2023-02-04 15:04 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/network.rs
> +    pub fn duplicate_if_needed(&mut self) -> u32 {
Сделал

2023-02-04 15:47 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +    pub fn check_if_dropped(&mut self, src: &String, dest: &String) -> bool {
Тогда `message_is_dropped`

2023-02-04 21:17 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/network.rs
> +    pub fn check_if_dropped(&mut self, src: &String, dest: &String) -> bool {
Поправил

2023-02-04 21:33 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/network.rs
> +    pub fn check_if_dropped(&mut self, src: &String, dest: &String) -> bool {
Сделал

2023-02-05 08:52 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/network.rs
> +    pub fn corrupt_rate(&self) -> f64 {
Перенёс

2023-02-05 09:30 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/node.rs
> +    fn handle_process_actions(&mut self, proc: String, time: f64, actions: Vec<ProcessEvent>) {
Перенёс

2023-02-05 10:40 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/network.rs
> +    pub(crate) fn new(
Поправил

2023-02-05 11:17 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/network.rs
> +                for _i in 0..dups {
Поправил

2023-02-06 12:10 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +    pub fn corrupt_rate(&self) -> f64 {
Остались внизу `get_drop_outgoing`, `get_drop_incoming`, `disabled_links`. Поправил это.

2023-02-06 12:18 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +                for _i in 0..dups {
Добавил также в mc network

2023-02-06 12:19 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +    pub fn corrupt_rate(&self) -> f64 {
Перенес оставшиеся три геттера

2023-02-06 21:59 UTC, KiK0S commented on crates/dslab-mp/src/mc/system.rs
> +                    .get_mut(self.net.borrow().get_proc_node(&src))
рантайм падает, потому что не находит процесс на ноде, вроде вот так
```suggestion
                    .get_mut(self.net.borrow().get_proc_node(&dest))
```

2023-02-06 22:06 UTC, KiK0S commented on crates/dslab-mp/src/mc/system.rs
> +                    .get_mut(self.net.borrow().get_proc_node(&src))
оба borrow - тут и ниже - чувствуют себя плохо, потому что делают borrow на сеть, а сеть потом используется в `on_message_received`. обошел, отдельно склонировав нужное имя узла

2023-02-06 22:07 UTC, KiK0S commented on crates/dslab-mp/src/mc/system.rs
> +                    .get_mut(self.net.borrow().get_proc_node(&proc))
https://github.com/osukhoroslov/dslab/pull/172/files#r1097970455

2023-02-07 20:20 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/system.rs
> +                    .get_mut(self.net.borrow().get_proc_node(&src))
Поправил

2023-02-07 20:23 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/system.rs
> +                    .get_mut(self.net.borrow().get_proc_node(&proc))
Так, а эта ссылка куда должна была вести?)
Если это про borrow из прошлого коммента, то я поправил. Если нет, поясни пожалуйста

2023-02-13 12:21 UTC, osukhoroslov requested changes
Выложил сюда предлагаемый рефакторинг логирования: https://github.com/osukhoroslov/dslab/commit/02a603f500a5d101654cde3eb8f98f63b264f023

2023-02-13 12:21 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +        mode: LogMode,
Лучше назвать `log_mode`

2023-02-13 19:42 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +                    }
блин а зачем я сейчас сидел и дебажил это в тестах пинг-понга, если вы тут уже предложили 1 в 1 мой фикс)))

2023-02-13 19:43 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +                    }
могу только сказать что протестировал, получается вот такое
```
before RefCell { value: [MessageReceived { msg: PING {"value": 0}, src: "client", dest: "server" }, MessageReceived { msg: PING {"value": 0}, src: "client", dest: "server" }, MessageReceived { msg: PING {"value": 0}, src: "client", dest: "server" }, TimerFired { proc: "client", timer: "check_pong" }] }
after RefCell { value: [MessageReceived { msg: PING {"value": 0}, src: "client", dest: "server" }, MessageReceived { msg: PING {"value": 0}, src: "client", dest: "server" }, MessageReceived { msg: PING {"value": 0}, src: "client", dest: "server" }] }
```

2023-02-13 20:10 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +            if let LogMode::Debug = self.mode {
Сделал

2023-02-13 20:10 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/node.rs
> +                    }
Поправил

2023-02-13 20:10 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +        mode: LogMode,
Исправил

2023-02-27 13:39 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +        self.decrease_max_dupl_count(system, event_num);
Я бы эту функцию сюда бы прямо добавил, а то приходится скакать по коду, чтобы понять что происходит

2023-02-27 13:39 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +    fn drop_impl(&mut self, system: &mut McSystem) -> Result<(), String> {
Нужен ли отдельный метод drop_impl? Нельзя ли использовать при дропе тот же search_step_impl? Например, считать что отбрасывание сообщения это тоже своего рода событие - ошибка сети (и в логе исполнения оно тоже будет записано как отдельный шаг), тогда получается глубина тоже увеличивается.

2023-03-05 10:09 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategy.rs
> +            self.debug_log(&event, self.search_depth(), LogContext::Duplicated);
Это рудимент старой версии кода. Я сначала думал, что сообщение лучше сначала корраптить, а потом дублировать, но быстро понял, что тогда некоторые сценарии исполнения окажутся непокрытыми. В итоге основной код переписал, а про логирование забыл)

2023-03-05 10:50 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategy.rs
> +        let event = self.clone_event(system, event_num);
Оттуда не получится взять без дополнительного клонирования, потому что в `match event` происходит move

2023-03-05 11:43 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategy.rs
> +        self.decrease_max_dupl_count(system, event_num);
В `decrease_max_dupl_count` довольно объёмный `match`. Если его сюда вставить, то сложнее будет с одного взгляда разобраться, что тут по сути происходит (взяли event, а обратно вернули его же, но с другим количеством возможных дупликаций). Я как раз из-за этого постарался все эти `match` унести в отдельные функции, чтобы они не мешались

2023-03-06 11:22 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/system.rs
> +    pub(crate) events: Rc<RefCell<Vec<McEvent>>>,
Поскольку events теперь убраны из Network и Node, то можно избавиться от Rc+RefCell и borrow при работе с system.events.

2023-03-06 12:39 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +        self.decrease_max_dupl_count(system, event_num);
Предлагаю сделать так, чтобы упростить понимание:

```
    fn duplicate_event(&self, system: &mut McSystem, event_num: usize) -> McEvent {
        let event = self.take_event(system, event_num);
        self.add_event(system, event.duplicate().unwrap(), event_num);
        self.debug_log(&event, self.search_depth(), LogContext::Duplicated);
        event
    }
```

Здесь duplicate() это функция на McEvent, которая создает копию события с уменьшенным max_dupl_count (обратите внимание как я сжал match):

```
impl McEvent {
    pub fn duplicate(&self) -> Option<McEvent> {
        match self {
            McEvent::MessageReceived {
                msg,
                src,
                dest,
                options:
                    PossibleFailures {
                        can_be_dropped,
                        max_dupl_count,
                        can_be_corrupted,
                    },
            } => Some(McEvent::MessageReceived {
                msg: msg.clone(),
                src: src.clone(),
                dest: dest.clone(),
                options: PossibleFailures {
                    can_be_dropped: *can_be_dropped,
                    max_dupl_count: max_dupl_count - 1,
                    can_be_corrupted: *can_be_corrupted,
                },
            }),
            _ => None,
        }
    }
}
```

2023-03-06 12:42 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +        let event = self.clone_event(system, event_num);
Описал выше подход, который позволяет избавиться от клонирования (на match использовать ссылку и делать копию события при создании дубликата, вместо клона и move в дубликат).

2023-03-10 15:55 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +        let events_num = system.events.len();
dependency_resolver.available.size

2023-03-19 15:20 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +                }
Паниковать надо раньше в process_event

```suggestion
                _ => {}
```

2023-03-19 15:21 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +            _ => {}
```suggestion
            TimerCancelled { .. } => {
                panic!("Strategy should not receive TimerCancelled events")
            }
```

2023-03-29 17:27 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +        self.search_step_impl(system)?;
Почему бы нам не проверять `have_visited` здесь (вместо check_state) и не дергать стратегию если состояние уже видели?

2023-03-29 20:16 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategy.rs
> +        self.search_step_impl(system)?;
Для рекурсивных алгоритмов (как DFS) этот вызов – единственный способ продолжить рекурсию в глубину. Для алгоритмов с сохранением состояний (как BFS) внутри этого вызова сохраняется полученное состояние, чтобы потом можно было к нему вернуться и продолжить с него исполнение, иначе тоже эту ветку графа мы не рассмотрим в глубину.

2023-03-29 20:18 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategy.rs
> +        self.search_step_impl(system)?;
Хорошая идея, сделаю (но не сегодня)

2023-03-29 20:37 UTC, osukhoroslov commented on crates/dslab-mp-python/python/__pycache__/dslabmp.cpython-38.pyc
Надо удалить

2023-03-31 11:03 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +        self.search_depth += 1;
Кажется, что изменение `search_depth` можно вынести полностью внутрь Strategy. А именно - изменять depth при вызове `process_event` на глубину состояния переданной туда системы. Собственно в BFS так сейчас и делается руками. В DFS такой подход тоже должен работать.

2023-04-06 21:19 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategy.rs
> +    fn check_state(&mut self, state: &McState, events_num: usize) -> Option<Result<(), String>> {
Поправил

2023-04-06 21:38 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategies/bfs.rs
> +                return result;
Поправил

2023-04-06 21:41 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategies/bfs.rs
> +            let state = self.states_queue.pop_front().expect("BFS error");
Вообще убрал expect, там двумя строчками выше явная проверка на непустоту

2023-04-07 12:52 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/pending_events.rs
> +    /// Returns number of currently available events
```suggestion
    /// Returns the number of currently available events
```

2023-04-17 18:46 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/dependency.rs
> +        let index_event = ids.iter().position(|id| *id == event_id).unwrap();
Если все работает корректно, то удаляемое сообщение должно быть всегда первым в векторе (индекс всегда 0), если конечно я чего-то не упустил.

2023-04-17 18:47 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/dependency.rs
> +        ids.remove(index_event);
Удалять первый элемент из вектора много раз не очень эффективно, сразу в голову приходит перейти на https://doc.rust-lang.org/std/collections/struct.VecDeque.html#method.pop_front

2023-04-17 18:48 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/dependency.rs
> +        if index_event == 0 && !ids.is_empty() {
Не понятно почему здесь нельзя оставить проверку просто на `!ids.is_empty()`?

2023-04-17 18:52 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/pending_events.rs
> +            }
```suggestion
            if let Some(unblocked_event) = self.resolver.remove_message(msg, event_id) {
                self.available_events.insert(unblocked_event);
            }
```

2023-04-20 20:46 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/message.rs
> +#[derive(Serialize, Clone, Eq, Hash, PartialEq, PartialOrd, Ord)]
В данном случае это нужно для использования `entry` в депенденси резолвере при добавлении нового сообщения. Наверное, это можно обойти так или иначе, но зачем? Вроде уметь упорядочивать сообщения – довольно разумное желание

2023-04-21 17:04 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/dependency.rs
> +use std::collections::{BTreeMap, VecDeque};
```suggestion
use std::collections::{BTreeMap, BTreeSet, VecDeque};
```

2023-04-21 17:10 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/system.rs
> +use std::collections::HashMap;
```suggestion
use std::collections::{BTreeMap, BTreeSet, HashMap};
```

2023-04-21 18:24 UTC, osukhoroslov approved these changes

2023-04-21 18:46 UTC, KiK0S approved these changes
![](https://media3.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

2023-04-21 18:53 UTC, merged