[faas] Improved stats + fixed invoker queue
osukhoroslov/dslab pull request #177
Opened 2022-12-29 15:32 UTC by SYury

- Добавил вычисление квантилей и дисперсии для SampleMetric
- Добавил тесты для метрик и для симуляции
- Реализовал сбор метрик для каждой функции отдельно
- Поправил очень проблемный баг с очередью инвокера
- Добавил в LeastLoadedScheduler и HermesScheduler возможность использовать суммарное число вызовов вместо нагрузки на CPU и возможность избегать хостов, где вызов попадёт в очередь инвокера

2022-12-30 17:23 UTC, osukhoroslov requested changes
И clippy запусти, если не запускал

2022-12-30 17:23 UTC, osukhoroslov commented on crates/dslab-faas/src/simulation.rs
> +    stats: Rc<RefCell<StatsMonitor>>,
Тут сейчас путаница, с учётом того что есть типы `Stats` и `StatsMonitor`, это поле было правильнее назвать `stats_monitor`. Выше я написал предложение изменить `StatsMonitor` на `Stats` тогда не придется менять имя поля.

2022-12-30 17:23 UTC, osukhoroslov commented on crates/dslab-faas/src/simulation.rs
>          self.stats.borrow().clone()
Clone() для read-only доступа к статистике?

2022-12-30 17:23 UTC, osukhoroslov commented on crates/dslab-faas/tests/test_contention.rs
> +    let stats = serverless.get_global_stats().invocation_stats;
Можно для удобства сделать в simulation метод - `serverless.invoсation_stats()`

2022-12-30 17:23 UTC, osukhoroslov commented on crates/dslab-faas/tests/test_contention.rs
>      let sim = Simulation::new(1);
Давай в этих тестах тоже уберем `serverless` и заменим на `let mut sim = ServerlessSimulation::new(Simulation::new(1), Default::default());`

2022-12-30 17:23 UTC, osukhoroslov commented on crates/dslab-faas/tests/test_simulation.rs
> +        monitor.global_stats.wasted_resource_time.get(&0).unwrap().sum(),
```suggestion
        monitor.global_stats.wasted_resource_time[0].sum(),
```
и в других подобных местах

2022-12-30 17:23 UTC, osukhoroslov commented on crates/dslab-faas/src/extra/azure_trace.rs
> +            force_fixed_memory: None,
Эта настройка переопределяет потребление памяти у приложений? Зачем ты её добавил?

2022-12-30 18:39 UTC, SYury commented on crates/dslab-faas/src/extra/azure_trace.rs
> +            force_fixed_memory: None,
Я ещё раз почитал статью про планировщики и увидел маленькую приписку, что они установили всю память в 256мб независимо от того, что в трейсе

2022-12-30 18:39 UTC, SYury commented on crates/dslab-faas/src/simulation.rs
>          self.stats.borrow().clone()
Да. Можно добавить и доступ по ссылке, но пока вроде не нужно

2022-12-30 19:30 UTC, osukhoroslov commented on crates/dslab-faas/src/extra/azure_trace.rs
> +            force_fixed_memory: None,
А есть объяснение почему?

2022-12-30 19:58 UTC, SYury commented on crates/dslab-faas/src/extra/azure_trace.rs
> +            force_fixed_memory: None,
Нет, но у них в память любого инвокера влезает ровно 104 контейнера, скорее всего они хотели избежать всякой нетривиальной фрагментации памяти и возникновения очередей на инвокерах из-за этого

2023-01-04 17:05 UTC, SYury commented on crates/dslab-faas/src/cpu.rs
> +            let delta = 0.0_f64.max(it.finish - self.work_total);
Сделал

2023-01-04 17:05 UTC, SYury commented on crates/dslab-faas/src/host.rs
> +    pub fn get_queued_invocations(&self) -> u64 {
Переименовал

2023-01-04 17:05 UTC, SYury commented on crates/dslab-faas/src/host.rs
> +                let deq = self.invoker.dequeue(
Готово

2023-01-04 17:06 UTC, SYury commented on crates/dslab-faas/src/host.rs
> +                    drop(stats);
Да, там раньше было изменение статистик, поэтому был drop. Убрал.

2023-01-04 17:06 UTC, SYury commented on crates/dslab-faas/src/host.rs
> +                let mut stats = self.stats.borrow_mut();
Вынес в dequeue_requests

2023-01-04 17:06 UTC, SYury commented on crates/dslab-faas/src/invoker.rs
> +                    panic!();
Добавил

2023-01-04 17:06 UTC, SYury commented on crates/dslab-faas/src/stats.rs
> +pub struct Stats {
Сделал

2023-01-04 17:07 UTC, SYury commented on crates/dslab-faas/src/simulation.rs
> +    stats: Rc<RefCell<StatsMonitor>>,
Готово

2023-01-04 17:07 UTC, SYury commented on crates/dslab-faas/tests/test_contention.rs
> +    let stats = serverless.get_global_stats().invocation_stats;
Сделал

2023-01-04 17:07 UTC, SYury commented on crates/dslab-faas/tests/test_contention.rs
>      let sim = Simulation::new(1);
Поменял

2023-01-04 17:07 UTC, SYury commented on crates/dslab-faas/tests/test_simulation.rs
> +        monitor.global_stats.wasted_resource_time.get(&0).unwrap().sum(),
Сделал (только с [0] не заработало, надо [&0])

2023-01-15 18:48 UTC, osukhoroslov commented on crates/dslab-faas/src/stats.rs
> +    /// Extends current metric with zeros to given number of samples. If given number of samples is less than current number of samples, does nothing.
```suggestion
    /// Extends current metric with zeros to given number of samples.
    /// If given number of samples is less than current number of samples, does nothing.
```

2023-01-15 19:29 UTC, osukhoroslov commented on crates/dslab-faas/tests/test_simulation.rs
> +    assert_float_eq(stats2.abs_total_slowdown.mean(), 2.0, 1e-9);
```suggestion
    let stats = sim.stats();
    let inv_stats = stats.global_stats.invocation_stats;
    assert_eq!(inv_stats.invocations, 3);
    assert_eq!(inv_stats.cold_starts, 2);
    assert_float_eq(inv_stats.cold_start_latency.min().unwrap(), 1.0, 1e-9);
    assert_float_eq(inv_stats.cold_start_latency.max().unwrap(), 1.0, 1e-9);
    assert_float_eq(inv_stats.abs_exec_slowdown.mean(), 2.0 / 3.0, 1e-9);
    assert_float_eq(inv_stats.rel_exec_slowdown.mean(), 2.0 / 3.0, 1e-9);
    assert_float_eq(inv_stats.abs_total_slowdown.mean(), 4.0 / 3.0, 1e-9);
    assert_float_eq(inv_stats.rel_total_slowdown.mean(), 4.0 / 3.0, 1e-9);
    assert_float_eq(stats.global_stats.wasted_resource_time[&0].sum(), 3.0 - 1e-9, 1e-9);
    let f1_stats = &stats.func_stats[&0];
    assert_float_eq(f1_stats.abs_total_slowdown.mean(), 1.0, 1e-9);
    let f2_stats = &stats.func_stats[&1];
    assert_float_eq(f2_stats.abs_total_slowdown.mean(), 2.0, 1e-9);
```
И ниже аналогично отрефактори

2023-01-15 19:48 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +        stats.invocation_stats.abs_exec_slowdown.quantile(0.99)
Почему здесь 99-й квантиль, а в других примерах среднее? Может быть сделать во всех примерах похожий вывод? Или даже предложить встроенную функцию для печати статистики с разумными дефолтными метриками, потому что сейчас эти print_results дублируются во всех примерах.

2023-01-16 11:53 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +        stats.invocation_stats.abs_exec_slowdown.quantile(0.99)
Я лично люблю использовать среднее в качестве метрики, но в статьях регулярно используют различные квантили, в этой статье например 0.99 квантиль.

2023-01-16 14:47 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +        stats.invocation_stats.abs_exec_slowdown.quantile(0.99)
А что скажешь насчёт второго предложения, насчёт встроенной функции?

2023-01-16 16:51 UTC, SYury commented on crates/dslab-faas/src/stats.rs
> +    /// Extends current metric with zeros to given number of samples. If given number of samples is less than current number of samples, does nothing.
Сделал

2023-01-16 16:51 UTC, SYury commented on crates/dslab-faas/tests/test_simulation.rs
> +    assert_float_eq(stats2.abs_total_slowdown.mean(), 2.0, 1e-9);
Готово

2023-01-16 16:55 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +        stats.invocation_stats.abs_exec_slowdown.quantile(0.99)
Надо поразмыслить над тем, как это лучше сделать

2023-01-16 18:53 UTC, osukhoroslov commented on crates/dslab-faas/src/stats.rs
> +    pub fn overview(&self, name: &str) {
Предлагаю назвать `print_summary`

2023-01-16 19:08 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +        stats.invocation_stats.abs_exec_slowdown.quantile(0.99)
В faas-scheduling-experiment решил тоже перейти на среднее? Квантили кстати могут быть осмыслены, если мы говорим про здержку, и у неё какое-то плохое распределение типа с хвостом, а нам важны гарантии по задержке (интерактивный сервис на функциях). Надо бы потом построить распределение задержки запросов.

2023-01-16 19:08 UTC, SYury commented on crates/dslab-faas/src/stats.rs
> +    pub fn overview(&self, name: &str) {
Переименовал

2023-01-16 19:21 UTC, osukhoroslov approved these changes

2023-01-16 19:21 UTC, merged