[faas] Switched all examples to clap
osukhoroslov/dslab pull request #178
Opened 2022-12-29 19:19 UTC by SYury

closes #173

2022-12-30 18:08 UTC, osukhoroslov commented on examples/serverless-in-the-wild/src/main.rs
> +    let matches = command!()
А что в clap 4.0 теперь нельзя описать CLI с помощью структуры? Примеры: [раз](https://github.com/osukhoroslov/dslab/blob/6e4dd5dd04de69b267f185a55a8ae6e599594f5c/examples/master-workers/src/main.rs#L30), [два](https://github.com/osukhoroslov/dslab/blob/6e4dd5dd04de69b267f185a55a8ae6e599594f5c/examples/mp-guarantees/src/main.rs#L370). Мне этот подход больше нравится.

2022-12-30 18:38 UTC, SYury commented on examples/serverless-in-the-wild/src/main.rs
> +    let matches = command!()
Для двух аргументов структура оверкилл, да и такой метод привычный питоновский argparse напоминает

2022-12-30 19:42 UTC, osukhoroslov commented on examples/serverless-in-the-wild/src/main.rs
> +    let matches = command!()
Вот что авторы clap пишут по этому поводу: https://docs.rs/clap/latest/clap/_faq/index.html#when-should-i-use-the-builder-vs-derive-apis

Пример с двумя аргументами не выглядит громоздко: https://github.com/osukhoroslov/dslab/blob/6e4dd5dd04de69b267f185a55a8ae6e599594f5c/examples/iaas-traces/src/main.rs#L122

Ну и это пока два, а потом может понадобится больше аргументов.

2022-12-30 19:46 UTC, osukhoroslov commented on examples/serverless-in-the-wild/src/main.rs
> +    let matches = command!()
Кроме того удобнее читать аргументы, вместо `&matches.get_one::<String>("trace").unwrap()` будет `args.trace`.

2023-01-03 17:08 UTC, SYury commented on examples/serverless-in-the-wild/src/main.rs
> +    let matches = command!()
Ок, поменял на derive

2023-01-15 20:11 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +#[clap(author, version, about, long_about = None)]
А что это за макрос `clap`? Во всех примерах к clap здесь `command`, а где аргументы `arg`.

2023-01-15 20:13 UTC, osukhoroslov commented on examples/faas-opendc-benchmark/Cargo.toml
> +clap = { version = "3.0.14", features = ["derive"] }
Используй свежую версию v4.1.1

2023-01-16 11:51 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +#[clap(author, version, about, long_about = None)]
Поменял на command и arg

2023-01-16 11:51 UTC, SYury commented on examples/faas-opendc-benchmark/Cargo.toml
> +clap = { version = "3.0.14", features = ["derive"] }
Сделано

2023-01-16 15:09 UTC, osukhoroslov requested changes

2023-01-16 15:09 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +    #[arg()]
Атрибут не нужен, а комментарий не помешает.

2023-01-16 15:09 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +    #[arg(long)]
Почему конфиг опция? Он же всегда ожидается в main и в readme передается без флага. И также нужен комментарий.

2023-01-16 15:09 UTC, osukhoroslov commented on examples/serverless-in-the-wild/src/main.rs
> +    #[arg(long)]
Почему конфиг опция? Он же всегда ожидается в main и в readme передается без флага. И также нужен комментарий.

2023-01-16 15:09 UTC, osukhoroslov commented on examples/serverless-in-the-wild/src/main.rs
> +    #[arg()]
Атрибут не нужен, а комментарий не помешает.

2023-01-16 15:09 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +#[clap(author, version, about, long_about = None)]
Вспомнил, это в старой версии был макрос такой

2023-01-16 16:26 UTC, SYury commented on examples/faas-parallel/src/main.rs
> +    #[arg()]
Сделал

2023-01-16 16:26 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +    #[arg()]
Сделал

2023-01-16 16:26 UTC, SYury commented on examples/serverless-in-the-wild/src/main.rs
> +    #[arg()]
Сделал

2023-01-16 16:29 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +    #[arg(long)]
Я сделал его именованной опцией, чтобы можно было переставлять конфиг и трейс. При этом эту опцию нельзя опустить, то есть конфиг остался обязательным. Комментарий добавил и readme поправил.

2023-01-16 17:14 UTC, osukhoroslov approved these changes

2023-01-16 17:14 UTC, merged