[WIP] Resolve dependencies for timers
osukhoroslov/dslab pull request #181
Opened 2023-01-12 20:01 UTC by KiK0S

* Структура для резолва зависимостей
* Резолв таймеров - есть список упорядоченный по времени, есть зависимости от первых событий к последним
* Тест

Чего еще нет:
* Удаления зависимостей
* Обработки равных времен - сейчас между ними есть неявная зависимость
* Мне не нравится, что все на каких-то линейных поисках и проходах, но с другой стороны всякие хитрые алгоритмы, думаю, тут будут хуже перформить - и таймеров внутри узла, и узлов всего у нас в среднем очень мало

2023-01-19 21:54 UTC, KiK0S commented
Побороть общие таймеры было сложнее, но вроде как получилось, тест написал

2023-01-30 20:17 UTC, osukhoroslov reviewed
Предлагаю для каждого узла завести binary heap и складывать туда моменты времени, а все события для момента времени хранить в hash set внутри отдельной hash map. При добавлении события надо добавить его в set, и если еще не было такого времени, то время в heap. Доступные события для узла получаются путем peek времени из heap и доставания событий для этого времени из map. При удалении события мы удаляем его из set для этого времени, и если set пустой, то делаем pop из heap. Кажется этого достаточно чтобы реализовать нужную логику в резолвере для таймеров.

Текущая логика со списками выглядит громоздкой. Использование heap позволит отслеживать зависимости не между отдельными событиями, а моментами времени (группами событий). И также упростится логика обновления зависимостей при добавлении и удалении событий.

2023-02-03 07:57 UTC, KiK0S commented on crates/dslab-mp/src/dependencies.rs
> +                .into_iter()
вроде убрал везде где надо было

2023-02-03 07:59 UTC, KiK0S commented on crates/dslab-mp/src/dependencies.rs
> +    pub fn add(&mut self, node: Id, time: f64, event: Rc<RefCell<DependencyWrapper<EventId>>>) {
добавил

2023-02-03 08:00 UTC, KiK0S commented on crates/dslab-mp/src/dependencies.rs
> +use dslab_core::component::Id;
сделано

2023-02-03 08:01 UTC, KiK0S commented on crates/dslab-mp/src/dependencies.rs
> +use rand::prelude::SliceRandom;
да, я понял, там надо в отдельный модуль вынести, потому что используется только в тестах

2023-02-03 08:01 UTC, KiK0S commented on crates/dslab-mp/src/dependencies.rs
> +/// It is guaranteed that if t is not the earliest timer it is connected with at least one timer before it in queue.
ну вот это уже точно неактуально, надо поправить

2023-02-03 08:04 UTC, KiK0S commented
У меня есть некоторые сомнения теперь, что DependencyWrapper вообще нужен, потому что теперь выглядит как оверинжениринг. Объясняю себе его существование тем, что такая система может понадобиться в других модулях или даже в рамках модел чекинга и в нее будет проще добавить дополнительную логику создания зависимостей

2023-02-03 14:21 UTC, osukhoroslov requested changes
Все еще громоздко. Я не вижу необходимости отслеживать зависимости между отдельными событиями (dependencies_before и dependencies_after) и пользоваться DependencyWrapper. Все что надо для обновления available events можно получить из add и pop.

2023-02-03 14:21 UTC, osukhoroslov commented on crates/dslab-mp/src/dependencies.rs
> +            available_events: Vec::default(),
А почему вектор, а не сет?

2023-02-03 14:21 UTC, osukhoroslov commented on crates/dslab-mp/src/dependencies.rs
> +    }
Почему бы просто не возвращать в add пару вещей:
- является ли добавленное событие available (внутри add мы это знаем, если время события самое раннее для этого узла)
- список событый которые надо убрать из available (их время теперь не самое раннее на этом узле)

2023-02-03 14:21 UTC, osukhoroslov commented on crates/dslab-mp/src/dependencies.rs
> +        }
Почему бы в pop не возвращать список тех событий что стали available (их время теперь самое ранее для узла).

2023-02-09 10:29 UTC, KiK0S commented on crates/dslab-mp/src/dependencies.rs
> +            let timer = timer.clone();
Поправил (правда не до конца уверен что есть какая-то разница)

2023-02-09 10:30 UTC, KiK0S commented on crates/dslab-mp/src/dependencies.rs
> +        let next_events = min_time_after.and_then(|x| Some(x.1.clone())).unwrap_or_default();
сделал

2023-02-09 10:30 UTC, KiK0S commented on crates/dslab-mp/src/dependencies.rs
> +                next_event.as_ref().borrow_mut().add_parent(&fake_dependency);
теперь это не нужно

2023-02-09 10:31 UTC, KiK0S commented on crates/dslab-mp/src/dependencies.rs
> +            event.as_ref().borrow_mut().add_parent(&dependency_before);
теперь это не нужно

2023-02-09 10:31 UTC, KiK0S commented on crates/dslab-mp/src/dependencies.rs
> +            available_events: Vec::default(),
Раньше казалось разумным, сейчас вроде сет лучше

2023-02-09 10:31 UTC, KiK0S commented on crates/dslab-mp/src/dependencies.rs
> +    }
так и сделал

2023-02-09 10:31 UTC, KiK0S commented on crates/dslab-mp/src/dependencies.rs
> +        }
так и сделал

2023-02-10 20:35 UTC, osukhoroslov reviewed
в процессе ревью кода резолверов я его прилично отрефакторил и оформил это как PR в вашу ветку: https://github.com/KiK0S/dslab/pull/2

2023-02-17 15:42 UTC, KiK0S commented on crates/dslab-mp/src/dependency.rs
> +                let (is_available, blocked_events) = self.timer_resolver.add(event.dest, event.time + 1.0, event.id);
вот тут нужно задержку сети поддержать

2023-02-17 16:00 UTC, KiK0S commented on crates/dslab-mp/src/dependency.rs
> +                if is_available {
```suggestion

```

2023-02-17 16:01 UTC, KiK0S commented on crates/dslab-mp/src/dependency.rs
> +                if is_available {
таймеры не блокируют доставку сообщения

2023-02-17 16:02 UTC, KiK0S commented on crates/dslab-mp/src/dependency.rs
> +        assert!(events.remove(&event), "event to pop was not first in queue");
этот ассерт для сообщений будет неверным

2023-02-17 16:19 UTC, KiK0S commented on crates/dslab-mp/src/dependency.rs
> +    available_events: HashSet<EventId>,
добавить events для хеширования

2023-03-10 14:41 UTC, KiK0S commented on crates/dslab-mp/src/dependency.rs
> +        assert!(events.remove(&event), "event to pop was not first in queue");
сделал две логики для удаления

2023-03-10 14:41 UTC, KiK0S commented on crates/dslab-mp/src/dependency.rs
> +                if is_available {
теперь сообщение доступно всегда

2023-03-10 14:48 UTC, KiK0S commented on crates/dslab-mp/src/dependency.rs
> +    available_events: HashSet<EventId>,
вроде бы не понадобилось

2023-03-11 15:39 UTC, KiK0S commented on crates/dslab-mp/src/mc/pending_events.rs
> +    fn get_all_available_events(&self, proc: &String) -> HashSet<McEventId> {
это не очень эффективное решение, но в какой-то момент поддержка того, какие у нас новые события доступны, разрослась настолько, что это было бы слишком сложно ревьювить. можем ускорить после мерджа, история сохранилась

2023-03-11 15:40 UTC, KiK0S commented on crates/dslab-mp/src/mc/pending_events.rs
> +struct DependencyResolver {
возможно стоит переместить эту структуру в  dependency_resolver.rs

2023-03-11 15:40 UTC, KiK0S commented on crates/dslab-mp/src/mc/pending_events.rs
> +type BidirectionalMapping = (
не уверен, что это хороший вариант

2023-03-11 15:41 UTC, KiK0S commented on crates/dslab-mp/src/mc/pending_events.rs
> +mod tests {
сейчас тут есть какие-то тесты на упорядочивание событий, на блокирование, на группировку в рамках одного времени, на барьер от сообщений. 

не уверен, нужно ли что-то еще, возможно тест на глобальное время

2023-03-11 15:43 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +        self.add_event(system, event.duplicate().unwrap());
вот тут я не уверен что сделал то что нужно @AnthonyUdovichenko

2023-03-12 12:00 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategy.rs
> +    fn take_event(&self, system: &mut McSystem, event_num: McEventId) -> McEvent {
Го везде event_num -> event_id тогда

2023-03-12 12:04 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategy.rs
> +        self.add_event(system, event.duplicate().unwrap());
Ну тут единственное что – хотелось бы конечно, чтобы добавляемому event'у был передан id только что удалённого event'а. Когда мы будем делать трейс ошибки для студентов, нам это поможет

2023-03-19 20:34 UTC, osukhoroslov requested changes

2023-03-19 20:34 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +        }
```suggestion
        for event_id in system.events() {
            self.process_event(system, event_id)?;
        }
```

2023-03-19 20:34 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +    fn process_event(&mut self, system: &mut McSystem, event_num: usize) -> Result<(), String> {
```suggestion
    fn process_event(&mut self, system: &mut McSystem, event_id: usize) -> Result<(), String> {
```
и в остальных местах аналогично

2023-03-19 20:34 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/pending_events.rs
> +struct DependencyResolver {
Да, надо переместить

2023-03-19 20:34 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/pending_events.rs
> +        let default = 0.0;
Неудачное название из которого непонятен смысл этой переменной

2023-03-19 20:34 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/pending_events.rs
> +                options: DeliveryOptions::NoFailures(rtt),
Замените `rtt` на `max_delay`

2023-03-19 20:34 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/events.rs
> +        duration: f64,
`duration` не очень понятно, предлагаю назвать `timer_delay`.

2023-03-19 20:34 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/pending_events.rs
> +    pub fn add_message(&mut self, proc: String, time: f64, event: McEventId) -> HashSet<McEventId> {
Неконсистентно что здесь мы возвращаем blocked_events как HashSet, в add_timer - как Option<HashSet>

2023-03-19 20:34 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/pending_events.rs
> +mod tests {
тесты надо перенести в отдельный файл в `dslab-mp/tests`

2023-03-19 20:34 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/pending_events.rs
> +                start_time: *self.global_time.get(proc).unwrap_or(&default),
`self.global_time.get(proc).unwrap_or(&default)` повторяется выше несколько раз. предлагаю один раз в начале метода это время взять в переменную и далее ей пользоваться.

2023-03-19 20:34 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/pending_events.rs
> +                *entry = event_timed.start_time + duration;
Громоздкий кусок, можно упростить

2023-03-20 09:36 UTC, KiK0S commented on crates/dslab-mp/src/mc/pending_events.rs
> +struct DependencyResolver {
готово

2023-03-20 09:36 UTC, KiK0S commented on crates/dslab-mp/src/mc/pending_events.rs
> +mod tests {
готово

2023-03-20 09:36 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +        self.add_event(system, event.duplicate().unwrap());
переименовал все

2023-03-20 09:36 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +    fn take_event(&self, system: &mut McSystem, event_num: McEventId) -> McEvent {
сделал

2023-03-20 09:37 UTC, KiK0S commented on crates/dslab-mp/src/mc/system.rs
> +    pub fn events(&self) -> HashSet<McEventId> {
переназвал

2023-03-20 09:37 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +        }
готово

2023-03-20 09:37 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +    fn process_event(&mut self, system: &mut McSystem, event_num: usize) -> Result<(), String> {
готово

2023-03-20 09:38 UTC, KiK0S commented on crates/dslab-mp/src/mc/pending_events.rs
> +        let default = 0.0;
убрал вообще, вынес логику в get_global_time

2023-03-20 09:38 UTC, KiK0S commented on crates/dslab-mp/src/mc/pending_events.rs
> +                options: DeliveryOptions::NoFailures(rtt),
готово

2023-03-20 09:38 UTC, KiK0S commented on crates/dslab-mp/src/mc/events.rs
> +        duration: f64,
да, давайте так

2023-03-20 09:38 UTC, KiK0S commented on crates/dslab-mp/src/mc/pending_events.rs
> +    pub fn add_message(&mut self, proc: String, time: f64, event: McEventId) -> HashSet<McEventId> {
теперь везде Option

2023-03-20 09:38 UTC, KiK0S commented on crates/dslab-mp/src/mc/pending_events.rs
> +                start_time: *self.global_time.get(proc).unwrap_or(&default),
Вынес в get_global_time

2023-03-20 09:39 UTC, KiK0S commented on crates/dslab-mp/src/mc/pending_events.rs
> +                *entry = event_timed.start_time + duration;
Да, сделал через insert

2023-03-20 09:58 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +        self.add_event(system, event.duplicate().unwrap());
сделал push_with_fixed_id

2023-03-20 13:51 UTC, osukhoroslov requested changes

2023-03-20 13:51 UTC, osukhoroslov commented on crates/dslab-mp/Cargo.toml
> +ordered-float = { version = "3.0", default-features = false }
```suggestion
ordered-float = { version = "3.4.0", default-features = false }
```

2023-03-20 13:51 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/events.rs
> +pub struct SystemTime(pub OrderedFloat<f64>);
Точно нельзя обойтись просто OrderedFloat без этой структуры контейнера? Serialize например кажется входит как фича в ordered_float. Кроме того название SystemTime запутывает (речь ведь на самом деле про продолжительность доставки или таймера).

2023-03-20 13:51 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/network.rs
> +    roundtrip_time: Option<f64>,
Надо переименовать в `max_delay`

2023-03-20 13:51 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/network.rs
> +                options: DeliveryOptions::NoFailures(SystemTime::from(self.roundtrip_time.unwrap())),
Если мы так смело делаем unwrap, то зачем хранить delay в Option?

2023-03-20 13:51 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/pending_events.rs
> +        self.global_time.get(proc).map(|x| *x).unwrap_or_default()
```suggestion
        self.global_time.get(proc).copied().unwrap_or_default()
```

2023-03-20 13:51 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/pending_events.rs
> +        }
```suggestion
        if let McEvent::TimerFired { timer_delay, proc, .. } = &event_timed.event {
            assert!(self.get_global_time(proc) <= event_timed.start_time + *timer_delay);
            self.global_time
                .insert(proc.clone(), event_timed.start_time + *timer_delay);
        }
```

2023-03-20 13:51 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +        let events_num = system.events_num();
Предлагаю избавиться от events_num:

```
    fn dfs(&mut self, system: &mut McSystem) -> Result<(), String> {
        let state = system.get_state(self.search_depth);
        let available_events = system.available_events();

        let result = self.check_state(&state, available_events.len());

        self.mark_visited(state);
        if let Some(result) = result {
            return result;
        }

        for event_id in available_events {
            self.process_event(system, event_id)?;
        }
        Ok(())
    }
```

аналогично в BFS

2023-03-20 13:51 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +    pub fn get_max_delay(&self) -> f64 {
Лучше без get - `max_delay` и перенести над `set_delays`.

2023-03-20 13:51 UTC, osukhoroslov commented on crates/dslab-mp/tests/pending_events.rs
> +use rand::prelude::IteratorRandom;
Неверный порядок импортов

2023-03-21 17:36 UTC, KiK0S commented on crates/dslab-mp/Cargo.toml
> +ordered-float = { version = "3.0", default-features = false }
поправил, добавил serde feature

2023-03-21 17:36 UTC, KiK0S commented on crates/dslab-mp/src/mc/network.rs
> +    roundtrip_time: Option<f64>,
готово

2023-03-21 17:37 UTC, KiK0S commented on crates/dslab-mp/src/mc/network.rs
> +                options: DeliveryOptions::NoFailures(SystemTime::from(self.roundtrip_time.unwrap())),
да, там надо default проставить

2023-03-21 17:37 UTC, KiK0S commented on crates/dslab-mp/src/mc/network.rs
> +                options: DeliveryOptions::NoFailures(SystemTime::from(self.roundtrip_time.unwrap())),
сделал

2023-03-21 17:37 UTC, KiK0S commented on crates/dslab-mp/src/mc/pending_events.rs
> +        self.global_time.get(proc).map(|x| *x).unwrap_or_default()
сделал

2023-03-21 17:37 UTC, KiK0S commented on crates/dslab-mp/src/mc/pending_events.rs
> +        }
поправил

2023-03-21 17:38 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +        let events_num = system.events_num();
поправил, метод удалил

2023-03-21 17:39 UTC, KiK0S commented on crates/dslab-mp/tests/pending_events.rs
> +use rand::prelude::IteratorRandom;
поправил

2023-03-21 17:39 UTC, KiK0S commented on crates/dslab-mp/src/network.rs
> +    pub fn get_max_delay(&self) -> f64 {
поправил

2023-03-22 20:16 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/network.rs
> +    max_delay: Option<f64>,
Предлагаю убрать Option, если кроме значения и INFINITY ничего больше не ожидается. Кстати, у сети в dslab-mp сейчас всегда выставлен дефолтный max_delay.

2023-03-24 09:44 UTC, KiK0S commented on crates/dslab-mp/src/mc/network.rs
> +    max_delay: Option<f64>,
да, разумно, убрал

2023-03-25 15:15 UTC, KiK0S commented on crates/dslab-mp/src/mc/dependency_resolver.rs
> +    proc_timers: BTreeMap<String, BidirectionalMapping>,
done

2023-03-25 15:16 UTC, KiK0S commented on crates/dslab-mp/src/mc/dependency_resolver.rs
> +        let messages_iter = self.pending_messages[proc].1.keys().map(|x| *x);
теперь не нужно

2023-03-25 15:16 UTC, KiK0S commented on crates/dslab-mp/src/mc/dependency_resolver.rs
> +    BTreeMap<McEventId, McDuration>,
глобальный маппинг хорошая идея

2023-03-25 15:16 UTC, KiK0S commented on crates/dslab-mp/src/mc/dependency_resolver.rs
> +            if *timer < time {
уже неактуально

2023-03-25 15:16 UTC, KiK0S commented on crates/dslab-mp/src/mc/dependency_resolver.rs
> +        if let Some((timer, first_group)) = timers.0.iter().next() {
аналогично неактуально уже

2023-03-25 15:17 UTC, KiK0S commented on crates/dslab-mp/src/mc/dependency_resolver.rs
> +            "duplicate McEventId not allowed"
поменял

2023-03-25 15:17 UTC, KiK0S commented on crates/dslab-mp/src/mc/dependency_resolver.rs
> +        mapping.0.entry(McDuration::from(time)).or_default().insert(id);
тоже больше нигде нет

2023-03-25 15:18 UTC, KiK0S commented on crates/dslab-mp/src/mc/events.rs
> +use std::ops::Add;
убрал

2023-03-25 15:18 UTC, KiK0S commented on crates/dslab-mp/src/mc/pending_events.rs
> +        assert!(self.get(id).is_none(), "use unique id's");
да, так лучше

2023-03-25 15:18 UTC, KiK0S commented on crates/dslab-mp/src/mc/pending_events.rs
> +        assert!(self.get(id).is_none(), "use unique id's");
поправил

2023-03-25 15:18 UTC, KiK0S commented on crates/dslab-mp/src/mc/events.rs
> +pub type McDuration = OrderedFloat<f64>;
вернул, хотя мне кажется сейчас и Duration норм

2023-03-25 19:16 UTC, osukhoroslov approved these changes

2023-03-25 19:30 UTC, merged