[faas] Performance enhancement
osukhoroslov/dslab pull request #193
Opened 2023-01-30 15:03 UTC by SYury

Оптимизировал производительность faas-симулятора:
- Заменил некоторые хеш-таблицы на расширяющиеся векторы там, где возможно
- Заменил хеш-функцию во многих таблицах и сетах на более слабую и быструю
- Сделал добавление запросов в симуляцию через буфер

Результаты на бенчмарке OpenDC:
```
size    time (s)       throughput (evt/s)      main branch time (s)      main branch throughput (evt/s)
4*10^4  0.04             309 * 10^4                    0.07                         174 * 10^4
4*10^5  0.38             319 * 10^4                    0.74                         161 * 10^4
4*10^6  3.77             318 * 10^4                    8.52                         141 * 10^4
4*10^7  37.25            322 * 10^4                    105.02                       114 * 10^4
```

2023-02-05 16:27 UTC, osukhoroslov commented on crates/dslab-faas/src/simulation.rs
> +    /// simulation time since next event extraction is logarithmic in the number of pending events.
Есть цифры на сколько именно буффер ускоряет симуляцию? Стоит ли дополнительных усложнений логики?

2023-02-05 16:27 UTC, osukhoroslov commented on crates/dslab-faas/src/simulation.rs
> +            for item in iter {
А почему если буфер не пустой, то мы им не пользуемся?

2023-02-05 16:27 UTC, osukhoroslov commented on crates/dslab-faas/src/simulation.rs
> +            // technically we can append iterator contents to buffer even if it is not empty; in case
Не понял комментарий, можешь пояснить что имеется ввиду?

2023-02-05 16:27 UTC, osukhoroslov commented on crates/dslab-faas/src/request_buffer.rs
> +        if id == self.update_id {
Почему важно проверять `id == self.update_id`, а нельзя просто позвать в контроллере `buffer.next()`?

2023-02-05 16:27 UTC, osukhoroslov commented on crates/dslab-faas/src/controller.rs
> +                let id = request.id;
Не стоит вводить ради одного использования

2023-02-05 16:27 UTC, osukhoroslov commented on crates/dslab-faas/src/controller.rs
> +                if let Some(next) = self.buffer.borrow_mut().try_update(id) {
Я правильно понимаю, что логика такая - контроллер при получении события из симуляции, пропихивает в очередь симуляции следующее событие из буфера?

2023-02-05 16:27 UTC, osukhoroslov commented on crates/dslab-faas/src/stats.rs
> +            self.wasted_resource_time.get(0).unwrap().sum()
Тоже можно реализовать для удобства Index.index

2023-02-05 18:22 UTC, SYury commented on crates/dslab-faas/src/simulation.rs
> +    /// simulation time since next event extraction is logarithmic in the number of pending events.
Конкретных цифр нет, но именно он вылечил проблемы с масштабируемостью: число запросов в секунду раньше падало из-за логарифма в очереди событий. Навскидку где-то половину ускорения даёт буфер.

2023-02-05 18:24 UTC, SYury commented on crates/dslab-faas/src/simulation.rs
> +            for item in iter {
Мне не хотелось возиться со всякими проверками на упорядоченность при добавлении итератора к непустому буферу

2023-02-05 18:26 UTC, SYury commented on crates/dslab-faas/src/simulation.rs
> +            // technically we can append iterator contents to buffer even if it is not empty; in case
Если все запросы буфера происходят раньше всех запросов в итераторе, то можно добавить содержимое итератора сзади к буферу, но это всегда можно сделать на стороне пользователя, склеив все подаваемые сюда итераторы в порядке возрастания во времени

2023-02-05 18:27 UTC, SYury commented on crates/dslab-faas/src/request_buffer.rs
> +        if id == self.update_id {
Теоретически пользователь может добавить часть запросов так, что они не попадут в буфер, а я хочу вынимать очередной запрос из буфера только при обработке предыдущего.

2023-02-05 18:27 UTC, SYury commented on crates/dslab-faas/src/controller.rs
> +                if let Some(next) = self.buffer.borrow_mut().try_update(id) {
Да

2023-02-06 11:54 UTC, osukhoroslov commented on crates/dslab-faas/src/simulation.rs
> +    /// simulation time since next event extraction is logarithmic in the number of pending events.
Предлагаю перенести эту оптимизацию прямо в `dslab_core`, чтобы упростить код здесь и заодно ускорить остальные модули где используются большие трейсы (например, iaas). Идея такая. Добавить в SimulationContext метод `emit_ordered`, который размещает события внутри deque (внутри SimulationState). Предполагается, что события туда передаются в порядке неубывания их времени, это можно проверять при добавлении и паниковать если пользователь нарушил контракт. При вызове SimulationState.next_event, если первое событие в deque меньше чем первое в heap (по времени и id события), то берем событие из deque.

2023-02-06 11:55 UTC, osukhoroslov commented on crates/dslab-faas/src/simulation.rs
> +            for item in iter {
Будет решено если перенести буфер в `dslab-core`

2023-02-06 11:56 UTC, osukhoroslov commented on crates/dslab-faas/src/simulation.rs
> +            // technically we can append iterator contents to buffer even if it is not empty; in case
Будет неактуально если перенести буфер в `dslab-core`

2023-02-06 11:56 UTC, osukhoroslov commented on crates/dslab-faas/src/request_buffer.rs
> +        if id == self.update_id {
Будет неактуально если перенести буфер в `dslab-core`

2023-02-06 11:57 UTC, osukhoroslov commented on crates/dslab-faas/src/controller.rs
> +                if let Some(next) = self.buffer.borrow_mut().try_update(id) {
Можно избавиться если перенести буфер в `dslab-core`

2023-02-12 14:12 UTC, SYury commented on crates/dslab-faas/src/simulation.rs
> +    /// simulation time since next event extraction is logarithmic in the number of pending events.
Сделал

2023-02-14 17:25 UTC, SYury commented on crates/dslab-faas/src/trace.rs
> +    /// by time.
Поправил

2023-02-14 17:25 UTC, SYury commented on crates/dslab-faas/src/trace.rs
> +    fn ordered_requests(&self) -> bool;
Переименовал

2023-02-14 17:25 UTC, SYury commented on crates/dslab-faas/src/util.rs
> +/// A simple mapping type for storing (key, value) pairs where the keys are assumed to be taken
Добавил

2023-02-14 17:25 UTC, SYury commented on crates/dslab-faas/src/util.rs
> +/// Similar to VecMap, but returns default value instead of None and auto-extends to keys in
Поправил

2023-02-14 17:26 UTC, SYury commented on crates/dslab-faas/src/util.rs
> +pub struct RawVecMap<T: Default> {
Переименовал в DefaultVecMap

2023-02-14 17:26 UTC, SYury commented on crates/dslab-faas/src/invocation.rs
> +    invocations: VecMap<Invocation>,
Так VecMap это и есть Vec, который не надо в явном виде расширять

2023-02-14 19:39 UTC, SYury commented on crates/dslab-faas/src/stats.rs
> +            self.wasted_resource_time.get(0).unwrap().sum()
Сделал

2023-02-14 19:39 UTC, SYury commented on crates/dslab-faas/tests/test_simulation.rs
> +    let f2_stats = stats.func_stats.get(1).unwrap();
Сделал

2023-02-15 17:30 UTC, osukhoroslov commented on crates/dslab-faas/src/invocation.rs
> +    invocations: VecMap<Invocation>,
А надо расширять потому что new_invocation может вызываться не в порядке следования request.id? Если бы запросы приходили строго в порядке их id и без пропусков (или же бы сама registry) их нумеровала, то можно было использовать обычный Vec.

2023-02-15 18:07 UTC, SYury commented on crates/dslab-faas/src/controller.rs
> +    buffer: Rc<RefCell<RequestBuffer>>,
После переноса буфера неактуально

2023-02-15 18:07 UTC, SYury commented on crates/dslab-faas/src/controller.rs
> +                let id = request.id;
После переноса буфера неактуально

2023-02-15 18:09 UTC, SYury commented on crates/dslab-faas/src/invocation.rs
> +    invocations: VecMap<Invocation>,
Да, id выдаются в порядке добавления запросов в симуляцию, а new_invocation в порядке времени запроса. Конечно можно было бы при выдаче нового id добавлять None в конец, но я не вижу очевидных преимуществ по сравнению с ленивым расширением внутри VecMap

2023-02-15 19:12 UTC, osukhoroslov commented on crates/dslab-faas/src/invocation.rs
> +    invocations: VecMap<Invocation>,
>  id выдаются в порядке добавления запросов в симуляцию, а new_invocation в порядке времени запроса.

а зачем нам нужно присваивать id запросам до их попадания в InvocationRegistry. Почему нельзя сделать выдачу id при регистрации запроса в registry?

2023-02-15 20:01 UTC, SYury commented on crates/dslab-faas/src/invocation.rs
> +    invocations: VecMap<Invocation>,
Я хотел, чтобы InvocationRequest всегда был корректно проинициализирован, а для этого пришлось выдавать ему id при создании

2023-02-15 20:20 UTC, osukhoroslov commented on crates/dslab-faas/src/invocation.rs
> +    invocations: VecMap<Invocation>,
В реальности у нас сначала приходит какой-то внешний запрос, и на входе в систему мы его преобразуем во внутренний с id. С этой точки зрения логично было бы в качестве прототипа InvocationRequest использовать InvocationStartEvent, добавив в него все поля кроме id, а InvocationRequest создавать в controller.invoke() получив id от registry.

2023-02-18 16:20 UTC, osukhoroslov requested changes

2023-02-18 16:20 UTC, osukhoroslov commented on crates/dslab-core/src/state.rs
> +        true
Предлагаю убрать `1e-12` и возложить решение возможных проблем с точностью на пользователя.

```suggestion
        self.ordered_events
            .back()
            .map(|last| last.time <= self.clock + delay)
            .unwrap_or(true)
```

2023-02-18 16:20 UTC, osukhoroslov commented on crates/dslab-faas/src/simulation.rs
> +            if self.ctx.can_emit_ordered(item.time - self.sim.time()) {
Если в итераторе запросы упорядочены по времени, то не требуется делать проверку на каждый запрос. Достаточно сделать проверку в начале только для первого запроса, чтобы понять какой emit дальше использовать.

2023-02-18 16:32 UTC, SYury commented on crates/dslab-core/src/state.rs
> +            if maybe_heap.is_some() && (maybe_deque.is_none() || maybe_heap.unwrap() > maybe_deque.unwrap()) {
Там же компаратор наоборот сделан, так как куча по умолчанию на максимум.

2023-02-18 17:09 UTC, SYury commented on crates/dslab-core/src/state.rs
> +        true
Я опасаюсь, что тут может возникнуть очень маленькая ошибка в delay + self.clock, играющая роль при delay + self.clock == evt.time, причем погрешность вызвана не действиями пользователя.

2023-02-18 17:11 UTC, SYury commented on crates/dslab-faas/src/simulation.rs
> +            if self.ctx.can_emit_ordered(item.time - self.sim.time()) {
Тут так и сделано. Или ты про проверку с паникой внутри emit_ordered?

2023-02-18 19:12 UTC, osukhoroslov commented on crates/dslab-faas/src/simulation.rs
> +            if self.ctx.can_emit_ordered(item.time - self.sim.time()) {
Действительно так и делается.

2023-02-18 19:13 UTC, SYury commented on crates/dslab-faas/src/container.rs
> +        let id = app.id as usize;
Заменил вообще все id на usize

2023-02-18 19:13 UTC, osukhoroslov commented on crates/dslab-faas/src/simulation.rs
> +                self.ctx.emit_ordered(
Можно попробовать избавиться от отдельного emit_ordered для первого запроса с помощью peek(). https://doc.rust-lang.org/stable/std/iter/struct.Peekable.html

2023-02-18 19:16 UTC, SYury commented on crates/dslab-faas/src/invocation.rs
> +    invocations: VecMap<Invocation>,
Я начал было это делать, а потом увидел, что вызовы всё равно не станут добавляться в нужном порядке, так как каждый вызов добавляется в момент начала исполнения (чтобы сразу проставить ему поле start), а тут уже порядок предсказать не выйдет, более ранний вызов вполне может застрять на инвокере. К тому же, я возвращал эти id сразу после регистрации вызова, и можно было после симуляции достать Invocation по id. Так что я добавил возвращение первого id в функцию, добавляющую итератор.

2023-02-18 19:16 UTC, osukhoroslov commented on crates/dslab-core/src/state.rs
> +        true
Если будет ошибка, то пользователь пусть решает проблему, например путем округления времен событий или использования max(clock+delay, prev_event_time).

2023-02-18 19:17 UTC, osukhoroslov commented on crates/dslab-core/src/state.rs
> +        true
У тебя самого такая ошибка была?

2023-02-18 19:19 UTC, SYury commented on crates/dslab-core/src/state.rs
> +        self.ordered_events.retain(|x| !pred(x));
Так всё равно придётся по всей очереди пройти, чтобы проверить предикат

2023-02-18 19:20 UTC, SYury commented on crates/dslab-core/src/state.rs
> +        self.ordered_events.retain(|x| !pred(x));
Может лучше сделать наоборот `cancel_events_without_ordered` или `cancel_heap_events`, которая будет делать как раньше, а в этой функции оставить так? Всё-таки от функции `cancel_events` ожидается отмена всех подходящих событий, а наличие отдельной очереди -- это уже детали реализации, которые необязательно знать

2023-02-18 19:23 UTC, SYury commented on crates/dslab-core/src/state.rs
> +        true
Не знаю, я сразу такое условие сделал. Но у меня были ошибки с добавлением delay порядка -1e-16 (фактически ноль), и наличие таких ошибок не всегда очевидно

2023-02-18 19:29 UTC, osukhoroslov commented on crates/dslab-core/src/state.rs
> +        self.ordered_events.retain(|x| !pred(x));
В retain еще происходит перенос элементом массива, насколько я себе это представляю

2023-02-18 19:32 UTC, osukhoroslov commented on crates/dslab-core/src/state.rs
> +        self.ordered_events.retain(|x| !pred(x));
Хорошо, пусть будет `cancel_heap_events`.

2023-02-18 19:37 UTC, SYury commented on crates/dslab-core/src/state.rs
> +        self.ordered_events.retain(|x| !pred(x));
Это правда, тут лучшее решение зависит от того, какая доля событий отменяется. Кажется, что положить событие в HashSet должно работать медленнее, чем просто перенос

2023-02-18 19:42 UTC, osukhoroslov commented on crates/dslab-core/src/state.rs
> +        true
Тогда надо не только в can_add_ordered_event это учитывать, но и когда добавляем событие у которого время меньше clock, то округлять вверх до clock, а то монотонности в симуляции не будет.

2023-02-18 19:42 UTC, osukhoroslov commented on crates/dslab-core/src/state.rs
> +        true
Ну и обязательно про это написать в документации

2023-02-18 19:48 UTC, SYury commented on crates/dslab-core/src/state.rs
> +        true
Округлять пожалуй долго будет, а события с временем меньше clock вроде как паникуют при добавлении. Или ты предлагаешь заменять delay на max(delay, 0) для delay > -epsilon?

2023-02-18 19:51 UTC, osukhoroslov commented on crates/dslab-core/src/state.rs
> +        self.ordered_events.retain(|x| !pred(x));
Я исхожу из того, что ordered_events будет использоваться для trace-driven симуляций и соответственно в нём может быть очень много событий. Скажем 1M событий, мы отменяем одно где-то в середине, в результате переносим 500K событий. Вот это меня беспокоит.

Пока есть только сценарии где отменяемых событий мало, но наверное могут появиться и такие, где их много. Можно реализовать гибридную стратегию, если доля событий небольшая - используем canceled_events, если большая - то retain.

2023-02-18 19:54 UTC, SYury commented on crates/dslab-core/src/state.rs
> +        self.ordered_events.retain(|x| !pred(x));
Тогда лучше сделаю складывание в canceled_events, так как в случае гибридной стратегии при использовании retain придётся два раза предикат считать.

2023-02-18 20:01 UTC, osukhoroslov commented on crates/dslab-core/src/state.rs
> +        true
Допустим clock=90, last=100 (последнее время в буфере). Приходит запрос add_ordered_event c delay 9.99.... Допустим проверка в can_add_ordered_event пройдена, тогда событие будет добавлено в буфер c временем 99.99... Паники не будет, но теперь события в буфере не упорядочены по времени.

2023-02-18 20:07 UTC, SYury commented on crates/dslab-core/src/state.rs
> +        true
Да, действительно. Сделаю так.

2023-02-19 14:43 UTC, SYury commented on crates/dslab-core/src/state.rs
> +        self.ordered_events.retain(|x| !pred(x));
Сделал

2023-02-19 14:43 UTC, SYury commented on crates/dslab-core/src/state.rs
> +        self.ordered_events.retain(|x| !pred(x));
Сделал

2023-02-19 14:44 UTC, SYury commented on crates/dslab-core/src/state.rs
> +            panic!("Event order is broken! Make sure you are passing events to emit_*_ordered functions in non-decreasing order of time.");
Сделал

2023-02-19 14:44 UTC, SYury commented on crates/dslab-core/src/context.rs
> +    /// This and all other `emit_..._ordered` functions are special variants of normal `emit_...` functions
Сделал

2023-02-19 14:44 UTC, SYury commented on crates/dslab-core/src/state.rs
> +        true
Сделал

2023-02-19 14:44 UTC, SYury commented on crates/dslab-faas/src/simulation.rs
> +                self.ctx.emit_ordered(
Сделал

2023-02-20 11:05 UTC, osukhoroslov commented on crates/dslab-core/src/state.rs
> +        true
Кажется все еще остается проблема с отрицательным delay. Допустим clock=100, last=100 (последнее время в буфере). Приходит запрос add_ordered_event c delay -0.000.... Допустим проверка в can_add_ordered_event пройдена, тогда событие будет добавлено в буфер c временем 100 (работает max). Но потом будет паника из-за отрицательного delay.

2023-02-20 11:50 UTC, osukhoroslov commented on crates/dslab-faas/src/invocation.rs
> +    invocations: VecMap<Invocation>,
> каждый вызов добавляется в момент начала исполнения (чтобы сразу проставить ему поле start)

Можно все поля, которые неизвестны на момент начала исполнения, типа start сделать Option. И тогда можно в register_invocation сразу добавить вызов в invocations. И раз есть возможность через симуляцию узнать про запрос через get_invocation, то для еще не начавшихся запросов будет тоже что-то возвращаться. Вообще кажется InvocationRegistry могла быть хорошим местом для отслеживания жизненного цикла запроса (с разными состояниями в которых он может пребывать) и попутно там же можно было бы считать связанную с этим статистику. Нечто похожее (без статистики) реализовано [здесь](https://github.com/osukhoroslov/dslab/blob/304583dd3802db21852561999b9ba223b99b6520/crates/dslab-iaas/src/core/vm_api.rs#L49) в IaaS.

2023-02-20 11:54 UTC, osukhoroslov commented on crates/dslab-core/src/state.rs
> +    /// This function does not check events added with emit_ordered methods.
```suggestion
    /// This function does not check events from `ordered_events`.
```

2023-02-20 11:57 UTC, osukhoroslov commented on crates/dslab-core/src/state.rs
> +            panic!("Event order is broken! Pass events to emit_*_ordered functions in non-decreasing order of time.");
Предлагаю не ссылаться здесь на emit_ordered_*, все таки это не часть интерфейса самого SimulationState, Думаю из сообщения и так будет понятно в чем дело.

```suggestion
            panic!("Event order is broken! Ordered events should be added in non-decreasing order of their time.");
```

2023-02-20 11:58 UTC, osukhoroslov commented on crates/dslab-faas/src/simulation.rs
> +    /// Returns id of the first invocation if the iterator is not empty, invocations have consecutive ids that follow their order inside the iterator.
```suggestion
    /// This function provides a way to send invocation requests to a special ordered deque
    /// inside the simulation, which works faster than the default heap.
    /// Returns id of the first invocation if the iterator is not empty,
    /// invocations have consecutive ids that follow their order inside the iterator.
```

2023-02-20 11:58 UTC, osukhoroslov commented on crates/dslab-faas/src/simulation.rs
> +    /// Returns id of the first invocation if the trace is not empty. Invocations have consecutive ids in increasing order of time.
```suggestion
    /// Returns id of the first invocation if the trace is not empty.
    /// Invocations have consecutive ids in increasing order of time.
```

2023-02-20 12:08 UTC, osukhoroslov commented on crates/dslab-faas/src/trace.rs
> +    /// Indicates whether the requests produced by `request_iter` are ordered in increasing order by time.
```suggestion
    /// Indicates whether the requests produced by `request_iter` are ordered in non-decreasing order of their time.
```

2023-02-20 17:41 UTC, SYury commented on crates/dslab-core/src/state.rs
> +        true
Так если паника будет, то неважно, было ли событие добавлено или нет

2023-02-20 17:59 UTC, osukhoroslov commented on crates/dslab-core/src/state.rs
> +        true
Так я думал мы такие события хотим добавлять, и не паниковать если очень маленький отрицательный delay

2023-02-20 19:16 UTC, SYury commented on crates/dslab-core/src/state.rs
> +        true
Нет, я хотел избавиться от проблем, когда в условии <= возникает равенство, но из-за погрешности сложения в левой части условие нарушается. Если пытаться решить проблему с delay, то это надо ещё и при добавлении в кучу epsilon прибавлять

2023-03-03 21:06 UTC, SYury commented on crates/dslab-faas/src/invocation.rs
> +    invocations: VecMap<Invocation>,
Сделал

2023-03-04 07:58 UTC, SYury commented on crates/dslab-core/src/state.rs
> +    /// This function does not check events added with emit_ordered methods.
Поправил

2023-03-04 07:58 UTC, SYury commented on crates/dslab-core/src/state.rs
> +            panic!("Event order is broken! Pass events to emit_*_ordered functions in non-decreasing order of time.");
Поправил

2023-03-04 07:59 UTC, SYury commented on crates/dslab-faas/src/simulation.rs
> +    /// Returns id of the first invocation if the iterator is not empty, invocations have consecutive ids that follow their order inside the iterator.
Поправил

2023-03-04 08:02 UTC, SYury commented on crates/dslab-faas/src/trace.rs
> +    /// Indicates whether the requests produced by `request_iter` are ordered in increasing order by time.
Поправил

2023-03-04 08:02 UTC, SYury commented on crates/dslab-faas/src/simulation.rs
> +    /// Returns id of the first invocation if the trace is not empty. Invocations have consecutive ids in increasing order of time.
Поправил

2023-03-04 13:54 UTC, osukhoroslov requested changes

2023-03-04 13:54 UTC, osukhoroslov commented on crates/dslab-core/src/state.rs
> +            time: last_time.max(self.clock + delay),
Комментарий чтобы помнить

```suggestion
            // max is used to enforce time order despite of floating-point errors
            time: last_time.max(self.clock + delay),
```

2023-03-04 13:54 UTC, osukhoroslov commented on crates/dslab-core/src/state.rs
> +            if delay + self.clock < evt.time - 1e-12 {
Комментарий чтобы помнить

```suggestion
            // small epsilon is used to account for floating-point errors
            if self.clock + delay < evt.time - 1e-12 {
```

2023-03-04 13:54 UTC, osukhoroslov commented on crates/dslab-faas/src/controller.rs
>          let app = reg.get_app(app_id).unwrap();
```suggestion
        let app = reg.get_app_by_function(func_id).unwrap();
```

2023-03-04 13:54 UTC, osukhoroslov commented on crates/dslab-faas/src/host.rs
> +            &ir[id],
от `ir[id]` везде можно избавиться так:

```
    pub fn invoke(&mut self, id: usize, time: f64) -> InvokerDecision {
        let mut ir = self.invocation_registry.borrow_mut();
        let mut invocation = &mut ir[id];
        invocation.host_id = Some(self.id);
        self.container_manager.inc_active_invocations();
        let status = self
            .invoker
            .invoke(invocation, self.function_registry.clone(), &mut self.container_manager, time);
        let mut stats = self.stats.borrow_mut();
        stats.on_new_invocation(invocation.func_id);
        match status {
            InvokerDecision::Warm(container_id) => {
                drop(stats);
                drop(ir);
                self.start_invocation(container_id, id, time);
            }
            InvokerDecision::Cold((container_id, delay)) => {
                invocation.status = InvocationStatus::WaitingForContainer;
                invocation.container_id = Some(container_id);
                stats.on_cold_start(invocation.func_id, delay);
                drop(stats);
                self.container_manager.reserve_container(container_id, id);
            }
            _ => {
                invocation.status = InvocationStatus::Queued;
            }
        }
        status
    }
```

2023-03-04 13:54 UTC, osukhoroslov commented on crates/dslab-faas/src/invocation.rs
>      pub finished: Option<f64>,
Предлагаю назвать `start_time` и `finish_time`

2023-03-04 13:54 UTC, osukhoroslov commented on crates/dslab-faas/src/invoker.rs
> +    queue: Vec<(usize, usize, f64)>,
Надо заменить tuple на структуру, чтобы избавиться от обращений по числовым индексам в dequeue.

2023-03-04 13:54 UTC, osukhoroslov commented on crates/dslab-faas/src/invoker.rs
> +            let status = self.try_invoke(item.1, fr.clone(), cm, time);
С учетом переменований я бы заменил `status` на `decision`

2023-03-04 13:54 UTC, osukhoroslov commented on crates/dslab-faas/src/invoker.rs
> +        let status = self.try_invoke(invocation.func_id, fr, cm, time);
С учетом переменований я бы заменил `status` на `decision`

2023-03-04 13:54 UTC, osukhoroslov commented on crates/dslab-faas/src/invocation.rs
> +    pub fn new_invocation(&mut self, func_id: usize, duration: f64, arrival_time: f64) -> usize {
Поскольку функция не возвращает Invocation (как обычно функции с именем new), то предлагаю переименовать в `add_invocation` или `register_invocation`.

2023-03-04 13:54 UTC, osukhoroslov commented on crates/dslab-faas/src/stats.rs
> +        let total_len = invocation.finished.unwrap() - invocation.arrival_time;
Под эти времена можно завести на Invocation функции `response_time`, `execution_time`, `wait_time` (response_time = wait_time + execution_time).

2023-03-04 13:54 UTC, osukhoroslov commented on crates/dslab-faas/tests/test_invocation_lifecycle.rs
> +    }
```suggestion
    let mem = sim.create_resource("mem", 1);
    sim.add_host(None, ResourceProvider::new(vec![mem]), 1);
```

2023-03-06 08:10 UTC, SYury commented on crates/dslab-core/src/context.rs
> +    /// order of time, otherwise the simulation will panic.
Добавил комментарий

2023-03-06 08:10 UTC, SYury commented on crates/dslab-core/src/context.rs
> +    /// Returns true if and only if new event will **not** break the contract.
Добавил комментарий

2023-03-06 08:10 UTC, SYury commented on crates/dslab-core/src/state.rs
> +            time: last_time.max(self.clock + delay),
Добавил

2023-03-06 08:10 UTC, SYury commented on crates/dslab-core/src/state.rs
> +            if delay + self.clock < evt.time - 1e-12 {
Добавил

2023-03-06 08:10 UTC, SYury commented on crates/dslab-faas/src/controller.rs
>          let app = reg.get_app(app_id).unwrap();
Сделал

2023-03-06 08:11 UTC, SYury commented on crates/dslab-faas/src/host.rs
> +            &ir[id],
Сделал

2023-03-06 08:11 UTC, SYury commented on crates/dslab-faas/src/invocation.rs
>      pub finished: Option<f64>,
Переименовал

2023-03-06 08:11 UTC, SYury commented on crates/dslab-faas/src/invoker.rs
> +        let status = self.try_invoke(invocation.func_id, fr, cm, time);
Сделал

2023-03-06 08:11 UTC, SYury commented on crates/dslab-faas/src/invocation.rs
> +    pub fn new_invocation(&mut self, func_id: usize, duration: f64, arrival_time: f64) -> usize {
Сделал

2023-03-06 08:11 UTC, SYury commented on crates/dslab-faas/src/stats.rs
> +        let total_len = invocation.finished.unwrap() - invocation.arrival_time;
Сделал

2023-03-06 08:11 UTC, SYury commented on crates/dslab-faas/tests/test_invocation_lifecycle.rs
> +    }
Сделал

2023-03-06 11:12 UTC, osukhoroslov commented on crates/dslab-faas/src/invocation.rs
> +    pub end_time: Option<f64>,
`finish_time` лучше подходит к `start_time`

2023-03-06 11:17 UTC, SYury commented on crates/dslab-faas/src/invocation.rs
> +    pub end_time: Option<f64>,
Готово

2023-03-06 11:37 UTC, merged