Check heft memory usage
osukhoroslov/dslab pull request #194
Opened 2023-01-30 16:38 UTC by maksim1744

Добавил проверку на наличие необходимого количества памяти перед назначением задачи в конкретный временной слот на ресурсе

2023-02-03 20:16 UTC, osukhoroslov requested changes

2023-02-03 20:16 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/common.rs
> +    let memory_usage = build_memory_usage(&scheduled_tasks[resource], dag);
Каждый раз считать заново график потребления памяти неэффективно. Предлагаю сразу вести учёт графика потребляемых ядер и памяти на каждом ресурсе, обновляя его при назначении задач. И передавать этот график в evaluate_assignment наряду scheduled_tasks. Затем этот график передавать в find_earliest_slot, где сначала с помощью него искать самый ранний слот с достаточными ядрами и памятью, а потом для этого слота по scheduled_tasks уже определять набор ядер (это позволит сэкономить на местах, где ядер заведомо недостаточно, в сравнении с текущим подходом где суммируем доступные ядра). Ну и тогда вся логика будет внутри find_earliest_slot, без отдельных blocked_intervals.

2023-02-15 17:53 UTC, maksim1744 commented
Добавил замер времени построения расписания. Можно сравнить на `RUST_LOG=info cargo run --release -- --scheduler lookahead --run-one montage`, например. С текущей реализацией получается примерно `66ms` без проверки на память, `131ms` с проверкой.

2023-02-15 18:44 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/common.rs
> +    let memory_usage = build_memory_usage(&scheduled_tasks[resource], dag);
График потребления ядер не получится использовать, так как в разные моменты могут быть доступны разные наборы ядер, а мы пока требуем фиксированный набор ядер для выполнения задачи.

2023-02-15 18:47 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/common.rs
> +    let memory_usage = build_memory_usage(&scheduled_tasks[resource], dag);
Предложение вести график потебления памяти вне evaluate_assignment остается.

2023-02-15 18:52 UTC, osukhoroslov commented
> Добавил замер времени построения расписания. Можно сравнить на `RUST_LOG=info cargo run --release -- --scheduler lookahead --run-one montage`, например. С текущей реализацией получается примерно `66ms` без проверки на память, `131ms` с проверкой.

У меня цифры примерно такие - `100ms` vs `230ms`. Двукратное замедление это серьезно. В качестве быстрой оптимизации можно в build_memory_usage игнорировать задачи, завершившиеся до start_time (у меня время упало где-то до `160ms`). Но все-таки я предлагаю попробовать вести учет графика потребления памяти вне evaluate_assignment и измерить что получится при таком подходе.

2023-02-15 19:43 UTC, maksim1744 commented
Добавил поддержку графика памяти в виде [декартового дерева с поддержкой массовых операций](https://en.wikipedia.org/wiki/Treap#Addition/painting_in_a_given_range), время уменьшилось до `103ms`

2023-02-19 15:49 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/treap.rs
> +    left: Option<Box<Node>>,
Почему нужен Box?

2023-02-19 15:49 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/treap.rs
> +    pub fn add(&mut self, l: f64, r: f64, value: i64) {
Принципиально что тип value `i64` или можно сделать `u64`, чтобы избежать кастов в алгоритмах и common?

2023-02-19 15:49 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/treap.rs
> +            treap.height() as u32 <= (ITS.ilog2() + 1) * 7,
У меня компилятор (1.66) ругается error[E0658]: use of unstable library feature 'int_log'. Эта фича стаблизировалась уже? И если нет, то есть ли какая-то стабильная замена?

2023-02-19 15:49 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/treap.rs
> +        let mut rand = rand::thread_rng();
Я бы здесь использовал какой-то отдельный генератор, а не thread rng. Еще можно попробовать что-то простое типа как Xorshift здесь: https://github.com/kenkoooo/competitive-programming-rs/blob/master/src/data_structure/treap.rs

2023-02-19 15:56 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/treap.rs
> +    pub fn add(&mut self, l: f64, r: f64, value: i64) {
Мне нужно было вычитать в lookahead, чтобы уметь отменять операции, там я в `add` отрицательное значение передавал, делать отдельный метод `sub` здесь мне показалось странным

2023-02-19 15:56 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/treap.rs
> +    left: Option<Box<Node>>,
Это указатели на детей, иначе размер структуры на стеке будет бесконечным https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=554ee19e506d362841fe661bc7e8f385

2023-02-19 15:56 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/treap.rs
> +    pub fn max(&mut self, l: f64, r: f64) -> i64 {
Почему эта операция mutable?

2023-02-19 15:57 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/treap.rs
> +            treap.height() as u32 <= (ITS.ilog2() + 1) * 7,
В 1.67 стабилизировалась https://doc.rust-lang.org/std/primitive.usize.html#method.ilog2

2023-02-19 16:01 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/treap.rs
> +    pub fn max(&mut self, l: f64, r: f64) -> i64 {
Там в глубине зовется `push`, который проталкивает обновления в детей. Можно попробовать где-нибудь `Cell` расставить, чтобы сам метод не требовал мутабельной ссылки https://doc.rust-lang.org/std/cell/#when-to-choose-interior-mutability

2023-02-19 16:01 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/treap.rs
> +        let mut rand = rand::thread_rng();
Почему? Тут примерно любой подойдет, thread_rng мне показалось легче всего подставить

2023-02-19 16:03 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/treap.rs
> +        let mut rand = rand::rngs::SmallRng::seed_from_u64(42);
Просто взял первый, который умеет инициализироваться числом

2023-02-19 16:38 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/treap.rs
> +    pub fn max(&mut self, l: f64, r: f64) -> i64 {
В отдельном коммите поставил `Cell`. Методы `treap` немного разрослись, зато теперь не нужна мутабельная ссылка на массив `memory_usage` в `evaluate_assignment`, достаточно константной

2023-02-19 16:40 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/treap.rs
> +    pub fn add(&mut self, l: f64, r: f64, value: i64) {
А то что в max возвращается i64? Если не допускать уменьшения потребления ниже 0, то было бы удобно u64. Ну и remove не вижу причин не добавить. Так даже понятнее будет при чтении что мы уменьшаем потребление.

2023-02-19 16:42 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/treap.rs
> +        let mut rand = rand::thread_rng();
Потому что thread rng он общий и кто-то ещё может им пользоваться. Хотя здесь наверное это действительно не важно.

2023-02-20 12:12 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/treap.rs
> +        let mut rand = rand::rngs::SmallRng::seed_from_u64(42);
Предлагаю взять `Pcg64::seed_from_u64(seed)`, который уже добавлен в Cargo.toml, и тогда не надо будет добавлять туда `features = ["small_rng"]`.

2023-02-20 12:17 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/treap.rs
> +    value: i64,
Здесь тоже предлагаю сделать `u64`, так как потребление не может быть отрицательным.

2023-02-20 12:19 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/treap.rs
> +mod tests {
Надо бы еще добавить тесты, проверяющие корректность (ответы max в присутствии нескольких add и remove).

2023-02-20 15:28 UTC, osukhoroslov commented on crates/dslab-dag/Cargo.toml
> +rand = { version = "0.8.4" }
```suggestion
rand = "0.8.4"
```

2023-02-20 16:46 UTC, osukhoroslov approved these changes

2023-02-20 16:47 UTC, merged