[wip] model checker summary proposal
osukhoroslov/dslab pull request #199
Opened 2023-02-08 21:35 UTC by KiK0S

2023-02-09 18:37 UTC, AnthonyUdovichenko requested changes

2023-02-09 18:37 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/model_checker.rs
> +    pub fn start(&mut self) -> Result<super::strategy::McSummary, String> {
Кажется лучше сделать
```
use crate::mc::strategy::McSummary;
```
в начало, а тут
```
Result<McSummary, String>
```

2023-02-13 19:28 UTC, KiK0S commented on crates/dslab-mp/src/mc/model_checker.rs
> +    pub fn start(&mut self) -> Result<super::strategy::McSummary, String> {
починил это

2023-02-13 19:34 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +            if let LogMode::Debug = self.mode {
В целом я бы даже может убрал этот иф, потому что мы же теперь ничего не копируем, почему бы не поддержать статистику

2023-02-13 19:41 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +            if let LogMode::Debug = self.mode {
Убрать несложно, если понадобится для тестирования решений. Сейчас не очень понятно, зачем считать статистику в дефолтном режиме, если она там не используется. Мб в будущем можно сделать больше всяких разных `LogMode`, например `verbose` или что-то такое, и использовать это там.

2023-02-19 19:35 UTC, AnthonyUdovichenko approved these changes

2023-02-19 19:57 UTC, merged