use hash from state in dfs
osukhoroslov/dslab pull request #206
Opened 2023-02-17 19:13 UTC by KiK0S

2023-02-17 19:14 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +        self.local_outbox == other.local_outbox && self.pending_timers == other.pending_timers && self.sent_message_count == other.sent_message_count && self.received_message_count == other.received_
я кстати не знаю, почему тут такой стиль странный...

2023-02-17 19:18 UTC, KiK0S commented on crates/dslab-mp/src/process.rs
> +
```suggestion
```

2023-02-17 19:18 UTC, KiK0S commented on crates/dslab-mp/src/mc/system.rs
> +
```suggestion
```

2023-02-17 19:18 UTC, KiK0S commented on crates/dslab-mp/src/mc/system.rs
> +
```suggestion
```

2023-02-17 19:18 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +use dslab_mp::mc::strategy::LogMode;
```suggestion
```

2023-02-17 19:18 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategies/dfs.rs
>  use crate::mc::system::{McState, McSystem};
```suggestion

use crate::mc::strategy::{LogMode, Strategy};
use crate::mc::system::{McState, McSystem};
```

2023-02-18 13:33 UTC, osukhoroslov requested changes

2023-02-18 13:33 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/node.rs
> +        self.proc_state.hash().hash(state);
Предлагаю изменить сигнатуру hash() у ProcessState, чтобы избежать создания отдельного hasher-а:

```
pub trait ProcessState: Downcast + Debug {
    fn hash(&self, hasher: &mut dyn Hasher);
}
```

тогда здесь будет

```suggestion
        self.proc_state.hash(state);
```

2023-02-18 13:33 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/node.rs
> +        self.proc_state.hash() == other.proc_state.hash() &&
Сравнивать по хэшу опасно. По хорошему надо иметь возможность проверить на равенство сами ProcessState. Но непонятно как это сделать пока они фигурируют в виде trait-объектов. Разве только добавить в трейт еще один метод `to_string` (или навесить трейт Display), и здесь сравнивать строки. Но тогда мы возвращаемся к тому, что проще изначально состояние хранить в строке (вместо трейта ProcessState использовать type-алиас String). @AnthonyUdovichenko как инициатор этого трейта, что скажете?

2023-02-18 13:33 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/node.rs
> +        self.sent_message_count == other.sent_message_count &&
Почему в eq сравниваются все поля, а не только те, что фигурируют в hash? Если для хранения посещенных событий `self.used` в стратегии используется HashSet, то он по идее в `self.used.contains(&state)` проверяет не только хэши, но и равенство с помощью eq (на случай коллизий). И тогда получается, что мы добавим событие в сет, хотя хэш у него тот же, но допустим отличается received_message_count.

2023-02-18 13:59 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +        self.proc_state.hash().hash(state);
Да, наверное смысл есть,  вроде так просто исторически было у Антона

2023-02-18 14:01 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +        self.proc_state.hash() == other.proc_state.hash() &&
Вроде как вариант можно сказать что trait ProcessState = serde::Serialize, и тогда можно сериализовывать в строку для точного равенства,  а также считать хеш тоже от строки

2023-02-18 14:01 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +        self.sent_message_count == other.sent_message_count &&
да, разумно, я что-то не подумал, что hashset делает :sweat_smile:

2023-02-18 16:26 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/node.rs
> +        self.proc_state.hash().hash(state);
Вполне можно поменять

2023-02-18 16:34 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/node.rs
> +        self.proc_state.hash() == other.proc_state.hash() &&
> Вроде как вариант можно сказать что trait ProcessState = serde::Serialize, и тогда можно сериализовывать в строку для точного равенства, а также считать хеш тоже от строки

Если так заработает, то вроде неплохой вариант (всё ещё не очень хочется привязываться к строке как к единственно возможному представлению `ProcessState`)

2023-02-18 19:20 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/node.rs
> +        self.proc_state.hash() == other.proc_state.hash() &&
Serialize это про те же строки. @AnthonyUdovichenko непонятно какие преимущества даст трейт, если мы все равно будем заставлять разработчика состояния серализовать его в строку )

2023-02-18 21:00 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/node.rs
> +        self.proc_state.hash() == other.proc_state.hash() &&
А давайте тогда как-нибудь вот так сделаем?
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e196fa74e75662a7ae8e511f262b6814

2023-02-18 22:33 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/node.rs
> +        self.proc_state.hash() == other.proc_state.hash() &&
Давайте попробуем

2023-03-09 22:24 UTC, KiK0S commented on crates/dslab-mp-python/src/tests.rs
> +use std::rc::Rc;
надо удалить

2023-03-09 22:24 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +    fn assert_receiver_is_total_eq(&self) {}
кажется можно сделать derive

2023-03-09 22:24 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +        self.sent_message_count == other.sent_message_count &&
поправил

2023-03-09 22:24 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +        self.proc_state.hash().hash(state);
поправил

2023-03-09 22:25 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +        self.proc_state.hash().hash(state);
смог сделать полноценный трейт

2023-03-09 22:25 UTC, KiK0S commented on crates/dslab-mp/src/mc/events.rs
> +#[derive(Serialize, Clone, Debug, Eq, Hash, PartialEq)]
согласен, убрал

2023-03-09 22:25 UTC, KiK0S commented on crates/dslab-mp/src/mc/system.rs
> +        hash_states.hash(hasher);
Да, красиво

2023-03-09 22:25 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +use std::collections::hash_map::DefaultHasher;
убрал

2023-03-09 22:25 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +use std::collections::hash_map::DefaultHasher;
убрал

2023-03-09 22:26 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +    used: HashSet<McState>,
поменял название

2023-03-09 22:26 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +        self.used.insert(state.clone());
да, очень красиво получилось

2023-03-09 22:47 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +    fn assert_receiver_is_total_eq(&self) {}
не, нельзя, он все равно рекурсивно собирает, несмотря на то что уже определен

2023-03-10 17:46 UTC, KiK0S commented on crates/dslab-mp/src/mc/node.rs
> +        self.proc_state.hash() == other.proc_state.hash() &&
Сделал что-то типа этого, реализация работает для другого типа - единственное что, называется по-другому

2023-03-11 14:40 UTC, osukhoroslov requested changes

2023-03-11 14:40 UTC, osukhoroslov commented on crates/dslab-mp/src/process.rs
> +#[derive(Debug, Clone, Hash, Eq, PartialEq)]
Clone не нужен

2023-03-11 14:40 UTC, osukhoroslov commented on crates/dslab-mp/src/process.rs
> +#[derive(Debug, Hash, Eq, PartialEq)]
Почему бы не просто:

```
pub type StringProcessState = String;
```

и просто со строкой работать в PyProcess

2023-03-11 14:40 UTC, osukhoroslov commented on crates/dslab-mp/src/process.rs
> +    fn derived_eq(&self, other: &Box<dyn ProcessState>) -> bool;
Предлагаю переименовать методы (derived менее удачно, т.к. можно их реализовать и без derive) и упростить сигнатуры (без box) так:

```
    fn hash_with_dyn(&self, hasher: &mut dyn Hasher);
    fn eq_with_dyn(&self, other: &dyn ProcessState) -> bool;
```

Тогда реализация будет такая:

```
impl<T: Hash + Eq + Debug + 'static> ProcessState for T {
    fn hash_with_dyn(&self, mut hasher: &mut dyn Hasher) {
        self.hash(&mut hasher);
    }

    fn eq_with_dyn(&self, other: &dyn ProcessState) -> bool {
        if let Some(other) = other.downcast_ref::<T>() {
            self.eq(other)
        } else {
            false
        }
    }
}
```

И в node.rs код изменится так:

```
impl Hash for ProcessEntryState {
    fn hash<H: Hasher>(&self, hasher: &mut H) {
        self.proc_state.hash_with_dyn(hasher);
        self.local_outbox.hash(hasher);
    }
}

impl PartialEq for ProcessEntryState {
    fn eq(&self, other: &Self) -> bool {
        let equal_process_states = self.proc_state.eq_with_dyn(&*other.proc_state);
        equal_process_states && self.local_outbox == other.local_outbox
    }
}
```

Позаимствовал идеи отсюда:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=058eb1f023897651251c631436688345

2023-03-11 14:42 UTC, osukhoroslov commented on crates/dslab-mp/src/process.rs
> +
Лишняя пустая строка

2023-03-12 05:35 UTC, KiK0S commented on crates/dslab-mp/src/process.rs
> +
поправил

2023-03-12 05:36 UTC, KiK0S commented on crates/dslab-mp/src/process.rs
> +    fn derived_eq(&self, other: &Box<dyn ProcessState>) -> bool;
да, выглядит хорошо! поменял

2023-03-12 05:38 UTC, KiK0S commented on crates/dslab-mp/src/process.rs
> +#[derive(Debug, Hash, Eq, PartialEq)]
сделал

2023-03-12 05:39 UTC, KiK0S commented on crates/dslab-mp/src/process.rs
> +#[derive(Debug, Clone, Hash, Eq, PartialEq)]
убрал

2023-03-13 16:58 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +        self.visited.insert(state);
Согласен, что достаточно хранить только хэши. Поскольку вероятность коллизии очень мала, а мы в любом случае не гарантируем ичерпывающий перебор всех состояний. Для случаев, когда все-таки хочется иметь 100% гарантии можно предусмотреть опцию включающую хранение состояний вместо хэшей. Кстати, а как поступают авторы DSLabs?

2023-03-17 17:24 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategies/dfs.rs
> +        self.visited.insert(state);
Попробовал сделать оптимальный вариант, чтобы разную логику вынести за пределы кода стратегии

2023-03-19 15:04 UTC, closed without merging