[network] Add simgrid network benchmark
osukhoroslov/dslab pull request #218
Opened 2023-03-20 12:30 UTC by maksim1744

2023-03-20 22:35 UTC, osukhoroslov commented on examples-other/simgrid/network/network.cpp
> +    xbt_assert(argc == 4 || argc == 3, "Usage: %s NET_TYPE HOST_COUNT [STAR_COUNT]", argv[0]);
А почему не сделать точно такой же CLI как в нашем бенчмарке? Было бы удобнее все сразу запускать.

2023-03-24 20:16 UTC, osukhoroslov commented on examples-other/simgrid/network/network.cpp
> +        std::vector<sg4::Mailbox*> peers = process_mailboxes;
Здесь копирование происходит?

2023-03-24 20:42 UTC, osukhoroslov requested changes

2023-03-24 20:42 UTC, osukhoroslov commented on examples-other/simgrid/network/network.cpp
> +    int aks_left = peers.size();
```suggestion
    int acks_left = peers.size();
```

2023-03-24 20:42 UTC, osukhoroslov commented on examples-other/simgrid/network/network.cpp
> +    std::shuffle(peers.begin(), peers.end(), rng);
В растовском бенчмарке нет шаффла получателей, давайте туда тоже его добавим, что не было DDoS )

2023-03-24 20:42 UTC, osukhoroslov commented on examples-other/simgrid/network/network.cpp
> +        peer->put_init(data, random.uniform_int(500, 2000))
Размеры должны быть как в расте - от 1 до 1000 МБ.

2023-03-24 20:42 UTC, osukhoroslov commented on examples-other/simgrid/network/network.cpp
> +            sg4::LinkInRoute link{zone->create_link("link-" + std::to_string(i) + "-" + std::to_string(j), 100)->set_latency(0.1)->set_sharing_policy(sg4::Link::SharingPolicy::SHARED)};
```suggestion
            sg4::LinkInRoute link{zone->create_link("link-" + std::to_string(i) + "-" + std::to_string(j), "1000MBps")->set_latency(1e-4)->set_sharing_policy(sg4::Link::SharingPolicy::SHARED)};

```

2023-03-24 20:42 UTC, osukhoroslov commented on examples-other/simgrid/network/network.cpp
> +            if (i != j) {
Хост сам с собой по идее не требуется соединять, так как у нас в тестах нет таких передач на самого себя.

2023-03-24 20:42 UTC, osukhoroslov commented on examples-other/simgrid/network/network.cpp
> +        auto link = zone->create_link("link-" + std::to_string(i), 100)->set_latency(0.1)->set_sharing_policy(sg4::Link::SharingPolicy::SHARED);
```suggestion
        auto link = zone->create_link("link-" + std::to_string(i), "1000MBps")->set_latency(1e-4)->set_sharing_policy(sg4::Link::SharingPolicy::SHARED);

```

2023-03-24 20:42 UTC, osukhoroslov commented on examples-other/simgrid/network/network.cpp
> +            zone->add_route(
не надо соединять хост сам с собой, тем более так через двойной собственный линк

2023-03-24 20:42 UTC, osukhoroslov commented on examples-other/simgrid/network/network.cpp
> +        auto link = zone->create_link("link-" + std::to_string(i), 100)->set_latency(0.1)->set_sharing_policy(sg4::Link::SharingPolicy::SHARED);
Здесь bandwidth должно быть downlink_bw * hosts_per_star (см. раст бенчмарк)

2023-03-24 20:42 UTC, osukhoroslov commented on examples-other/simgrid/network/network.cpp
> +        auto link = zone->create_link("link-host-" + std::to_string(i), 100)->set_latency(0.1)->set_sharing_policy(sg4::Link::SharingPolicy::SHARED);
```suggestion
        auto link = zone->create_link("link-host-" + std::to_string(i), "1000MBps")->set_latency(1e-4)->set_sharing_policy(sg4::Link::SharingPolicy::SHARED);

```

2023-03-24 20:42 UTC, osukhoroslov commented on examples-other/simgrid/network/network.cpp
> +                sg4::LinkInRoute c{host_links[j / hosts_per_star]};
```suggestion
                sg4::LinkInRoute c{star_links[j / hosts_per_star]};

```

2023-03-24 21:00 UTC, maksim1744 commented on examples-other/simgrid/network/network.cpp
> +    xbt_assert(argc == 4 || argc == 3, "Usage: %s NET_TYPE HOST_COUNT [STAR_COUNT]", argv[0]);
У симгрида же проблемы с несколькими симуляциями в одной программе

2023-03-24 21:01 UTC, maksim1744 commented on examples-other/simgrid/network/network.cpp
> +        std::vector<sg4::Mailbox*> peers = process_mailboxes;
да

2023-03-24 22:18 UTC, osukhoroslov commented on examples-other/simgrid/network/network.cpp
> +    xbt_assert(argc == 4 || argc == 3, "Usage: %s NET_TYPE HOST_COUNT [STAR_COUNT]", argv[0]);
Напомните что за проблема?

2023-03-27 10:48 UTC, maksim1744 commented on examples-other/simgrid/network/network.cpp
> +    xbt_assert(argc == 4 || argc == 3, "Usage: %s NET_TYPE HOST_COUNT [STAR_COUNT]", argv[0]);
То что один запуск программы это одна симуляция.
Например ниже зона `auto* zone = sg4::create_full_zone("net");` не привязана ни к какой структуре симуляции, как у нас, а просто глобальная.

2023-03-27 10:52 UTC, maksim1744 commented on examples-other/simgrid/network/network.cpp
> +            if (i != j) {
Есть `START`, который с нулевого хоста отправляется всем, в том числе самому себе

2023-03-27 17:32 UTC, osukhoroslov commented on examples-other/simgrid/network/network.cpp
> +            zone->add_route(
Кстати, текущая модель линка в dslab-network не учитывает направление передач? То есть передачи в обе стороны делят общую пропускную способность линка?

2023-03-27 17:37 UTC, maksim1744 commented on examples-other/simgrid/network/network.cpp
> +            zone->add_route(
> Кстати, текущая модель линка в dslab-network не учитывает направление передач? То есть передачи в обе стороны делят общую пропускную способность линка?

Вроде да

2023-03-27 17:37 UTC, osukhoroslov commented
@maksim1744 выложите сюда табличку с результатами нашего и simgrid бенчмарков для сравнения - топология, время работы и время в симуляции.

2023-03-27 17:49 UTC, maksim1744 commented
Время в симуляции
| |dslab|simgrid|
|-|-|-|
|star|`69.97`|`76.32`|
|tree|`69.97`|`76.35`|
|full mesh|`11.12`|`10.86`|

Время симуляции, с
| |dslab|simgrid|
|-|-|-|
|star|`3.25`|`1.53`|
|tree|`4.50`|`2.50`|
|full mesh|`0.62`|`0.08`|

2023-03-27 18:15 UTC, osukhoroslov commented on examples-other/simgrid/network/network.cpp
> +            zone->add_route(
Записал пока не забыл что надо реализовать поддержку full duplex линков https://github.com/osukhoroslov/dslab/issues/223

2023-03-27 18:17 UTC, osukhoroslov commented
> Время в симуляции
> 	dslab 	simgrid
> star 	`69.97` 	`76.32`
> tree 	`69.97` 	`76.35`
> full mesh 	`11.12` 	`10.86`
> 
> Время симуляции, с
> 	dslab 	simgrid
> star 	`3.25` 	`1.53`
> tree 	`4.50` 	`2.50`
> full mesh 	`0.62` 	`0.08`

2023-03-27 18:18 UTC, osukhoroslov commented
А какие будут результаты если сделать в 2 раза больше хостов - 128? Хочется понять динамику.

2023-03-27 18:19 UTC, osukhoroslov commented
И что насчёт fat tree? Получится её реализовать на симгриде?

2023-03-27 18:28 UTC, maksim1744 commented
> И что насчёт fat tree? Получится её реализовать на симгриде?

На самом деле я бы его и из dslab пока убрал --- там же все пути видимо через один верхний коммутатор идут, так как эти пути строятся один раз в самом начале.
В симгриде наверное можно реализовать, задав несколько возможных путей между парой хостов, но я не знаю как это будет работать в итоге

2023-03-27 18:41 UTC, osukhoroslov commented
128 хостов - а времена в симуляции близкие?

2023-03-27 20:01 UTC, osukhoroslov commented
У меня такие времена на Rust получились (SimGrid не ставил):

![изображение](https://user-images.githubusercontent.com/1322460/228053204-f2304613-111b-4fff-b931-1a49663abd48.png)

Заметно медленнее. Что за процессор у вас?

2023-03-27 20:09 UTC, osukhoroslov commented
> > И что насчёт fat tree? Получится её реализовать на симгриде?
> 
> На самом деле я бы его и из dslab пока убрал --- там же все пути видимо через один верхний коммутатор идут, так как эти пути строятся один раз в самом начале. В симгриде наверное можно реализовать, задав несколько возможных путей между парой хостов, но я не знаю как это будет работать в итоге

Да пусть остается раз сделали, надо будет только потом поддержать роутинг с явными маршрутами. 

Посмотрел как FatTree сделана в SimGrid - там статические маршруты вычисляются между каждой парой хостов по [какой-то известной схеме](https://github.com/simgrid/simgrid/blob/5ed37babb2fa9097abe82df299c0aa259ed84d5a/include/simgrid/kernel/routing/FatTreeZone.hpp#L84), реализация [здесь](https://github.com/simgrid/simgrid/blob/4e68c6fc1ff039dd2cea2688981f4c19919874d4/src/kernel/routing/FatTreeZone.cpp#L46). Видимо равномерно распределяют маршруты между коммутаторами. 

Здесь показано как через API соорудить FatTree, вроде не сложно:
https://simgrid.org/doc/latest/Platform_cpp.html?highlight=fattree#beyond-the-xml-the-power-of-c-platforms

2023-03-27 20:13 UTC, osukhoroslov commented
> i9-12900k

Ну понятно https://cpu.userbenchmark.com/Compare/Intel-Core-i9-12900K-vs-Intel-Core-i7-1185G7/4118vsm1268967

2023-04-03 14:13 UTC, maksim1744 commented
> > > И что насчёт fat tree? Получится её реализовать на симгриде?
> > 
> > 
> > На самом деле я бы его и из dslab пока убрал --- там же все пути видимо через один верхний коммутатор идут, так как эти пути строятся один раз в самом начале. В симгриде наверное можно реализовать, задав несколько возможных путей между парой хостов, но я не знаю как это будет работать в итоге
> 
> Да пусть остается раз сделали, надо будет только потом поддержать роутинг с явными маршрутами.
> 
> Посмотрел как FatTree сделана в SimGrid - там статические маршруты вычисляются между каждой парой хостов по [какой-то известной схеме](https://github.com/simgrid/simgrid/blob/5ed37babb2fa9097abe82df299c0aa259ed84d5a/include/simgrid/kernel/routing/FatTreeZone.hpp#L84) (destination-mod-k scheme), реализация [здесь](https://github.com/simgrid/simgrid/blob/4e68c6fc1ff039dd2cea2688981f4c19919874d4/src/kernel/routing/FatTreeZone.cpp#L46). Видимо равномерно распределяют маршруты между коммутаторами.
> 
> Здесь показано как через API соорудить FatTree, вроде не сложно: https://simgrid.org/doc/latest/Platform_cpp.html?highlight=fattree#beyond-the-xml-the-power-of-c-platforms

Построил руками по аналогии, так точно понятно что происходит внутри

2023-04-03 17:44 UTC, osukhoroslov commented on examples-other/simgrid/network/network.cpp
> +                sg4::LinkInRoute a{uplinks[i / hosts_per_switch][cur_l2_switch % l2_switch_count]};
Маленькое замечание - для лучшего понимания я бы расположил линки в порядке пути из i в j (i -> downlink -> uplink -> uplink -> downlink -> j)

2023-04-03 21:19 UTC, osukhoroslov approved these changes

2023-04-03 21:20 UTC, merged