[mp] 7-kv-sharding dslib -> mp-kv-sharding dslab
osukhoroslov/dslab pull request #240
Opened 2023-04-08 21:01 UTC by LadyPython

2023-04-21 19:24 UTC, osukhoroslov requested changes

2023-04-21 19:24 UTC, osukhoroslov commented on examples/mp-kv-sharding/src/main.rs
> +fn send_proc_removed(sys: &mut System, removed: &str) {
```suggestion
fn send_node_removed(sys: &mut System, removed: &str) {
```

2023-04-21 19:24 UTC, osukhoroslov commented on examples/mp-kv-sharding/src/main.rs
> +fn send_proc_added(sys: &mut System, added: &str) {
```suggestion
fn send_node_added(sys: &mut System, added: &str) {
```

2023-04-21 19:24 UTC, osukhoroslov commented on examples/mp-kv-sharding/src/main.rs
> +    assume!(!crashed_keys.is_empty(), "Proc stores no records, bad distribution")?;
```suggestion
    assume!(!crashed_keys.is_empty(), "Node stores no records, bad distribution")?;
```

2023-04-21 19:24 UTC, osukhoroslov commented on examples/mp-kv-sharding/src/main.rs
> +    for _i in 0..config.proc_count {
```suggestion
    for _ in 0..config.proc_count {
```

2023-04-21 19:24 UTC, osukhoroslov commented on examples/mp-kv-sharding/src/main.rs
> +    for _i in 0..config.proc_count {
```suggestion
    for _ in 0..config.proc_count {
```

2023-04-21 19:24 UTC, osukhoroslov commented on examples/mp-kv-sharding/Cargo.toml
> +name = "kv-sharding"
```suggestion
name = "mp-kv-sharding"
```

2023-04-21 19:24 UTC, osukhoroslov commented on examples/mp-kv-sharding/Cargo.toml
> +version = "0.1.0"
```suggestion
version = "0.1.0"
license = "MIT OR Apache-2.0"
```

2023-04-21 19:24 UTC, osukhoroslov commented on examples/mp-kv-sharding/python/solution.py
> +class StorageProcess(Process):
В данном случае процесс представляет узел хранилища, поэтому удобнее оставить как было

```suggestion
class StorageNode(Process):
```

2023-04-21 19:24 UTC, osukhoroslov commented on examples/mp-kv-sharding/python/solution.py
> +        self._processes = set(processes)
```suggestion
    def __init__(self, node_id: str, nodes: List[str]):
        self._id = node_id
        self._nodes = set(nodes)
```

2023-05-24 23:02 UTC, KiK0S commented
Я перехватил пулл-реквест на себя, сменил базовую ветку - все исправления и дальнейшие работы в #267

2023-05-24 23:02 UTC, closed without merging