[mp] 8-kv-replecation dslib -> mp-kv-replecation dslab
osukhoroslov/dslab pull request #244
Opened 2023-04-16 20:05 UTC by LadyPython

2023-04-21 20:06 UTC, osukhoroslov requested changes

2023-04-21 20:06 UTC, osukhoroslov commented on examples/mp-kv-replication/src/main.rs
> +    sys.network().make_partition(&part1, &part2);
В make_partition должны передаваться имена узлов

2023-04-25 19:43 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +    for proc in sys.process_names() {
баг, авторское решение не проходит. дело в том что process_names это ключи хеш-мапы, и их порядок не задан явно, а `sloppy_quorum_tricky` опирается на порядок

я запатчил так:
```rust
    pub fn process_names_sorted(&self) -> Vec<String> {
        let mut res = self.process_names();
        res.sort();
        res
    }
```

2023-05-24 23:32 UTC, KiK0S commented
Я перехватил пулл-реквест на себя, сменил базовую ветку - все исправления и дальнейшие работы в #268

2023-05-24 23:32 UTC, closed without merging