[mp/visualization] add event logging
osukhoroslov/dslab pull request #245
Opened 2023-04-17 09:25 UTC by amgfrthsp

2023-04-19 17:42 UTC, osukhoroslov requested changes

2023-04-19 17:42 UTC, osukhoroslov commented on crates/dslab-mp/src/system.rs
> +            Rc::clone(&logger),
```suggestion
            logger.clone(),
```

2023-04-19 17:42 UTC, osukhoroslov commented on crates/dslab-mp/src/system.rs
> +        self.logger
Мы вроде обсуждали что печать в консоль (строку выше) унесем внутрь логгера.

2023-04-19 17:42 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    pub fn new() -> Self {
При создании логгера надо уметь задавать следующие вещи:
- надо ли писать события в файл (или только в консоль)
- в какой файл писать (например, в задании несколько тестов, для каждого теста понадобится отдельный файл)
Можно в `new` создавать логгер без записи в файл, а для создания логгера с записью в файл сделать конструктор `with_log_file(log_path: Path)`.

2023-04-19 17:42 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    pub fn write_log(&mut self, vis_event: EventLogType) {
Предлагаю назвать просто `log()`

2023-04-19 17:42 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +pub enum EventLogType {
Предлагаю назвать `EventLogEntry`

2023-04-19 17:42 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    TypeNodeAdded(EventNodeAdded),
`TypeNodeAdded` не нужен, вы можете опредить нужные структуры прямо внутри enum-а. Пример: https://github.com/osukhoroslov/dslab/blob/201454d8a26f7f43a0960ed316fa79caaf61e78c/crates/dslab-dag/src/scheduler.rs#L27

2023-04-19 17:42 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    pub timestamp: f64,
Пусть будет просто `time` здесь в других событиях

2023-04-19 17:42 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    pub id: String,
```suggestion
    pub node_id: String,
```

2023-04-19 17:42 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    pub msg: LogMessage,
Почему бы не занести прямо сюда поля из LogMessage, или он где-то еще будет использоваться?

2023-04-19 17:42 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +pub struct EventMessageSent {
Лучше просто `MessageSent`, ну или `MessageSentLogEntry`.

2023-04-19 17:42 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    pub id: String,
```suggestion
    pub message_id: String,
```

2023-04-19 17:42 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    pub id: String,
```suggestion
    pub node_id: String,
```

2023-04-19 17:42 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    pub id: String,
```suggestion
    pub node_id: String,
```

2023-04-19 17:42 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +                    self.logger
Получение надо логировать не здесь (иначе порядок событий в логе может нарушиться), а в том месте где приходит это событие: https://github.com/osukhoroslov/dslab/blob/06c119486a117601b25062f9223692a3da924d4b/crates/dslab-mp/src/node.rs#L252

2023-04-19 17:42 UTC, osukhoroslov commented on crates/dslab-mp/src/system.rs
>      pub fn new(seed: u64) -> Self {
Предлагаю сделать отдельный конструктор `System::with_log_file(path: Path)` куда передавать путь к файлу, в который надо писать лог. А в `new` создавать логгер без записи в файл (только консоль).

2023-04-19 17:42 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +        self.logger
Мы вроде обсуждали что печать в консоль (строку выше) унесем внутрь логгера.

2023-04-20 08:02 UTC, amgfrthsp commented on crates/dslab-mp/src/logger.rs
> +pub enum EventLogType {
будет коллизия с `node::EventLogEntry` и одно на другое, кажется, не заменить, потому что за разное отвечают

2023-04-20 08:15 UTC, amgfrthsp commented on crates/dslab-mp/src/logger.rs
> +    pub msg: LogMessage,
не будет, можно перенести.

2023-04-21 11:38 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +pub enum EventLogType {
тогда просто `LogEntry`, и `EventLogger` тоже переименовать в просто `Logger`, чтобы не было путаницы

2023-04-21 11:39 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    write_to_file: bool,
Кажется достаточно хранить только log file и по его наличию определять надо ли писать в файл

2023-04-21 12:07 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    pub fn with_log_file(log_path: &Path) -> Self {
Добавьте пустую строку перед функцией

2023-04-21 12:16 UTC, osukhoroslov commented on crates/dslab-mp/src/node.rs
> +        self.logger.borrow_mut().log(
Удобнее было бы передавать в log() только LogEntry, а строку формировать уже внутри Logger-а в зависимости от логируемого события. Тогда у нас вся логика по форматированию этих строк будет в одном месте, что логично и удобно. Ну и в местах вызова log() код упростится.

2023-04-21 12:37 UTC, osukhoroslov commented on crates/dslab-mp/src/node.rs
> +                        None,
Можно логировать MessageSent прямо здесь, для этого достаточно вернуть message id в `net.send_message` и после этого поставить логирование. И тогда не нужно будет логирование в сети с пустым сообщением.

2023-04-25 13:43 UTC, amgfrthsp commented on crates/dslab-mp/src/node.rs
> +                        None,
Так не получится сделать, потому что нарушится хронология событий в случае, например, дропа сообщений -- дроп происходит внутри net.send_message

2023-04-25 20:15 UTC, osukhoroslov requested changes

2023-04-25 20:15 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +        &mut self,
```suggestion
        &self,
```

2023-04-25 20:15 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +            } => {}
```suggestion
            LogEntry::TimerSet { .. } => {}
```

2023-04-25 20:15 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +            LogEntry::TimerCancelled { time: _, timer_id: _ } => {}
```suggestion
            LogEntry::TimerCancelled { .. } => {}
```

2023-04-25 20:15 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +                node_id: _,
```suggestion
                ..
```

2023-04-25 20:15 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +        node_name: String,
```suggestion
        node: String,
```

2023-04-25 20:15 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +        node_name: String,
```suggestion
        node: String,
```

2023-04-25 20:15 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +        node_name: String,
```suggestion
        node: String,
```

2023-04-25 20:15 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +        from: String,
Предлагаю сделать такие же поля как в MessageSent (src/dest_node/proc) аналогично событиям для локальных сообщений

2023-04-25 20:15 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +        node_name: String,
```suggestion
        node: String,
```

2023-04-25 20:15 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +        node_name: String,
```suggestion
        node: String,
```

2023-04-25 20:15 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +        node_name: String,
```suggestion
        node: String,
```

2023-04-25 20:15 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +        proc: String,
Добавьте node

2023-04-25 20:15 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    TimerCancelled {
Добавьте node и proc

2023-04-25 20:15 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +            LogEntry::NodeAdded {
Добавьте еще логирование событий `ProcessStarted` из system.add_process() и `NodeCrashed/Recovered` из system.crash/recover_node().

2023-04-25 20:17 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +    fn log_message_sent(
Добавьте также логирование дропа сообщения, заменив `t!(...)` выше

2023-04-26 12:03 UTC, amgfrthsp commented
Перенесла все логирование (t!) и соответствующие события в логгер

2023-04-28 18:58 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +        from: String,
По-прежнему не хватает src_node и dest_node, как в MessageSent

2023-04-28 19:24 UTC, osukhoroslov requested changes

2023-04-28 19:24 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +            LogEntry::NodeAdded { time, node, .. } => {
```suggestion
            LogEntry::NodeStarted { time, node, .. } => {
```

2023-04-28 19:24 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +            LogEntry::ProcessAdded { time, node, proc } => {
```suggestion
            LogEntry::ProcessStarted { time, node, proc } => {
```

2023-04-28 19:24 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +                let msg = Message {
А почему не хотите сразу Message внутри LocalMessageSent передать, чтобы не собирать по частям здесь? И аналогично в других местах.

2023-04-28 19:24 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +            from_node: self.proc_locations.get(from).unwrap().clone(),
Вообще `from` и `to` это уже имена нод. Обрубается связь между нодами, да и сеть ничего не знает про процессы. Поэтому в LinkDisabled нет смысла хранить имена процессов.

2023-04-28 19:24 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +            from_node: self.proc_locations.get(from).unwrap().clone(),
Аналогично в `enable_link`

2023-04-28 19:24 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +        let group1_nodes = group1
`group1` и `group2` это уже имена нод, а не процессов.

2023-04-28 19:24 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +        self.logger.borrow_mut().log(LogEntry::MakePartition {
В MakePartition должны остаться только списки нод.

2023-04-28 19:24 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    MessageDropped {
Добавьте src_node и dest_node

2023-04-28 19:24 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    MakePartition {
```suggestion
    NetworkPartition {
```

2023-04-28 19:24 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    ResetNetwork {
```suggestion
    NetworkReset {
```

2023-04-28 19:24 UTC, osukhoroslov commented on crates/dslab-mp/src/node.rs
> +        format!("{} {} {}", self.name, proc, local_message_count)
```suggestion
        format!("{}-{}-{}", self.name, proc, local_message_count)
```

2023-04-29 12:23 UTC, amgfrthsp commented on crates/dslab-mp/src/logger.rs
> +        from: String,
Вроде же есть? Я ниже сделала коммит с этими изменениями

2023-04-29 14:04 UTC, amgfrthsp commented on crates/dslab-mp/src/network.rs
> +            from_node: self.proc_locations.get(from).unwrap().clone(),
Я смотрела на [этот код ](https://github.com/osukhoroslov/dslab/blob/main/examples/mp-membership/src/main.rs#L351)из примеров. Сбивает с толку, что передаются proc1 и proc2 из sys.process_names. Аналогично MakePartition

2023-04-30 11:46 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    MessageReceived {
Добавьте `src_node` и `dest_node` как в MessageSent

2023-04-30 11:49 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +            from_node: self.proc_locations.get(from).unwrap().clone(),
Там используется предположение https://github.com/osukhoroslov/dslab/blob/cb001a59ebbf25806fe2a76a4231e2f11a3cbd5c/examples/mp-membership/src/main.rs#L55
Но согласен что не зная это может сбить с толку.

2023-04-30 11:55 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +            from_node: self.proc_locations.get(from).unwrap().clone(),
Если взглянуть сопоставить код disable/enable_link и send_message в сети, то видно что в `disabled_links` требуется хранить имена нод, ну и соответственно передавать в disable/enable_link именно их, а не имена процессов. К сожалению, София так и не добралась до документации кода dslab-mp.

2023-04-30 13:40 UTC, amgfrthsp commented on crates/dslab-mp/src/logger.rs
> +    MessageReceived {
Для того, чтобы добавить `src_node`, потребуется добавлять поле `src_node` в MessageReceived, поскольку насколько я разобралась, из node его нельзя получить по имени процесса. 

Это нормальный подход? Или можно что-то лучше придумать?

2023-04-30 17:37 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    MessageReceived {
Да, нормальный

2023-04-30 19:47 UTC, osukhoroslov commented
Пора сделать rebase перед мержем

2023-04-30 20:00 UTC, amgfrthsp commented
Добавила логирование состояния процесса. Как мы обсуждали - после event-хэндлеров. Но почему-то в логе, который я генерирую, state пустой. Что я делаю не так?

2023-04-30 20:00 UTC, amgfrthsp commented
Займусь rebase после того, как сделаю логирование состояния

2023-05-01 12:37 UTC, osukhoroslov commented on crates/dslab-mp/src/node.rs
> +                state = self.processes.get(&dest).unwrap().proc_impl.state();
Лучше вынести получение и логирование состояния процесса в отдельную функцию и вызывать её в конце `on_message_received` и `on_timer_fired`. Тогда здесь в `on` никакого вспомогательного кода и создания пустого state не потребуется.

2023-05-01 12:42 UTC, osukhoroslov commented
> Добавила логирование состояния процесса. Как мы обсуждали - после event-хэндлеров. Но почему-то в логе, который я генерирую, state пустой (`"{}"`). Что я делаю не так?
> 
> Также не смогла найти место (кроме dslab-mp-python), где явно бы state создавался из питоновского словаря

По-умолчанию state пустой. Чтобы добавить в state поля класса процесса на питоне надо обернуть нужные поля в StateMember как это делается здесь: https://github.com/osukhoroslov/dslab/blob/cb001a59ebbf25806fe2a76a4231e2f11a3cbd5c/crates/dslab-mp-python/python-tests/process.py#L6. Тогда эти поля будут сериализовываться в JSON и попадать в state.

2023-05-01 12:44 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    StateUpdated {
```suggestion
    ProcessStateUpdated {
```

2023-05-01 12:44 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +        node: String,
Добавьте имя процесса

2023-05-01 12:45 UTC, osukhoroslov commented on crates/dslab-mp/src/node.rs
> +        self.logger.borrow_mut().log(LogEntry::StateUpdated {
Предлагаю хранить предыдущее состояние процесса и логировать новое состояние только если оно изменилось, это поможет уменьшить размер лога в некоторых случаях.

2023-05-02 11:37 UTC, amgfrthsp commented
> 
То есть это целиком на пользователе - какие поля заносить в state, а какие - нет? 

Здесь еще возникает проблема того, что некоторые структуры, которые часто используются в домашках, например set, не сериализуются по умолчанию и для них нужно писать свой encoder.

Что делать в такой ситуации? Можно написать отдельный encoder для set'а ([например такой](https://stackoverflow.com/questions/8230315/how-to-json-serialize-sets#:~:text=You%20can%20create%20a%20custom%20encoder%20that%20returns%20a%20list%20when%20it%20encounters%20a%20set.%20Here%27s%20an%20example%3A)), но ведь могут возникнуть другие несериализуемые структуры.

2023-05-02 18:03 UTC, osukhoroslov commented
> > По-умолчанию state пустой. Чтобы добавить в state поля класса процесса на питоне надо обернуть нужные поля в StateMember как это делается здесь:
> > Тогда эти поля будут сериализовываться в JSON и попадать в state.
> 
> 
> 
> То есть это целиком на пользователе - какие поля заносить в state, а какие - нет? 
> 
> Здесь еще возникает проблема того, что некоторые структуры, которые часто используются в домашках, например set, не сериализуются по умолчанию и для них нужно писать свой encoder.
> 
> Что делать в такой ситуации? Можно написать отдельный encoder для set'а ([например такой](https://stackoverflow.com/questions/8230315/how-to-json-serialize-sets#:~:text=You%20can%20create%20a%20custom%20encoder%20that%20returns%20a%20list%20when%20it%20encounters%20a%20set.%20Here%27s%20an%20example%3A)), но ведь могут возникнуть другие несериализуемые структуры. 

Этот вопрос исследуется в другом PR: https://github.com/osukhoroslov/dslab/pull/207

2023-05-10 19:32 UTC, osukhoroslov commented
У меня больше замечаний нет, сделайте rebase.

2023-05-12 19:37 UTC, osukhoroslov commented on crates/dslab-mp/src/network.rs
> +use dslab_core::event::EventId;
Надо перенести ниже в блок импортов из dslab_core

2023-05-19 13:52 UTC, osukhoroslov approved these changes

2023-05-19 13:53 UTC, merged