Integration tests + bug fixes for model checking
osukhoroslov/dslab pull request #255
Opened 2023-05-01 17:51 UTC by AnthonyUdovichenko

2023-05-10 19:01 UTC, osukhoroslov requested changes

2023-05-11 20:30 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/state.rs
> +/// Stores comprehensive information about the state of model checking system.
Но я имел в виду McSystem, а не System

2023-05-12 10:48 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/state.rs
> +/// Stores comprehensive information about the state of model checking system.
Тогда лучше так:

```suggestion
/// Stores comprehensive information about the state of McSystem.
```
потому что `model checking system` звучит непонятно

2023-05-12 19:06 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +                    static ref RE: Regex = Regex::new(r"\w+").unwrap();
```rust
use lazy_static::lazy_static;
use regex::Regex;

fn main() {
    let data: String = "{\"key1\": \"value1\", \"key2\": 33}".to_string();
    lazy_static! {
        static ref RE: Regex = Regex::new(r#""[^"]+""#).unwrap();
    }
    let corrupted_data = RE.replace_all(&data, "\"\"").to_string();
    print!("{}", corrupted_data)
}
```

2023-05-19 18:54 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +    assert!(if let Err(msg) = result {
Можно, если добавить `PartialEq` к `McSummary`:

https://stackoverflow.com/questions/57234140/how-to-assert-io-errors-in-rust#comment101365259_57236366

2023-05-19 18:57 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +            self.mark_visited(system.get_state());
Нужен ли теперь вызов `mark_visited` в BFS? По идее те состояния, что доходят до BFS уже помечаются здесь.

2023-05-21 11:13 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategies/bfs.rs
>              }
```rust
            if let Some(result) = self.check_state(&state) {
                result?;
                continue;
            }
```

2023-05-21 11:14 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategies/dfs.rs
>          }
```rust
        if let Some(result) = self.check_state(&state) {
            return result;
        }
```

2023-05-26 19:39 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/pending_events.rs
> +        if self.directives.iter().next().is_some() {
```suggestion
        if !self.directives.is_empty() {
```

2023-05-26 19:47 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +    let mut mc = ModelChecker::new(&mut sys, strategy);
```suggestion
    let mut mc = ModelChecker::new(&sys, strategy);
```

2023-05-26 19:48 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +                Message {
Переделать на `Message::new()`

2023-05-26 19:49 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +    fn set_state(&mut self, _: Box<dyn ProcessState>) {}
Не нужны

2023-05-26 19:55 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/dependency.rs
> +            return counter;
```suggestion
            counter
```

2023-05-26 19:55 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/dependency.rs
> +            return counter;
```suggestion
            counter
```

2023-05-26 20:00 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/pending_events.rs
> +            McEvent::MessageReceived { msg, src, dest, .. } => {
Поправьте в `pending_events.rs`

```
(0..3).into_iter().collect()
```

на

```
(0..3).collect()
```

2023-05-27 19:49 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +            ctx.send(Message::new("MESSAGE".to_string(), i.to_string()), self.other.clone());
```suggestion
            ctx.send(Message::new("MESSAGE", i.to_string()), self.other.clone());
```

2023-05-27 20:00 UTC, osukhoroslov approved these changes

2023-05-27 20:15 UTC, merged