feat iaas: simplify dataset usages by config
osukhoroslov/dslab pull request #258
Opened 2023-05-09 17:49 UTC by vetand

2023-06-05 15:23 UTC, osukhoroslov requested changes

2023-06-05 15:23 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +        let mut test_case = sim.clone();
Просто так (просто добавив Clone) клонировать CloudSimulation опасно - внутри него много Rc/RefCell-ов. По сути вы сейчас просто ссылки копируете, то есть состояние симуляции не чистится, а переносится между разными запусками, что чревато разными ошибками. Надо или реализовывать полноценный deep clone симуляции, либо создавать симуляцию какждый раз с нуля по конфигу. Второй поход выглядит более простым и надежным, а также позволяет легче перейти на потоки (см. предыдущий комментарий).

2023-06-05 15:23 UTC, osukhoroslov commented on crates/dslab-iaas/src/simulation.rs
> +    pub fn set_sim_config(&mut self, config: SimulationConfig) {
Возможность подменять целиком конфиг в любой момент выглядит не очень красиво и потенциально опасно. По хорошему конфиг должен передаваться симуляции только один раз - при её создании, и далее не меняться. Если реально надо изменить какие-то параметры по ходу симуляции, например, задержку сети - это должно делаться с помощью отдельных методов.

2023-06-05 15:23 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/config.rs
>  pub struct SimulationConfig {
Идея с заданием дипазонов значений для параметров конфига в файле выглядит разумной. Но мне не нравится, что это диапазоны попадают прямо в SimulationConfig, усложняя логику работы с ним. Лучше разделить понятия - конфиг эксперимента (серии симуляций) и конфиг симуляции (одного запуска в рамках эксперимента). Соответственно, если мы хотим запустить эксперимент, то мы читаем из файла не `SimulationConfig`, а некий новый `ExperimentConfig`, который в свою очередь умеет выдать нам итератор с `SimulationConfig` - конфигами отдельных запусков в рамках этого эксперимента. И тогда вся сложность работы с диапазонами уйдет туда, а `SimulationConfig` останется в первозданнном виде. И для всего этого нового логично завести отдельный модуль `experiment.rs`.

2023-06-17 10:58 UTC, osukhoroslov requested changes
Посмотрите еще раз [мое предложение](https://github.com/osukhoroslov/dslab/pull/258#discussion_r1218237702) убрать все что связано с динамическими переменными в `ExperimentConfig`, и вернуться к первоначальному `SimulationConfig`.

2023-06-17 10:58 UTC, osukhoroslov commented on crates/dslab-iaas/src/simulation.rs
> +#[derive(Clone)]
Уберите, больше не нужно

2023-06-17 10:58 UTC, osukhoroslov commented on crates/dslab-iaas/src/simulation.rs
> +#[derive(Clone)]
Уберите

2023-06-17 10:58 UTC, osukhoroslov commented on crates/dslab-iaas/src/simulation.rs
> +    pub fn set_sim_config(&mut self, config: ConfigData) {
Уберите, больше не используется

2023-06-17 10:58 UTC, osukhoroslov commented on crates/dslab-core/src/context.rs
> +#[derive(Clone)]
Уберите, теперь не нужно

2023-06-17 10:58 UTC, osukhoroslov commented on crates/dslab-core/src/simulation.rs
> +#[derive(Clone)]
Уберите, теперь не нужно

2023-06-17 10:58 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +        while self.config.can_increment() {
По-прежнему считаю что лучше разделить ExperimentConfig и SimulationConfig как [писал выше](https://github.com/osukhoroslov/dslab/pull/258#discussion_r1218237702), тогда код здесь станет примерно такой:

```rust
        // self.config is ExperimentConfig with iterator returning configs for simulations
        for sim_config in self.config.iter() {
            let sim = Simulation::new(123);
            let duration = sim_config.simulation_length;
            let mut cloud_sim = CloudSimulation::new(sim, sim_config);
            cloud_sim.step_for_duration(duration);
            self.final_callback.on_experiment_finish(&mut cloud_sim);
        }
```

2023-06-17 10:58 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +    pub fn start(&mut self) {
```suggestion
    pub fn run(&mut self) {
```

2023-06-17 10:58 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +    pub final_callback: Box<dyn OnTestCaseFinishedCallback>,
Давайте добавим еще один callback для контроля симуляции - он вызывается после каждого шага, ему передается симуляция и он решает надо ли её продолжать или нет. Таким образом можно будет реализовать произвольные правила остановки - например, при первом отказе размещения ВМ (надо только вывести счетчик числа отказов через CloudSimulation)

2023-06-17 10:58 UTC, osukhoroslov commented on examples/iaas-traces/src/main.rs
> -use std::str::FromStr;
Договорились отставить старый пример `iaas-traces`, а пример с экспериментами перенести в `iaas-experiment`

2023-06-17 10:58 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/config.rs
> +pub struct SimulationConfig {
Не вижу особой разницы между тем, что было в первой итерации. Только переменные собраны в `data`, и теперь надо всем компонентам включая симуляцию передавать её, а весь конфиг (что тоже неудобно). Но самое главное в `data` по-прежнему хранятся динамические переменные и эта вся кухня видна зачем-то компонентам. Например, ничто не мешает в хост менеджере позвать `self.sim_config.message_delay.increment()`. И помимо `data` здесь же еще хранится копия этих `dynamic_variables`, что больше запутывает.

Посмотрите еще раз [мое предложение](https://github.com/osukhoroslov/dslab/pull/258#discussion_r1218237702) убрать все что связано с динамическими переменными в `ExperimentConfig`, и вернуться к первоначальному `SimulationConfig`. Это должно решить описанные проблемы.

2023-06-18 10:43 UTC, osukhoroslov commented on crates/dslab-core/src/simulation.rs
> +#[derive(Clone)]
Нн убрано

2023-06-18 12:21 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +    fn on_step(&mut self, _sim: Rc<RefCell<CloudSimulation>>) {
Надо добавить возвращаемое значение - если оно `false`, то останавливать симуляцию (позволит реализовать кастомные правила остановки):

```suggestion
    fn on_step(&mut self, _sim: Rc<RefCell<CloudSimulation>>) -> bool {
```

2023-06-18 12:21 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/config/exp_config.rs
> +            panic!("Multiple dynamic variables still not supported :(");
Пора реализовать

2023-06-25 19:50 UTC, vetand commented
TODO:
  - Строковые переменные
  - Потоки
  - Отчеты в файл

2023-06-26 16:44 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +        while let (Some(current_config), current_state) = self.config.get() {
Предлагаю в `config.get()` возвращать только `current_config`, а строковое представление конфига для отладки получать с помощью метода на `current_config`.

2023-07-23 14:51 UTC, vetand commented on crates/dslab-iaas/src/experiments.rs
> +            pool.execute(move || {
Вот тут вынес в функцию process_test_case, потому не поправил, сложно будет занести всё это внутрь треда

2023-07-24 15:05 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/config/exp_config.rs
> +            }
Осталось, надо обсудить почему

2023-07-24 15:34 UTC, osukhoroslov commented on examples/iaas-experiment/azure.yaml
> +trace:
Сейчас сделано так, что надо trace записывать строкой. Почему не получается поддержать формат выше?

2023-07-24 15:52 UTC, osukhoroslov commented on examples/iaas-experiment/azure.yaml
> +threads_count: 1
Надо убрать

2023-07-24 15:52 UTC, osukhoroslov commented on examples/iaas-experiment/huawei.yaml
> +trace:
Такой формат перестал работать

2023-07-24 15:52 UTC, osukhoroslov commented on examples/iaas-experiment/src/main.rs
> +    /// Parallel mode on
Непонятно зачем нужна эта опция, если можно указать threads=1

2023-07-24 15:52 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +    pub threads: Option<usize>,
Непонятно зачем делать Option

2023-07-24 15:52 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +            pool.execute(move || {
А я же выше показал как можно занести вывод внутри треда. И если хочется, чтобы вывод был по мере выполнения, то поставить threads=1, а Option и ветвление не нужны.

2023-07-24 15:56 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +            if self.threads.is_some() {
А я же выше показал как можно занести вывод внутри треда. И если хочется, чтобы вывод был по мере выполнения, то поставить threads=1, а Option и ветвление не нужны.

2023-07-24 17:03 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/config/exp_config.rs
> +        .unwrap_or_else(|_| panic!("Can't parse YAML from file {}", file_name));
```suggestion
        .unwrap_or_else(|err| panic!("Can't parse YAML from file {}: {}", file_name, err));
```
супер полезно если что-то не так в файле

2023-07-31 16:03 UTC, osukhoroslov requested changes

2023-08-07 13:51 UTC, vetand commented on examples/iaas-experiment/src/main.rs
>                  sim.borrow().context(),
Предлагаю всё-таки реализовать вне трейта, чтобы не передавать контекст в качестве аргумента. Иначе приходится в одну строчку и вызывать context() и логировать

2023-08-07 15:34 UTC, osukhoroslov commented on examples/iaas-experiment/src/main.rs
>                  sim.borrow().context(),
Согласен, просто продублировать функции логгера, но без контекста.

2023-08-14 13:24 UTC, osukhoroslov requested changes

2023-08-14 13:24 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/logger.rs
> +        });
Чтобы уменшить дублирующийся код предлагаю сделать у FileLogger приватный метод `log_internal(&mut self, ctx: &SimulationContext, log: String, level: Level)`. Тогда здесь код сократится до:

```rust
        self.log_internal(ctx, log, Level::Error)
```

Аналогично в остальных методах.

2023-08-14 13:24 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/logger.rs
> +    trace: Vec<LogEntryRow>,
```suggestion
    log: Vec<LogEntryRow>,
```

2023-08-14 13:24 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/logger.rs
> +    log: String,
```suggestion
    message: String,
```

2023-08-14 13:24 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +}
```suggestion
pub enum DictValue {
    String(String),
    Dict(HashMap<String, String>),
}
```

2023-08-14 13:24 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +        log_file_prefix: Option<String>,
Предлагаю назвать `results_dir` и передавать туда путь к директории в которой сохранять результаты и логи. И для удобства надо сделать так, чтобы директория создавалась автоматически если не существует. Что касается префикса именно у файлов, то я не вижу в нем потребности - файлы логов и результатов могут иметь стандартные имена типа `log_0.csv` и `results.json`. Этого достаточно, если хранить результаты разных экспериментов в разных папках.

2023-08-14 13:24 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +    }
```suggestion
    let log_level = log_level.unwrap_or(Level::Info);
    let logger: Box<dyn Logger> = if log_file.is_some() {
        Box::new(FileLogger::with_level(log_level))
    } else {
        Box::new(StdoutLogger::with_level(log_level))
    };
```

2023-08-14 13:24 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +        let save_result = cloud_sim.borrow_mut().save_trace_to_file(&log_file.clone().unwrap());
Мутабельный borrow не требуется

```suggestion
        let save_result = cloud_sim.borrow().save_trace_to_file(&log_file.clone().unwrap());
```
и внутри `save_trace_to_file` тоже заменить на `borrow`

2023-08-25 18:41 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +            //test_case_entry.insert("config".to_string(), Dict::Config(config_fmt));
Почему закомментировано?

2023-08-25 18:50 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +            test_case_entry.insert("config".to_string(), Dict::Dict(fields));
Сейчас `config` вообще перестал выписываться в файл с результами:

![изображение](https://github.com/osukhoroslov/dslab/assets/1322460/3d150419-68c7-4e88-8ae8-14ff8ab9f7a1)

2023-08-25 19:30 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +                test_cases.lock().unwrap().push(process_test_case(current_config.clone(), &mut callbacks.clone(), log_file, log_level));
Выполнение `process_test_case` происходит под мьютексом (держим его все время пока не появится результат), то есть потоки работают по очереди. Надо вынести вычисление результата:

```suggestion
                let result = process_test_case(current_config.clone(), &mut callbacks.clone(), log_file, log_level);
                test_cases.lock().unwrap().push(result);
```

2023-08-25 19:52 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_api.rs
> +    pub vms: HashMap<u32, Rc<RefCell<VirtualMachine>>>,
Зачем делать публичными все поля? Если нужен к чему-то доступ, то правильнее сделать метод.

2023-08-25 19:55 UTC, osukhoroslov commented on examples/iaas-experiment/src/main.rs
> +    ) -> IndexMap<std::string::String, std::string::String> {
```suggestion
    ) -> IndexMap<String, String> {
```

2023-08-25 19:55 UTC, osukhoroslov commented on crates/dslab-iaas/src/experiments.rs
> +use threadpool::ThreadPool;
Перенесите в следующий блок импортов, где внешние библиотеки

2023-08-30 15:57 UTC, osukhoroslov commented on examples/iaas-experiment/src/main.rs
> +    log_dir: Option<String>,
```suggestion
    results_dir: Option<String>,
```

2023-09-06 13:49 UTC, osukhoroslov approved these changes

2023-09-06 13:50 UTC, merged