[mp] python serialization with pickle
osukhoroslov/dslab pull request #270
Opened 2023-05-25 00:01 UTC by KiK0S

2023-05-26 20:25 UTC, osukhoroslov requested changes

2023-05-26 20:25 UTC, osukhoroslov commented on crates/dslab-mp-python/python/dslabmp.py
> +import sys
Не нужен

2023-05-26 20:25 UTC, osukhoroslov commented on crates/dslab-mp-python/src/tests.rs
>      // process sends local message only if it has a secret which is not a state member
Осталась старая логика с секретами и state member. Надо переделать тест под новые реалии (видимо мы хотим просто проверить что можем откатить состояние процесса назад из имеющегося у нас начального state после его изменений), включая питоновский код. И упростить, потому что сейчас тяжело сходу понять что происходит. Может комментарии бы помогли.

2023-05-28 13:01 UTC, KiK0S commented on crates/dslab-mp-python/python/dslabmp.py
> +import sys
ага, убрал

2023-05-28 13:04 UTC, KiK0S commented on crates/dslab-mp-python/src/tests.rs
>      // process sends local message only if it has a secret which is not a state member
постарался упростить, насколько получилось - там все равно нужно дважды запрос делать (потому что нужно просимулировать изменение). Ну и сделал проверки на все примитивные типы - list, dict, set, None, строки, числа, кастомные классы. Вроде как сейчас читается нормально, но если есть идеи то могу еще поправить

2023-05-28 16:10 UTC, osukhoroslov requested changes

2023-05-28 16:10 UTC, osukhoroslov commented on crates/dslab-mp-python/python-tests/process.py
> +        self.data = ["elem1", (2, 3), {'key': 'value'}, set([1, 2, 3])]
```suggestion
        self.data = ["elem1", (2, 3), {'key': 'value'}, {1, 2, 3}]
```

2023-05-28 16:10 UTC, osukhoroslov commented on crates/dslab-mp-python/python-tests/process.py
> +        assert type(self.data[3]) == set
Проверка в порядке декларации полей в init

```suggestion
        assert type(self.data) == list
        assert type(self.data[0]) == str
        assert type(self.data[1]) == tuple
        assert type(self.data[2]) == dict
        assert type(self.data[3]) == set
        assert type(self.messages) == list
        assert type(self.messages[0]) == Message
        assert self.inner_member.data == 42
```

2023-05-29 20:17 UTC, osukhoroslov approved these changes

2023-05-29 20:20 UTC, merged