[mp/mc] use depth as time in mc
osukhoroslov/dslab pull request #272
Opened 2023-05-28 13:34 UTC by KiK0S

2023-06-09 15:55 UTC, osukhoroslov requested changes

2023-06-09 15:55 UTC, osukhoroslov commented on crates/dslab-mp/src/context.rs
> +        // it makes time value look more natual and closer to simulation time
```suggestion
        // every step of system execution in model checking advances the time by 0.1s
        // this makes the time value look more natural and closer to the time in simulation
```

2023-06-09 15:55 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/system.rs
> +                    .on_message_received(dest, msg, src, self.depth)
Вместо пробрасывания depth вплоть до конструктора Context предлагаю прямо здесь в McSystem вычислять какое сейчас time (можно даже завести под это дело метод у системы) и передавать сразу время вместо глубины. Так будет более прозрачная логика.

2023-06-09 15:55 UTC, osukhoroslov commented on crates/dslab-mp/src/context.rs
> +    pub fn from_mc(proc_name: String, state_depth: u64) -> Self {
Где-то мы потеряли clock skew у процесса, а он ведь тоже важен и кое-где в обычных тестах домашках используется.

2023-06-14 21:21 UTC, KiK0S commented on crates/dslab-mp/src/context.rs
> +    pub fn from_mc(proc_name: String, state_depth: u64) -> Self {
ага, стал его прокидывать

2023-06-14 21:21 UTC, KiK0S commented on crates/dslab-mp/src/mc/system.rs
> +                    .on_message_received(dest, msg, src, self.depth)
так и сделал

2023-06-14 21:21 UTC, KiK0S commented on crates/dslab-mp/src/context.rs
> +        // it makes time value look more natual and closer to simulation time
поменял

2023-06-14 21:29 UTC, KiK0S commented on crates/dslab-mp/src/context.rs
> +    pub fn create(proc_name: String, time: f64, clock_skew: f64) -> Self {
поменял нейминг, потому что как будто бы такой контекст это просто пустой контекст, не привязанный к модел чекингу вообще никак - не вижу смысла тянуть mc в нейминг

2023-06-14 21:29 UTC, KiK0S commented on crates/dslab-mp/tests/test_mc.rs
> +            (*goal_data.borrow_mut()).push(state.node_states[&node][&proc].local_outbox[0].data.clone());
решил сделать функцией общего вида, потому что полезная

2023-06-14 21:29 UTC, KiK0S commented on crates/dslab-mp/tests/test_mc.rs
> +    assert_eq!(str::parse::<f64>(&goal_data.borrow()[0]).unwrap(), 0.1 + clock_skew);
вот тут меня смущает, что 0.1 явным образом тащится как `get_approximate_event_time(1)`. Но:
1. Если метод будет правиться, то в общем-то тут несложно поменять тест, это не очень страшно, что у нас внешний тест имеет такую зависимость
2. Вряд ли этот метод будет правиться часто
3. Публичить `get_approximate_event_time` не хочется

2023-06-14 21:29 UTC, KiK0S commented on crates/dslab-mp/tests/test_mc.rs
> +    assert_eq!(str::parse::<f64>(&goal_data.borrow()[0]).unwrap(), 0.1 + clock_skew);
добавил комментарий чтобы было понятнее

2023-06-16 11:33 UTC, osukhoroslov commented on crates/dslab-mp/src/context.rs
> +    pub fn from_simulation(proc_name: String, sim_ctx: Rc<RefCell<SimulationContext>>, clock_skew: f64) -> Self {
Посколько sim_ctx нужен в контексте только для random-а, то появилась идея реструктурировать код так, чтобы хранить именно random и поддержать в будущем возможность передачи кастомной реализации:

```rust
pub struct Context {
    proc_name: String,
    time: f64,
    rng: Option<Box<dyn RandomProvider>>,
    actions: Vec<ProcessEvent>,
}

trait RandomProvider {
    fn rand(&mut self) -> f64;
}

struct SimulationRng {
    sim_ctx: Rc<RefCell<SimulationContext>>,
}

impl RandomProvider for SimulationRng {
    fn rand(&mut self) -> f64 {
        self.sim_ctx.borrow().rand()
    }
}

impl Context {
    pub fn from_simulation(proc_name: String, sim_ctx: Rc<RefCell<SimulationContext>>, clock_skew: f64) -> Self {
        let time = sim_ctx.borrow().time() + clock_skew;
        Self {
            proc_name,
            time,
            rng: Some(Box::new(SimulationRng { sim_ctx })),
            actions: Vec::new(),
        }
    }

    pub fn basic(proc_name: String, time: f64, clock_skew: f64) -> Self {
        Self {
            proc_name,
            time: time + clock_skew,
            rng: None,
            actions: Vec::new(),
        }
    }

    pub fn rand(&mut self) -> f64 {
        self.rng.as_mut().expect("Random is not available!").rand()
    }
```

Надо обсудить нужен ли нам кастомный рандом в MC.

2023-06-16 11:33 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +    println!("{:#?}", result);
print надо убрать

2023-06-16 11:33 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +        "expected timestamp formula 0.1 * depth + clock_skew"
```suggestion
        "expected timestamp formula: 0.1 * depth + clock_skew"
```

2023-06-17 22:36 UTC, KiK0S commented on crates/dslab-mp/src/context.rs
> +    pub fn create(proc_name: String, time: f64, clock_skew: f64) -> Self {
согласен, обновил

2023-06-17 22:36 UTC, KiK0S commented on crates/dslab-mp/tests/test_mc.rs
> +    println!("{:#?}", result);
сделано

2023-06-17 22:45 UTC, KiK0S commented on crates/dslab-mp/src/context.rs
> +    pub fn from_simulation(proc_name: String, sim_ctx: Rc<RefCell<SimulationContext>>, clock_skew: f64) -> Self {
про кастомный рандом в МС на созвоне обсудили следующее:
- возможно, нужно расширить API рандома, например для выбора случайной вершины через choice.
- теоретически, в МС может быть полезно проверять поведение системы при различных иходах рандома
- с другой стороны, нужно понимать, что многие алгоритмы при использовании рандома опираются на то, что в среднем выполнение будет эффективным/корректным, а худшие случаи могут быть какими угодно - точно ли их тогда надо проверять?
- Модел чекингу хочется быть детерменированным

Из всего этого думаю, что в теории можно какие-то random.choice с перебором вариантов добавить, но это отдельная задача, надо бы issue завести и нормально так про нее подумать

2023-06-17 22:58 UTC, KiK0S commented on crates/dslab-mp/src/context.rs
> +    pub fn from_simulation(proc_name: String, sim_ctx: Rc<RefCell<SimulationContext>>, clock_skew: f64) -> Self {
Что касается этого PR, предлагаю следующее:
- Нам все равно понадобится рандом для mc в первой итерации тестов, поэтому я бы не делал Option, а явно форсил его наличие. Тем более, это API контекста, странно его не предоставлять.
- Для первой итерации тестов будет нормально работать использование честного рандома, над которым у mc не будет контроля. У нас сейчас так тесты и работают - мы явно пользуемся питоновским рандомом с заданным хешом.

Я бы сделал `RandomProvider` из стандартного `Pcg64` - это достаточно общий подход, при этом нам не придется потом думать, как же прикрутить рандом. И можно пользоваться стандартным питоновским рандомом, ожидая примерно такие же гарантии. Единственное, в чем вижу разницу - при работе через `ctx.rand()` мы сможем инициализировать сид через хеш состояния и тем самым он будет более консистентным для mc вне зависимости от порядка обхода графа.

2023-06-18 10:36 UTC, osukhoroslov commented on crates/dslab-mp/src/context.rs
> +    pub fn from_simulation(proc_name: String, sim_ctx: Rc<RefCell<SimulationContext>>, clock_skew: f64) -> Self {
Согласен с предложенным решением. Завел issue https://github.com/osukhoroslov/dslab/issues/278

2023-06-18 10:36 UTC, osukhoroslov approved these changes

2023-06-18 12:51 UTC, merged