[mp/mc] Tracing of paths in state graph
osukhoroslov/dslab pull request #273
Opened 2023-05-28 13:58 UTC by AnthonyUdovichenko

2023-06-09 17:32 UTC, osukhoroslov requested changes

2023-06-25 12:11 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +        msg.str() == "broken"
```suggestion
    assert!(if let Err(err) = result {
        err.message() == "broken"
```

2023-06-25 12:11 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +    let expected_trace = vec![
Конечно не хватает здесь первых двух событий, что произошли до MC (LocalMessageReceived и MessageSent). Может в Logger сохранять события в векторе аналогично трейсу, и на этапе создания MC вытаскивать из обычной системы этот лог и добавлять в MC-трейс?

2023-06-25 17:48 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/logger.rs
> +    McLocalMessageSent {
Я не решил, точно ли нужно его выводить в трейсе для студентов. Они могут воспринять это время буквально и начать заводить какие-то таймеры или удивляться, почему они не срабатывают в нужный момент

2023-06-25 17:49 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategy.rs
> +                    t!("{:>10} | {:>10} <-- {:<10} {:?}", depth, dest, src, msg);
Ага, надо решить про глубину сначала, см. другой комментарий

2023-06-25 17:52 UTC, AnthonyUdovichenko commented on crates/dslab-mp/tests/test_mc.rs
> +    let expected_trace = vec![
Мне показалось, что они не нужны, так как они не относятся непосредственно к model checking'у. По идее, поскольку и для обычного исполнения, и для модел чекинга используется один и тот же логгер, довольно логично, что сначала через него идёт вывод обычного исполнения, а потом по итогу модел чекинга дописывается трейс из него в случае ошибки

2023-06-25 21:29 UTC, KiK0S requested changes
Меня очень смущает добавление MessageDuplicated и MessageCorrupted событий, потому что раньше мы их ифали какими-то параметрами, а теперь приводим к общему формату, но со старыми ифами.

Я не уверен, можно ли, но попробовал бы сделать что-то такое:
* Из сигнатуры `apply_event` в стратегии убрать параметры duplicated и corrupted
* А на уровне системы в `apply_event` добавить хендлеры на MessageDuplicated и MessageCorrupted и сделать вообще то же самое, что в методах `duplicate_event` и `corrupt_msg_data`.
* Оба этих события сделать директивами в PendingEvents, ничего не сломается по идее
* Может быть с глубиной что-то не то будет, но ее можно увеличивать только на определенных типах событий

2023-06-25 21:29 UTC, KiK0S commented on crates/dslab-mp/src/logger.rs
> +    McLocalMessageSent {
имхо не нужно

2023-06-25 21:29 UTC, KiK0S commented on crates/dslab-mp/src/mc/pending_events.rs
> +            _ => {}
а можем как-то явно тут указать, что игнорируем и почему? мне сходу непонятно как произойдет обработка `McEvent::MessageCorrupted`, например,  если мы ее тут игнорим.

2023-06-25 21:29 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +            _ => {}
аналогично хочется прозрачно понимать, почему мы какие-то события игнорим

2023-06-25 21:29 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +            _ => {}
мне кажется хватит комментария какого-то

2023-06-25 21:29 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
>          system.events.push_with_fixed_id(event.duplicate().unwrap(), event_id);
Вот почему мы логику ниже оставляем тут, а не относим в system.apply_event под match с MessageDuplicated? для меня выглядит очень непрозрачно

2023-06-25 21:29 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +    fn update_summary_statuses(&mut self, status: String) {
мы с тобой с неймингами подеремся конечно))))) я предлагаю тому кто второй вмерджит аккуратно пройтись ребейзом, потому что мы примерно одни и те же места некритично тут ренеймили

2023-06-25 21:29 UTC, KiK0S commented on crates/dslab-mp/tests/test_mc.rs
> +    let expected_trace = vec![
меня напрягает, что в dslab-mp мы, если правильно помню, просто пишем логи на каждое событие, а в mp/mc мы строим специальный вектор с трейсом. в дебаг-режиме мы еще пишем в каком-то рекурсивном формате, и поэтому первые логи от dslab-mp могут уже где-то в консоли потеряться. А не в дебаг-режиме вообще непонятно, как можно понять, какие были события до трейса

2023-06-25 21:29 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
>          corrupt: bool,
мне кажется, если мы ввели два дополнительных типа события, то очень странно тут передавать бул-параметры

2023-06-26 00:29 UTC, AnthonyUdovichenko commented on crates/dslab-mp/tests/test_mc.rs
> +    let expected_trace = vec![
Дебаг-режим студентами использоваться не будет, за него можно не волноваться. А насчёт понимания, когда какие логи пишутся, сейчас во время запуска model cheking пишется вот это: https://github.com/osukhoroslov/dslab/blob/mc-trace/crates/dslab-mp/src/mc/model_checker.rs#L76-L78. Поэтому тут будет явно видно, что произошло до старта mc, а что уже во время mc

2023-06-26 10:13 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +    let expected_trace = vec![
> По идее, поскольку и для обычного исполнения, и для модел чекинга используется один и тот же логгер, довольно логично, что сначала через него идёт вывод обычного исполнения, а потом по итогу модел чекинга дописывается трейс из него в случае ошибки

Надо учитывать, что сейчас лог с историей для обычного исполнения пишется в консоль только если тест запущен с [флагом debug](https://github.com/osukhoroslov/dslab/blob/368ce7377600aa81947b590800c84ed71e3d2608/examples/mp-guarantees/src/main.rs#L382). И общая практика была такая - по умолчанию этот флаг выключен, чтобы не загромождать вывод тестов (особенно если там большие трассы), и включается студентом по желанию, например для отладки падающего теста. Поэтому в случае MC, если студент не включит этот флаг, то он не увидит предысторию до трейса MC.

2023-06-26 10:31 UTC, osukhoroslov requested changes

2023-06-26 10:31 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/error.rs
> +//! Implementation of model checking error struct
```suggestion
//! Model checking error.
```

2023-06-26 10:31 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/error.rs
> +/// Model checking error struct
```suggestion
/// Stores information about an error found by model checking.
```

2023-06-26 10:31 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/error.rs
> +    /// Create new model checking error
```suggestion
    /// Creates new model checking error.
```

2023-06-26 10:31 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/error.rs
> +    /// Get model checking error message
```suggestion
    /// Returns the error message.
```

2023-07-08 11:27 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/error.rs
> +        self.trace.clone()
Эта правка куда-то пропала

2023-07-08 11:49 UTC, osukhoroslov requested changes

2023-07-08 11:49 UTC, osukhoroslov commented on crates/dslab-mp/src/logger.rs
> +    pub fn trace(&self) -> Vec<LogEntry> {
Предлагаю вместо клонирования выдавать здесь иммутабельную ссылку на вектор, а там в зависимости от необходимости клонировать уже на стороне вызывающего

2023-07-08 11:49 UTC, osukhoroslov commented on crates/dslab-mp/src/system.rs
> +    }
Давайте дадим доступ сразу до логгера, может потом пригодится, и заодно это поможет получить трейс без клонирования в логгере:

```suggestion
    pub fn logger(&self) -> RefMut<Logger> {
        self.logger.borrow_mut()
    }
```

2023-07-08 11:51 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/error.rs
> +        self.trace.clone()
https://github.com/osukhoroslov/dslab/pull/273/commits/37f6d57be1ba245b8a4506e614f6284ffab466dd

2023-07-08 18:35 UTC, osukhoroslov commented on crates/dslab-mp/src/system.rs
> +    pub fn trace(&self) -> Vec<LogEntry> {
Я предлагаю этот метод совсем убрать, и давать доступ напрямую к логгеру. См. [этот комментарий](https://github.com/osukhoroslov/dslab/pull/273#discussion_r1257240856). А потом уже где надо из логгера напрямую вызывать `logger.trace().clone()`.

2023-07-16 17:20 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
>          system.events.push_with_fixed_id(event.duplicate().unwrap(), event_id);
Согласен, можно попробовать унести в system.apply_event

2023-07-16 17:54 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +                            self.search_step(system, StepType::Add(vec![corruption_event]))?;
Кстати, при таком подходе совсем необязательно вообще добавлять событие типа MessageCorrupted в `events`. Так как мы сразу хотим применить его к системе, то добавление в `events` и последующее удаление по `event_id` выглядит избыточным.

2023-07-21 14:45 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +                            self.search_step(system, StepType::Add(vec![corruption_event]))?;
Выложил предлагаемый рефакторинг в ветку `mc-trace-sol`, вот коммит: https://github.com/osukhoroslov/dslab/commit/b2c4a0e5d7eabe01a90f80a59480a0266194c590

2023-07-21 14:55 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/events.rs
> +        msg_id: McEventId,
Предалагаю поправить так везде (см. мою ветку `mc-trace-sol`)

```suggestion
        /// The id of original MessageReceived event.
        receive_event_id: McEventId,
```

2023-07-22 10:48 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategy.rs
> +        match &mut event {
Паттерн матчинг в любом случае останется либо здесь, либо в месте вызова функции, потому что нам нужно вынуть delivery_options, чтобы пометить в них, что корраптить сообщение больше не нужно, но при этом оставить другие PossibleFailures. Кажется, уж лучше здесь делать этот паатерн матчинг, чем в месте вызова

2023-07-23 17:17 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategy.rs
> +                    msg: corrupted_msg.clone(),
Если есть паттерн матчинг, то нельзя (см. комментарий к коду выше)

2023-07-23 18:46 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +        match &mut event {
Предлагаю так сделать:

```rust
    fn create_corrupted_receive(&self, event: McEvent, corrupted_msg: Message) -> McEvent {
        if let MessageReceived {
            src, dest, mut options, ..
        } = event
        {
            if let DeliveryOptions::PossibleFailures { can_be_corrupted, .. } = &mut options {
                *can_be_corrupted = false;
            }
            MessageReceived {
                msg: corrupted_msg,
                src,
                dest,
                options,
            }
        } else {
            panic!("Unexpected event type")
        }
    }
```

2023-07-23 18:49 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +                    msg: corrupted_msg.clone(),
Можно так сделать: https://github.com/osukhoroslov/dslab/pull/273#discussion_r1271542564. Единственное при вызове `create_corrupted_receive` надо будет склонировать `corrupted_msg`:

```rust
            MessageCorrupted {
                receive_event_id,
                corrupted_msg,
                ..
            } => {
                let msg = self.take_event(system, *receive_event_id);
                let corrupted = self.create_corrupted_receive(msg, corrupted_msg.clone());
                system.events.push_with_fixed_id(corrupted, *receive_event_id);
            }
```

2023-07-23 21:19 UTC, AnthonyUdovichenko commented on crates/dslab-mp/src/mc/strategy.rs
> +    fn update_summary_statuses(&mut self, status: String) {
Поребейзил, нейминги нормально смёржились)

2023-07-24 16:54 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +    /// Makes search step according to `step_type`, calls `search_step_impl` with the produced state
```suggestion
    /// Applies the specified event to the system, calls `search_step_impl` with the produced state
```

2023-07-24 16:56 UTC, osukhoroslov approved these changes

2023-07-24 19:08 UTC, KiK0S approved these changes
LGTM!

`build_dumb_delivery_system_with_useless_timer` )))))))))))

2023-07-24 19:12 UTC, merged