[wip] model checking tests for mp-ping-pong & mp-guarantees
osukhoroslov/dslab pull request #285
Opened 2023-06-28 22:57 UTC by KiK0S

Для гарантий все работает примерно так же, как и для пинг-понга, так что предлагаю заносить их вместе, чтобы одну и ту же работу не проделывать в двух разных ревью

2023-06-30 07:15 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +        for msg in delivered.iter() {
скорее всего начиная отсюда можно со стандартным объединить

2023-06-30 07:15 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +use std::borrow::BorrowMut;
скорее всего borrow не нужен

2023-07-08 11:18 UTC, osukhoroslov requested changes

2023-07-08 11:18 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +fn mc_invariant_received_messages(messages_expected: HashSet<String>) -> InvariantFn {
Не проверяется, что все сообщения из `messages_expected` были доставлены.

2023-07-08 11:18 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +fn mc_invariant_depth(depth: u64) -> InvariantFn {
См. комментарии к гарантиям

2023-07-08 11:18 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +fn mc_invariant_combined(mut rules: Vec<InvariantFn>) -> InvariantFn {
Повторно используемые функции точно стоит вынести в mc-библиотеку.

2023-07-08 11:18 UTC, osukhoroslov commented on examples/mp-guarantees/src/main.rs
> +    boxed!(move |state| { mc_invariant_depth(depth)(state).err() })
Лучше переписать без использования mc_invariant_depth, кода немного.

2023-07-08 11:18 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +            Some("too many messages sent from client".to_owned())
```suggestion
            Some("too many messages sent by client".to_owned())
```

2023-07-08 11:18 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +            Some("too many messages sent from server".to_owned())
```suggestion
            Some("too many messages sent by server".to_owned())
```

2023-07-08 11:18 UTC, osukhoroslov commented on examples/mp-guarantees/src/main.rs
> +    let strategy = Dfs::new(prune, goal, invariant, dslab_mp::mc::strategy::ExecutionMode::Default);
```suggestion
    let strategy = Dfs::new(prune, goal, invariant, ExecutionMode::Default);
```

2023-07-08 11:18 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +    let strategy = Dfs::new(prune, goal, invariant, dslab_mp::mc::strategy::ExecutionMode::Default);
```suggestion
    let strategy = Dfs::new(prune, goal, invariant, ExecutionMode::Default);
```

2023-07-08 11:18 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +        format!("model checher found error: {}", res.as_ref().err().unwrap())
```suggestion
        format!("model checker found error: {}", res.err().unwrap())
```

2023-07-08 11:18 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +        format!("model checher found error: {}", res.as_ref().err().unwrap())
```suggestion
        format!("model checker found error: {}", res.err().unwrap())
```

2023-07-08 11:18 UTC, osukhoroslov commented on examples/mp-guarantees/src/main.rs
> +    boxed!(|state| {
Без указания типа моя IDE не видит методы `state`, поэтому предлагаю прописать

```suggestion
    boxed!(|state: &McState| {
```

2023-07-19 22:46 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +fn mc_goal_got_two_messages() -> GoalFn {
ага, сделал

2023-07-19 22:55 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +fn mc_invariant_depth(depth: u64) -> InvariantFn {
перенес поправленное

2023-07-19 22:55 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +fn mc_invariant_combined(mut rules: Vec<InvariantFn>) -> InvariantFn {
перенес

2023-07-19 22:55 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +    boxed!(move |state| { mc_invariant_depth(depth)(state).err() })
ага, сделал

2023-07-19 22:58 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +use dslab_mp::mc::model_checker::ModelChecker;
поправил

2023-07-20 10:36 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +fn mc_invariant_received_messages(messages_expected: HashSet<String>) -> InvariantFn {
поправил, теперь там биективно

2023-07-20 11:12 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +        for msg in delivered.iter() {
там теперь цикл прогоняется два раза вместо одного, но зато все более модульно

2023-07-20 18:46 UTC, osukhoroslov commented on examples/mp-guarantees/src/main.rs
> +        format!("model checher found error: {}", res.err().unwrap())
```suggestion
        format!("model checker found error: {}", res.err().unwrap())
```

2023-07-20 18:50 UTC, osukhoroslov commented on examples/mp-guarantees/src/main.rs
> +    let messages = messages;
```suggestion
```

2023-07-20 18:54 UTC, osukhoroslov commented on examples/mp-guarantees/src/main.rs
> +        .invariant(mc_invariant_received_messages(messages, config));
```suggestion
    let strategy_config = StrategyConfig::default()
        .prune(predicates::mc_prune_state_depth(5))
        .goal(predicates::mc_goal_got_n_local_messages(
            "receiver-node".to_string(),
            "receiver".to_string(),
            2,
        ))
        .invariant(mc_invariant_received_messages(messages, *config));
```

2023-07-20 19:03 UTC, osukhoroslov commented on examples/mp-guarantees/src/main.rs
> +    boxed!(|state| {
Все еще актуально

2023-07-20 19:11 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/predicates.rs
> +                    return Some(format!("too many messages sent by {node_name}:{proc_name}"));
```suggestion
                    return Some(format!("too many messages sent by {proc_name}"));
```

2023-07-20 19:12 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/predicates.rs
> +                "{node}:{proc} received {} messages but {} expected",
```suggestion
                "{proc} received {} messages but {} expected",
```

2023-07-20 19:17 UTC, osukhoroslov commented on examples/mp-guarantees/src/main.rs
> +        let mut msg_count = HashMap::new();
Не используется, ниже перезаписывается на результат `check_delivered_message_type`

2023-07-20 19:31 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/predicates.rs
> +//! Predicates that can be used for configuration in model checker
```suggestion
//! Standard predicate implementations that can be used in model checking strategy.
```

2023-07-20 19:43 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/predicates.rs
> +/// Chains invariants using AND predicate.
```suggestion
/// Combines multiple invariant functions by returning `Ok` iff all invariants are satisfied.
```

2023-07-20 19:44 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/predicates.rs
> +pub fn mc_invariant_combined(mut rules: Vec<InvariantFn>) -> InvariantFn {
Кстати может `mc_all_invariants`? И по аналогии потом можно сделать `mc_any_invariant`.

2023-07-20 19:47 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/predicates.rs
> +/// Checks if n messages were received by a given process.
```suggestion
/// Checks if the given process produced `n` local messages.
```

2023-07-20 19:49 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/predicates.rs
> +/// Checks if state is located deeper that allowed
```suggestion
/// Checks that state depth does not exceed the given value.
```

2023-07-20 19:50 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/predicates.rs
> +/// Checks if state is located deep enough to skip it during model checking run
```suggestion
/// Prunes states with depth exceeding the given value.
```

2023-07-20 19:53 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/predicates.rs
> +/// Checks that every process have not sent more that allowed number of messages
```suggestion
/// Prunes states where some process has sent more messages than the given value.
```

2023-07-20 19:57 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/predicates.rs
> +/// Verifies that set of messages received by process matches with expectations
```suggestion
/// Verifies that the set of local messages delivered by a process matches exactly the expected messages.
/// No duplications or other messages are allowed. 
```

2023-07-20 20:24 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +        mc_prune_depth(5),
прогнал эксперимент, глубины 7 тоже хватает, тестирование выполняется порядка 40 секунд локально. Когда будет трейс, я подтяну еще тест с ограничением на количество дропов, там можно позволить себе полный обход графа

2023-07-20 20:25 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +    boxed!(|state| {
ага, что-то проморгал при переносе, поправил

2023-07-20 20:27 UTC, KiK0S commented on crates/dslab-mp/src/mc/model_checker.rs
> +    /// Runs model checking and returns the result on completion.
```suggestion
    /// Runs model checking after applying callback.
```

2023-07-20 20:41 UTC, KiK0S commented on crates/dslab-mp/src/mc/predicates.rs
> +pub fn mc_invariant_combined(mut rules: Vec<InvariantFn>) -> InvariantFn {
Да, давайте. У меня как раз еще такой предикат для goal появился, будут хорошо смотреться вместе

2023-07-20 20:42 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +    }
переиспользовать смог в одном месте. В `mc_unreliable_network` в рантайме обнаружил проблему: пакеты дропаются сразу же, надо их закидывать уже после создания `mc`. Прокинул метод `run_with_change`

2023-07-20 20:43 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +    let messages = messages;
уже, кажется, неактуально

2023-07-20 20:47 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +        .invariant(mc_invariant_received_messages(messages, config));
поправил

2023-07-20 20:48 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +        format!("model checher found error: {}", res.err().unwrap())
поправил

2023-07-20 20:48 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +        let mut msg_count = HashMap::new();
ага, убрал и переименовал для понятности

2023-07-20 20:51 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +        mc_prune_depth(5),
можем в unreliable_network доставлять одно сообщение, чтобы хватало времени на обход побольше. Но с двумя сообщениями основную пользу точно будет давать limited_drops тест

2023-07-21 10:20 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/predicates.rs
> +/// Combines multiple goal functions by returning `Ok` iff at least one goal is reached.
```suggestion
/// Combines multiple goal functions by returning `Some(status)` iff at least one goal is reached.
```

2023-07-21 12:22 UTC, osukhoroslov requested changes

2023-07-21 12:22 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +            predicates::mc_invariant_received_messages(
`mc_invariant_received_messages` всегда возвращает `Ok` в случае если есть необработанные события. Нам же надо проверить доставку даже если есть такие события, но клиент уже доставил 2 локальных сообщения, то есть выполнен goal. Предалагю в `mc_invariant_received_messages` проверять что процесс уже доставил ожидаемое число сообщений вместо проверки на `available_events_num`. И надо подумать насчет того, насколько востребованным может быть возможность задавать инвариант только для goal-состояний.

2023-07-24 22:08 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +            predicates::mc_invariant_received_messages(
Решил сделать еще более в общем виде - проверять валидность тех сообщений, которые уже имеются на момент запуска инварианта. Мы сразу проверяем, что не появляется ничего лишнего и ничего не дублируется. И в конце остается сделать проверку, что мы в финальном состоянии все сообщения по итогу были доставлены

2023-07-24 22:28 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +        for message in messages.clone() {
done, надо было сделать Fn -> FnOnce

2023-07-24 22:28 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +fn check_delivered_message_type(delivered: &[Message], sent: &[Message]) -> Result<HashMap<String, i32>, String> {
ага, заменил

2023-07-24 22:28 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +    let mut expected_msg_count: HashSet<String> = HashSet::default();
Пришлось отдельно прокинуть тип, но сделал, да

2023-07-24 22:29 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +    msg_count: &HashMap<String, i32>,
done

2023-07-24 22:30 UTC, KiK0S commented on crates/dslab-mp/src/mc/predicates.rs
> +pub fn mc_goal_nothing_left_to_do() -> GoalFn {
сделал

2023-07-24 22:31 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +    let msg_count = check_delivered_message_type(&delivered, sent)?;
сделано

2023-07-24 22:49 UTC, KiK0S commented on crates/dslab-mp/src/mc/predicates.rs
> +pub fn mc_invariant_state_depth(depth: u64) -> InvariantFn {
решил разделить на модули, чтобы если что еще и в rustdoc хорошо подтягивались

2023-07-24 22:56 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +        ))
сделал

2023-07-24 22:56 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +fn mc_invariant_received_messages(messages_expected: Vec<Message>, config: TestConfig) -> InvariantFn {
ага, поправил

2023-07-26 18:05 UTC, osukhoroslov requested changes

2023-07-26 18:05 UTC, osukhoroslov commented on examples/mp-guarantees/src/main.rs
> +fn check_guarantees(sys: &mut System, sent: &[Message], config: &TestConfig) -> TestResult {
Решение solution.py проходит 32 из 36 тестов, тогда как в main оно проходит только 1:

![изображение](https://github.com/osukhoroslov/dslab/assets/1322460/5e18851d-8f7f-4005-81a0-136124bcf638)

Где-то сломалась проверка гарантий.

2023-07-27 17:09 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +            test_mc_limit_drop_number,
```suggestion
            test_mc_limited_message_drops,
```

2023-07-27 17:10 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +    tests.add("MODEL CHECKING DROP LIMIT", test_mc_limit_drop_number, config);
```suggestion
    tests.add("MODEL CHECKING DROP LIMIT", test_mc_limited_message_drops, config);
```

2023-07-27 17:11 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +            prunes::mc_prune_events_limit(rc!(LogEntry::is_mc_timer_set), 4),
```suggestion
            prunes::mc_prune_events_limit(LogEntry::is_mc_message_dropped, num_drops_allowed),
            prunes::mc_prune_events_limit(LogEntry::is_mc_message_sent, 2 + num_drops_allowed),
            prunes::mc_prune_events_limit(LogEntry::is_mc_timer_set, 4),
```

2023-07-27 17:12 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +            prunes::mc_prune_events_limit(rc!(LogEntry::is_mc_message_sent), 2 + num_drops_allowed),
```suggestion
            prunes::mc_prune_events_limit(LogEntry::is_mc_message_dropped, num_drops_allowed),
            prunes::mc_prune_events_limit(LogEntry::is_mc_message_sent, 2 + num_drops_allowed),
```

2023-07-27 17:13 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +use sugars::{boxed, rc};
```suggestion
use sugars::boxed;
```

2023-07-27 17:14 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +    tests.add("MODEL CHECKING DROP LIMIT", test_mc_limit_drop_number, config);
https://github.com/osukhoroslov/dslab/pull/285/files#r1276588365

2023-07-28 12:37 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +    tests.add("MODEL CHECKING", test_mc_reliable_network, config.clone());
отписался в чате - это честная паника от решения, сходу не знаю как поступать тут

2023-07-28 12:37 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +            sys.send_local_message("sender-node".to_string(), "sender".to_string(), msg.clone());
сделано

2023-07-28 12:37 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +        .goal(goals::mc_goal_got_n_local_messages("client-node", "client", 2))
сделано

2023-07-28 12:37 UTC, KiK0S commented on crates/dslab-mp/src/mc/predicates.rs
> +/// Prunes cut exploration branches if further analysis is considered unnecessary or computation-heavy.
сделано

2023-07-28 16:01 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +    tests.add("MODEL CHECKING", test_mc_reliable_network, config.clone());
в этой лабе как и в [DSLabs](https://github.com/emichael/dslabs/tree/master/labs/lab0-pingpong) предполагается, что клиент отправляет только один Ping и следующий может отправить только после получения Pong

2023-07-28 17:22 UTC, osukhoroslov commented on examples/mp-guarantees/src/main.rs
> +        let expected_count = expected_msg_count.get(data).unwrap_or(&0);
Предлагаю в этой функции просто игнорировать те доставленные сообщения, которых нет в expected

2023-07-28 17:26 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +    tests.add("MODEL CHECKING", test_mc_reliable_network, config.clone());
Решили пока убрать тест с 2 одновременными пингами и сделать MC-тесты на один пинг и два последовательных (через collect)

2023-07-28 17:27 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +    tests.add("MODEL CHECKING", test_mc_reliable_network, config.clone());
См #293

2023-07-29 15:47 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +        let expected_count = expected_msg_count.get(data).unwrap_or(&0);
сделал проверку через contains_key

2023-07-30 11:24 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/predicates.rs
> +            Some("combied goal reached".to_string())
```suggestion
            Some("combined goal is reached".to_string())
```

2023-07-30 11:39 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +    for (i, message_data) in messages_data.iter().enumerate() {
чтобы не преобразовывать везде `i` в `u64`:

```suggestion
    for (message_data, i) in messages_data.iter().zip(0u64..) {
```

2023-07-30 11:39 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +        messages_prefix.push(message_data.to_string());
Так как уже строка

```suggestion
        messages_prefix.push(message_data.clone());
```

2023-07-30 11:40 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +    for (i, message_data) in messages_data.iter().enumerate() {
И можно даже стартовать с 1, чтобы избавиться от `i+1`

2023-07-30 11:44 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +                    HashSet::<String>::from_iter(messages_prefix.clone()),
Если нам не важен порядок, то предлагаю `messages_prefix` сделать сразу `HashSet` и переименовать в `messages_expected` как в другом тесте.

2023-07-30 12:04 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +                return Err(e.message());
Заметил что в трейсе для `retry.py` пишется не самая короткая история (клиент отправил PING аж 4 раза). Предлагаю сделать так, чтобы в `run_from_states_with_change` состояния обследовались в порядке увеличения числа событий в них.

2023-08-01 22:51 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +                    HashSet::<String>::from_iter(messages_prefix.clone()),
сделал

2023-08-01 23:02 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +                return Err(e.message());
вообще я сейчас сделал так, и все равно 4 раза. несколько причин:
- я починил `retry.py`, чтобы он был с багом, но не рантаймил. При таком баге нужно минимум три отправки, чтобы создать плохую ситуацию.
- если у нас общая глубина на втором запуске collect это сумма двух глубин, то минимизируя первую глубину мы не обязательно минимизируем сумму, тем более что вторая глубина определяется DFS-ом

2023-08-02 21:28 UTC, osukhoroslov requested changes

2023-08-02 21:28 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/model_checker.rs
> +        for state in sorted_states {
```suggestion
        let mut states = Vec::from_iter(states);
        // sort starting states by increasing depth to produce shorter error traces
        states.sort_by_key(|x| x.depth);
        for state in states {
```

Упростил и добавил комментарий

2023-08-02 21:28 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/error.rs
>  }
Зачем нужны реализации Display и Debug? Без них кажется все работает.

2023-08-02 21:28 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/error.rs
> +        t!("\n\n===\n");
Предлагаю убрать

```suggestion
```

2023-08-02 21:28 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/error.rs
> +    pub fn print(&self) {
```suggestion
    pub fn print_trace(&self) {
```

2023-08-02 21:28 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/error.rs
> +        }
```suggestion
        for entry in &self.trace {
            entry.print();
        }
```

2023-08-02 21:28 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/error.rs
> +    /// Prints error information required for debugging
```suggestion
    /// Prints error trace.
```

2023-08-02 21:28 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/error.rs
> +        t!("\n\n===\n");
И предлагаю избавиться от ненужных выводов в консоль до трейса ошибки:
- Закомментировать пока печать NodeStarted, ProcessStarted и McStarted в LogEntry.print()
- Убрать печать `RUNNING MODEL CHECKING THROUGH POSSIBLE EXECUTION PATH` в ModelChecker

После этого в результате теста останется только трейс ошибки от MC, ничего лишнего.

2023-08-02 21:28 UTC, osukhoroslov commented on examples/mp-guarantees/src/main.rs
> +fn test_mc_unstable_network(config: &TestConfig) -> TestResult {
Корректные авторские решения не проходят тесты:

```
Passed 33 from 36 tests

Failed tests:
- [AT LEAST ONCE] MODEL CHECKING UNSTABLE NETWORK: state depth exceeds maximum allowed depth 20
- [EXACTLY ONCE] MODEL CHECKING LIMITED UNSTABLE NETWORK: state depth exceeds maximum allowed depth 20
- [EXACTLY ONCE ORDERED] MODEL CHECKING UNSTABLE NETWORK: state depth exceeds maximum allowed depth 20
```

2023-08-02 21:28 UTC, osukhoroslov commented on examples/mp-guarantees/src/main.rs
> +            "[EXACTLY ONCE] MODEL CHECKING LIMITED UNSTABLE NETWORK",
```suggestion
            "[EXACTLY ONCE] MODEL CHECKING UNSTABLE NETWORK",
```

2023-08-02 21:32 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +                return Err(e.message());
Я попробовал заменить DFS на BFS и получил желаемую короткую историю:

![изображение](https://github.com/osukhoroslov/dslab/assets/1322460/f7c912e9-b19a-461f-8d7f-63483a57354e)

Может так и сделаем? И заодно можете посмотреть откуда берется выделенное событие отмены таймера?

2023-08-03 08:17 UTC, KiK0S commented
Статус по имеющимся решениям:
* AMO с багом - ломается
* ALO с багом - не ломается. но если спамить меньше (3 вместо 5) - то не ломается. Не вижу способа сделать так, чтобы не ломалось - можно константу под тесты подогнать
* EOO с багом - ломается
* Авторское - Проходит тесты - единственное что есть трейдофф - мы либо ловим баг в EOO и работаем ~3 минуты, либо не ловим баг в EOO и работаем полминуты-минуту. Просто баг в EOO не ловится 2 сообщениями, поэтому нужно 3 и граф разрастается.

Баги, которые я ловил в рамках диплома, тоже нашлись!

2023-08-03 08:21 UTC, KiK0S commented on crates/dslab-mp/src/mc/error.rs
> +    pub fn print(&self) {
да, это хороший нейминг - я всякие debug навешивал как раз потому что мне не нравилось выдавать print

2023-08-03 08:29 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +fn test_mc_unstable_network(config: &TestConfig) -> TestResult {
починил, теперь проходят

2023-08-03 08:40 UTC, KiK0S commented on crates/dslab-mp/src/mc/error.rs
>  }
`Debug` нужен, чтобы можно было делать `unwrap()`. сделал дефолтный `Debug`, убрал `Default`

2023-08-03 08:53 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/error.rs
>  }
Где делать unwrap?

2023-08-03 08:55 UTC, KiK0S commented on crates/dslab-mp/src/mc/error.rs
>  }
например в internal тестах, test_mc имеет всякие `.expect`, `assert_eq` для McError

2023-08-03 08:55 UTC, KiK0S commented on crates/dslab-mp/src/mc/error.rs
>  }
вроде кроме них не нужно нигде

2023-08-03 08:56 UTC, osukhoroslov commented
> * ALO с багом - не ломается. но если спамить меньше (3 вместо 5) - то не ломается.

Здесь противоречие

2023-08-03 08:56 UTC, KiK0S commented on crates/dslab-mp/src/mc/error.rs
> +        t!("\n\n===\n");
если комментить NodeStarted то оно же везде пропадет, и в обычных тоже. Или нам это норм?

2023-08-03 08:58 UTC, KiK0S commented
> > * ALO с багом - не ломается. но если спамить меньше (3 вместо 5) - то не ломается.
> 
> Здесь противоречие

@osukhoroslov поправил, одно не было лишним) если решение меньше спамит, то его можно сломать, если больше то нельзя -- и константу на больше можно бесконечно увеличивать

2023-08-03 09:01 UTC, KiK0S commented on crates/dslab-mp/src/mc/error.rs
> +        t!("\n\n===\n");
в общем сделал так, как вы предложили, могу поправить как было - мне в целом норм, что для обычных тестов node started пропали

2023-08-03 10:01 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +                return Err(e.message());
BFS сделал, про лог отписался в чате:

```
сейчас разбираюсь с (cм. картинку), вердикт такой:
У нас TimerCancelled пишется в двух местах - когда он только создается, и когда он применяется. При этом это происходит не одновременно. То есть, поскольку это директива, то это должно происходить вплотную друг к другу, но поскольку мы работаем в collect-режиме, то это состояние между двумя этими логами и после этих двух логов - два разных состояния, и мы находим первое

Наверное, это плохо и баг, надо видимо еще раз подумать что такое директива, а что мгновенное событие))) вот LocalMessageSent работает правильно в этом плане — он сразу применяется и все
```

2023-08-03 16:25 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +                return Err(e.message());
завел #296

2023-08-03 18:53 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/error.rs
> +        t!("\n\n===\n");
Да, именно так я и предлагал

2023-08-03 19:46 UTC, osukhoroslov commented on examples/mp-ping-pong/src/main.rs
> +                goals::got_n_local_messages("client-node", "client", i as usize),
Заметил маленькую неконсистентность - в этой функции число сообщений передается как usize, а ниже в `collects::got_n_local_messages` как u64. Предлагаю сделать одинаково. Мне больше нравится usize, так как внутри мы к нему и приводим.

2023-08-03 21:44 UTC, KiK0S commented on examples/mp-ping-pong/src/main.rs
> +                goals::got_n_local_messages("client-node", "client", i as usize),
да, мне тоже так больше нравится. поправил

2023-08-04 15:34 UTC, osukhoroslov commented on examples/mp-guarantees/src/main.rs
> +        .invariant(invariant);
Немного доработал и повысил лимит до 60 секунд.

```suggestion
    let mut invariants = vec![
        invariants::state_depth(20),
        mc_invariant_guarantees(messages.clone(), *config),
    ];
    if config.ordered {
        invariants.push(invariants::time_limit(Duration::from_secs(60)))
    };
    let strategy_config = StrategyConfig::default()
        .prune(prunes::any_prune(vec![
            prunes::events_limit(LogEntry::is_mc_message_dropped, num_drops_allowed),
            prunes::events_limit(LogEntry::is_mc_message_duplicated, num_duplication_allowed),
            prunes::events_limit(LogEntry::is_mc_timer_fired, 1),
            prunes::events_limit(LogEntry::is_mc_message_received, msg_count + num_drops_allowed),
        ]))
        .goal(goal)
        .invariant(invariants::all_invariants(invariants));
```

2023-08-04 15:36 UTC, osukhoroslov approved these changes

2023-08-04 15:59 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +        .invariant(invariant);
ой, да, 10 у меня от тестирования просочилось  :sweat_smile:

2023-08-04 18:25 UTC, KiK0S commented on examples/mp-guarantees/src/main.rs
> +        .invariant(invariant);
поднял до 80

2023-08-04 18:31 UTC, KiK0S commented on crates/dslab-mp/src/mc/predicates.rs
> +        // We use counter to calculate time 1 out of 256 for performance purposes.
```suggestion
        // We use counter to calculate time 1 out of 256 calls for performance purposes.
```

2023-08-04 18:37 UTC, merged