[mp/mc] better strategy configuration
osukhoroslov/dslab pull request #286
Opened 2023-07-02 19:37 UTC by KiK0S

2023-07-08 09:58 UTC, osukhoroslov requested changes

2023-07-08 09:58 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +/// Helps to specify a Strategy instance with given predicates and execution mode
```suggestion
/// Configuration of model checking strategy.
```

2023-07-08 09:58 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +    /// Set prune function
```suggestion
    /// Sets prune function.
```

2023-07-08 09:58 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +    /// Set invariant function
```suggestion
    /// Sets invariant function.
```

2023-07-08 09:58 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +    /// Set goal function
```suggestion
    /// Sets goal function.
```

2023-07-08 09:58 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +    /// Set collect function
```suggestion
    /// Sets collect function.
```

2023-07-08 09:58 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +    /// Set execution mode
```suggestion
    /// Sets execution mode.
```

2023-07-08 09:58 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +    Empty,
```suggestion
    /// Does not store any data about the previously visited system states.
    Disabled,
```

2023-07-08 09:58 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +    Full,
Зачем понадобился такой режим? И с названием может возникнуть путаница с `VisitedStates::Full`.

2023-07-08 09:58 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +    let mut mc = build_model_checker(&sys, strategy_name, prune, goal, invariant, None, ExecutionMode::Debug);
Почему режим стал Debug?

2023-07-08 09:58 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/model_checker.rs
> +        let mut strategy = boxed!(S::default());
А почему бы не добавить в трейт Strategy метод:

```
pub trait Strategy {
    fn build(config: StrategyConfiguration) -> Self;
    ...
```
и здесь просто вызывать его:
```
let strategy = boxed!(S::build(config));
```
Это избавит от необходимости делать дефолтный конструктор у стратегий и переопределять их поля после инициализации здесь, что выглядить не очень красиво. Также отпадет необходимость в `set_execution_mode()`.

2023-07-09 11:44 UTC, KiK0S commented on crates/dslab-mp/tests/test_mc.rs
> +    let mut mc = build_model_checker(&sys, strategy_name, prune, goal, invariant, None, ExecutionMode::Debug);
Потому что это тест на `VisibleStates`, а в Default-режиме мы кешируем по хешам состояний, и не хочется в тесте завязываться на то, что хеши не совпадут. В debug мы честно сохранили все стейты

2023-07-09 11:44 UTC, KiK0S commented on crates/dslab-mp/src/mc/model_checker.rs
> +use super::strategy::StrategyConfiguration;
починил

2023-07-09 11:44 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +pub struct StrategyConfiguration {
ага, сделал

2023-07-09 11:44 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +/// Helps to specify a Strategy instance with given predicates and execution mode
done

2023-07-09 11:44 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +    /// Set prune function
done

2023-07-09 11:44 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +    /// Set invariant function
done

2023-07-09 11:44 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +    /// Set goal function
done

2023-07-09 11:44 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +    /// Set collect function
done

2023-07-09 11:44 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +    /// Set execution mode
done

2023-07-09 11:44 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +    Empty,
done

2023-07-09 11:44 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +    Full,
Вообще, он был нужен, потому что `ExecutionMode` определял `VisitedStates`, и без этого нельзя было использовать `VisitedStates::Disabled`, но я сейчас придумал вынести это в отдельное поле конфигурации, и стало лучше

2023-07-09 11:44 UTC, KiK0S commented on crates/dslab-mp/src/mc/model_checker.rs
> +        let mut strategy = boxed!(S::default());
сделал, хорошая идея!

2023-07-09 11:44 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +    Full,
так что сейчас не нужен, убрал

2023-07-09 11:45 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +            visited_states: VisitedStates::Disabled,
Возможно мы тут другой дефолтный хеш хотим?

2023-07-09 11:45 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +            visited_states: VisitedStates::Disabled,
Типа,
```suggestion
            visited_states: VisitedStates::Partial(HashSet::default()),
```

2023-07-09 16:19 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +fn build_default_model_checker(
Предлагаю назвать `build_mc` по аналогии с методом `build_mc_from_config`.

2023-07-09 16:20 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +    println!("{:?}", result);
Нужен?

2023-07-09 16:21 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +            visited_states: VisitedStates::Disabled,
Да, Partial, как было раньше по-умолчанию

2023-07-09 16:33 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +            visited_states: VisitedStates::Disabled,
ага, поправил

2023-07-09 16:33 UTC, KiK0S commented on crates/dslab-mp/tests/test_mc.rs
> +fn build_default_model_checker(
сделал

2023-07-09 16:33 UTC, KiK0S commented on crates/dslab-mp/tests/test_mc.rs
> +    println!("{:?}", result);
неа, вернул

2023-07-09 17:07 UTC, osukhoroslov approved these changes

2023-07-09 17:36 UTC, merged