[network] Add docs
osukhoroslov/dslab pull request #287
Opened 2023-07-03 15:19 UTC by maksim1744

2023-07-09 20:18 UTC, osukhoroslov requested changes
Часть публичного кода пока не покрыта. Добавьте в `lib.rs`:

```
#![warn(missing_docs)]
```

и добейтесь отсутствия ворнингов.

2023-07-09 20:18 UTC, osukhoroslov commented on crates/dslab-network/src/network.rs
> +    /// Adds new node to underlying topology.
```suggestion
    /// Adds new network node.
```

2023-07-09 20:18 UTC, osukhoroslov commented on crates/dslab-network/src/network.rs
> +    /// Adds new link to underlying topology, see [Topology::add_link].
```suggestion
    /// Adds a link between two nodes, see [`Topology::add_link`].
```

2023-07-09 20:18 UTC, osukhoroslov commented on crates/dslab-network/src/network.rs
> +    /// See [Topology::init].
```suggestion
    /// See [`Topology::init`].
```

2023-07-09 20:18 UTC, osukhoroslov commented on crates/dslab-network/src/network.rs
> +    /// See [Topology::set_location].
```suggestion
    /// See [`Topology::set_location`].
```

2023-07-09 20:18 UTC, osukhoroslov commented on crates/dslab-network/src/network.rs
> +    /// See [Topology::check_same_node].
```suggestion
    /// See [`Topology::check_same_node`].
```

2023-07-09 20:18 UTC, osukhoroslov commented on crates/dslab-network/src/network.rs
> +    /// See [Topology::get_nodes].
```suggestion
    /// See [`Topology::get_nodes`].
```

2023-07-09 20:18 UTC, osukhoroslov commented on crates/dslab-network/src/network.rs
> +    /// Sends given message from `src` to `dest`. Size is assumed to be zero.
```suggestion
    /// Sends a message from node `src` to node `dest`. 
    /// 
    /// The message size is assumed to be zero, so the message delivery time is determined only by the network latency.
```

2023-07-09 20:18 UTC, osukhoroslov commented on crates/dslab-network/src/network.rs
> +    /// Sends event from `src` to `dest`. Size is assumed to be zero.
```suggestion
    /// Sends an event from node `src` to node `dest`.
    ///
    /// The event size is assumed to be zero, so the event delay is determined only by the network latency.
```

2023-07-09 20:18 UTC, osukhoroslov commented on crates/dslab-network/src/network.rs
> +    /// Starts data transfer from `src` to `dest`.
```suggestion
    /// Starts a data transfer from node `src` to node `dest`.
```

2023-07-09 20:18 UTC, osukhoroslov commented on crates/dslab-network/src/network.rs
> +    /// Returns bandwidth between `src` and `dest`.
```suggestion
    /// Returns the network bandwidth from node `src` to node `dest`.
```

2023-07-17 11:55 UTC, maksim1744 commented
> Часть публичного кода пока не покрыта. Добавьте в `lib.rs`:
> 
> ```
> #![warn(missing_docs)]
> ```
> 
> и добейтесь отсутствия ворнингов.

Я не понимаю, в чем смысл над функцией с сигнатурой `pub fn new() -> TopologyResolver` писать `Creates new TopologyResolver`. Только чтобы ворнингов не было?

2023-07-17 12:05 UTC, maksim1744 commented on crates/dslab-network/src/topology.rs
> +    /// Returns `true` if two actors are located on one node.
Тут тоже по сигнатуре должно быть понятно про `id1` and `id2`, при этом на мой взгляд `if two simulation components` более читаемо чем `if simulation components id1 and id2`. В некоторых других замечаниях аналогично не понимаю, зачем переписывать сигнатуру в комментарий

2023-07-17 12:06 UTC, maksim1744 commented on crates/dslab-network/src/topology.rs
> +    /// Returns latency between two actors on the same node.
В продолжение https://github.com/osukhoroslov/dslab/pull/287/files#r1265251462: вот же, тут явно лучше)

2023-07-17 12:23 UTC, osukhoroslov commented on crates/dslab-network/src/topology.rs
> +    /// Recalculates all paths between nodes.
Согласен, пусть будет

2023-07-17 12:25 UTC, osukhoroslov commented on crates/dslab-network/src/topology.rs
> +    /// Returns `true` if two actors are located on one node.
Хорошо, пусть будет `if two simulation components`

2023-07-17 12:26 UTC, osukhoroslov commented on crates/dslab-network/src/topology.rs
> +    /// Returns latency between two actors on the same node.
Хорошо

2023-07-24 14:50 UTC, osukhoroslov commented
@maksim1744 я основательно отрефакторил dslab-network и доработал документацию (кроме README, его позже напишу). Посмотрите на предмет возможных проблем.

2023-07-31 15:16 UTC, maksim1744 commented on crates/dslab-network/src/routing.rs
> +    fn init(&mut self, topology: Ref<Topology>);
Почему Ref, а не обычная ссылка? Кажется Ref->& легко [конвертируется](https://doc.rust-lang.org/std/cell/struct.Ref.html#impl-Deref-for-Ref%3C'_,+T%3E) в месте вызова, а в обратную сторону такого не нашел

2023-07-31 15:16 UTC, maksim1744 commented on crates/dslab-network/src/routing.rs
> +    fn dijkstra_for_node(&mut self, node: NodeId, topology: &Ref<Topology>) {
зачем тут ссылка на Ref? Ref сама по себе же ссылка

2023-07-31 15:16 UTC, maksim1744 commented on crates/dslab-network/src/topology.rs
> +    pub fn get_path_latency(&mut self, path: Vec<LinkId>) -> f64 {
Может тут передавать `&[LinkId]`? Копировать тогда только если в кэше не нашлось

2023-07-31 15:16 UTC, maksim1744 commented on crates/dslab-network/src/topology.rs
> +        for link_id in &path {
можно кстати `.iter.map.sum`, учитывая как активно мы (или только я?) ) такие конструкции используем

2023-07-31 15:16 UTC, maksim1744 commented on crates/dslab-network/src/topology.rs
> +        assert!(link.bandwidth > 0.0, "Link bandwidth must be > 0");
А может все-таки `>=0` сделать? Вроде не  должно сломаться ничего. Вдруг там у пользователя bandwidth как-то сложно считается, и он `.max(0.)` делает, чтобы отрицательных eps не было, а так придется какие-то ифы на 0 писать перед добавлением линки

2023-07-31 17:46 UTC, osukhoroslov commented on crates/dslab-core/readme.md
> -    fn send_ping(&mut self, dst: Id) {
В смысле `dst` вместо `dest`?

2023-07-31 17:49 UTC, maksim1744 commented on crates/dslab-core/readme.md
> -    fn send_ping(&mut self, dst: Id) {
да

2023-07-31 18:28 UTC, osukhoroslov commented on crates/dslab-network/src/topology.rs
> +        assert!(link.bandwidth > 0.0, "Link bandwidth must be > 0");
> Вроде не должно сломаться ничего. 

Потому что TopologyAwareNetworkModel сейчас нигде не делит на bandwidth? А если пользователь напишет свою модель и в ней где-то решит поделить?

> а так придется какие-то ифы на 0 писать перед добавлением линки

Я не очень понимаю смысл такого линка с нулевой пропускной способностью. По нему же ничего не передашь, зачем тогда добавлять ) Есть какой-то пример?

2023-07-31 18:30 UTC, osukhoroslov commented on crates/dslab-network/src/routing.rs
> +    fn init(&mut self, topology: Ref<Topology>);
Согласен, заменил на обычную ссылку

2023-07-31 18:30 UTC, maksim1744 commented on crates/dslab-network/src/topology.rs
> +        assert!(link.bandwidth > 0.0, "Link bandwidth must be > 0");
> Есть какой-то пример?

нет)

> А если пользователь напишет свою модель и в ней где-то решит поделить?

хм, ок, пусть остается >0

2023-07-31 18:35 UTC, osukhoroslov commented on crates/dslab-network/src/topology.rs
> +        for link_id in &path {
Сделал

2023-07-31 19:16 UTC, maksim1744 commented on crates/dslab-network/src/topology.rs
> +    pub fn get_path_latency(&mut self, path: Vec<LinkId>) -> f64 {
А кэш путей нужен вообще? Вроде на построение уходит `O(path.len * log)`, на копирование из кэша просто `O(path.len)`, и то в первой части лог только из-за того, что мы используем `BTreeMap` для стабильного порядка, но можно и правильную хеш-таблицу подобрать наверное. А node_links_map поменять на `Vec<BTreeMap>` можно и сейчас, там и так на каждую ноду заранее создается элемент

`bandwidth_cache` и `latency_cache` большого смысла кажется не имеют, если там вектор ключом является, тоже по асимптотике что хеш этого вектора для хеш-таблицы считать, что пройти по нему должно быть одинаково

2023-07-31 19:31 UTC, maksim1744 commented on crates/dslab-network/src/topology.rs
> +    pub fn get_path_latency(&mut self, path: Vec<LinkId>) -> f64 {
И при желании можно из топологии возвращать итератор на путь, а не вектор, у этого итератора будут храниться координаты начала и конца и ссылка на node_links_map, тогда вообще вектор например в момент вызова latency() нигде создаваться не будет, будут просто итераторы на итераторах. Это правда сработает только если раст разрешит ссылку на node_links_map выдать, могу попробовать

2023-07-31 20:10 UTC, maksim1744 commented on crates/dslab-network/src/topology.rs
> +    pub fn get_path_latency(&mut self, path: Vec<LinkId>) -> f64 {
Сделал в отдельной ветке: https://github.com/osukhoroslov/dslab/commits/remove-extra-rc

Там два коммита: [первый](https://github.com/osukhoroslov/dslab/commit/c68eb65195b573404e47c31c0332f85ce06f348c) удаляет лишние кэши и заодно пачку RefCell. В частности не очень понятно, зачем хранить топологию в самой сети, можно получать ее из модели и избавиться от `Rc<RefCell<_>>`.

[Второй](https://github.com/osukhoroslov/dslab/commit/4f29468185ce9306f4ca8d618c291e730134b248) я очень примерно набросал, там есть функция get_path_iter, которая возвращает итератор на путь и лениво считает его, когда нужно. Никаких проблем с lifetime в текущем коде не возникло, если что всегда можно позвать `.collect()` на итераторе и получить путь на месте.

И кажется в роутинге появились небольшие баги после добавления односторонних линков, там нужно искать путь в инвертированном графе из dst в src, а потом по родительским ссылкам идти обратно, тогда получается без `path.reverse()` в конце, что важно для работы итератора.
Сейчас баг живет [тут](https://github.com/osukhoroslov/dslab/pull/287/files#diff-ec1e73504fec0fb34cb46812fe711bff212426d4cacf0903b4c446b1f88be93fR151): `cur_node двигается от `dest` к `src`, поэтому надо аргументы этой `node_links_map` в обратном порядке передавать, иначе мы не по тем линкам идем. Надо бы наверное тест, где путь только в одну сторону есть, чтобы такое отлавливать

2023-07-31 20:23 UTC, osukhoroslov commented on crates/dslab-core/readme.md
> -    fn send_ping(&mut self, dst: Id) {
Пожалуй да, переделал на `dst`

2023-08-01 21:28 UTC, osukhoroslov commented on crates/dslab-network/src/topology.rs
> +    pub fn get_path_latency(&mut self, path: Vec<LinkId>) -> f64 {
Насчёт кэша согласен. Насчёт топологии - тоже, пусть живет внутри модели, раз так получается проще. Применил ваши коммиты и немного доработал. А упомянутый баг в роутинге получается вы пофиксили? Можете тест такой написать?

2023-08-01 21:57 UTC, osukhoroslov commented on crates/dslab-network/src/topology.rs
> +    pub fn get_path_latency(&mut self, path: Vec<LinkId>) -> f64 {
Все-таки из-за переноса топологии внутрь модели возникла проблема. Тесты падают при вызове `Network.add_node` для простых моделей без топологии, где теперь не получается зарегистрировать узел без топологии. Надо подумать что с этим делать.

2023-08-01 22:03 UTC, maksim1744 commented on crates/dslab-network/src/topology.rs
> +    pub fn get_path_latency(&mut self, path: Vec<LinkId>) -> f64 {
Получается раньше они добавлялись в топологию, но не использовались нигде? Тогда выглядит логичным просто на None там проверять

2023-08-01 22:12 UTC, maksim1744 commented on crates/dslab-network/src/topology.rs
> +    pub fn get_path_latency(&mut self, path: Vec<LinkId>) -> f64 {
> А упомянутый баг в роутинге получается вы пофиксили? Можете тест такой написать?

Добавил ориентированный diamond, чтобы проверить что действительно кратчайший по latency путь находится, и цикл из трех вершин, чтобы убедиться, что по обратной линке случайно трансфер не пойдет (так как там latency было бы меньше)

2023-08-01 22:22 UTC, osukhoroslov commented on crates/dslab-network/src/topology.rs
> +    pub fn get_path_latency(&mut self, path: Vec<LinkId>) -> f64 {
> Получается раньше они добавлялись в топологию, но не использовались нигде? 

Использовались, чтобы хранить информацию о местоположении компонентов (кто на каком узле). Это надо уметь всегда, чтобы отличать локальные трансферы от сетевых.

2023-08-01 22:25 UTC, osukhoroslov commented on crates/dslab-network/src/topology.rs
> +    pub fn get_path_latency(&mut self, path: Vec<LinkId>) -> f64 {
Есть вариант в случае простых моделей назначать node_id узлам силами самой Network, для чего понадобится завести отдельных счетчик. Тогда вроде бы все должно заработать.

2023-08-01 22:26 UTC, osukhoroslov commented on crates/dslab-network/src/topology.rs
> +    pub fn get_path_latency(&mut self, path: Vec<LinkId>) -> f64 {
Наконец победил clippy чтобы CI дошел и упал на тестах

2023-08-01 22:31 UTC, maksim1744 commented on crates/dslab-network/src/topology.rs
> +    pub fn get_path_latency(&mut self, path: Vec<LinkId>) -> f64 {
> > Получается раньше они добавлялись в топологию, но не использовались нигде?
> 
> Использовались, чтобы хранить информацию о местоположении компонентов (кто на каком узле). Это надо уметь всегда, чтобы отличать локальные (в пределах узла) трансферы от сетевых.

А это где? Вроде там своя хеш-таблица в network с локациями: https://github.com/osukhoroslov/dslab/blob/1c2d73b192b5be3f980e3c557e25e53549527354/crates/dslab-network/src/network.rs#L50

> Есть вариант в случае простых моделей назначать node_id узлам силами самой Network, для чего понадобится завести отдельных счетчик. Тогда вроде бы все должно заработать.

Тут да, согласен

2023-08-02 18:50 UTC, osukhoroslov commented on crates/dslab-network/src/topology.rs
> +    pub fn get_path_latency(&mut self, path: Vec<LinkId>) -> f64 {
Починил `Network.add_node`, обошелся без отдельного счетчика с помощью `self.nodes_name_map.len()`. Также доработал и упростил местами код (например, теперь роутинг сразу передается в модель, а не через init). Посмотрите все ли хорошо.

2023-08-02 19:39 UTC, maksim1744 commented on crates/dslab-network/src/topology.rs
> +    pub fn get_path_latency(&mut self, path: Vec<LinkId>) -> f64 {
Все ок

2023-08-06 09:45 UTC, osukhoroslov approved these changes

2023-08-06 09:46 UTC, merged