Add resource restrictions for tasks
osukhoroslov/dslab pull request #291
Opened 2023-07-24 15:51 UTC by maksim1744

2023-07-28 19:35 UTC, osukhoroslov requested changes

2023-07-28 19:35 UTC, osukhoroslov commented on crates/dslab-dag/src/parsers/yaml_parser.rs
> +                dag.get_task_mut(task_id).resource_restriction = match restriction {
Предлагаю сразу добавить `Dag::set_resource_restriction(&mut self, task_id: usize, restriction: ResourceRestriction)` и пользоваться им здесь

2023-07-28 19:35 UTC, osukhoroslov commented on crates/dslab-dag/src/task.rs
> +pub enum ResourceRestriction {
Надо добавить комментарии для документации

2023-07-28 19:35 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/heft.rs
> +                if !dag.get_task(task_id).is_allowed_on(resource) {
А давайте эту проверку унесем в `evaluate_assignment` -- там уже есть проверки на ресурсы и при нарушении возвращается `None`, так что несложно еще и эту добавить.

2023-07-31 15:29 UTC, maksim1744 commented on examples/dag-demo/dags/diamond.yaml
> +      resources: [0]
Да, но сейчас непонятно как. Вообще говоря граф, сеть и ресурсы могут лежать в разных файлах, и граф парсится в структуру DAG, не зная ничего про ресурсы. Только если до конца хранить имена

2023-07-31 17:28 UTC, osukhoroslov commented on examples/dag-demo/dags/diamond.yaml
> +      resources: [0]
Решили убрать возможность задавать ограничения в dag-файле, поскольку пока не надо и непонятно как это лучше поддержать.

2023-07-31 17:39 UTC, osukhoroslov approved these changes

2023-07-31 17:40 UTC, merged