[mp/mc]  model checking tests for mp-kv-replication
osukhoroslov/dslab pull request #300
Opened 2023-08-10 22:52 UTC by KiK0S

2023-08-11 16:34 UTC, KiK0S commented on crates/dslab-mp/src/mc/model_checker.rs
> +    fn run_impl(&mut self) -> McResult {
можем добавить callback в сигнатуру чтобы не плодить McStarted

2023-08-11 18:11 UTC, osukhoroslov requested changes

2023-08-11 18:11 UTC, osukhoroslov commented on examples/mp-kv-sharding/src/main.rs
> +        let node = sys.proc_node_name(&proc);
Можно просто считать что совпадает с `proc` по логике `build_system`

2023-08-11 18:11 UTC, osukhoroslov commented on examples/mp-kv-sharding/src/main.rs
> +        let proc = sys.process_names().choose(&mut rand).unwrap().clone();
```suggestion
        let proc = random_proc(&sys, &mut rand);
```

2023-08-11 18:11 UTC, osukhoroslov commented on examples/mp-kv-sharding/src/main.rs
> +    let removed = sys.process_names().choose(&mut rand).unwrap().clone();
```suggestion
    let removed = random_proc(&sys, &mut rand);
```

2023-08-11 18:11 UTC, osukhoroslov commented on examples/mp-kv-sharding/src/main.rs
> +        assert!(states.clone().is_none() || states.clone().unwrap() != res.collected_states);
Непоятно зачем нужна эта проверка (и clone тут не требуется).

2023-08-14 20:23 UTC, KiK0S commented on examples/mp-kv-sharding/src/main.rs
> +            goals::no_events(),
да

2023-08-14 20:27 UTC, KiK0S commented on examples/mp-kv-sharding/src/main.rs
> +        assert!(states.clone().is_none() || states.clone().unwrap() != res.collected_states);
кажется, осталось как легаси при переносе - а зачем там было, я не помню -- кажется, можно вытащить

2023-08-14 21:19 UTC, KiK0S commented on examples/mp-kv-sharding/src/main.rs
> +            goals::event_happened_n_times(LogEntry::is_mc_local_message_sent, 1),
Там есть такая проблема, что local_messages счетчики общие на все запуски, и тогда нужно на стороне тестов как-то поддерживать счетчик "сколько сообщений система уже обработала" -- и вариант без этого выглядит как-то приятнее

2023-08-14 21:20 UTC, KiK0S commented on examples/mp-kv-sharding/src/main.rs
> +    let removed_node = &sys.proc_node_name(removed_proc);
ага, переделал везде

2023-08-14 21:23 UTC, KiK0S commented on examples/mp-kv-sharding/src/main.rs
> +    sys.network().disconnect_node(removed_node);
да, но нам все равно в пайплайне нужно контролировать, как мы с системой работаем -- условно говоря, что первый и второй МС создавались из одинакового набора узлов. Кажется, нас спасает то, что создать систему из ниоткуда особо некуда, мы ее создаем единожды. Не знаю, умеем ли мы дешево включить защиту от дурака в апи на `ModelChecker::new`

2023-08-14 21:24 UTC, KiK0S commented on crates/dslab-mp/src/mc/model_checker.rs
> +    fn run_impl(&mut self) -> McResult {
сделал, оставил общий run_impl, чтобы было удобнее

2023-08-14 21:24 UTC, KiK0S commented on crates/dslab-mp/src/mc/predicates.rs
> +    /// Checks if trace to given state matched the predicate n times.
сделал

2023-08-14 21:24 UTC, KiK0S commented on crates/dslab-mp/src/mc/predicates.rs
> +    /// Checks that state depth does not exceed the given value.
обновил

2023-08-14 21:24 UTC, KiK0S commented on examples/mp-kv-sharding/src/main.rs
> +use dslab_mp::logger::LogEntry;
поправил

2023-08-14 21:25 UTC, KiK0S commented on crates/dslab-mp/src/mc/predicates.rs
> +    /// Checks if trace to given state matched the predicate n times.
обновил

2023-08-14 21:25 UTC, KiK0S commented on crates/dslab-mp/src/mc/state.rs
> +    pub fn current_stage_trace(&self) -> &[LogEntry] {
заменил

2023-08-14 21:26 UTC, KiK0S commented on examples/mp-kv-sharding/src/main.rs
> +    let achieved_states = check_mc_get(&mut sys, node.clone(), proc.clone(), key.clone(), None, max_steps, None)?;
Я не уверен, что получилось совсем аналогично `check_*`, но перечисленные проблемы починил предложенными способами

2023-08-14 21:26 UTC, KiK0S commented on examples/mp-kv-sharding/src/main.rs
> +        let proc = sys.process_names().choose(&mut rand).unwrap().clone();
обновил

2023-08-14 21:26 UTC, KiK0S commented on examples/mp-kv-sharding/src/main.rs
> +    let removed = sys.process_names().choose(&mut rand).unwrap().clone();
обновил

2023-08-14 21:27 UTC, KiK0S commented on examples/mp-kv-sharding/src/main.rs
> +        assert!(states.clone().is_none() || states.clone().unwrap() != res.collected_states);
убрал

2023-08-14 21:27 UTC, KiK0S commented on crates/dslab-mp/src/mc/predicates.rs
> +    pub fn state_depth_last_stage(depth: u64) -> InvariantFn {
переименовал

2023-08-14 21:39 UTC, KiK0S commented
Тесты только что прогнал на решениях - поведение выглядит +- как когда я в дипломе тестировал

2023-08-18 09:47 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/predicates.rs
> +    pub fn event_happened_n_times<F>(predicate: F, n: usize) -> GoalFn
Предлагаю уточнить что это текущий run

```suggestion
    /// Checks if current run trace has at least `n` events matching the predicate.
    pub fn event_happened_n_times_current_run<F>(predicate: F, n: usize) -> GoalFn
```

2023-08-18 09:48 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/predicates.rs
> +    pub fn event_happened_n_times<F>(predicate: F, n: usize) -> CollectFn
```suggestion
    /// Checks if current run trace has at least `n` events matching the predicate.
    pub fn event_happened_n_times_current_run<F>(predicate: F, n: usize) -> CollectFn
```

2023-08-18 11:13 UTC, osukhoroslov commented on examples/mp-kv-sharding/src/main.rs
> +        test_model_checking_normal,
Предлагаю везде сократить имена функций с `model_checking` до `mc`: 

```suggestion
        test_mc_normal,
```

2023-08-18 12:13 UTC, osukhoroslov commented on examples/mp-kv-sharding/src/main.rs
> +    let achieved_states = check_mc_get(&mut sys, &proc, &key, None::<&String>, max_steps, None)?;
```suggestion
    let achieved_states = check_mc_get(&mut sys, &proc, &key, None, max_steps, None)?;
```

2023-08-18 12:14 UTC, osukhoroslov commented on examples/mp-kv-sharding/src/main.rs
> +        None::<&String>,
```suggestion
        None,
```

2023-08-18 16:37 UTC, KiK0S commented on examples/mp-kv-sharding/src/main.rs
> +    let mut mc = ModelChecker::new::<Bfs>(sys, strategy_config);
```suggestion
    let mut mc = ModelChecker::new::<Bfs>(sys);
```

перенести strategy_config в run

2023-08-19 12:22 UTC, KiK0S commented on examples/mp-kv-sharding/src/main.rs
> +        test_model_checking_node_removed,
```suggestion
        test_mc_node_removed,
```

2023-08-20 12:17 UTC, KiK0S commented
Я в свое решение добавил бессмысленные запросы PING, которые бы летели на отказавший узел -- вот, можно видеть, что они реально дропаются (это та часть логов, которая после балансировки)

```  84 |          2 --x 0          PING {"key": "HZGYYFHD"} <-- message dropped
        85 |          1 <-- 2          GET {"key": "HZGYYFHD"}
        86 |          2 <-- 1          GET_RESP {"key": "HZGYYFHD", "value": "brzcf89g"}
        84 |          2 --x 0          PING {"key": "HZGYYFHD"} <-- message dropped
        85 |          1 <-- 2          GET {"key": "HZGYYFHD"}
        86 |          2 <-- 1          GET_RESP {"key": "HZGYYFHD", "value": "brzcf89g"}
        84 |          2 --x 0          PING {"key": "HZGYYFHD"} <-- message dropped
        85 |          1 <-- 2          GET {"key": "HZGYYFHD"}
        86 |          2 <-- 1          GET_RESP {"key": "HZGYYFHD", "value": "brzcf89g"}
        84 |          2 --x 0          PING {"key": "HZGYYFHD"} <-- message dropped
        85 |          1 <-- 2          GET {"key": "HZGYYFHD"}
        86 |          2 <-- 1          GET_RESP {"key": "HZGYYFHD", "value": "brzcf89g"}
        87 |          1 --x 0          PING {"key": "0HHHH88F"} <-- message dropped
        88 |          1 <-- 1          GET {"key": "0HHHH88F"}
        89 |          1 <-- 1          GET_RESP {"key": "0HHHH88F", "value": "uxi99bux"}
        87 |          1 --x 0          PING {"key": "0HHHH88F"} <-- message dropped
        88 |          1 <-- 1          GET {"key": "0HHHH88F"}
        89 |          1 <-- 1          GET_RESP {"key": "0HHHH88F", "value": "uxi99bux"}
        87 |          1 --x 0          PING {"key": "0HHHH88F"} <-- message dropped
        88 |          1 <-- 1          GET {"key": "0HHHH88F"}
        89 |          1 <-- 1          GET_RESP {"key": "0HHHH88F", "value": "uxi99bux"}
        87 |          1 --x 0          PING {"key": "0HHHH88F"} <-- message dropped
        88 |          1 <-- 1          GET {"key": "0HHHH88F"}
        89 |          1 <-- 1          GET_RESP {"key": "0HHHH88F", "value": "uxi99bux"}
        90 |          1 --x 0          PING {"key": "8KHRZLH8"} <-- message dropped
        91 |          2 <-- 1          GET {"key": "8KHRZLH8"}
        92 |          1 <-- 2          GET_RESP {"key": "8KHRZLH8", "value": "1t8k1z02"}
        90 |          1 --x 0          PING {"key": "8KHRZLH8"} <-- message dropped
        91 |          2 <-- 1          GET {"key": "8KHRZLH8"}
        92 |          1 <-- 2          GET_RESP {"key": "8KHRZLH8", "value": "1t8k1z02"}
        90 |          1 --x 0          PING {"key": "8KHRZLH8"} <-- message dropped
        91 |          2 <-- 1          GET {"key": "8KHRZLH8"}
        92 |          1 <-- 2          GET_RESP {"key": "8KHRZLH8", "value": "1t8k1z02"}
        90 |          1 --x 0          PING {"key": "8KHRZLH8"} <-- message dropped
        91 |          2 <-- 1          GET {"key": "8KHRZLH8"}
        92 |          1 <-- 2          GET_RESP {"key": "8KHRZLH8", "value": "1t8k1z02"}
        93 |          2 --x 0          PING {"key": "1PPFHBJQ"} <-- message dropped
        94 |          2 <-- 2          GET {"key": "1PPFHBJQ"}
        95 |          2 <-- 2          GET_RESP {"key": "1PPFHBJQ", "value": "0ub9ks8a"}
```

2023-08-20 12:32 UTC, KiK0S commented on examples/mp-kv-sharding/src/main.rs
> +    let mut mc = ModelChecker::new::<Bfs>(sys, strategy_config);
перенес и адаптировал тесты

2023-08-20 12:32 UTC, KiK0S commented on examples/mp-kv-sharding/src/main.rs
> +    let achieved_states = check_mc_get(&mut sys, &proc, &key, None::<&String>, max_steps, None)?;
Ага, сделал

2023-08-20 12:33 UTC, KiK0S commented on examples/mp-kv-sharding/src/main.rs
> +    sys.network().disconnect_node(removed_node);
закинул сеть в состояние, теперь можно обновить один раз и это более прозрачно

2023-08-20 12:35 UTC, KiK0S commented
Закинул McNetwork в State -- потому что, я так посмотрел, McNetworkState это то же самое, что McNetwork :). Теперь можно более прозрачно отключить узел и прокидывать стейты дальше.

2023-08-20 12:41 UTC, KiK0S commented
+ Обновил апи у ModelChecker-а, теперь он получает StrategyConfig для run-а, а new() требует только System.

Единственное, что не очень нравится -- что теперь там два шаблонных параметра, и получается какая-то недочастичная специализация -- я хочу, чтобы компилятор сам вывел, что делать с F из аргументов, но не могу его опустить, потому что мне нужно явно специализировать по виду стратегии.

То есть это не очень страшно, но везде приходится писать
```rust
mc.run_with_change::<_, Bfs>(strategy_config, |sys| {})
```

2023-08-23 22:28 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/model_checker.rs
> +    pub fn run_with_change<F, S>(&mut self, strategy_config: StrategyConfig, preliminary_callback: F) -> McResult
От `F` здесь и в `run_from_states_with_change` можно избавиться так:

```suggestion
    pub fn run_with_change<S>(&mut self, strategy_config: StrategyConfig, preliminary_callback: impl FnOnce(&mut McSystem)) -> McResult
```

2023-08-23 22:28 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/model_checker.rs
> +        let mut strategy = RefCell::new(S::build(strategy_config));
Безопаснее создавать стратегию с нуля на каждый run, ведь у нее есть состояние. Я бы вообще создание стратегии унес внутрь `run_impl`.

2023-08-23 22:28 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/state.rs
> +    pub network: Rc<RefCell<McNetwork>>,
Почему в состоянии хранится ссылка, а не сама сеть? Если мы просто клонируем ссылку, то изменения в сети будут попадать в ранее сохраненные состояния.

2023-08-23 22:28 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +    let result = run_mc(&mut mc, strategy_config, strategy_name.as_str());
Поменяйте лучше тип аргумента `strategy_name` на `&str`, чтобы не вызывать везде `as_str()`.

2023-08-23 22:39 UTC, KiK0S commented on crates/dslab-mp/src/mc/model_checker.rs
> +        let mut strategy = RefCell::new(S::build(strategy_config));
проблема такая, что мы стратегию создаем из конфига, конфиг хранит box-ы с предикатами, создание стратегии из конфига явно мувает все эти box-ы.
я сходу придумал решить так, как в пр - есть еще вариант везде использовать Rc и реализовать Clone
то есть, условно говоря, 1 инстанс StrategyConfig — 1 инстанс Strategy.

2023-08-23 22:48 UTC, KiK0S commented on crates/dslab-mp/src/mc/model_checker.rs
> +        let mut strategy = RefCell::new(S::build(strategy_config));
решили пробовать клонировать конфиг

2023-08-24 22:42 UTC, KiK0S commented on crates/dslab-mp/tests/test_mc.rs
> +    let result = run_mc(&mut mc, strategy_config, strategy_name.as_str());
сделал

2023-08-24 22:42 UTC, KiK0S commented on crates/dslab-mp/src/mc/state.rs
> +    pub network: Rc<RefCell<McNetwork>>,
теперь честно храним сеть

2023-08-24 22:42 UTC, KiK0S commented on crates/dslab-mp/src/mc/model_checker.rs
> +    pub fn run_with_change<F, S>(&mut self, strategy_config: StrategyConfig, preliminary_callback: F) -> McResult
Сделал так, да

2023-08-24 23:22 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +        if let Some(status) = x {
вот тут что-то странное, потому что наша старая цепочка if-else-if-else-if-... не прохлдит borrow checker. Но я не разобрался, как это пройти. Буквально, если сделать подстановку по x, оно уже не компилится

2023-08-24 23:24 UTC, KiK0S commented on crates/dslab-mp/src/mc/model_checker.rs
> +        let mut strategy = RefCell::new(S::build(strategy_config));
прокинул -- но пришлось везде делать Rc<RefCell<>> вокруг предикатов

2023-08-25 15:48 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/model_checker.rs
> +        let mut strategy = RefCell::new(S::build(strategy_config));
Предлагаю добавить в Strategy метод reset, чтобы чистить состояние, и переиспользовать один инстанс стратегии. Это позволит избежать возникших проблем, переусложнения кода и также поддержать кэширование visited.

2023-08-25 19:30 UTC, KiK0S commented on crates/dslab-mp/src/mc/strategy.rs
> +        if let Some(status) = x {
откатил этот коммит насовсем

2023-08-25 19:31 UTC, KiK0S commented on crates/dslab-mp/src/mc/model_checker.rs
> +        let mut strategy = RefCell::new(S::build(strategy_config));
так и сделал, вроде норм получилось

2023-08-25 21:33 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/strategy.rs
> +    /// Resets the state so strategy can be ran again
```suggestion
    /// Resets the internal state so that the strategy can be safely run again.
```

2023-08-25 21:49 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/system.rs
> +        self.net.replace(state.network);
Мы забыли что ссылка на сеть есть также в McNode, и она при этом останется старой. Я бы попробовал избавиться от net в McNode. Она нужна там только для обработки MessageSent, но это событие можно прокинуть из handle_process_actions в систему (аналогично TimerCancelled) и уже внутри системы его обработать сетью (в add_events). Тогда у нас сеть будет жить только в McSystem, Rc/RefCell не нужен будет и жизнь упростится.

2023-08-25 21:59 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +            run_mc!(mc, strategy_config, strategy_name)
Можно еще упростить, передавая систему в макрос и создавая ModelChecker уже внутри (кажется в тестах последний нигде не используется несколько раз):

```suggestion
            run_mc!(&sys, strategy_config, strategy_name)
```

2023-08-26 14:15 UTC, KiK0S commented on crates/dslab-mp/tests/test_mc.rs
> +            run_mc!(mc, strategy_config, strategy_name)
сделал

2023-08-26 14:15 UTC, KiK0S commented on crates/dslab-mp/src/mc/system.rs
> +        self.net.replace(state.network);
сделал

2023-08-26 15:11 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/system.rs
>      fn add_events(&mut self, events: Vec<McEvent>) {
Чтобы логика была такая же как раньше, события типа MessageReceived надо обрабатывать отдельно в начале (так мы получим от сети конечное событие, которое сразу же обработаем, и MessageDropped не будут попадать в events):

```rust
    fn add_events(&mut self, events: Vec<McEvent>) {
        for mut event in events {
            if let McEvent::MessageReceived { msg, src, dst, .. } = event {
                event = self.net.send_message(msg, src, dst);
            }
            match event {
                McEvent::MessageDropped { receive_event_id, .. } => {
                    receive_event_id.map(|id| self.events.pop(id));
                    self.trace_handler.borrow_mut().push(event.to_log_entry());
                }
                McEvent::TimerCancelled { proc, timer } => {
                    self.events.cancel_timer(proc, timer);
                }
                _ => {
                    self.events.push(event);
                }
            }
        }
    }
```

2023-08-26 19:11 UTC, KiK0S commented on crates/dslab-mp/src/mc/system.rs
>      fn add_events(&mut self, events: Vec<McEvent>) {
а, действительно, мой косяк, я как-то не увидел что там messagedropped хендлится

2023-08-26 19:23 UTC, KiK0S commented on crates/dslab-mp/src/mc/system.rs
>      fn add_events(&mut self, events: Vec<McEvent>) {
поправил

2023-08-26 19:51 UTC, osukhoroslov approved these changes

2023-08-27 15:49 UTC, AnthonyUdovichenko commented on crates/dslab-mp/tests/test_mc.rs
> +fn local_message_in_mc_trace(msg: Message) -> Vec<LogEntry> {
Название конечно немного запутывает теперь, там же и нормальное сообщение тоже добавляется. Может `local_message_processed_trace`?

2023-08-27 15:57 UTC, AnthonyUdovichenko approved these changes

2023-08-27 19:28 UTC, KiK0S commented on crates/dslab-mp/tests/test_mc.rs
> +fn local_message_in_mc_trace(msg: Message) -> Vec<LogEntry> {
да, хороший вариант, обновил

2023-08-27 19:33 UTC, merged