[mp/mc] Remove directives where possible
osukhoroslov/dslab pull request #301
Opened 2023-08-13 18:06 UTC by AnthonyUdovichenko

2023-08-14 10:45 UTC, KiK0S approved these changes
LGTM

2023-08-18 17:05 UTC, KiK0S requested changes
обсудили, что хочется совсем избавиться от McDropped - но тогда нужно менять инициализацию, и переписывать наше использование mc на run_with_change

2023-08-25 15:14 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/system.rs
> +    fn add_events(&mut self, events: Vec<McEvent>) {
Перенесите ниже к приватным функциям, чтобы сначала шли публичные

2023-08-25 15:29 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +}
Предлагаю назвать так и перенести вверх:

```suggestion
pub enum SystemInitMethod {
    Simulation,
    PreliminaryCallback,
}
```

2023-08-25 15:30 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +fn two_states_one_message_ok(#[case] strategy_name: String, conf_type: McSystemConfiguringType) {
```suggestion
fn two_states_one_message_ok(#[case] strategy_name: String, init_method: SystemInitMethod) {
```

2023-08-25 15:32 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +            sys.network().set_drop_rate(0.5);
В этом тесте если хотите промоделировать оба исхода (сообщение дойдет или потеряно), то метод инициализации системы через симуляцию не подходит (сообщения только дойдет), если мы будем переность события из симуляции as is

2023-08-25 15:38 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
> +            let mut mc = build_mc_from_config(&sys, strategy_name.clone(), config);
Кажется система должна создавать здесь и здесь же отправляться соощение, а не выше

2023-08-25 15:42 UTC, osukhoroslov commented on crates/dslab-mp/tests/test_mc.rs
>      let mut sys: System = build_postponed_delivery_system();
Сейчас эта система используется только в режиме инициализации через симуляцию, предлагаю её создание и отправку начального сообщения перенести внутрь ветки `McSystemConfiguringType::DefaultSimulation` как в других тестах. На втором этапе можно заново создать систему аналогично тому как это делается для  `McSystemConfiguringType::McPreliminaryCallback`

2023-08-25 18:19 UTC, KiK0S approved these changes

2023-08-25 18:20 UTC, merged