[mp/mc] model checking tests for mp-kv-replication
osukhoroslov/dslab pull request #323
Opened 2023-10-19 21:10 UTC by KiK0S

2023-10-30 20:36 UTC, osukhoroslov requested changes

2023-10-30 20:36 UTC, osukhoroslov commented on examples/mp-kv-replication/src/main.rs
> +    let start_states = run_mc(
Лучше назвать просто `states`

2023-10-30 20:36 UTC, osukhoroslov commented on examples/mp-kv-replication/src/main.rs
> +    let start_states = run_mc(
Дальше эти состояния никак не используются. Если так, то зачем вообще делать collect? Для общности?

2023-10-30 20:36 UTC, osukhoroslov commented on examples/mp-kv-replication/src/main.rs
> +    // stage 3: let data propagate to all replicas
Зачем нужен этап 3? В обычном тесте мы не ждем распространения и сразу переходим к этапу 4, где запрос на чтение с кворумом 2.

2023-11-02 20:58 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +            if let Some([part1, part2]) = &partition {
просто так в функцию нельзя, потому что, как я понял, нельзя создать lvalue-лямбду с параметром приватного типа

2023-11-02 20:59 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +    let start_states = run_mc(
для общности + проверка, что что-то происходит, полезная

2023-11-02 22:40 UTC, KiK0S commented on crates/dslab-mp/src/mc/network.rs
> +                self.disable_link(node1, node2);
ага, стал отключать в обе стороны

2023-11-02 22:40 UTC, KiK0S commented on crates/dslab-mp/src/mc/system.rs
> +    }
done

2023-11-02 22:40 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +fn mc_get_invariant<S>(node: S, proc: S, key: String, expected: Option<String>) -> InvariantFn
done

2023-11-02 22:41 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +    config.proc_count = 4;
вообще на 6 так же по скорости, потому что там же все равно кворум из трех. Поставил чтобы дефолтные 6 были

2023-11-02 22:41 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +use dslab_mp::mc::events::EventOrderingMode;
done

2023-11-02 22:41 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +use dslab_mp::mc::events::EventOrderingMode;
done

2023-11-02 22:42 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +    let key = "ZXSA0H2K".to_string();
вроде нет, использовал, чтобы вывод был консистентный между запусками, но и так норм

2023-11-02 22:42 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +    procs.sort();
вроде нет, использовал, чтобы вывод был консистентный

2023-11-02 22:42 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +    procs.sort();
убрал сортировку

2023-11-02 22:43 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +    let value = "9ps2p1ua".to_string();
аналогично ключу, теперь не рандомно.

2023-11-02 22:43 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +
теперь вроде норм

2023-11-02 22:43 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +    let first_stage_strategy = mc_query_strategy(&procs[0], &procs[0], McQueryPlaceholder::GetQuery(key.clone(), None));
убрал

2023-11-02 22:44 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +            if let Some([part1, part2]) = &partition {
повесил макрос, вроде как выглядит нормально, хотя без контекста сложно понять, почему там именно макрос, а не отдельная функция

2023-11-02 22:44 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +    let start_states = run_mc(
название поменял

2023-11-02 22:44 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +    // stage 3: let data propagate to all replicas
можно убрать, да, убрал

2023-11-02 22:44 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +    let first_stage_strategy = mc_query_strategy(&procs[0], &procs[0], McQueryPlaceholder::GetQuery(key.clone(), None));
переименовал

2023-11-03 13:58 UTC, osukhoroslov commented on examples/mp-kv-replication/src/main.rs
> +    mc = ModelChecker::new(&sys);
Нужно ли создавать заново ModelChecker? Или можно убрать?

2023-11-03 13:58 UTC, osukhoroslov commented on examples/mp-kv-replication/src/main.rs
> +        return Err("stage 1 has no positive outcomes".to_owned());
Текст ошибки может быть не понятен студенту (что такое `positive outcome`). Надо заменить на что-то более понятное. Например: `stage 1 - GET response is not received`.

2023-11-03 13:58 UTC, osukhoroslov commented on examples/mp-kv-replication/src/main.rs
> +    mc = ModelChecker::new(&sys);
Нужно ли создавать заново ModelChecker? Или можно убрать?

2023-11-03 13:58 UTC, osukhoroslov commented on examples/mp-kv-replication/src/main.rs
> +    let res = mc.run_with_change::<Bfs>(strategy_config, |sys| {
Кажется здесь тоже можно заменить на использование `run_mc` (без разделения сети), если сделать опциональным network reset там (передавать как bool флаг)

2023-11-03 13:58 UTC, osukhoroslov commented on examples/mp-kv-replication/src/main.rs
> +    let strategy_config = StrategyConfig::default()
Почему бы не переиспользовать здесь `mc_query_strategy`?

2023-11-03 13:58 UTC, osukhoroslov commented on examples/mp-kv-replication/src/main.rs
> +            if let Some([part1, part2]) = &partition {
Предлагаю сделать `McSystem` публичной, она же и так фигурирует как часть API, т.к. её могут вызывать колбеки

2023-11-03 16:03 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +    mc = ModelChecker::new(&sys);
нужно, иначе подтягиваются события из `stage1_` через систему под запуск без `stage1_states`. А с ними долго работает, при этом запросы независимые, поэтому хочется чтобы stage1 прогнался, а потом мы забыли про него

2023-11-03 16:06 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +    mc = ModelChecker::new(&sys);
https://github.com/osukhoroslov/dslab/pull/323#discussion_r1381925134

2023-11-03 16:23 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/predicates.rs
> +    /// Collects states where the number of events matching the predicate is more than the limit.
```suggestion

    /// Collects states where the number of events matching the predicate is more than the limit.
```

2023-11-03 16:27 UTC, osukhoroslov commented on crates/dslab-mp/src/mc/predicates.rs
> +    fn count_events_in_trace<F>(predicate: F, state: &McState) -> usize
Эта функция уже есть в prunes, предлагаю её на дублировать в каждом подмодуле, а разместить выше и переиспользовать.

2023-11-03 16:49 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +            if let Some([part1, part2]) = &partition {
done

2023-11-03 16:50 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +            if let Some([part1, part2]) = &partition {
немного смущает, что network торчит наружу, он нужен для тестов

2023-11-03 16:50 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +        return Err("stage 1 has no positive outcomes".to_owned());
поправил, вроде стало лучше

2023-11-03 16:50 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +    let res = mc.run_with_change::<Bfs>(strategy_config, |sys| {
сделал McNetworkPlaceholder и вообще покрасивее стало

2023-11-03 16:51 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +    let strategy_config = StrategyConfig::default()
вроде можно, да - но что-то все равно много состояний коллектится, разбираюсь

2023-11-04 14:32 UTC, KiK0S commented on examples/mp-kv-replication/src/main.rs
> +    let strategy_config = StrategyConfig::default()
разобрался

2023-11-04 14:36 UTC, KiK0S commented on crates/dslab-mp/src/mc/predicates.rs
> +    fn count_events_in_trace<F>(predicate: F, state: &McState) -> usize
ага, сделал общей

2023-11-06 15:46 UTC, osukhoroslov commented on examples/mp-kv-replication/src/main.rs
> +            if let Some([part1, part2]) = &partition {
Сделал McNetwork публичной

2023-11-06 15:47 UTC, osukhoroslov approved these changes

2023-11-06 16:01 UTC, merged