Async unsafe fix
osukhoroslov/dslab pull request #340
Opened 2024-05-07 06:57 UTC by nogokama

2024-06-01 12:15 UTC, osukhoroslov requested changes

2024-06-01 12:15 UTC, osukhoroslov commented on examples/ping-pong-async/src/process.rs
> +use dslab_core::{Event, Id, SimulationContext};
```suggestion
use dslab_core::{Event, Id, SimulationContext, StaticEventHandler};
```

2024-06-01 16:31 UTC, nogokama commented on crates/dslab-core/Cargo.toml
> -rust-version = "1.62"
убрал версию, поднимал из-за clippy warning-ов

2024-06-01 16:33 UTC, nogokama commented on crates/dslab-core/src/simulation.rs
> +    enum EventHandlerComponent {
done

2024-06-01 17:11 UTC, nogokama commented on crates/dslab-core/src/context.rs
> +        ///             // Compile fails because reference to self is used in the async task,
done

2024-06-03 09:30 UTC, osukhoroslov commented on crates/dslab-core/src/simulation.rs
> +            id
```suggestion
            "Handler for component {} with Id {} already exists",
            name.as_ref(), id
```

2024-06-03 09:30 UTC, osukhoroslov commented on crates/dslab-core/src/simulation.rs
> +                id
```suggestion
                "Handler for component {} with Id {} already exists",
                name.as_ref(), id
```

2024-06-03 11:04 UTC, osukhoroslov approved these changes

2024-06-03 11:05 UTC, merged