Async core: fix promise store bug + add tests
osukhoroslov/dslab pull request #344
Opened 2024-06-04 13:55 UTC by nogokama

2024-06-04 20:46 UTC, osukhoroslov requested changes

2024-06-04 20:46 UTC, osukhoroslov commented on crates/dslab-core/src/async_mode/promise_store.rs
> +                // check that promise with such key does not exists yet
```suggestion
                // check that promise with such key and some source doesn't exist yet
```

2024-06-04 20:46 UTC, osukhoroslov commented on crates/dslab-core/src/async_mode/promise_store.rs
> +            return Err(format!("Event promise for {:?} already exists", key));
```suggestion
            return Err(format!("Event promise for key {:?} already exists", key));
```

2024-06-04 20:46 UTC, osukhoroslov commented on crates/dslab-core/src/async_mode/promise_store.rs
> +                        "Event promise for {:?} with source {} already exists",
```suggestion
                        "Event promise for key {:?} with source {} already exists",
```

2024-06-04 20:46 UTC, osukhoroslov commented on crates/dslab-core/src/async_mode/promise_store.rs
> +                        "Event promise for {:?} with source {} already exists",
```suggestion
                        "Event promise for key {:?} with source {} already exists",
```

2024-06-04 20:46 UTC, osukhoroslov commented on crates/dslab-core/src/state.rs
> +                // return future back to the caller in order to release BorrowMut of the
А может сразу здесь паниковать вместо возврата Result, если все-равно паника далее будет?

2024-06-04 20:46 UTC, osukhoroslov commented on crates/dslab-core/tests/async_tests/conflict_waiting.rs
> +use serde::Serialize;
```suggestion
use serde::Serialize;

use dslab_core::{async_mode::EventKey, Simulation, SimulationContext};
```

2024-06-05 08:25 UTC, nogokama commented on crates/dslab-core/src/state.rs
> +                // return future back to the caller in order to release BorrowMut of the
Если паниковать сразу, то future разрушится и возьмет borrow_mut() на SimulationState в деструкторе и будет двойная паника, поэтому я решил сначала достать future наружу, чтобы отпустить borrow_mut() на SimulationState и паниковать уже из контекста, тогда future нормально разрушится. 

Как альтернатива можно было бы конечно вообще не создавать future, если мы не смогли установить promise, но это будет выглядеть более некрасиво по коду, и смысла в этом особо нет, т.к. если не смогли установить promise -- все равно сразу паника и программа останавливается.

2024-06-05 20:44 UTC, osukhoroslov approved these changes

2024-06-05 20:44 UTC, merged