Network topology model
osukhoroslov/dslab pull request #75
Opened 2022-05-23 11:38 UTC by ZeDRoman

2022-05-24 00:26 UTC, maksim1744 commented on crates/network/src/topology_model.rs
> +            let mut min_bandwidth_index = 0;
Несколько раз встретились такие циклы, где вручную минимум ищется, кажется проще через `let(bandwidth, index) = transfers_bandwidth.iter().enumerate().min_by(...)`

2022-05-24 00:26 UTC, maksim1744 commented on crates/network/src/topology_resolver.rs
> +    latency: HashMap<String, HashMap<String, f64>>,
В ядре симуляции специально избавлялись от строк в пользу Id ради ускорения, возможно тут также стоит сделать

2022-05-24 00:26 UTC, maksim1744 commented on crates/network/src/topology_resolver.rs
> +            for next_node in links_map.keys() {
Тоже через min_by можно

2022-06-06 16:56 UTC, osukhoroslov commented on examples/network_topology/src/main.rs
> +    let topology_network = rc!(refcell!(Network::new(
Вместо того, чтобы сразу сеть помещать в rc/refcell предлагаю сначала задать топологию:

```
    let network_model_rc = rc!(refcell!(TopologyNetwork::new()));
    let mut network = Network::new(network_model_rc.clone(), sim.create_context("net"));
    // network nodes
    network.add_node("sender_1", 100.0, 0.0);
    network.add_node("sender_2", 100.0, 0.0);
    network.add_node("switch_1", 100.0, 0.0);
    network.add_node("switch_2", 100.0, 0.0);
    network.add_node("receiver_1", 100.0, 0.0);
    network.add_node("receiver_2", 100.0, 0.0);
    network.add_node("sender_3", 100.0, 0.0);
    // network links
    network.add_link("sender_1", "switch_1", 1.0, 100.0);
    network.add_link("sender_2", "switch_1", 1.0, 90.0);
    network.add_link("switch_1", "switch_2", 1.0, 50.0);
    network.add_link("switch_2", "receiver_1", 1.0, 90.0);
    network.add_link("switch_2", "receiver_2", 1.0, 10.0);
    // init topology
    network.init_topology();

    let network_rc = rc!(refcell!(network));
```
Получается менее громоздко, и также вся топология (включая линки) задается сначала, до размещения процессов по нодам.

2022-06-06 16:56 UTC, osukhoroslov commented on examples/network_topology/src/main.rs
> +    topology_network_model
Выглядит неудобно. Раз модели нужна топология, то почему бы не передавать ей топологию сразу в конструкторе Network, куда передается модель. Можно добавить метод `set_topology` в трейт NetworkModel и дергать его в конструкторе Network. Модели, которым топология не нужна будут просто её игнорировать.

2022-06-06 16:56 UTC, osukhoroslov commented on examples/network_topology/src/main.rs
> +pub struct DataTransferRequester {
Предлагаю назвать `DataSender` по аналогии с `DataReceiver`

2022-06-06 16:56 UTC, osukhoroslov commented on crates/network/src/topology.rs
> +        match self.component_nodes.get(&id) {
Почему сделано клонирование вместо старой реализации?

```
    pub fn get_location(&self, id: Id) -> Option<&String> {
        self.component_nodes.get(&id)
    }
```

2022-06-06 16:56 UTC, osukhoroslov commented on crates/network/src/topology.rs
> +    pub fn get_nodes_amount(&self) -> usize {
```suggestion
    pub fn get_nodes_count(&self) -> usize {
```

2022-06-06 16:56 UTC, osukhoroslov commented on crates/network/src/topology.rs
> +    pub fn get_link_connection(&self, node_1: &str, node_2: &str) -> Option<&Link> {
```suggestion
    pub fn get_link_between(&self, src: &str, dest: &str) -> Option<&Link> {
```

2022-06-06 16:56 UTC, osukhoroslov commented on crates/network/src/topology.rs
> +    pub fn get_path(&self, node_1: &str, node_2: &str) -> Option<Vec<LinkID>> {
```suggestion
    pub fn get_path(&self, src: &str, dest: &str) -> Option<Vec<LinkID>> {
```

2022-06-06 16:56 UTC, osukhoroslov commented on crates/network/src/topology.rs
> +    pub fn add_link(&mut self, node_1: &str, node_2: &str, latency: f64, bandwidth: f64) {
```suggestion
    pub fn add_link(&mut self, src: &str, dest: &str, latency: f64, bandwidth: f64) {
```

2022-06-20 12:06 UTC, ZeDRoman commented on crates/network/src/topology_model.rs
> +            let mut min_bandwidth_index = 0;
Fixed

2022-06-20 12:06 UTC, ZeDRoman commented on crates/network/src/topology_resolver.rs
> +            for next_node in links_map.keys() {
Слишком громоздкая получается лямбда

2022-06-20 12:06 UTC, ZeDRoman commented on examples/network_topology/src/main.rs
> +    topology_network_model
Fixed

2022-06-20 12:07 UTC, ZeDRoman commented on crates/network/src/topology.rs
> +        match self.component_nodes.get(&id) {
Нельзя наружу передавать данные из Borrowed
сделал сейчас возврат с помощью Ref

2022-06-20 12:07 UTC, ZeDRoman commented on crates/network/src/topology.rs
> +    pub fn get_link_connection(&self, node_1: &str, node_2: &str) -> Option<&Link> {
Fixed

2022-06-20 12:07 UTC, ZeDRoman commented on crates/network/src/topology.rs
> +    pub fn get_path(&self, node_1: &str, node_2: &str) -> Option<Vec<LinkID>> {
Fixed

2022-06-20 12:07 UTC, ZeDRoman commented on crates/network/src/topology.rs
> +    pub fn add_link(&mut self, node_1: &str, node_2: &str, latency: f64, bandwidth: f64) {
Fixed

2022-06-24 18:51 UTC, osukhoroslov requested changes

2022-06-24 18:51 UTC, osukhoroslov commented on crates/dslab-network/src/topology.rs
> +                for node in self.nodes.keys() {
Почему вместо цикла по узлам, не построить пути между всеми парами узлов за один вызов?

2022-06-24 18:51 UTC, osukhoroslov commented on crates/dslab-network/src/topology_model.rs
> +    fn check_path_exist(&self, src: Id, dst: Id) -> bool {
```suggestion
    fn check_path_exists(&self, src: Id, dst: Id) -> bool {
```

2022-06-24 18:51 UTC, osukhoroslov commented on crates/dslab-network/src/topology_model.rs
> +            if bandwidth == 0.0 {
Перепишите как поиск минимума (см. замечание Максима)

2022-06-24 18:51 UTC, osukhoroslov commented on crates/dslab-network/src/topology_model.rs
> +        match self.next_event {
```
        if let Some(event_id) = self.next_event {
            ctx.cancel_event(event_id)
        };
```

2022-06-24 18:51 UTC, osukhoroslov commented on crates/dslab-network/src/topology_model.rs
> +        match self.next_event_index {
```
        if let Some(event_idx) = self.next_event_index {
            let transfer = self.current_transfers.get(event_idx).unwrap();
            let time = transfer.size_left / transfer.throughput;
            self.next_event = Some(ctx.emit_self(
                DataReceive {
                    data: transfer.data.clone(),
                },
                time,
            ));
        };
```

2022-06-24 18:51 UTC, osukhoroslov commented on crates/dslab-network/src/topology_model.rs
> +    pub connections_amount: usize,
```suggestion
    pub transfers_count: usize,
```

2022-06-24 18:51 UTC, osukhoroslov commented on crates/dslab-network/src/topology_model.rs
> +                None => panic!("Transfer with no path"),
Паниковать лучше выше где заполняется `paths`. Заодно можно избавиться от хранения Option в `paths`, что упростит работу с ней дальше.

2022-06-24 18:51 UTC, osukhoroslov commented on crates/dslab-network/src/topology_model.rs
> +                let mut transfer_bandwidth = current_link_usage.get(&first_link_id).unwrap().left_bandwidth
Тут тоже можно переписать на min_by

2022-06-24 18:51 UTC, osukhoroslov commented on crates/dslab-network/src/topology_model.rs
> +        self.next_event_index = Some(next_event_index);
Кажется это поле не нужно хранить внутри `TopologyNetwork`, а достаточно просто возвращать это значение в этом методе.

2022-07-24 09:31 UTC, ZeDRoman commented on crates/dslab-network/src/topology_model.rs
> +        self.next_event_index = Some(next_event_index);
оно нужно, чтобы при получении данных убирать трансфер из списка

2022-07-25 17:40 UTC, osukhoroslov requested changes

2022-07-25 17:40 UTC, osukhoroslov commented on crates/network/src/topology_resolver.rs
> +    latency: HashMap<String, HashMap<String, f64>>,
Теперь NodeId = usize

2022-07-25 17:40 UTC, osukhoroslov commented on crates/dslab-network/src/topology_resolver.rs
> +    pub fn resolve_with_floyd_warshall(
Функцию можно и нужно сделать приватной, убрав pub. Проверьте остальной код и поправьте в аналогичных случаях. Приватные функции лучше размещать после публичных.

2022-07-25 18:17 UTC, maksim1744 commented on crates/dslab-network/src/topology_model.rs
> +                    .partial_cmp(&(y.1.size_left / y.1.throughput))
тоже `total_cmp`

2022-07-25 18:17 UTC, maksim1744 commented on crates/dslab-network/src/topology_resolver.rs
> +    parent_path: HashMap<NodeId, HashMap<NodeId, NodeId>>,
Если NodeId от 0 до n-1, то можно использовать двумерный массив, должно быть немного быстрее. В других аналогичных местах, возможно, тоже

2022-07-25 18:34 UTC, osukhoroslov commented on crates/dslab-network/src/topology.rs
>      pub fn get_nodes(&self) -> Vec<String> {
Хочется, чтобы порядок узлов был детерминированным и соответствовал порядку их создания. Сейчас это не гарантируется. Добиться желаемого можно заменив `HashMap` на `IndexMap` [отсюда](https://crates.io/crates/indexmap/) (BTreeMap здесь не подходит).

2022-07-25 19:00 UTC, osukhoroslov commented
Попробовал перенести `master-workers` на `TopologyNetwork` и задать топологию звезда так:

```
    let mut topology = Topology::new();
    // network nodes
    for i in 0..host_count {
        topology.add_node(&format!("host{}", i), local_bandwidth as f64, local_latency);
    }
    topology.add_node("switch", local_bandwidth as f64, local_latency);
    // network links
    for i in 0..host_count {
        topology.add_link(&format!("host{}", i), "switch", network_latency, network_bandwidth as f64);
    }
    // init topology
    topology.init();

    let topology_rc = rc!(refcell!(topology));
    let network_model = rc!(refcell!(TopologyNetwork::new(topology_rc.clone())));
    let network =  rc!(refcell!(Network::new_with_topology(network_model, topology_rc.clone(), sim.create_context("net"))));
    sim.add_handler("net", network.clone());
    let hosts = network.borrow().get_nodes();
```

С новой моделью время сильно выросло в сравнении с SharedBandwidthNetwork:
- 100 hosts, 10000 tasks: было 0.13s, стало 3.64s
- 1000 hosts, 10000 tasks: было 0.16s, стало 57.37s

С Дейкстрой результаты примерно такие же.

Надо понять, где тратится время, и попробовать заоптимизировать.

2022-07-27 19:54 UTC, osukhoroslov commented on crates/dslab-network/src/topology.rs
> +            self.latency_cache.insert((*dst, *src), bandwidth);
Здесь должен быть bandwidth_cache

2022-07-27 19:58 UTC, osukhoroslov commented on crates/dslab-network/src/topology.rs
> +        if let Some(path) = self.path_cache.get(&(*dst, *src)) {
Вариант со вставкой в кэш обоих пар и поиском только по (src, dst), как сделано для latency и bandwidth кэшей, выглядит компактнее. Предлагаю здесь тоже так сделать, если нет каких-то других соображений.

2022-07-27 20:07 UTC, osukhoroslov commented on crates/dslab-network/src/topology_model.rs
> +            .min_by(|x, y| (x.1.size_left / x.1.throughput).total_cmp(&(y.1.size_left / y.1.throughput)))
Слишком длинная строка, странно что rustfmt её пропустил

2022-08-01 15:45 UTC, maksim1744 approved these changes
Осталась еще оптимизация из второго абзаца первого комментария, но не факт что она сильно ускорит в общем случае, можно пока на будущее оставить.

2022-08-01 15:45 UTC, maksim1744 approved these changes
Осталась еще оптимизация из второго абзаца первого комментария, но не факт что она сильно ускорит в общем случае, можно пока на будущее оставить.

2022-08-07 06:13 UTC, ZeDRoman commented on crates/dslab-network/src/topology.rs
> +        if let Some(path) = self.path_cache.get(&(*dst, *src)) {
Не хочется хранить две копии массива в структуре.

2022-08-15 09:32 UTC, ZeDRoman commented on crates/dslab-network/src/topology_model.rs
> +            .min_by(|x, y| (x.1.size_left / x.1.throughput).total_cmp(&(y.1.size_left / y.1.throughput)))
он не хочет никак укорачивать её.
мои попытки он возвращает обратно

2022-08-15 13:36 UTC, osukhoroslov approved these changes

2022-08-15 15:16 UTC, merged