[serverless] OpenDC experiment
osukhoroslov/dslab pull request #85
Opened 2022-06-19 09:57 UTC by SYury

2022-06-22 20:26 UTC, osukhoroslov requested changes

2022-06-22 20:26 UTC, osukhoroslov commented on examples-other/opendc/faas/readme.md
> +2. Patch it: replace [this line](https://github.com/atlarge-research/opendc/blob/prod/opendc-serverless/opendc-serverless-service/src/main/kotlin/org/opendc/serverless/service/FunctionObject.kt#L132)
Сделай ссылку прямо на нужную версию, а то потом может сломаться номер строки

2022-06-22 20:26 UTC, osukhoroslov commented on examples-other/opendc/faas/ServerlessExperiment.kt
> +// Slightly modified https://github.com/atlarge-research/opendc/blob/prod/opendc-experiments/opendc-experiments-serverless20/src/main/kotlin/org/opendc/experiments/serverless/ServerlessExperiment.kt
Сделай ссылку на конкретную версию файла

2022-06-22 20:26 UTC, osukhoroslov commented on examples/faas-opendc-benchmark/src/main.rs
> +        for row in app.iter() {
`sample` вместо `row` понятнее

2022-06-22 20:26 UTC, osukhoroslov commented on crates/dslab-faas-extra/src/opendc_trace.rs
> +    pub cpu: usize,
В оргинале были "provisionedCpu, provisionedMemory, cpuUsage, memoryUsage", а здесь что чему соответствует?

2022-06-22 20:26 UTC, osukhoroslov commented on examples-other/opendc/faas/generate.py
> +# Some function traces can be found here: https://github.com/JOUNAIDSoufiane/OpenDC-Serverless/tree/master/experiment-analysis/resources/lambda/traces
Перенеси ссылку на отдельную строку

2022-06-25 17:56 UTC, SYury commented on examples/faas-opendc-benchmark/src/main.rs
> +    let mut serverless = ServerlessSimulation::new(sim, None, policy, None);
Заменил

2022-06-25 17:56 UTC, SYury commented on examples-other/opendc/faas/readme.md
> +2. Patch it: replace [this line](https://github.com/atlarge-research/opendc/blob/prod/opendc-serverless/opendc-serverless-service/src/main/kotlin/org/opendc/serverless/service/FunctionObject.kt#L132)
Сделал

2022-06-25 17:56 UTC, SYury commented on examples-other/opendc/faas/ServerlessExperiment.kt
> +// Slightly modified https://github.com/atlarge-research/opendc/blob/prod/opendc-experiments/opendc-experiments-serverless20/src/main/kotlin/org/opendc/experiments/serverless/ServerlessExperiment.kt
Сделал

2022-06-25 17:56 UTC, SYury commented on examples/faas-opendc-benchmark/src/main.rs
> +        for row in app.iter() {
Заменил

2022-06-25 17:56 UTC, SYury commented on crates/dslab-faas-extra/src/opendc_trace.rs
> +pub struct FunctionRow {
Заменил

2022-06-25 17:57 UTC, SYury commented on crates/dslab-faas-extra/src/opendc_trace.rs
> +    pub cpu: usize,
cpu/mem это provisioned, allocCpu/allocMem это usage

2022-06-25 17:57 UTC, SYury commented on examples-other/opendc/faas/generate.py
> +# Some function traces can be found here: https://github.com/JOUNAIDSoufiane/OpenDC-Serverless/tree/master/experiment-analysis/resources/lambda/traces
Перенес

2022-06-25 17:57 UTC, SYury commented on examples-other/opendc/faas/readme.md
> +4. Generate trace with `generate.py`.
Добавил

2022-06-25 17:58 UTC, SYury commented on examples-other/opendc/faas/run.py
> +    parser.add_argument('-opendc-harness', type=str, help='path to opendc-harness script')
Он в OpenDC 2.0 есть, в мастере его убрали

2022-06-28 19:56 UTC, osukhoroslov commented on examples-other/opendc/faas/readme.md
> +4. Generate trace with `generate.py`.
Так, а как ты эти два файла подаешь generate.py? Он вроде из stdin читает.

2022-06-28 20:01 UTC, SYury commented on examples-other/opendc/faas/readme.md
> +4. Generate trace with `generate.py`.
Каждый на stdin по очереди, получаю два новых трейса.

2022-06-28 20:01 UTC, SYury commented on examples-other/opendc/faas/run.py
> +    parser.add_argument('-opendc-harness', type=str, help='path to opendc-harness script')
Да, должен появиться.

2022-06-28 20:07 UTC, osukhoroslov commented on crates/dslab-faas-extra/src/opendc_trace.rs
> +    pub cpu: usize,
Тогда путаница получается. По смыслу provisioned это то же что выделенные (allocated) ресурсы, а usage это про реальное потребление. Если так, то лучше назвать `cpu_provisioned` и `cpu_used`.

2022-06-28 20:10 UTC, osukhoroslov commented on examples-other/opendc/faas/readme.md
> +4. Generate trace with `generate.py`.
Ясно. В статье 40000 соответствует двум generate по 20000?

2022-06-29 05:41 UTC, SYury commented on examples-other/opendc/faas/readme.md
> +4. Generate trace with `generate.py`.
Да

2022-07-01 15:24 UTC, SYury commented on crates/dslab-faas-extra/src/opendc_trace.rs
> +    pub cpu: usize,
Переименовал

2022-07-01 18:33 UTC, osukhoroslov commented on crates/dslab-faas-extra/src/opendc_trace.rs
> +    pub cpu: usize,
Еще мне не понятно почему в некоторых трейсах (например, timer-noconcurrency.csv) Avg mem usage per Invocation больше  Provisioned Memory. Есть идеи?

И насчёт cpu_provisioned. Ты его не используешь потому что в этой ветке нет модели разделения CPU?

2022-07-01 19:37 UTC, SYury commented on crates/dslab-faas-extra/src/opendc_trace.rs
> +    pub cpu: usize,
Я думаю, что дело тут в том, что в allocated входит ещё оверхед на контейнер и рантайм языка. CPU не использую из-за того, что в мастер не вошло, да.

2022-07-01 20:32 UTC, osukhoroslov commented on examples/faas-opendc-benchmark/src/main.rs
> +    println!("processed {} invocations", stats.invocations);
Добавь еще замер времени симуляции, число событий и событий/секунду (см. ping-pong например)

2022-07-03 17:06 UTC, SYury commented on examples/faas-opendc-benchmark/src/main.rs
> +    println!("processed {} invocations", stats.invocations);
Добавил

2022-07-04 07:27 UTC, osukhoroslov approved these changes

2022-07-04 10:57 UTC, merged