[serverless] CPU contention + scheduling experiment
osukhoroslov/dslab pull request #87
Opened 2022-06-20 14:57 UTC by SYury

* Добавил конкуренцию за процессор (с возможностью отключения).
* Добавил реализации нескольких планировщиков и эксперимент с ними.
* Сделал небольшие улучшения: перенес чтение трейса в extra, сделал передачу параметров через конфиг, ...

2022-08-06 10:45 UTC, osukhoroslov commented on crates/dslab-faas/src/invoker.rs
> +        cm.inc_active_invocations();
Не нравится, что inc и dec выполняются в разных компонентах. Может перенести inc в Host?

2022-08-06 10:53 UTC, osukhoroslov commented on crates/dslab-faas/src/stats.rs
>              if let Some(old) = self.wasted_resource_time.get_mut(&req.id) {
Здесь и в аналогичных местах можно упростить используя `or_insert` или `or_default`:

```
self.wasted_resource_time.entry(req.id).or_default().add(delta);
```

2022-08-06 13:15 UTC, osukhoroslov commented on crates/dslab-faas/src/cpu.rs
> +    ctx: Rc<RefCell<SimulationContext>>,
SimulationContext предлагается всегда указывать последним полем

2022-08-06 13:20 UTC, osukhoroslov commented on crates/dslab-faas/src/host.rs
> +            .progress_computer
Предлагаю скрыть `progress_computer` от клиентов CPU, чтобы не загромождать код, и сделать методы обертки

2022-08-06 13:47 UTC, osukhoroslov commented on crates/dslab-faas/src/cpu.rs
> +            .partial_cmp(&other.finish)
С Rust 1.62 можно пользоваться https://doc.rust-lang.org/std/primitive.f64.html#method.total_cmp , в остальных местах уже перешли на недо

2022-08-06 13:57 UTC, osukhoroslov commented on crates/dslab-faas/src/cpu.rs
> +    work_map: HashMap<u64, WorkItem>,
Фактически не используется, элемент добавляется и в конце удаляется, чтений нет

2022-08-06 18:17 UTC, osukhoroslov commented
Попробовал восстановить логику вычислений в ProgressComputer. Вот что у меня получилось.

Для начала простая и понятная модель с объемами задач и производительностью ресурсов.
Производительность ядра: `core_flops`
Условный объем вычислений на вызов: `inv_work = duration * share * core_flops`
Реальная производительность ядра при contention: `core_real_flops = core_flops / max(1, load/cores)`
Начальное время выполнения вызова: `inv_time = inv_work / (core_real_flops * share) = duration * max(1, load/cores)`
Оставшийся объем вычислений в момент t: `inv_work(t) = inv_work(prev) - (t - prev) * core_real_flops`
Оставшееся время выполнения вызова: `inv_time_left = inv_work(t) / (core_real_flops * share)`

Если вызовы в `work_tree` сортировать по объему работы на ядро (`duration * core_flops`), то можно отслеживать ближайшее событие и считать его время как описано выше. Но надо будет при каждом событии обновлять оставшиеся объемы у всех вызовов.

Как я понял, вместо этого предлагается хранить суммарную работу CPU, которая должна быть проделана в момент завершения вызова.

Работа CPU от начала до момента завершения вызова: `inv_cpu_work = duration * core_flops * cores`
Суммарная работа CPU: `total_cpu_work(t) = интеграл core_real_flops * cores от 0 до t`
Cуммарная работа CPU в момент завершения вызова: `inv_total_cpu_work = total_cpu_work(inv_start) + inv_cpu_work`
Оставшийся объем работы в момент t: `inv_cpu_work(t) = inv_total_cpu_work - total_cpu_work(t)`
Оставшееся время выполнения вызова: `inv_time_left = inv_cpu_work(t) / (cores * core_real_flops) = inv_cpu_work(t) * max(1, load/cores) / (cores * core_flops)`

Для простоты сделаем `core_flops = 1`, тогда получим:
- Приращение суммарной работы CPU: `total_cpu_work(t) += (t-prev) * cores * core_real_flops = (t-prev) * cores / max(1, load/cores)`
- Объем работы до завершения вызова: `inv_cpu_work = duration * cores`
- Оставшееся время выполнения вызова: `inv_time_left = inv_cpu_work(t) * max(1, load/cores) / cores`

Чтобы избавиться от деления load/cores, поделим работу на `cores^2` (и домножим затем в формуле времени). Тогда формулы будут выглядеть так:
- Приращение суммарной работы CPU: `total_cpu_work(t) += (t-prev) / max(cores, load)`
- Объем работы до завершения вызова: `inv_cpu_work = duration / cores`
- Оставшееся время выполнения вызова: `inv_time_left = inv_cpu_work(t) * max(cores, load)`

Вроде бы все совпало, кроме `inv_cpu_work` - в `transform_time()` еще есть умножение на `share`, зачем?

2022-08-07 08:24 UTC, SYury commented
У меня был немного другой подход к выводу формул, но шаги похожие. Скорость выполнения функции должна быть пропорциональна её `share` и зависеть от нагрузки, при этом для случая без конкуренции время исполнения функции равно `t`. Для того, чтобы это смоделировать, присвоим каждой функции некоторый объем работы `work`, который выполняется со скоростью `share/max(load, cores)`. Для случая без конкуренции скорость постоянна и равна `share/cores`, поэтому `work = t * share / cores`. Теперь для моделирования можно на каждом промежутке времени `delta` между соседними событиями вычитать из работы `delta * share / max(load, cores)`. Заметим, что в такой постановке `share` присутствует как множитель как в `work`, так и в том, что мы вычитаем, поэтому если сократить всё на `share`, то ничего не изменится, так как нас интересует только момент, когда `work` станет нулем, а конкретные числа не так важны. Но если сократить на `share`, то мы вычитаем отовсюду одно и то же число `delta / max(load, cores)`, поэтому можно применить стандартный трюк и заменить множество вычитаний на одно прибавление к глобальному счетчику, что я и сделал. Когда я это расписал, я понял, что умножение на share это баг, спасибо, что обнаружил)

2022-08-07 10:30 UTC, SYury commented on crates/dslab-faas/src/invoker.rs
> +        cm.inc_active_invocations();
Перенёс

2022-08-07 10:31 UTC, SYury commented on crates/dslab-faas/src/stats.rs
>              if let Some(old) = self.wasted_resource_time.get_mut(&req.id) {
Упростил тут и ещё в 1 месте, больше не нашел

2022-08-07 10:31 UTC, SYury commented on crates/dslab-faas/src/cpu.rs
> +    ctx: Rc<RefCell<SimulationContext>>,
Сделал

2022-08-07 10:31 UTC, SYury commented on crates/dslab-faas/src/host.rs
> +            .progress_computer
Сделал

2022-08-07 10:31 UTC, SYury commented on crates/dslab-faas/src/cpu.rs
> +            .partial_cmp(&other.finish)
Заменил

2022-08-07 19:57 UTC, osukhoroslov commented on crates/dslab-faas/src/cpu.rs
> +    pub fn on_new_invocation(&mut self, invocation: &mut Invocation, container: &mut Container, time: f64) {
```suggestion
    pub(crate) fn on_new_invocation(&mut self, invocation: &mut Invocation, container: &mut Container, time: f64) {
```

2022-08-07 19:57 UTC, osukhoroslov commented on crates/dslab-faas/src/cpu.rs
> +    pub fn on_invocation_end(&mut self, invocation: &mut Invocation, container: &mut Container, time: f64) {
```suggestion
    pub(crate) fn on_invocation_end(&mut self, invocation: &mut Invocation, container: &mut Container, time: f64) {
```

2022-08-07 19:57 UTC, osukhoroslov commented on crates/dslab-faas/src/cpu.rs
> +    pub progress_computer: ProgressComputer,
```suggestion
    progress_computer: ProgressComputer,
```

2022-08-07 20:09 UTC, osukhoroslov commented
> Скорость выполнения функции должна быть пропорциональна её `share`

По идее скорость выполнения функции не зависит от `share`, а только от уровня нагрузки (который определяет реальную долю ресурсов, выделенных для выполнения функции). Ведь для функции уже указано её время выполнения в расчёте, что она получит ровно свой `share`. Поэтому я считаю, что умножать в твоих расчётах умножать на `share` изначально избыточно, а `share` функций нужна только для вычисления `load`.

> Когда я это расписал, я понял, что умножение на share это баг, спасибо, что обнаружил)

Надо бы для полной уверенности еще написать хотя бы несколько тестов на основе несложных примеров, где можно руками посчитать времена завершения функций. Примеры тестов можно найти в `dslab-models` и `dslab-iaas`.

2022-08-08 16:56 UTC, SYury commented on crates/dslab-faas/src/cpu.rs
> +    pub fn on_new_invocation(&mut self, invocation: &mut Invocation, container: &mut Container, time: f64) {
А зачем?

2022-08-08 16:56 UTC, SYury commented on crates/dslab-faas/src/cpu.rs
> +    pub progress_computer: ProgressComputer,
Сделал

2022-08-08 16:57 UTC, SYury commented
Добавил тесты

2022-08-08 17:52 UTC, osukhoroslov commented on crates/dslab-faas/src/cpu.rs
> +    pub fn on_new_invocation(&mut self, invocation: &mut Invocation, container: &mut Container, time: f64) {
Не то написал, можно вообще убрать `pub`, т.к. используется только внутри модуля

2022-08-08 17:52 UTC, osukhoroslov commented on crates/dslab-faas/src/cpu.rs
> +    pub fn on_invocation_end(&mut self, invocation: &mut Invocation, container: &mut Container, time: f64) {
Не то написал, вообще убрать `pub`, т.к. используется только внутри модуля

2022-08-08 18:38 UTC, SYury commented on crates/dslab-faas/src/cpu.rs
> +    pub fn on_new_invocation(&mut self, invocation: &mut Invocation, container: &mut Container, time: f64) {
Убрал

2022-08-08 18:38 UTC, SYury commented on crates/dslab-faas/src/cpu.rs
> +    pub fn on_invocation_end(&mut self, invocation: &mut Invocation, container: &mut Container, time: f64) {
Убрал

2022-08-10 19:39 UTC, osukhoroslov commented
> Добавил тесты

- Для надежности я бы сверил ещё времена завершения отдельных вызовов, а не только совокупные метрики
- Не хватает теста с разнесенными временами вызовов, сейчас все вызовы приходят в 0

2022-08-10 19:56 UTC, osukhoroslov commented on crates/dslab-faas-extra/src/hermes.rs
> +            if h.get_active_invocations() < (h.get_cpu_cores() as u64) {
Почему число вызовов должно быть меньше числа ядер? Может быть вызов потребляет 0.5 ядра. Или здесь считается что каждый вызов всегда потребляет 1 ядро?

2022-08-10 19:59 UTC, osukhoroslov commented on crates/dslab-faas-extra/src/simple_schedulers.rs
> +/// LocalityBasedScheduler picks a host based on appication hash.
```suggestion
/// LocalityBasedScheduler picks a host based on application hash.
```

2022-08-10 20:01 UTC, osukhoroslov commented on crates/dslab-faas-extra/src/hermes.rs
> +    high_load: LeastLoadedScheduler,
```suggestion
    least_loaded: LeastLoadedScheduler,
```

2022-08-12 10:14 UTC, osukhoroslov commented on crates/dslab-faas-extra/src/simple_schedulers.rs
> +/// In case host number i can't invoke, the scheduler considers host number (i + step)%hosts.len().
```suggestion
/// In case host number `i` can't invoke, the scheduler considers host number `(i + step) % hosts.len()`.
```

2022-08-12 10:15 UTC, osukhoroslov commented on crates/dslab-faas-extra/src/simple_schedulers.rs
> +        let init = ((self.hasher)(app.id) % (hosts.len() as u64)) as usize;
```suggestion
        let start_idx = ((self.hasher)(app.id) % (hosts.len() as u64)) as usize;
```

2022-08-12 10:29 UTC, osukhoroslov commented on examples/faas/src/main.rs
> +    let mut serverless = ServerlessSimulation::new(sim, Default::default());
Предлагаю везде для краткости называть `ServerlessSimulation` как `sim`. О слово `serverless` больше спотыкаешься при чтении кода.

```suggestion
    let mut sim = ServerlessSimulation::new(Simulation::new(1), Default::default());
```

2022-08-12 10:40 UTC, osukhoroslov commented on crates/dslab-faas-extra/src/azure_trace.rs
> +/// This function parses Azure trace and generates experiment.
Хочется подробностей что за процессинг здесь происходит, судя по коду это не просто считывание трейса из файла

2022-08-12 10:43 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +    let mut time_range = 0.0;
Кажется подсчёт `time_range` можно сделать один раз при создании трейса и сохранить его в нём

2022-08-12 10:52 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +    let trace = process_azure_trace(Path::new(&args[1]), 200000);
Добавь readme с инструкцией по запуску, откуда брать трейс и т.д.

2022-08-12 11:00 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +    let trace = process_azure_trace(Path::new(&args[1]), 200000);
Попробовал заустить на трейсе 2019:

```
$ ..\..\target\release\faas-scheduling-experiment.exe ..\..\..\..\datasets\azure-functions-traces\2019\

thread 'main' panicked at 'index out of bounds: the len is 436 but the index is 436', crates\dslab-faas-extra\src\azure_trace.rs:230:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

2022-08-12 16:08 UTC, SYury commented
> > Добавил тесты
> 
>     * Для надежности я бы сверил ещё времена завершения отдельных вызовов, а не только совокупные метрики
> 
>     * Не хватает теста с разнесенными временами вызовов, сейчас все вызовы приходят в 0
> 
>     * И кажется еще нужен тест с concurrent_invocations > 1, чтобы проверить как вызовы делят ресурсы контейнера

Сделал

2022-08-12 16:09 UTC, SYury commented on crates/dslab-faas-extra/src/simple_schedulers.rs
> +/// LocalityBasedScheduler picks a host based on appication hash.
Готово

2022-08-12 16:10 UTC, SYury commented on crates/dslab-faas-extra/src/hermes.rs
> +            if h.get_active_invocations() < (h.get_cpu_cores() as u64) {
В статье про Hermes описывалось именно количество вызовов, но и про cpu share я там ничего не видел. Попробую сделать с суммой cpu share

2022-08-12 16:10 UTC, SYury commented on crates/dslab-faas-extra/src/hermes.rs
> +    high_load: LeastLoadedScheduler,
Тут смысл названия был в том, что этот планировщик вызывается при высокой нагрузке

2022-08-12 16:10 UTC, SYury commented on crates/dslab-faas-extra/src/simple_schedulers.rs
> +/// In case host number i can't invoke, the scheduler considers host number (i + step)%hosts.len().
Готово

2022-08-12 16:10 UTC, SYury commented on crates/dslab-faas-extra/src/simple_schedulers.rs
> +        let init = ((self.hasher)(app.id) % (hosts.len() as u64)) as usize;
Готово

2022-08-12 16:13 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +    let trace = process_azure_trace(Path::new(&args[1]), 200000);
С какой-то попытки смог воспроизвести, скорее всего проблема появляется при нескольких днях в папке, я почти всегда на сокращенном трейсе из 1 дня тестирую и там всегда работает. Буду разбираться.

2022-08-12 17:22 UTC, osukhoroslov commented on crates/dslab-faas-extra/src/hermes.rs
> +    high_load: LeastLoadedScheduler,
Это не было очевидно сходу, может тогда `high_load_fallback`

2022-08-13 18:45 UTC, SYury commented on crates/dslab-faas-extra/src/hermes.rs
> +            if h.get_active_invocations() < (h.get_cpu_cores() as u64) {
Переделал

2022-08-13 18:45 UTC, SYury commented on crates/dslab-faas-extra/src/hermes.rs
> +    high_load: LeastLoadedScheduler,
Переименовал

2022-08-13 18:45 UTC, SYury commented on examples/faas/src/main.rs
> +    let mut serverless = ServerlessSimulation::new(sim, Default::default());
Переименовал

2022-08-13 18:45 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +    let mut time_range = 0.0;
Сделал

2022-08-13 18:45 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +    let trace = process_azure_trace(Path::new(&args[1]), 200000);
Починил баг

2022-08-13 18:46 UTC, SYury commented on crates/dslab-faas-extra/src/azure_trace.rs
> +/// This function parses Azure trace and generates experiment.
Я пока не стал расписывать детали, так как в планах переделать генерацию эксперимента и добавить больше опций для контроля

2022-08-13 19:13 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +    let trace = process_azure_trace(Path::new(&args[1]), 200000);
Добавил readme

2022-08-15 09:51 UTC, osukhoroslov requested changes

2022-08-15 09:51 UTC, osukhoroslov commented on crates/dslab-faas/src/invocation.rs
>      pub id: u64,
Переименуй везде в `func_id`, чтобы было понятно что это id-шник функции. А вот `invocation_id` я бы сделал просто `id`, и так будет ясно что это id самого InvocationRequest.

2022-08-15 09:51 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/readme.md
> +This crate experiments with several simple scheduling strategies and [Hermes](https://arxiv.org/abs/2111.07226) scheduler.
`This example evaluates different approaches for scheduling of function invocations (several simple strategies and [Hermes](https://arxiv.org/abs/2111.07226) scheduler) on Azure functions dataset.`

2022-08-15 10:05 UTC, osukhoroslov commented on examples/faas-scheduling-experiment/src/main.rs
> +}
Так удобнее читать: 

```suggestion
fn print_results(stats: Stats, name: &str) {
    println!("{}", name);
    println!("- {} successful invocations", stats.invocations);
    println!(
        "- cold start rate = {}",
        (stats.cold_starts as f64) / (stats.invocations as f64)
    );
    println!(
        "- wasted memory time = {}",
        stats.wasted_resource_time.get(&0).unwrap().sum()
    );
    println!("- mean absolute slowdown = {}", stats.abs_slowdown.mean());
    println!("- mean relative slowdown = {}", stats.rel_slowdown.mean());
}
```

2022-08-15 10:06 UTC, osukhoroslov commented
Почему так получается что у RoundRobin гораздо выше cold start rate, но при этом на порядок меньше slowdown?

```
Round Robin
- 199992 successful invocations
- cold start rate = 0.3389785591423657
- wasted memory time = 19917445911.671467
- mean absolute slowdown = 0.000014090747730502504
- mean relative slowdown = 0.000004396045952060361
Hermes
- 199992 successful invocations
- cold start rate = 0.04327173086923477
- wasted memory time = 7520473693.995928
- mean absolute slowdown = 0.00029172012165806397
- mean relative slowdown = 0.00008534074916654834
```

2022-08-15 19:37 UTC, osukhoroslov commented on crates/dslab-faas/src/cpu.rs
> +    work_total: KahanSum,
Надо бы защититься от переполнения. И нужен ли в итоге алгоритм Кэхэна?

2022-08-16 18:24 UTC, SYury commented on crates/dslab-faas/src/invocation.rs
>      pub id: u64,
Сделал

2022-08-16 18:24 UTC, SYury commented on examples/faas-scheduling-experiment/readme.md
> +This crate experiments with several simple scheduling strategies and [Hermes](https://arxiv.org/abs/2111.07226) scheduler.
Поменял

2022-08-16 18:24 UTC, SYury commented on examples/faas-scheduling-experiment/src/main.rs
> +}
Сделал так здесь и в serverless in the wild

2022-08-16 18:25 UTC, SYury commented on crates/dslab-faas/src/cpu.rs
> +    work_total: KahanSum,
Добавил пересчет работы при work_total > 1e12, алгоритм Кэхэна в результате дал разницу в 10-11 знаке, убрал его.

2022-08-16 18:26 UTC, SYury commented
> > Почему так получается что у RoundRobin гораздо выше cold start rate, но при этом на порядок меньше slowdown?
> > ```
> > Round Robin
> > - 199992 successful invocations
> > - cold start rate = 0.3389785591423657
> > - wasted memory time = 19917445911.671467
> > - mean absolute slowdown = 0.000014090747730502504
> > - mean relative slowdown = 0.000004396045952060361
> > Hermes
> > - 199992 successful invocations
> > - cold start rate = 0.04327173086923477
> > - wasted memory time = 7520473693.995928
> > - mean absolute slowdown = 0.00029172012165806397
> > - mean relative slowdown = 0.00008534074916654834
> > ```
> 
> Сейчас slowdown считается без учета холодных запусков, я забыл добавить метрику, которая считала бы время от запроса до конца

Переименовал slowdown в exec_slowdown и добавил total_slowdown, тут уже все задержки учтены.

2022-08-17 19:07 UTC, osukhoroslov commented
Еще интересно почему 10 машин с 4 ядрами достаточно для комфортной обработки трейса? На всех алгоритмах, кроме Locality который делает жуткий overcommitment, load обычно не поднимается выше 5. Там что реально такая слабая нагрузка?

2022-08-18 16:36 UTC, SYury commented
> Еще интересно почему 10 машин с 4 ядрами достаточно для комфортной обработки трейса? На всех алгоритмах, кроме Locality который делает жуткий overcommitment, load обычно не поднимается выше 5. Там что реально такая слабая нагрузка?

Генерация эксперимента изначально была сделана для воспроизведения serverless in the wild, и там берутся приложения средней популярности как в статье, так что нагрузка действительно довольно равномерная. Я планирую сделать более продвинутую генерацию, где можно будет генерировать и тяжелые по нагрузке трейсы, но уже в другом MR.

2022-08-19 10:41 UTC, osukhoroslov approved these changes

2022-08-19 10:41 UTC, osukhoroslov commented
> > Еще интересно почему 10 машин с 4 ядрами достаточно для комфортной обработки трейса? На всех алгоритмах, кроме Locality который делает жуткий overcommitment, load обычно не поднимается выше 5. Там что реально такая слабая нагрузка?
> 
> Генерация эксперимента изначально была сделана для воспроизведения serverless in the wild, и там берутся приложения средней популярности как в статье, так что нагрузка действительно довольно равномерная. Я планирую сделать более продвинутую генерацию, где можно будет генерировать и тяжелые по нагрузке трейсы, но уже в другом MR.

Понял, можно мержить.

2022-08-19 18:36 UTC, merged