[storage] Benchmarking DSLab disk vs SimGrid disk
osukhoroslov/dslab pull request #88
Opened 2022-06-20 17:10 UTC by kuskarov

2022-06-24 11:42 UTC, osukhoroslov requested changes

2022-06-24 11:42 UTC, osukhoroslov commented on examples/storage-disk-bench/src/main.rs
> +                    self.disk.borrow_mut().read(rnd.next(), self.ctx.id());
Какого размера (диапазон) запросы получаются в вашем генераторе?

2022-06-24 11:42 UTC, osukhoroslov commented on examples/storage-disk-bench/src/main.rs
> +const ACTIVITIES_COUNT: u64 = 10000;
Надо сделать параметром CLI, используя clap (см. ping-pong, master workers etc)

2022-06-24 11:42 UTC, osukhoroslov commented on examples/storage-disk-bench/src/main.rs
> +                    self.disk.borrow_mut().read(rnd.next(), self.ctx.id());
Может стоит разнести запросы по времени, добавив случайную задержку (хотя бы как опцию)? Все-таки очень большое кол-во однорвеменных запросов за раз это мало реалистично.

2022-06-24 11:42 UTC, osukhoroslov commented on examples/storage-disk-bench/src/main.rs
> +    let disk = rc!(refcell!(SharedDisk::new_simple(
Предлагаю обобщить, добавив несколько дисков (их число настраиваемый параметр), что позволит посмотреть как симулятор масштабируется по числу дисков. Юзер случайно выбирает диск куда отправить запрос.

2022-06-24 11:42 UTC, osukhoroslov commented on examples/storage-disk-bench/src/main.rs
> +    root.emit_now(
Вообще сейчас уже давно не обязательно стартовать отправляя событие. Проще и короче будет вызвать метод типа `start()` непосредственно на `user`.

2022-06-24 11:42 UTC, osukhoroslov commented on examples/storage-disk-bench/src/main.rs
> +    println!("Processed {} iterations in {} ms", ACTIVITIES_COUNT, elapsed,);
Добавьте также вывод числа событий и событий/сек (см. ping-pong и master-workers)

2022-06-24 12:35 UTC, kuskarov commented on examples/storage-disk-bench/src/main.rs
> +                    self.disk.borrow_mut().read(rnd.next(), self.ctx.id());
От 0 до 1e9+7

2022-06-24 12:37 UTC, kuskarov commented on examples/storage-disk-bench/src/main.rs
> +                    self.disk.borrow_mut().read(rnd.next(), self.ctx.id());
Да, сделаю. Хоть сейчас и смоделирован "худший случай" для модели, когда все активности перекрываются, для полноты действительно разброс времен начала нужен

2022-06-24 13:19 UTC, osukhoroslov commented on examples/storage-disk-bench/src/main.rs
> +                    self.disk.borrow_mut().read(rnd.next(), self.ctx.id());
Добавьте это как комментарий

2022-07-03 02:19 UTC, kuskarov commented on examples/storage-disk-bench/src/main.rs
> +                    self.disk.borrow_mut().read(rnd.next(), self.ctx.id());
Переписал это место, максимальный размер теперь в аргументах передается

2022-07-03 02:20 UTC, kuskarov commented on examples/storage-disk-bench/src/main.rs
> +const ACTIVITIES_COUNT: u64 = 10000;
Done

2022-07-03 02:21 UTC, kuskarov commented on examples/storage-disk-bench/src/main.rs
> +                    self.disk.borrow_mut().read(rnd.next(), self.ctx.id());
Done. Добавил параметр `--max-delay` - максимальное время начала активности. По умолчанию 0, то есть все стартуют в 0. Чем больше его указать, тем разреженнее будут запросы

2022-07-03 02:21 UTC, kuskarov commented on examples/storage-disk-bench/src/main.rs
> +    let disk = rc!(refcell!(SharedDisk::new_simple(
Done

2022-07-03 02:22 UTC, kuskarov commented on examples/storage-disk-bench/src/main.rs
> +    root.emit_now(
Действительно. Убрал в `run()`

2022-07-03 02:22 UTC, kuskarov commented on examples/storage-disk-bench/src/main.rs
> +    println!("Processed {} iterations in {} ms", ACTIVITIES_COUNT, elapsed,);
Done

2022-07-03 02:27 UTC, kuskarov commented
Пока изучаю, как в SimGrid отложенное событие правильно создать и как мультиплексировать ожидание `Io` и mailbox одновременно. В Rust-версии вроде бы все, что хотел, поменял. Еще обещал скрипт для сравнения выходов, как доделаю C++ код, тоже выложу.

2022-07-03 07:27 UTC, osukhoroslov commented
> как мультиплексировать ожидание `Io` и mailbox одновременно.

См. Worker из master-workers на SimGrid

2022-07-04 19:12 UTC, kuskarov commented
Пока еще баг есть, чиню

2022-07-11 16:04 UTC, osukhoroslov commented on examples/storage-disk-bench/src/main.rs
> +    /// Number of activities (>= 1)
Предлагаю вместо `activities` везде использовать `requests`, поскольку уже есть `DiskRequest` и не смысла вводить новое название.

2022-07-11 16:09 UTC, osukhoroslov commented on examples/storage-disk-bench/src/main.rs
> +        let plan = generate_plan(self.disks.len() as u64, activities_count, max_size, max_start_time);
`plan` тоже кажется лишним понятием, которое можно заменить на `requests`, а функцию назвать `generate_requests`.

2022-07-11 16:15 UTC, osukhoroslov commented on examples/storage-disk-bench/src/main.rs
> +        let disk_name = DISK_NAME.to_owned() + "-" + &i.to_string();
```suggestion
        let disk_name = format!("disk-{}", i);
```
и константа `DISK_NAME` не нужна

2022-07-11 16:18 UTC, osukhoroslov commented on examples/storage-disk-bench/src/main.rs
> +    let user = rc!(refcell!(Runner::new(disks, sim.create_context(USER_NAME))));
Тут тоже некоторая путаница с названиями `user` и `runner`. Предлагаю оставить второе и убрать первое (и константу `USER_NAME` заодно):

```
    let runner = rc!(refcell!(Runner::new(disks, sim.create_context("runner"))));
    sim.add_handler("runner", runner.clone());
```

2022-07-11 16:22 UTC, osukhoroslov commented on examples/storage-disk-bench/src/main.rs
> +    fn run(&mut self, activities_count: u64, max_size: u64, max_start_time: u64) {
Предлагаю назвать `start`, т.к. `run` обычно ассоциируется с полным жизненным циклом, а здесь только происходит генерация и инициализация событий.

2022-07-11 16:24 UTC, osukhoroslov commented
Добавьте `README.md` в пример на SimGrid, аналогично остальным примерам

2022-07-11 16:40 UTC, osukhoroslov commented on examples-other/simgrid/storage/main.cpp
> +[[maybe_unused]] std::unique_ptr<DisksSuit> MakeDisksWithDegradation(sg4::Host* host,
Дальше планируется добавить в бенчмарк поддержку запуска с деградацией?

2022-07-18 16:47 UTC, kuskarov commented on examples/storage-disk-bench/src/main.rs
> +    fn run(&mut self, activities_count: u64, max_size: u64, max_start_time: u64) {
Fixed

2022-07-18 16:47 UTC, kuskarov commented on examples/storage-disk-bench/src/main.rs
> +    let user = rc!(refcell!(Runner::new(disks, sim.create_context(USER_NAME))));
Fixed

2022-07-18 16:47 UTC, kuskarov commented on examples/storage-disk-bench/src/main.rs
> +        let disk_name = DISK_NAME.to_owned() + "-" + &i.to_string();
Fixed

2022-07-18 16:47 UTC, kuskarov commented on examples/storage-disk-bench/src/main.rs
> +        let plan = generate_plan(self.disks.len() as u64, activities_count, max_size, max_start_time);
Fixed

2022-07-18 16:47 UTC, kuskarov commented on examples/storage-disk-bench/src/main.rs
> +    /// Number of activities (>= 1)
Fixed

2022-07-18 16:48 UTC, kuskarov commented on examples-other/simgrid/storage/main.cpp
> +[[maybe_unused]] std::unique_ptr<DisksSuit> MakeDisksWithDegradation(sg4::Host* host,
Да, сделал такую опцию, но это на следующие итерации, думаю.

2022-07-18 16:49 UTC, kuskarov commented
Поднял минимальную версию CMake до 3.11, чтобы FetchContent работал

2022-07-18 16:52 UTC, kuskarov commented
Проблему с таймером обошел в итоге довольно просто - из отдельного актора `starter` шлю через mailbox сообщения `runner`-у, что пора запустить очередную операцию. Операции отсортированы для этого по возрастанию времени начала, и с помощью `simgrid::s4u::this_actor::sleep_until` стартер может спать между посылками сообщений.

2022-07-18 20:25 UTC, osukhoroslov commented on examples/storage-disk-benchmark/src/main.rs
> +    /// Maximal activity start time (0 by default, so all will start at 0)
```suggestion
    /// Maximal request start time (0 by default, so all will start at 0)
```

2022-07-18 20:28 UTC, osukhoroslov commented on examples-other/simgrid/storage/README.md
> +| `--max-start-time` | Maximal activity start time | `0`, so all will start at `0` |
```suggestion
| `--max-start-time` | Maximal request start time | `0`, so all will start at `0` |
```

2022-07-18 20:29 UTC, osukhoroslov commented on examples-other/simgrid/storage/main.cpp
> +static constexpr uint64_t kDefaultActivitiesCount = 1;
```suggestion
static constexpr uint64_t kDefaultRequestsCount = 1;
```

2022-07-18 20:29 UTC, osukhoroslov commented on examples-other/simgrid/storage/main.cpp
> +        .help("Maximal activity start time (0 by default, so all will start at 0)")
```suggestion
        .help("Maximal request start time (0 by default, so all will start at 0)")
```

2022-07-18 20:31 UTC, osukhoroslov commented on examples-other/simgrid/storage/main.cpp
> +    // Need to sort for sequental awaiting in `starter` actor
```suggestion
    // Need to sort for sequential awaiting in `starter` actor
```

2022-07-18 20:50 UTC, kuskarov commented
Да уж, авторефакторинг расслабляет, извиняюсь. Все закоммитил

2022-07-19 19:03 UTC, osukhoroslov commented on examples-other/simgrid/storage/README.md
> +This is a SimGrid example corresponding to [storage-disk-benchmark](../../../examples/storage-disk-benchmark). It starts given amount of disk read requests, randomly distributed on multiple disks. Re
```suggestion
This is a SimGrid example corresponding to [storage-disk-benchmark](../../../examples/storage-disk-benchmark). It executes the specified number of disk read requests with random size and start time. The requests are randomly distributed across the specified number of disks.
```

2022-07-19 19:09 UTC, osukhoroslov commented on examples-other/simgrid/storage/README.md
> +## Comparing script
```suggestion
## Comparing results with DSLab
```

2022-07-19 19:11 UTC, osukhoroslov commented on examples-other/simgrid/storage/README.md
> +There is a [script](./compare-with-dslab.py) for comparing results evaluated by SimGrid and DSLab. Argument format is the same as for examples. You should set environment variable `DSLAB_BASE_DIR` be
```suggestion
There is a [script](./compare-with-dslab.py) for running both SimGrid and DSLab implementations and comparing their results. Argument format is the same as for examples. You should set environment variable `DSLAB_BASE_DIR` before using and build both DSLab and SimGrid examples.
```

2022-07-19 19:23 UTC, osukhoroslov commented on examples/storage-disk-benchmark/src/main.rs
> +        "Processed {} requests in {:.2?} ms ({:.0} act/s)",
```suggestion
        "Processed {} requests in {:.2?} ms ({:.0} requests/s)",
```

2022-07-19 19:32 UTC, osukhoroslov commented
У меня больше замечаний нет. Разве что попрошу еще добавить сюда табличку с результатами бенчмарка для DSLab и SimGrid для разного числа запросов, дисков и т.д. А так можно мержить.

2022-07-19 19:32 UTC, osukhoroslov approved these changes

2022-07-20 22:00 UTC, kuskarov commented
Обновил шапку PR, добавил результаты. Интересная закономерность в SimGrid с ростом производительности при увеличении числа дисков. Посмотрел на флеймграфы для 1, 10 и 50 дисков (везде 10К запросов), как я понял, ему тяжелее дается обсчёт одного большого плана (когда диск один), чем множества меньших планов. Флеймграфы прилагаю.

* 1 диск: 
![perf-1](https://user-images.githubusercontent.com/45271875/180089849-389c1f2c-f52e-4ff3-bf92-8c9b5c41e530.svg)

* 10 дисков: 
![perf-10](https://user-images.githubusercontent.com/45271875/180089852-716aedc0-27d1-4218-839c-cd082c96ba62.svg)

* 50 дисков: 
![perf-50](https://user-images.githubusercontent.com/45271875/180089857-2c68cc19-830a-4348-b904-781029d15692.svg)

2022-07-20 22:16 UTC, kuskarov commented
Правда, теперь стали сильнее расходиться времена и иногда переставляются события, происходящие в одинаковое время в SimGrid. Минимальный пример, который смог подобрать -- `--requests 12 --max-size 3 --max-start-time 6 --disks 10`.

С этим уже вряд ли что-то можно сделать, но если держать `max-start-time` и `max-size` на 2-3 порядка больше числа запросов, то сходится:

```
> ./compare-with-dslab.py  --requests 10000 --max-size 100000000 --max-start-time 10000000 --disks 10000

Time diff series analysis:
Avg: 0.010185399999719812
Max: 0.5099999997764826
Std: 0.04536546513402841
```

Мержу PR.

2022-07-20 22:18 UTC, merged

2022-07-24 13:41 UTC, osukhoroslov commented
> Time diff series analysis:
> Avg: 0.010185399999719812
> Max: 0.5099999997764826
> Std: 0.04536546513402841

Только сейчас заметил, что выводятся только абсолютные отклонения времен окончания запросов. Для полноты картины надо добавить также **времена обработки** запросов (среднее, минимальное и максимальное), и **относительные** отклонения (среднее, максимальное) для них. Сделайте в отдельном PR.