Iaas tests
osukhoroslov/dslab pull request #89
Opened 2022-06-21 07:57 UTC by vetand

1) Написал несколько тестов
2) Пофиксил несколько минорных багов по результатам тестов
3) Добавил механизм таймаута при аллокации ВМ, если не смогли аллоцировать за X секунд, то машина падает с FailedToAllocate. Статус доступен из внешнего API симулятора (см. последний тест)

2022-06-24 16:32 UTC, osukhoroslov requested changes

2022-06-24 16:32 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/monitoring.rs
> +        if vm_opt.is_none() {
Не стоит делать из мониторинга универсальный источник информации о ВМ. Он собирает информацию о состоянии хостов, включая ВМ которые на них сейчас живут. Добавление `self.vms` для учёта всех ВМ в системе в текущем виде может привести к ошибкам, так как у нас могут одновременно существовать несколько **экземпляров** одной ВМ на разных хостах. И в этом случае мониторинг получает инфу про ВМ от нескольких хостов, возможно с разными статусами. Корректно собрать эти апдейты в единый статус ВМ (не экземпляра, а вообще) не так просто. Вместо `self.vms` кажется лучше хранить в `self.allocations`вместо Allocation некоторый AllocationState где есть Map c отображением host->VM. Так мы будем явно учитывать несколько экземпляров одной ВМ. И это позволит также избавиться от `vm_locations`, которая тоже не внушает доверия (у ВМ может быть несколько локаций).

2022-06-24 16:32 UTC, osukhoroslov commented on crates/dslab-iaas/src/simulation.rs
> +            self.ctx.time(),
Время прихода запроса должно быть `self.ctx.time() + delay`

2022-06-24 16:32 UTC, osukhoroslov commented on crates/dslab-iaas/tests/static/config_with_overcommit.yaml
> +send_stats_period: 0.5
Конфиги унесите из `src` в `crates/dslab-iaas/test_configs`

2022-06-24 16:32 UTC, osukhoroslov commented on crates/dslab-iaas/tests/test_core.rs
> +// Best fit selects the host with the least free space lest
```suggestion
// Best fit selects the host with the least free space left
```

2022-06-24 16:32 UTC, osukhoroslov commented on crates/dslab-iaas/tests/test_core.rs
> +// No enough space for 11th VM, resources will be allocated on host №2
```suggestion
// Not enough space for 11th VM, resources will be allocated on host 2
```

2022-06-24 16:32 UTC, osukhoroslov commented on crates/dslab-iaas/tests/test_core.rs
> +    assert_eq!(cloud_sim.host(h1).borrow_mut().get_cpu_load(current_time), 1.0);
memory_load тоже можно проверить здесь и в аналогичных тестах

2022-06-24 16:32 UTC, osukhoroslov commented on crates/dslab-iaas/tests/test_core.rs
> +    let bad_s = cloud_sim.add_scheduler("bad_s", Box::new(BadScheduler::new(3)));
```suggestion
    let bad_s = cloud_sim.add_scheduler("bad_s", Box::new(BadScheduler::new(h1)));
```

Здесь и далее используйте вместо чисел id хостов.

2022-06-25 09:43 UTC, vetand commented on crates/dslab-iaas/src/core/vm_placement_algorithm.rs
> +        let mut best_free_space: u32 = 0;
Из-за того, что изначально target_host = None разницы нет, но поправил

2022-06-25 09:50 UTC, vetand commented on crates/dslab-iaas/src/core/scheduler.rs
> +        if self.ctx.time() > vm.scheduling_start_time + self.sim_config.vm_allocation_timeout {
Да, наверно сейчас выглядит не очень хорошо

Однако меня смущает, что у нас есть 2 класса VirtualMachine и Allocation, про которые мы не можем сколь-нибудь точно сказать, а за что же они отвечают. Кажется, что allocation отвечает за выделенные ресурсы (и служит исключительно для этого процесса), когда как VirtualMachine за всё остальное - статус, потребление, другие какие-то факты.

Предлагаю слить 2 класса в один VirtualMachine, организовов в нём 2 разных интерфейса для взаимодействия с шедулером и всем остальным. Чтобы не мешать производительности, всегда передавать rc::refcell

2022-06-25 09:55 UTC, vetand commented on crates/dslab-iaas/src/core/scheduler.rs
> +            vm.set_status(VmStatus::FailedToAllocate);
Мне кажется одно из преимуществ нашей работы - это давать большую гибкость пользователю, а тогда мы просто уберём возможность синхронно узнавть информацию о ВМ

Предлагаю внутри Simulation сделать компоненту (vm_api.rs), выдающую статус ВМ при помощи синхронного интерфейса. Аналогом такой компоненты является консоль пользователя в реальном оюлаке. Кроме того, туда неплохо бы отправлять нагрузку на ВМ и т.д.

2022-06-25 10:01 UTC, vetand commented on crates/dslab-iaas/src/core/monitoring.rs
> +        if vm_opt.is_none() {
Вот тут решительно не согласен - не хочется отказываться от хорошей фичи, просто потому что при миграциях машина может быть в 2 экземплярах. Тут стоит провести аналогию, опять же, с консолью пользователя он видит статус ВМ в real time, почему бы не передавать его и здесь.

При этом переход ВМ при миграции осуществялется весьма консистентно - старая машина переключает статус Migrating, а новая Running, причем второе строго позже первого, особенно если учесть, что сейчас все запросы гарантированно доходят за 0.2 секунды. Ну а то, что пользователю события придут с опозданием это нормально, ведь это распределённые системы) И мы моделируем работу реальной системы же...

Однако согласен, что хранить в мониторинге уже не очень комфортно, потому предлагая выделить vm_api, где будет сток событий с хостов и синхронный интерфейс для пользователя

2022-06-25 10:03 UTC, vetand commented
Добавил ещё тест на одиночную миграцию

2022-06-25 11:55 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithm.rs
> +                if result.is_none() || pool_state.get_available_cpu(host) < min_available_cpu {
```suggestion
                if pool_state.get_available_cpu(host) < min_available_cpu {
```

2022-06-25 11:56 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithm.rs
> +                if result.is_none() || pool_state.get_available_cpu(host) > max_available_cpu {
```suggestion
                if pool_state.get_available_cpu(host) > max_available_cpu {
```

2022-06-25 11:58 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/scheduler.rs
> +        if self.ctx.time() > vm.scheduling_start_time + self.sim_config.vm_allocation_timeout {
Согласен, давайте попробуем

2022-06-25 12:04 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/scheduler.rs
> +            vm.set_status(VmStatus::FailedToAllocate);
Под "хранить у себя эту инфу и давать её через свой API" я имел ввиду как раз синхронный интерфейс, так что противоречия нет. Но у пользователя также должна быть возможность если требуется подписаться на события, которые будут приходить в его компонент имитирующий клиента (для этого нужен requester).

2022-06-25 12:08 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/monitoring.rs
> +        if vm_opt.is_none() {
Хорошо, давайте попробуем унести это из мониторинга

2022-06-25 12:13 UTC, osukhoroslov commented on crates/dslab-iaas/tests/test_core.rs
> +    let bad_s = cloud_sim.add_scheduler("bad_s", Box::new(BadScheduler::new(3)));
Не исправлено, проверьте

2022-06-25 12:20 UTC, osukhoroslov commented on crates/dslab-iaas/tests/test_core.rs
> +    for _i in 1..12 {
В таких случаях достаточно просто оставить подчеркивание:

```
for _ in 1..12 {
```

2022-06-26 18:11 UTC, vetand commented
Пока не закончил

2022-07-15 09:55 UTC, vetand commented
Закончил - теперь почти вся работа с виртуалкали лежит в vm_api.rs - централизованном хранилище для определения её параметров, статуса и текущего местоположения.

В текущей модели все запросы доходят гарантированно и за константное время, а потому можно построить цепочку событий для любой миграции:
1) Планировщик принимает решение и миграции
2) Target host прожимает статус migrating, выделяет ресурсы и начинает потреблять электроэнергию. Для внешнего наблюдателя ВМ находится на source хосте в статусе migrating.
3) Target host прожимает статус running - теперь для внешнего наблюдателя ВМ полностью переместилась на второй сервер.

Потому можно спокойно считать, что ВМ находится в строго одном месте, но быть готовым, что информация не актуальна

2022-07-15 16:33 UTC, osukhoroslov commented on crates/dslab-iaas/src/simulation.rs
> +    fn generate_vm_id(&mut self) -> u32 {
Предлагаю унести генерацию id в vm_api (в register_new_vm и возвращать новый id оттуда)

2022-07-15 18:57 UTC, osukhoroslov requested changes
В целом рефакторинг мне понравился, удалось упростить код, но надо избавится от постоянных копирований VirtualMachine

2022-07-15 18:57 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/host_manager.rs
> +        for item in &self.recent_vm_status_changes {
```suggestion
        for (vm_id, (status, _)) in self.recent_vm_status_changes.drain() {
```
Используйте мощь pattern matching и drain(), и тогда не нужно ниже ковыряться в item и очищать после цикла changes.

2022-07-15 18:57 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/host_manager.rs
> +                    status: item.1 .0.clone(),
Время из status changes мы не используем, надо его тогда убрать

2022-07-15 18:57 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm.rs
> +            VmStatus::Finished => write!(f, "Finished"),
```suggestion
            VmStatus::Finished => write!(f, "finished"),
```
раз остальные статусы со строчной буквы

2022-07-15 18:57 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/host_manager.rs
>              // keep lifetime correct after migrations!
Добавьте тест на то, что ВМ с временем жизни 10 и прожившая на исходном хосте 5 после миграции живет 5, а не 10. Есть ощущение что это могло сломаться. start_time должно выставляться один раз за существование ВМ.

2022-07-15 18:57 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_api.rs
> +    _ctx: SimulationContext,
```suggestion
    ctx: SimulationContext,
```

2022-07-15 18:57 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_api.rs
> +        self.vm_status.insert(vm.id, VmStatus::Initializing);
```suggestion
        self.vm_status.insert(vm.id, VmStatus::Initializing);
        self.vms.insert(vm.id, vm);
```

2022-07-15 18:57 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_api.rs
> +        }
```suggestion
        if status == VmStatus::Running {
            self.vm_location.insert(vm_id, host_id);
        }
        self.vm_status.insert(vm_id, status);
```

2022-07-15 18:57 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_api.rs
> +        self.vm_location.get(&vm_id).unwrap().clone()
```suggestion
        self.vm_location[&vm_id]
```

2022-07-15 18:57 UTC, osukhoroslov commented on crates/dslab-iaas/src/extensions/vm_migrator.rs
> +                    let status = self.vm_api.as_ref().unwrap().borrow().get_vm_status(*vm_id);
Чтобы не загромождать код поступите как с мониторингом, заведя выше (см. `mon`):

```
let vm_api = self.vm_api.as_ref().unwrap().borrow();
```

2022-07-15 18:57 UTC, osukhoroslov commented on examples/iaas/src/main.rs
> +    for _i in 0..5 {
```suggestion
    for _ in 0..5 {
```

2022-07-15 18:57 UTC, osukhoroslov commented on examples/iaas/src/main.rs
> +    for _i in 5..10 {
```suggestion
    for _ in 5..10 {
```

2022-07-15 18:57 UTC, osukhoroslov commented on examples/iaas/src/main.rs
> +    for _i in 10..15 {
```suggestion
    for _ in 10..15 {
```

2022-07-15 18:57 UTC, osukhoroslov commented on examples/iaas/src/main.rs
> +    for _i in 15..20 {
```suggestion
    for _ in 15..20 {
```

2022-07-15 18:57 UTC, osukhoroslov commented on examples/iaas/src/main.rs
> +    for _i in 0..10 {
```suggestion
    for _ in 0..10 {
```

2022-07-15 19:09 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithm.rs
> +                if result.is_none() || pool_state.get_available_cpu(host) > max_available_cpu {
Не исправлено

2022-07-17 13:15 UTC, vetand commented on crates/dslab-iaas/src/core/host_manager.rs
> +                    status: item.1 .0.clone(),
Не понял - сделать emit_now()?

2022-07-17 13:16 UTC, vetand commented on crates/dslab-iaas/src/core/scheduler.rs
> +    vm_api_id: u32,
Добавил в остальные компоненты тогда уж

2022-07-17 13:17 UTC, vetand commented on crates/dslab-iaas/src/core/host_manager.rs
>              // keep lifetime correct after migrations!
Да, что-то немного сломалось, так что написал ещё полтора теста и починил баг

2022-07-17 19:39 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/host_manager.rs
> +                    status: item.1 .0.clone(),
Нет, я не про это. Внутри status changes хранится время изменения статуса, но оно потом нигде не используется (не передается в VM API).

2022-07-18 20:11 UTC, osukhoroslov requested changes
Обращайте внимание на целесообразность clone(), у вас они часто избыточны. Если структура не нужна после вызова, то можно просто передать её во владение вызываемому коду без копирования.

2022-07-25 19:28 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/host_manager.rs
>      #[allow(dead_code)]
Уже не актуально, уберите

2022-07-25 19:33 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/vm_placement_algorithm.rs
> +                if result.is_none() || pool_state.get_available_cpu(host) > max_available_cpu {
Проверка `result.is_none()` сейчас избыточная, уберите

2022-07-25 19:43 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/host_manager.rs
>              // keep lifetime correct after migrations!
Если концовку последнего теста заменить на 

```
    cloud_sim.step_for_duration(2.);
    current_time = cloud_sim.current_time();
    assert_eq!(current_time, 102.);
    assert_eq!(cloud_sim.vm_status(vm), VmStatus::Finished);
```

то тоже проходит. Ручной проверкой выяснил, что ВМ завершается в 102 вместо 103. Почините и доработайте тест, чтобы он не пропускал такое.

2022-07-25 20:08 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/host_manager.rs
>              // keep lifetime correct after migrations!
Также в тесте `test_migration_simple` я бы ожидал, что ВМ завершится в 21, а не 22, так как второй старт должен входить во время жизни (виртуалка живет непрерывно, живая миграция не останавливает её выполнение и не меняет тем самым время её выключения). Но надо также учитывать message_delay и send_stats_period, чтобы узнать когда статус достигнет VM API. Для отладки помогли бы логи, для этого надо добавить init_logger в тесты.

2022-07-25 20:32 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/host_manager.rs
>              // keep lifetime correct after migrations!
Посчитал что должно быть в тесте `test_migration_simple`:
- Запрос достигает хоста в 0.4 (2 message_delay требуются для аллокации)
- ВМ стартует в 1.4
- ВМ живет 20 секунд и в 21.4 хост изменяет статус на Finished
- В 21.5 (т.к. send_stats_period = 0.5) хост отправляет новый статус в VM_API
- В 21.7 статус приходит на VM_API

2022-07-31 09:08 UTC, vetand commented on crates/dslab-iaas/src/core/host_manager.rs
>      #[allow(dead_code)]
Всё-таки ещё актуально, используется для examples/iaas-traces

2022-07-31 09:38 UTC, vetand commented on crates/dslab-iaas/src/core/host_manager.rs
>              // keep lifetime correct after migrations!
Да, проверил, ваши подсчеты верны
Потому в обоих тестах время завершения 21.7 и 101.7 соответственно, везде расходы на асинхронность составляют 1.7 - поправил тесты.

Тут стоит подумать как добавить небольшие накладные расходы на миграцию, чтобы моделировать копирование активных страниц оперативной памяти и небольшой даунтайм, ибо сейчас для ВМ миграция совсем незаметна. Заведу issue

2022-07-31 17:27 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/host_manager.rs
>      #[allow(dead_code)]
Я имел ввиду убрать `#[allow(dead_code)]`

2022-07-31 17:49 UTC, osukhoroslov commented on crates/dslab-iaas/src/core/host_manager.rs
>      #[allow(dead_code)]
Как уберете можете мержить

2022-07-31 17:49 UTC, osukhoroslov approved these changes

2022-08-01 16:54 UTC, merged