Add SendData Action
osukhoroslov/dslab pull request #92
Opened 2022-07-11 12:43 UTC by maksim1744

2022-07-11 18:37 UTC, osukhoroslov requested changes

2022-07-11 18:37 UTC, osukhoroslov commented on crates/dslab-dag/src/scheduler.rs
> +    SendData {
Предлагаю заодно переименовать старые действия в `ScheduleTask` и `ScheduleTaskOnCores`, поскольку теперь планировщик может управлять не только задачами.

2022-07-11 18:37 UTC, osukhoroslov commented on crates/dslab-dag/src/runner.rs
>                  self.data_location.insert(data_item_id, self.resources[location].id);
Предлагаю обновлять `data_location` всегда, не зависимо от режима передачи. Информация о местоположении данных может быть всегда полезна. И попутно стоит вести учет местоположения всех копий (реплик) данных, сейчас это только "мастер"-копия, а после передач образуются копии на других ресурсах.

2022-07-11 18:37 UTC, osukhoroslov commented on crates/dslab-dag/src/runner.rs
> +        if self.config.data_transfer_mode != DataTransferMode::Manual {
В ручном режиме outputs надо самому пересылать на runner-хост?

2022-07-11 18:37 UTC, osukhoroslov commented on crates/dslab-dag/src/runner.rs
> +            && self.outputs.iter().all(|data_item| {
Я бы не делал наличие outputs на runner-хосте обязательным. Вариант с оставлением результатов на ресурсах может понадобиться в будущем, и не хочется здесь заранее ограничивать пользователя. Факт окончания выполнения предлагаю определять по завершению всех задач и отсутствию выполняющихся передач данных.

2022-07-11 18:37 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/simple_with_data.rs
> +    data_location: HashMap<usize, Id>,
Планировщик вынужден сам хранить локации данных, в то время как они известны раннеру. Предлагаю передавать их в schedule в виде `Map<usize, Set<Id>>` (по id данных можно получить набор ресурсов хранящих эти данные).

2022-07-11 18:37 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/heft.rs
> +                            DataTransferMode::Manual => 0.,
Я правильно понимаю, что HEFT c Manual режимом сейчас работать не будет?

2022-07-26 17:04 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/simple_with_data.rs
> +    data_location: HashMap<usize, Id>,
на планировщике есть обратная связь -- множество файлов на каждом ресурсе, можно ее передать

2022-07-26 17:04 UTC, maksim1744 commented on crates/dslab-dag/src/runner.rs
> +        if self.config.data_transfer_mode != DataTransferMode::Manual {
да

2022-07-26 17:04 UTC, maksim1744 commented on crates/dslab-dag/src/runner.rs
>                  self.data_location.insert(data_item_id, self.resources[location].id);
data_location нужно только для Direct, чтобы знать откуда файл забирать (именно оттуда, где он сгенерировался). А так есть resource_data_items, содержащая список файлов на данном ресурсе

2022-07-26 17:04 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/heft.rs
> +                            DataTransferMode::Manual => 0.,
да

2022-07-27 19:34 UTC, osukhoroslov commented on crates/dslab-dag/src/runner.rs
>                  self.data_location.insert(data_item_id, self.resources[location].id);
resource_data_items неудобна тем, что с её помощью нельзя быстро найти на каких ресурсах хранится файл. Для этого хочется иметь структуру где индексом будет id файла, как в data_location, поэтому и предлагаю её приспособить.

2022-07-27 19:40 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/simple_with_data.rs
> +    data_location: HashMap<usize, Id>,
Выше написал, что resource_data_items неудобна тем, что с её помощью нельзя быстро найти на каких ресурсах хранится файл. А это по идее и будет нужно узнавать планировщику. Для этого хочется иметь структуру где индексом будет id файла, как в data_location, поэтому и предлагаю её приспособить.

2022-07-27 19:45 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/heft.rs
> +                            DataTransferMode::Manual => 0.,
Предлагаю тогда сразу в начале start() сделать assert и паниковать если передан неподдерживаемый режим. И в других планировщиках сделать такие проверки на ожидаемые режимы, раз их у нас теперь развелось.

2022-08-01 15:27 UTC, maksim1744 commented on crates/dslab-dag/src/schedulers/simple_with_data.rs
> +    data_location: HashMap<usize, Id>,
Сейчас data_location в runner-е на самом деле хранит только локацию, где файл был создан, чтобы работа в Direct-режиме не поменялась. И здесь также, чтобы с ним сравнивать. В целом можно передавать data_locations, но это будет просто отдельное поле в runner-e и не будет использоваться в этом планировщике все равно

2022-08-01 17:27 UTC, osukhoroslov requested changes

2022-08-01 17:27 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/heft.rs
> +        assert!(config.data_transfer_mode != DataTransferMode::Manual);
Лучше `assert_ne!` в таком случае, и добавьте сообщение об ошибке.

2022-08-01 17:27 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/portfolio_scheduler.rs
> +        assert!(config.data_transfer_mode != DataTransferMode::Manual);
Лучше `assert_ne!` в таком случае, и добавьте сообщение об ошибке.

2022-08-01 17:27 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/simple_scheduler.rs
> +        assert!(config.data_transfer_mode != DataTransferMode::Manual);
Лучше `assert_ne!` в таком случае, и добавьте сообщение об ошибке.

2022-08-01 17:27 UTC, osukhoroslov commented on crates/dslab-dag/src/schedulers/simple_with_data.rs
> +        assert!(config.data_transfer_mode == DataTransferMode::Manual);
Лучше `assert_eq!` в таком случае, и добавьте сообщение об ошибке.

2022-08-01 18:05 UTC, osukhoroslov approved these changes

2022-08-01 18:15 UTC, merged